### ISSUE TITLE
Floating windows not accessible with focus follows mouse

### ISSUE THREAD

**Issue by minego** [ianyh/Amethyst#1005]
When using the "Focus follows mouse" option there is no way to access floating windows. Moving the mouse to the floating window causes the floating window to be hidden before the mouse gets there.

I'd like an option to make floating windows always on top. This would resolve the issue for my work flow. Other solutions might help for others.

**Comment by freebrowser1** [comment]
Another option can be to get a user specified mouse move timeout, i.e. the windows under the mouse does not immediately get focus, but after e.g. half a second.
Something similar is implemented in XFCE for Xubuntu when 'focus follows mouse' is implemented.

**Comment by patowod** [comment]
Love Amethyst and the focus follows mouse option but totally agree on the floating windows issue. Another suggestion that would to the trick for me: add a shortcut option to the focus follows mouse option: either to toggle on/off or to disable while holding modifier.

**Comment by bob-cb** [comment]
One workaround I was trying was to set window margins > 0 and then hopefully you can select and focus to a floating window between the gaps.  But once focused, the floating window still seems to lose focus as per #1026.

**Comment by ianyh** [comment]
Always on-top #324 
Adjustable raise delay #638 

Going to mark this one as duplicate.
