### ISSUE TITLE
Layouts dialog is broken

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#1010]
**Describe the bug**
see attached image

**Applications:**
What applications are involved?

**To Reproduce**
open preferences, click on Layouts tab

**Screenshots**

<img width="277" alt="screenshot_3512" src="https://user-images.githubusercontent.com/6774346/80113159-efc81800-854f-11ea-9920-0d323d597b91.png">

**Versions:**
 - macOS: 10.15.4
 - Amethyst: 0.15.2
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
```

**Additional context**

**Comment by ianyh** [comment]
You need 0.15.3.

**Comment by mwoffenden** [comment]
All set!
