### ISSUE TITLE
Throw focused window shortcut to space x BUG

### ISSUE THREAD

**Issue by pierrg** [ianyh/Amethyst#1011]
**Describe the bug**
When you want to throw a window to a space which is not the next one and that next one has no window, it'll throw the current window to the next instead of in the wanted one; if you reuse the same shorcut it'll throw the window to the next space until you are on the desired one.

**Applications:**
all with Amethyst

**To Reproduce**
- create 10 desktops (3 fingers up and 9 times button + on the upper right corner)
- set shortcuts for the then "Throw focused window shortcut to space " shortcuts in Amethyst (I choose ctrl+opt+<window number>)
- open only one application and throw its window on desktop 1
- focus on the previous window, use the shortcut you choose to throw it to space 5
- display your spaces (3 fingers up) and you can see that the window is on space 2 instead of space 5

**Versions:**
 - macOS: 10.15.4
 - Amethyst: 0.15.3 (88)

**Comment by gittagat** [comment]
Can confirm that I experience the same issue. 

Same versions:

macOS: 10.15.4
Amethyst: 0.15.3 (88)

**Comment by gittagat** [comment]
@pierrg Can you try the following? Open preferences window on Amethyst. Uncheck "Follow thrown windows between spaces". Does the thrown window end up in the right space in your case?

**Comment by gittagat** [comment]
Another related thing I noticed is that whenever a window is maximized (using Mac OS's Cmd + Shift + F), a new space is created containing just that window. This can be seen by doing the 3 fingers up motion. The addition of this new space somehow causes some or all original space numbers to change.

**Comment by lxnn** [comment]
I had this issue. I'm fairly certain it was fixed by disabling the "Automatically rearrange Spaces based on most recent use" setting in System Preferences > Mission Control.

Can someone confirm this works?

**Comment by pierrg** [comment]
> I had this issue. I'm fairly certain it was fixed by disabling the "Automatically rearrange Spaces based on most recent use" setting in System Preferences > Mission Control.
> 
> Can someone confirm?

Yes ! I confirm that fix this issue. Thank you very much.
I think it would be great to alert the user if this system setting is detected on launch.

**Comment by jccr** [comment]
> > I had this issue. I'm fairly certain it was fixed by disabling the "Automatically rearrange Spaces based on most recent use" setting in System Preferences > Mission Control.
> > Can someone confirm?
> 
> Yes ! I confirm that fix this issue. Thank you very much.
> I think it would be great to alert the user if this system setting is detected on launch.

It would also be great to have these kinds of System Preferences documented/called-out in the readme.

**Comment by ianyh** [comment]
This has since been documented.
