### ISSUE TITLE
can't immediately decrease main pane count after increasing it

### ISSUE THREAD

**Issue by natestemen** [ianyh/Amethyst#1016]
**Describe the bug**
When increasing, then decreasing the main pane count, sometimes get stuck in state where a command will have no action.

**Applications:**
Amethyst

**To Reproduce**
Have two windows in the "tall" configuration
<kbd>shift</kbd>+<kbd>option</kbd>+<kbd>,</kbd> twice, followed by
<kbd>shift</kbd>+<kbd>option</kbd>+<kbd>.</kbd> does nothing

**Expected behavior**
<kbd>shift</kbd>+<kbd>option</kbd>+<kbd>.</kbd> takes me back to a vertical layout

**Versions:**
 - macOS: 10.15.4
 - Amethyst: 0.15.3
 
**Debug Info**
<details>
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.15.3 (88)

OS version: Version 10.15.4 (Build 19E287)

Has permissions: true

Screens:
	(0.0, 0.0, 2048.0, 1280.0) [(0.0, 0.0, 2048.0, 1280.0)]

Manageable applications:
	*redacted

Configuration:
restore-layouts-on-launch: 1
enables-layout-hud-on-space-change: 1
new-windows-to-main: 0
focus-follows-mouse: 0
screen-padding-bottom: 0
window-margins: 0
debug-layout-info: 0
use-canary-build: 0
screen-padding-right: 0
mouse-follows-focus: 1
mod1: (
    option,
    shift
)
window-resize-step: 5
ignore-menu-bar: 0
floating: (
)
screen-padding-left: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
mod2: (
    option,
    shift,
    control
)
window-margin-size: 1
window-minimum-width: 0
enables-layout-hud: 1
floating-is-blacklist: 1
window-minimum-height: 0
float-small-windows: 1
follow-space-thrown-windows: 1
screen-padding-top: 0
</details>

**Comment by ianyh** [comment]
It does have an action. Decrementing once does not undo incrementing twice. The UI for the counts could be improved, but there's a separate issue tracking HUD improvements (#970).
