### ISSUE TITLE
Small Finder Copying window is not floated

### ISSUE THREAD

**Issue by mkhazov** [ianyh/Amethyst#1018]
**Describe the bug**
When I copy files in Finder, smal Copying window appears as a tile, it does not float.

**Applications:**
Finder

**Expected behavior**
Copying window should float, I believe that was implemented in #92 

**Versions:**
 - macOS: 10.12.6
 - Amethyst: 0.15.3 (88)
 
**Debug Info**
```
Version: 0.15.3 (88)

OS version: Version 10.12.6 (Build 16G2016)

Has permissions: false

Screens:
	(0.0, 0.0, 2560.0, 1440.0) [(0.0, 0.0, 2560.0, 1440.0)]

Manageable applications:
	Finder (com.apple.finder)
	Google Chrome (com.google.Chrome)

Configuration:
float-small-windows: 1
follow-space-thrown-windows: 1
enables-layout-hud: 1
screen-padding-bottom: 0
enables-layout-hud-on-space-change: 1
window-resize-step: 5
window-minimum-height: 0
screen-padding-left: 0
mouse-swaps-windows: 1
use-canary-build: 0
debug-layout-info: 0
mod2: (
    option,
    shift,
    control
)
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    "widescreen-tall",
    bsp
)
floating: (
        {
        id = "com.apple.Preview";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    }
)
window-margin-size: 0
focus-follows-mouse: 0
mod1: (
    option,
    shift
)
screen-padding-right: 0
mouse-resizes-windows: 1
screen-padding-top: 0
window-margins: 0
restore-layouts-on-launch: 1
ignore-menu-bar: 0
window-minimum-width: 0
new-windows-to-main: 0
floating-is-blacklist: 1
mouse-follows-focus: 1
```

**Comment by mkhazov** [comment]
`Toggle float for focused window` shortcut helps, but next copying window is opened as tiled.

**Comment by dvcrn** [comment]
Is there a solution for these windows? I noticed the same in some apps for stuff like "Quick Open", with new windows always getting tiled again

**Comment by rcarmo** [comment]
This is a moderate-to-high annoyance - every time I use the Finder to move files, my entire desktop is re-shuffled.

**Comment by LucasReyg** [comment]
Same here, the copying window is pretty annoying for long copy

**Comment by bashu** [comment]
still an issue with a latest Amethyst 0.15.6 (93)

**Comment by strujilloc** [comment]
this fix is working for me:
1- add floating application "com.apple.finder"
2- add window title restriction "Copy"
