### ISSUE TITLE
Keyboard Shortcut to Toggle Enable/Disable Amethyst (or Pause/Unpause)

### ISSUE THREAD

**Issue by Tormen** [ianyh/Amethyst#1019]
Hi,

I am wondering if there is any possibility to assign a keyboard shortcut to the function "Disable/Enable" that is already available in the bar-menu of Amethyst.

If not through the Amethyst preferences window, can I maybe through command-line disable Amethyst for a while?

The only way I can think off is to kill the process and then relaunch it when I want to enable it again, but it seems a bit drastic ...
 
Thanks a lot for any hint.

**Usecase:** 
Either manually or through BetterTouchTool (BTT) I sometimes place windows in a specific manner that is not in line with the Amethyst layout and in this case it seems the easiest to pause Amethyst for a while to keep the custom layout.
And for me this happens often enough to wish for a possibility to assign a keyboard shortcut.

**Comment by ulope** [comment]
That's already possible via the `Toggle global tiling` shortcut.

**Comment by Tormen** [comment]
:D ... rats. I went several times through the list as I could not believe that there is no toggle for this already... but I missed this one.

Thanks a lot (maybe rename the option to "Toggle global tiling (enable/disable Amethyst)" ... if thats not too long ?

At least now with this ticket there is hint out there :)
