### ISSUE TITLE
Add floating guide to the README

### ISSUE THREAD

**Issue by timvisher** [ianyh/Amethyst#102]
Really love Amethyst. It's the first tiling window manager I've used and its really changed the way I think about my windows.

One of the best enhancements for me would be the ability to specify an exclude list for all Applications that Amethyst should never manage.

Thanks in advance!

**Comment by thebigbstudio** [comment]
Is there any way that I can add any shell executable file or app in floating? I'm trying to figure out but can't able to do it. I want to add scrcpy(application mirrors Android devices), but can't able to add it. Please help, any help would really be appreciated.
