### ISSUE TITLE
"Maximize" single windows

### ISSUE THREAD

**Issue by typkrft** [ianyh/Amethyst#1025]
**Is your feature request related to a problem? Please describe.**
I suspect that because truly maximized windows occupy their own space we can't do this properly, but it would be nice if a layout that only has one window, had the option to ignore the gaps to utilize the maximum available space available. Adding a second window would then bring back whatever gap settings are set. 

**Describe the solution you'd like**
A toggle in the settings would be great. 

**Describe alternatives you've considered**

**Additional context**
Thanks for all your work.

**Comment by unknowledgeable** [comment]
Would love this feature too, an option to turn off margin when only one window is in a space. Having the margin is only really useful to me when using multiple windows that have no border decorations like my terminal.

At the moment I feel the need to constantly enable and disable Amethyst which defies the point of having a window manager in the first place!

**Comment by bergmul** [comment]
![Screenshot 2023-08-09 at 12 23 38](https://github.com/ianyh/Amethyst/assets/31454439/c7730c4b-a28f-4b21-aedb-39217846ae6d)

Smart window margins have implemented this. Issue can be closed.
