### ISSUE TITLE
Privacy Policy/ Data Retention

### ISSUE THREAD

**Issue by vvnlee** [ianyh/Amethyst#1027]
I have an employee that wants to use this product and I want to be sure that this project isn't collecting any consumer data or information. 

I suggest having a statement or privacy policy to address this issue. I want to be 100% sure before allowing the user to download and utilize Amethyst.

Thank you!

**Comment by ianyh** [comment]
We don't collect or retain any user-identifying information and nothing gets transmitted over a network. Is this sufficient for compliance purposes? https://github.com/ianyh/Amethyst/blob/privacy-policy/privacy-policy.md

**Comment by vvnlee** [comment]
Yes! Thank you. : ) This is sufficient. Thank you for taking the time to do this.
