### ISSUE TITLE
Windows can not be thrown to a space on external monitor using the native space number

### ISSUE THREAD

**Issue by patowod** [ianyh/Amethyst#1028]
**Describe the bug**
Windows can not be thrown to a space on external monitor using the native space number, while it does work on the primary display.

**Applications:**
All, system wide

**To Reproduce**
Attach external monitor to use as second screen. Setup 3 spaces per monitor, 1-3 primary device (Macbook), 4-6 external display. Try to select application on first space and throw it to space 6 (which results in nothing). Workaround: you first have to send the window to the  external monitor and then to the desired space, but not with it's actual number (6) but with (3) and you have to send it twice for it to land on space 6, because the first time its off by one and lands on space 5, instead of 6. Throwing it back to space 4 (using the number 1) works without doubling the action.

**Expected behavior**
Send focused window to actual space number provided by MacOs, regardless on which screen the space exists.

**Screenshots**
N/A

**Versions:**
- Version: 0.15.3 (88)
- OS version: Version 10.14.6 (Build 18G5033)
- Has permissions: false
 
**Debug Info**
```
Screens:
	(0.0, 0.0, 1280.0, 800.0) [(0.0, 0.0, 1280.0, 800.0)]
	(-369.0, 800.0, 1920.0, 1080.0) [(-369.0, -1080.0, 1920.0, 1080.0)]

Manageable applications: all, system wide

Configuration:
debug-layout-info: 0
ignore-menu-bar: 1
mod2: (
    option,
    shift,
    control
)
window-minimum-height: 0
screen-padding-left: 0
focus-follows-mouse: 0
screen-padding-bottom: 0
float-small-windows: 1
restore-layouts-on-launch: 1
enables-layout-hud: 0
mouse-swaps-windows: 0
window-minimum-width: 0
mouse-follows-focus: 1
floating-is-blacklist: 1
enables-layout-hud-on-space-change: 0
use-canary-build: 0
window-margin-size: 5
follow-space-thrown-windows: 1
mouse-resizes-windows: 1
window-margins: 0
screen-padding-top: 0
screen-padding-right: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    bsp,
    "3column-left",
    "middle-wide"
)
new-windows-to-main: 0
mod1: (
    option,
    shift
)
```

**Additional context**
All spaces are assigned an additional shortcut via system preferences: ctrl + 1 through 6, which work as expected (showing the wanted space on the respective monitor). The internal device keyboard is used.

**Comment by shinglyu** [comment]
I would also be useful to be able to "Throw focused window to left montior" or "Throw focused window to right monitor" etc. But I'm not sure if if MacOS expose this API.

**Comment by shinglyu** [comment]
> I would also be useful to be able to "Throw focused window to left montior" or "Throw focused window to right monitor" etc. But I'm not sure if if MacOS expose this API.

Sorry for my ignorance, it's already implemented: https://github.com/ianyh/Amethyst/issues/551#issuecomment-279572293

**Comment by 10zero11** [comment]
I'm also encountering this limitation.

Throwing from Space 1 on my left monitor to Space 8 on my right monitor is not possible with one shortcut.

First I must throw to the other screen and then do a second throw to 'space 4' which is actually space 8.

**Comment by dozzman** [comment]
I have created PR #1209 to adjust the behaviour of window throwing and match the behaviour expected in this issue.

You can always download my PR branch and build it locally if you want to use it immediately until it is (hopefully) accepted upstream.
