### ISSUE TITLE
Shortcut: Swap focused main window with previously focused window

### ISSUE THREAD

**Issue by ubuntudroid** [ianyh/Amethyst#1042]
**Is your feature request related to a problem? Please describe.**
I usually have three or more windows open on my laptop. Using the tall layout I often find myself swapping one of the non-main windows with the main one when checking something in those windows only to swap the previous main one back to main a few seconds later (a little bit like opt-tabbing). That becomes a bit tedious when doing very often (swapping the two windows as main windows back and forth).

**Describe the solution you'd like**
Pressing the shortcut for _swap focused window with main window_ while the main window already is focused could swap it with the previously focused window, but keep the focus on the main pane.

**Describe alternatives you've considered**
Right now I am using opt-tab + the shortcut for _swap focused window with main window_. This works, but it's not super convenient. If there is no good way to implement my preferred solution I will likely just set up an own shortcut using Alfred.app or BetterTouchTool which combines those two. However it would be another shortcut to memorise.

**Comment by maxandersen** [comment]
maybe have the short cut for focused main window when the focus is on the main focused window be to swap back.

so it becomes a toggle - that would be super nice.

**Comment by syl20bnr** [comment]
~~This shortcut would be awesome and make the `Two Panes` layout even more usable.~~
~~Returning from main window to last focused window is deeply needed, it is a pain to be forced to cycle through multiple windows just to get back to the previously focused window.~~

~~In other terms:~~
~~- changing focus to main windows is O(1)~~
~~- thus changing back focus to previously focused window should also be O(1)~~

See issue: https://github.com/ianyh/Amethyst/issues/1313

**Comment by syl20bnr** [comment]
shameless ping @ianyh 👼🏻

**Comment by syl20bnr** [comment]
mmm will open a new issue about this, this is a different feature request.

**Comment by ianyh** [comment]
Done in #1390
