### ISSUE TITLE
Support for Colemak (through keybindings)

### ISSUE THREAD

**Issue by creese** [ianyh/Amethyst#105]
I use the Colemak layout, but when I do xmonad, I like to keep the physical layout the same (in other words, HJKL becomes HNEI, etc.) 

I'd like to be able to do the same with your tool.

Nice job, btw!

[Trello Card](https://trello.com/c/dIac4FBn/34-amethyst-support-for-colemak-through-keybindings)

**Comment by ianyh** [comment]
I think this should actually function correctly now. Please reopen if it does not.
