### ISSUE TITLE
binary space middle layout

### ISSUE THREAD

**Issue by maxandersen** [ianyh/Amethyst#1056]
**Is your feature request related to a problem? Please describe.**
binary space layout works nice but on a ultra wide monitor it is not nice with pane being on the left.

**Describe the solution you'd like**
have a binary space layout that would have main center and then apply binary space layout on the sides.

**Comment by lougreenwood** [comment]
@maxandersen Isn't this the the 3 column middle layout?

**Comment by maxandersen** [comment]
> @maxandersen Isn't this the the 3 column middle layout?

not as it behaves on my screen.

Binary space layout does what I expect but the main window is on the left, not the middle.

3 colum middle layout just place each window on the sides stacked on each other - not using binary space layout.

if you know how to make it do that i'm all ears because as is now the windows are just too "squeezed"

**Comment by ianyh** [comment]
I think this can be handled with custom layouts.

**Comment by maxandersen** [comment]
Interesting. How would I get to apply binary layout from a custom layout?
