### ISSUE TITLE
Amethyst won't tile VLC or MplayerX

### ISSUE THREAD

**Issue by stylerw** [ianyh/Amethyst#106]
Hello! 

Love Amethyst, and am thrilled to have finally found a tiling WM for Mac :)

Regardless of the "FloatSmallWindows" setting, and regardless of within-App settings, Amethyst seems to completely ignore both VLC and MplayerX.  Quicktime is tiled as normal, but these other players are just left floating.  

It's just a minor annoyance, but still an annoyance.  Thanks!

[Trello Card](https://trello.com/c/6zOYWWMX/35-amethyst-amethyst-won-t-tile-vlc-or-mplayerx)

**Comment by ianyh** [comment]
More symptoms of #49
