### ISSUE TITLE
Allow a bit of overlapping in order to have bigger windows

### ISSUE THREAD

**Issue by fergonco** [ianyh/Amethyst#1064]
**Is your feature request related to a problem? Please describe.**
I have too many windows and my screen is too small.

**Describe the solution you'd like**
Same as now but making windows bigger, allowing a bit of overlapping. Make that bit configurable.

**Describe alternatives you've considered**
I layout the windows with amethyst, then I quit amethyst and make the windows bigger manually.

**Comment by ianyh** [comment]
@fergonco you can set minimum window dimensions in preferences.

**Comment by fergonco** [comment]
That does the trick. Thanks!
The windows move when losing/gaining focus. They retire a bit when the focus is lost, like leaving place for the other windows, which I don't find necessary. Is this a known feature? I find it a little bit disturbing but it's fine. Let me know if you want some more thorough explanation.

**Comment by ianyh** [comment]
That sounds like the window peeking behavior. and it is intentional. It makes more sense when you have a mix of dimensions involved, but we basically leave windows off screen if they don't need to be totally on screen.
