### ISSUE TITLE
Regex for floating window title exceptions

### ISSUE THREAD

**Issue by AdamSLevy** [ianyh/Amethyst#1065]
**Is your feature request related to a problem? Please describe.**
When I go to specify that a window should be floating using the Window Title Restrictions, I must use an exact match for the window title in an application. This doesn't work well for windows with a dynamic title such as a download dialog that lists the file name in the title. A good example is the dialog box that Firefox produces when downloading a file.

**Describe the solution you'd like**

I would like to be able to use a regex to match the window title.

**Describe alternatives you've considered**
There is no way that I am aware of to handle a situation where the title of a dialog window is not consistent. However better support for "Float small windows" where the floating window size threshold could be set might be a reasonable alternative.

**Comment by ianyh** [comment]
Duplicate of #981
