### ISSUE TITLE
Centered Main Column Layout

### ISSUE THREAD

**Issue by stylerw** [ianyh/Amethyst#107]
Ergonomically speaking, it's best if what you're looking at is centered in your view.  As such, I'm wondering if there would be any way to implement a centered column layout, wherein the middle 2/4 of the screen is "main", and there are columns on either side.

I figure that this could be made intuitive by considering the main window "12 O'Clock", and, having clockwise rotation move-to-main the top item on the left column, and CCW rotation move-to-main the top item on the right.

Any chance of this?

Thanks!

[Trello Card](https://trello.com/c/ExugFe9T/36-amethyst-centered-main-column-layout)

**Comment by ianyh** [comment]
Someone submitted a PR for this and it should make it out into 0.9.5 soon.
