### ISSUE TITLE
Add delay before focus following mouse

### ISSUE THREAD

**Issue by freebrowser1** [ianyh/Amethyst#1073]
The new version 0.15.4 works much better !

But sometimes, I am unable to access floating windows when 'focus follows mouse' is enabled. Probably there is missing a delay option before the focus actually follows the mouse.
Ubuntu has such a feature with a configurable delay, at least in XFCE. Settings => Window Manager => Focus.
A similar slider or other control for delay would be useful in Amethyst.

See screenshot. 

<img width="674" alt="Screenshot 2020-11-19 at 10 42 06" src="https://user-images.githubusercontent.com/26625141/99649207-3208f780-2a54-11eb-952b-9960aa51daa9.png">

**Comment by ianyh** [comment]
Duplicates #638
