### ISSUE TITLE
Widescreen Tall Mid layout

### ISSUE THREAD

**Issue by NoisomePossum** [ianyh/Amethyst#1074]
**Is your feature request related to a problem? Please describe.**
I'm using a 49" monitor. I like to keep my main work area in the middle of my screen and the current 3-column layout is _almost_ but not quite perfect for me. When I add a second main window the windows are split into rows which makes it very hard to read anything.

**Describe the solution you'd like**
I would love to have a 3-column layout that places the main window in the middle but splits that window into columns when a second main window is added. This way I can work with 1 window most of the time but add another whenever I need to compare things side-by-side.

**Describe alternatives you've considered**
Widescreen tall is decent but since I have to look to the left of the monitor it's a bit inconvenient/uncomfortable.

**Comment by rraihansaputra** [comment]
@NoisomePossum Are you still interested? Managed to implement what you described from the 3-column layout. If you're still interested, I'll make a Pull Request to this repo, and can send you a compiled app if you want.

Edit: currently the PR is still in draft here: https://github.com/ianyh/Amethyst/pull/1128

**Comment by ianyh** [comment]
Closing this as we now have custom layouts.
