### ISSUE TITLE
Max window size option?

### ISSUE THREAD

**Issue by MutatingFunc** [ianyh/Amethyst#1076]
**Is your feature request related to a problem? Please describe.**
When only a single window is open, making it fullscreen on a wide monitor can actually hinder productivity by making the window too stretched, spacing content further apart than most apps are designed for.

**Describe the solution you'd like**
Similar to the existing minimum window width & height options, a maximum width & height could allow a single window to be displayed in the middle of the screen, while still expanding to make use of the full screen when many windows are open.

**Describe alternatives you've considered**
It's possible to add "screen padding", but this still applies when multiple windows are open side-by-side. An alternative would be a checkbox to only apply screen padding when a single window is open.

**Comment by AllanHasegawa** [comment]
That would be a sweet feature for super ultrawide monitors.

Also, sometimes I want to focus on a single window on a new space, but the fullscreen window is way too big and unusable.

I'm currently using the "3column middle" layout with "dumb terminals" around the main panel. This works but it's not ideal.

**Comment by seraphyn** [comment]
Center with percent would be a great option

**Comment by mike-lloyd03** [comment]
I finally got around to implementing this with a custom layout today. Works pretty good in my limited testing except that Amethyst will crash when switching to this layout from time to time. Logs aren't printing any errors when it crashes. Any ideas?

```javascript
const MAX_WIDTH = 2400;

function layout() {
  return {
    name: "Tall (Max Width)",
    extends: "tall",
    getFrameAssignments: (windows, screenFrame, state, extendedFrames) => {
      const hasOneWindow =
        windows.length === 1 && screenFrame.width > MAX_WIDTH;
      const oneWindowXOffset = Math.round((screenFrame.width - MAX_WIDTH) / 2);

      return extendedFrames.reduce((frames, extendedFrame) => {
        const frame = {
          x: hasOneWindow ? oneWindowXOffset : extendedFrame.frame.x,
          y: extendedFrame.frame.y,
          width: hasOneWindow ? MAX_WIDTH : extendedFrame.frame.width,
          height: extendedFrame.frame.height,
        };
        return { ...frames, [extendedFrame.id]: frame };
      }, {});
    },
  };
}
```

**Comment by ianyh** [comment]
See my comment here on another ticket with regards to window width. https://github.com/ianyh/Amethyst/issues/997#issuecomment-1441059753
