### ISSUE TITLE
Support for M1 Apple Silicon (arm64)

### ISSUE THREAD

**Issue by spkane** [ianyh/Amethyst#1078]
**Is your feature request related to a problem? Please describe.**
It is unclear if Amethyst has a universal build or arm64 build that support the Apple Silicon (M1) arm64 hardware.

**Describe the solution you'd like**
And updating README that is clear about the status around supporting this and ideally the release of an arm64 build or at least a universal app.

**Describe alternatives you've considered**
Running via Rosetta, but that it a very poor substitute even if if works for a tool like this.

**Comment by pmsteil** [comment]
So it does work under Rosetta??? Very cool if so!

**Comment by spkane** [comment]
> So it does work under Rosetta??? Very cool if so!

Honestly, I have not tested it via Rosetta yet. It is next on my list, but for a core util like this I really would like to see a native version. May try building it myself soon.

**Comment by ianyh** [comment]
I don't have a M1 machine to test, but it should be straightforward to build.

**Comment by spkane** [comment]
> I don't have a M1 machine to test, but it should be straightforward to build.

I think you can build a universal app without an M1 system. If you could build it I could test pretty easily. I can try to build, but that might take me a bit longer to get around to.

**Comment by ianyh** [comment]
Yeah, they are trying to make building universal really easy so I wouldn't expect it to take too much time for me.

**Comment by killuazhu** [comment]
I can confirm 0.15.4 works fine on M1. I did not compile but just download the version from https://github.com/ianyh/Amethyst/releases/download/v0.15.4/Amethyst.zip, assume that's a Rosetta version.

**Comment by thejustinwalsh** [comment]
Trying to build / compile and having a hell of a time with Ruby & CocoaPods vs M1.

Install ruby 2.4.1 using rbenv:
```sh
RUBY_CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.4.1
```
Ruby 2.7.2 installs cleanly with no warnings that generate errors however, so may be worth updating ruby dependency.

gem ffi has a known issue on M1 and requires the use of a newer version. Adding:
`gem 'ffi', github: 'ffi/ffi'` to the .Gemfile ensures we pull from github master.

At this point `bundle install` is passing cleanly, however `bundle exec pod install` is now crashing with a segfault in ethon-0.12.0
```sh
c:0053 p:---- s:0321 e:000320 CFUNC  :easy_setopt_string
c:0052 p:1164 s:0314 e:000313 METHOD /Users/thejustinwalsh/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ethon-0.12.0/lib/ethon/curls/options.rb:103
```

Not sure how to proceed to get CocoaPods to install, any advise is welcome. I haven't used CocoaPods for active development in a very long time.

**Comment by thejustinwalsh** [comment]
Quick update, I was trying too hard to make `./bin/setup.sh` work.

If using `rbenv` then first switch back to system ruby w/ `rbenv local system`, rbenv global system`.

Then simply use rosetta2, and execute cocoapods against system ruby in the root of the repo:
```
arch -x86_64 sudo gem install cocoapods
arch -x86_64 sudo gem install ffi
arch -x86_64 pod install
```

**Comment by thejustinwalsh** [comment]
Able to compile and run on an M1 without issue. Not sure how to contribute a binary, sign it, etc. But if there is anything I can do to help let me know.

**Comment by lougreenwood** [comment]
Would be great to have an M1 build available on homebrew

**Comment by paolomainardi** [comment]
@ianyh can you help us to have an M1 build ? It seems that is already ready to be built on ARM. cc @killuazhu

**Comment by simoleone** [comment]
The [0.15.4 release from Oct 24, 2020](https://github.com/ianyh/Amethyst/releases/tag/v0.15.4) contains a universal binary in the zip. That version has been in homebrew for quite a long time already.

Contents of the 0.15.4 zip are a universal binary.
<img width="1141" alt="Screen Shot 2021-04-19 at 10 36 44" src="https://user-images.githubusercontent.com/150510/115198818-2d2b9b00-a0fb-11eb-9811-7c36bba38fd0.png">

Amethyst running on my M1 showing `Apple` not `Intel` architecture.
<img width="933" alt="Screen Shot 2021-04-19 at 10 31 33" src="https://user-images.githubusercontent.com/150510/115198153-6c0d2100-a0fa-11eb-808b-05f896fd6f7c.png">

Seems fine to me?

**Comment by coffenbacher** [comment]
Hi all, I am considering upgrading to M1 and I'm a little confused by this thread, are there any limitations to Amethyst in M1? It doesn't really sound like it from what I see, should this issue be closed?

**Comment by thejustinwalsh** [comment]
@coffenbacher looks like it is already done, I would argue you could squeeze some more battery life out of your mac on the Apple version, but like @simoleone posted above, looks to be good now, using Apple archetecture.

**Comment by simoleone** [comment]
Yep! It's been working fine on my M1 using the universal binary in the 0.15.4 release. There's nothing special to do, it just works.
