### ISSUE TITLE
Option to float Quicklook Windows by default

### ISSUE THREAD

**Issue by stylerw** [ianyh/Amethyst#108]
Quicklook (e.g. Hitting Space on a file in Finder) windows are some of few that really deserve to float, even over a tiled layout.  Perhaps the default configuration could be updated to allow them to float naturally?

[Trello Card](https://trello.com/c/zDqW4jmW/37-amethyst-option-to-float-quicklook-windows-by-default)

**Comment by ianyh** [comment]
Quick Look windows now have their own subrole, and are thus floated by default.
