### ISSUE TITLE
Build fails on 10.9.1

### ISSUE THREAD

**Issue by chdiza** [ianyh/Amethyst#109]
I followed the build instructions in the README file, but I have failed on two different machines running 10.9.1 to build Amethyst from HEAD. Are the instructions out of date?

I always get the error pasted below, and nothing else in the build output appears to offer info about what went wrong.

````
** INSTALL FAILED **


The following build commands failed:
	CompileC /Users/chdiza/Library/Developer/Xcode/DerivedData/Amethyst-bmaivanjamfbahfnilzaesznycql/Build/Intermediates/Pods.build/Debug/Pods-ReactiveCocoa.build/Objects-normal/x86_64/NSObject+RACKVOWrapper.o ReactiveCocoa/ReactiveCocoaFramework/ReactiveCocoa/NSObject+RACKVOWrapper.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
````

[Trello Card](https://trello.com/c/NWMqfwfa/38-amethyst-build-fails-on-10-9-1)

**Comment by ianyh** [comment]
Should hopefully be fixed now that ReactiveCocoa is installed via Carthage.
