### ISSUE TITLE
Vertical Shrink ?

### ISSUE THREAD

**Issue by pex81** [ianyh/Amethyst#1093]
**Is your feature request related to a problem? Please describe.**
It's possible to vertical shrink ?
For example I have 1 window on left and 2 window on right. Can I shrink this 2 vertical windows ?
Thanks good work.

**Describe the solution you'd like**
Nothing special.

**Describe alternatives you've considered**
Nothing special.

**Additional context**
Nothing special.

**Comment by ianyh** [comment]
This would need to be a custom layout.
