### ISSUE TITLE
Four Corners Layout

### ISSUE THREAD

**Issue by justin-vanwinkle** [ianyh/Amethyst#1097]
**Is your feature request related to a problem? Please describe.**
I have a very large 4k monitor that I use like it's 4x 1080p monitors by shoving windows into each corner. Although there are some relatively close layouts, Amethyst does not support a four corners layout.

**Describe the solution you'd like**
I'd like to have 1 screen in each corner. 

The first window would be full screen.
The second window would create a vertical split.
The third window would create a horizontal split on one side.
The fourth window would create another horizontal split on the other side such that all four windows are in a corner.

Going beyond 4 windows would begin adding windows in each row.
The fifth window would make the top row three equal size screens.
The sixth window would go in the bottom row in the same way.

**Additional context**
If you'd like to try this layout, Windows supports a similar four-corner feature out of the box by dragging a window into each corner.

**Comment by thomasmarr** [comment]
It's not exactly what you asked, but you can do a 'tall' layout, with 2x windows in the main pane. So, when you open four windows you'll end up with one in each corner (just like the Windows feature you mentioned).

The default shortcuts to increase / decrease the main pane window count are:

mod1 + , | Increase main pane count
-- | --
mod1 + . | Decrease main pane count

You can do the same thing with 'wide' if you prefer additional windows to split a pane into columns instead of rows.

**Comment by ianyh** [comment]
This should be possible with custom layouts.

**Comment by bryanculver** [comment]
@justin-vanwinkle I wrote a custom layout to do just this: https://gist.github.com/bryanculver/4c181881cca81d9963f49a77dd5ac127

Yes I know it's verbose but it was much easier to debug and is pretty performant.

What it does:

- 1 window: entire screen
- 2 windows: even split left and right of screen
- 3 windows: first window is on left, 2nd and 3rd split vertically the right
- 4 windows: all four corners (as you'd expect)
- 5+ windows: window 1 is top left, window 2 is top right, window 3 is bottom left, windows 4+ vertically split the bottom right corner.

**Comment by farheinheigt** [comment]
> @justin-vanwinkle I wrote a custom layout to do just this: https://gist.github.com/bryanculver/4c181881cca81d9963f49a77dd5ac127
> 
> Yes I know it's verbose but it was much easier to debug and is pretty performant.
> 
> What it does:
> 
> * 1 window: entire screen
> * 2 windows: even split left and right of screen
> * 3 windows: first window is on left, 2nd and 3rd split vertically the right
> * 4 windows: all four corners (as you'd expect)
> * 5+ windows: window 1 is top left, window 2 is top right, window 3 is bottom left, windows 4+ vertically split the bottom right corner.

I love U bro, thanks a lot

**Comment by mikupiku69** [comment]
> @justin-vanwinkle I wrote a custom layout to do just this: https://gist.github.com/bryanculver/4c181881cca81d9963f49a77dd5ac127
> 
> Yes I know it's verbose but it was much easier to debug and is pretty performant.
> 
> What it does:
> 
>     * 1 window: entire screen
> 
>     * 2 windows: even split left and right of screen
> 
>     * 3 windows: first window is on left, 2nd and 3rd split vertically the right
> 
>     * 4 windows: all four corners (as you'd expect)
> 
>     * 5+ windows: window 1 is top left, window 2 is top right, window 3 is bottom left, windows 4+ vertically split the bottom right corner.

thank you so much for this!!!
