### ISSUE TITLE
Spaces problems

### ISSUE THREAD

**Issue by brabalan** [ianyh/Amethyst#11]
Hello,

First of all, thank you for this great project. I'm always looking for a nice tiling window manager for OS X and this looks very promising.

I'm having trouble with the spaces support. I did enable the ctrl-n keyboard shortcut, but when I do option-ctrl-n, I just switch to the space and but the window is not sent there. Am I doing something wrong?

(I'm using Total Spaces, but I see the problem even when it does not run.)

**Comment by kylechadha** [comment]
I thought this wasn't working for me and realized the issue is switching between spaces on different screens. Ie: I have spaces 1-4 on my mac screen and 5-7 on an external monitor. If on screen 1, I can switch (with the window moving) to screen 4, but not to screen 5.

**Comment by kylechadha** [comment]
Perhaps it has to do with different resolutions?

**Comment by mdbootstrap** [comment]
Facing the same issue. Some additional info from my side is that I have configured macOS to move all spaces at once (so I have space 1 on all 3 displays when I switch to second space, it will switch on all screens simultaneously).

**Comment by ianyh** [comment]
I think you are describing #121
