### ISSUE TITLE
Amethyst build fails out of the box

### ISSUE THREAD

**Issue by kozikow** [ianyh/Amethyst#110]
I tried to build Amethyst on the clean box.  It failed without giving the explanation. To solve the problem (manually) I had to:
0. Build (sudo rake install) failed 
1. open /tmp/Amethyst.dst/Applications/Amethyst.app
2. It popped out the accessibility access option and I had to grant access to Amethyst
3. I reran the build and it succeeded.

It may be confusing to new users, since it doesn't give the explanation. It would be nice if failing would give more information about what could happened.

I think it failed on the line:
/bin/chmod -RH u+w,go-w,a+rX /tmp/Amethyst.dst/Applications/Amethyst.app
I am not 100% sure, since it's new laptop and I don't have configured shell output history.

[Trello Card](https://trello.com/c/6kMiUOLd/39-amethyst-amethyst-build-fails-out-of-the-box)

**Comment by ianyh** [comment]
I think this may no longer be applicable as the relevant build method no longer exists. Please reopen if some other stage of the build process fails.
