### ISSUE TITLE
evenly sized rectangular tile per Desktop

### ISSUE THREAD

**Issue by rmheiberger** [ianyh/Amethyst#1101]
I just learned about Amethyst.  It does something related to what I am looking for.

Here is my usage pattern.

I have a Mac with an external monitor.  I usually have 3 desktops on the macbook display and 6 to 10 on the external display.
I can easily have 20 or more open pdf files on several of the external desktops.  Every time I reboot, all the pdf files are
placed in desktop 1 and most are opened very large.  I spend a few minutes moving things where I want them.

I finally did a search on "split Macintosh desktop" and decided Amethyst looked best.

Here is what I would like:
1. each desktop individually rearranged by amethyst, only on explicit command, and each potentially in a different pattern.
2. my initial desire for a Desktop is for a rectangular grid of equally sized thumbnails, one per window.  My model is Zoom's display.
3. When I work on a specific window I resize it.  I want all other windows on that Desktop to stay put so I can find them where I left them.
4. It would be wonderful if the window assignment could survive rebooting.

Thank you

**Comment by ianyh** [comment]
(1) and (3) seem counter to automatic tiling as a concept. You might consider a different tool, but you could potentially accomplish this with custom layouts.
