### ISSUE TITLE
Website has old brew cask install command

### ISSUE THREAD

**Issue by chmac** [ianyh/Amethyst#1108]
https://ianyh.com/amethyst/

    brew cask install amethyst

Instead of

    brew install --cask amethyst

As per the readme.

PS> Thanks for this EPIC software, really looking forward to getting stuck into these shortcuts.

**Comment by joshuayoerger** [comment]
Additionally, the `--cask` flag is not strictly necessary, although there might be benefits to including it that I am not aware of -`brew install amethyst` worked for me.

**Comment by joshuayoerger** [comment]
> although there might be benefits to including it

Looks like this was asked and answered over on the homebrew-cask repo:

> Occasionally the --cask flag is necessary if a Formula and a Cask share the same name, for example with dotnet.

https://github.com/Homebrew/homebrew-cask/issues/107145
