### ISSUE TITLE
Windows sometimes get to strange layout

### ISSUE THREAD

**Issue by kozikow** [ianyh/Amethyst#111]
Sometimes application window gets into weird state. It moves to the corner and I can't maximize it. Here is a screenshot of this situation happening:
![screen shot 2014-01-17 at 2 14 21 pm](https://f.cloud.github.com/assets/722866/1944987/0fc807f6-7fc5-11e3-9740-1c2ad84c324a.png) . When I try to move the window it goes back to it's old corner soon. 
It is usually happening right after waking my computer from sleep or unlock. 

I am even not 100% sure that Amethyst is a problem here, but it never happened before I used Amethyst . I did a clean computer station setup this week and I don't have any other app than Amethyst that could cause such error. Closing and opening the application again seem to fix the problem. Reopening the Amethyst doesn't fix the 

Please let me know if I could debug the problem, since when it happens it is really annoying.

[Trello Card](https://trello.com/c/QtwxNuRR/40-amethyst-windows-sometimes-get-to-strange-layout)

**Comment by ianyh** [comment]
@kozikow Do you know if this still happens?

**Comment by ifreecarve** [comment]
I've noticed a similar problem that comes from changing the number of connected displays -- a window might move itself largely off screen and decide it belongs there.  Is this what you're noticiing here?  I.e. that there is always some portion of the window's title bar that is offscreen when you observe this behavior?

**Comment by ianyh** [comment]
I'm not sure this is valid anymore. Let me know if it's still an issue.
