### ISSUE TITLE
Tall + Wide Layout or modified BSP

### ISSUE THREAD

**Issue by diocletiann** [ianyh/Amethyst#1111]
**Describe the solution you'd like**
I would like a layout where the main window occupies the left 50% of the screen, and the other 3 look like the Wide Layout, one taking up the remaining 50% with and the other two would be 25% width and 50% height. 

**Describe alternatives you've considered**
I tried BSP but all 3 secondary windows end up with 25% width. Basically I'd like to rotate the right half of BSP clockwise.

**Additional context**
This would allow me to have a large Firefox window, one 50% width Terminal window, and two 25% width messaging windows. thanks.

**Comment by corpooo** [comment]
![image](https://user-images.githubusercontent.com/12585256/114824291-5a134180-9dcd-11eb-8ddd-6a3aef1b537d.png)

If I understood correctly, then you can achieve this with BSP.

**Comment by diocletiann** [comment]
That's the desired layout. How did you get the top right tile into that shape?

**Comment by corpooo** [comment]
If you use BSP, after you have 2 windows open, when you focus the window on the right and open two new windows, they will automatically split this way.
