### ISSUE TITLE
Layouts for ultra widescreen 

### ISSUE THREAD

**Issue by subokita** [ianyh/Amethyst#1118]
**Describe the solution you'd like**
Is it possible to have layouts that maximizes usability of ultra wide screen?
E.g:
- 2 x 3 layout (left application takes 2/5 of the screen, right one, 3/5)
- 4 columns layout

**Comment by prandelicious** [comment]
For me, 3 columns is tolerable on 38-inch ultrawide screens. Would be nice if these layouts were user-configurable.

**Comment by PaddyPatPat** [comment]
I am trying to change the `Widescreen Tall` layout for just such a case. I know nothing about Swift but it appears that changing the `mainPaneRatio` within `WidescreenTallLayout.swift` to a number greater than `0.5` (a proportion of the screen width) would do it. So far I've been unable to see any change though. I was hoping for making the main pane take up something like 75% of the screen width, giving me room for 1-4 main pane windows beside the stack of secondary pane windows.

**Comment by slaughtr** [comment]
@PaddyPatPat - you can already accomplish that with the shrink/expand main pane keyboard shortcuts - mod1 + h/l

**Comment by PaddyPatPat** [comment]
Oh that's fantastic! Thank you for pointing that out @slaughtr.

**Comment by ianyh** [comment]
Closing this in favor of custom layouts if needed.
