### ISSUE TITLE
Error Loading Configuration dialog popup

### ISSUE THREAD

**Issue by drewauff** [ianyh/Amethyst#1122]
Everytime I launch or re-launch I am presented with this dialog.

![Screen Shot 2021-06-01 at 4 54 38 pm](https://user-images.githubusercontent.com/13850060/120280300-d8cf2a00-c2fa-11eb-9d84-d081548e25ef.png)

 - macOS:  Catalina 10.14.5
 - Amethyst: 0.15.4
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
```

~//ᵀ1m56s /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.15.4 (91)

OS version: Version 10.15.7 (Build 19H15)

Has permissions: true

Screens:
	(0.0, 0.0, 2880.0, 1800.0) [(0.0, 0.0, 2880.0, 1800.0)]

Manageable applications:
	talagent (com.apple.talagent)
	AppSSOAgent (com.apple.AppSSOAgent)
	iTerm2 (com.googlecode.iterm2)
	Hex Fiend (com.ridiculousfish.HexFiend)
	qBittorrent (org.qbittorrent.qBittorrent)
	Finder (com.apple.finder)
	Semulov (com.kainjow.Semulov)
	ueli (com.electron.ueli)
	TextBar (com.RichSomerfield.TextBar)
	1Keyboard (com.eyalw.1Keyboard)
	AdGuard for Safari (com.adguard.safari.AdGuard)
	Simplenote (com.automattic.SimplenoteMac)
	MacForge (com.macenhance.MacForge)
	storeuid (com.apple.storeuid)
	Activity Monitor (com.apple.ActivityMonitor)
	System Preferences (com.apple.systempreferences)
	Vivaldi (com.vivaldi.Vivaldi)

Configuration:
enables-layout-hud: 1
screen-padding-bottom: 1
screen-padding-right: 0
mouse-resizes-windows: 0
screen-padding-top: 0
restore-layouts-on-launch: 1
use-canary-build: 1
focus-follows-mouse: 0
window-minimum-width: 150
window-resize-step: 2
float-small-windows: 0
mod2: (
    option,
    shift,
    control
)
mouse-swaps-windows: 0
floating-is-blacklist: 0
mod1: (
    option,
    shift
)
debug-layout-info: 0
follow-space-thrown-windows: 1
window-minimum-height: 0
layouts: (
    tall
)
window-margins: 1
new-windows-to-main: 0
ignore-menu-bar: 1
screen-padding-left: 0
window-margin-size: 7.5
enables-layout-hud-on-space-change: 0
floating: (
        {
        id = "com.googlecode.iterm2";
        "window-titles" =         (
        );
    },
        {
        id = "com.vivaldi.Vivaldi";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.quicklook.qlmanage.plist";
        "window-titles" =         (
        );
    },
        {
        id = "com.mortenjust.flotato";
        "window-titles" =         (
        );
    }
)
mouse-follows-focus: 0

**Additional context**

Bloody Annoying.

**Comment by drewauff** [comment]
I tried launching it in terminal with sudo access, so far working without issues.

**Comment by ianyh** [comment]
What is at `~/.amethyst`?

**Comment by drewauff** [comment]
`{
    "LAYOUTS": "----------------------",
    "layouts": [
    ],

    "MODIFIERS": "----------------------",
    "Valid modifiers are": [
        "option",
        "shift",
        "control",
        "command"
    ],

    "mod1": [
    ],
    "mod2": [
    ],

    "COMMANDS": "----------------------",
    "Commands are": {
        "cycle-layout": "Cycle layout to the next layout",
        "cycle-layout-backward": "Cycle layout to the previous layout",
        "focus-screen-1": "Focus the main window on the first screen",
        "focus-screen-2": "Focus the main window on the second screen",
        "focus-screen-3": "Focus the main window on the third screen",
        "focus-screen-2": "Focus the main window on the second screen",
        "focus-screen-3": "Focus the main window on the third screen",
        "focus-screen-4": "Focus the main window on the fourth screen",
        "throw-screen-1": "Throw the focused window to the first screen",
        "throw-screen-2": "Throw the focused window to the second screen",
        "throw-screen-3": "Throw the focused window to the third screen",
        "throw-screen-4": "Throw the focused window to the fourth screen",
        "shrink-main": "Shrink the main pane of the current layout",
        "expand-main": "Expand the main pane of the current layout",
        "increase-main": "Increase the number of windows in the main pane",
        "decrease-main": "Decrease the number of windows in the main pane",
        "focus-ccw": "Move window focus counter-clockwise on the current screen",
        "focus-cw": "Move window focus clockwise on the current screen",
        "swap-ccw": "Swap focused window with the next window going counter-clockwi$
        "swap-cw": "Swap focused window with the next window going clockwise",
        "swap-main": "Swap focused window with the main window of its screen",
        "throw-space-1": "Throw the focused window to the first space",
        "throw-space-2": "Throw the focused window to the second space",
        "throw-space-3": "Throw the focused window to the third space",
        "throw-space-4": "Throw the focused window to the fourth space",
        "throw-space-5": "Throw the focused window to the fifth space",
        "throw-space-6": "Throw the focused window to the sixth space",
        "throw-space-7": "Throw the focused window to the seventh space",
        "throw-space-8": "Throw the focused window to the eighth space",
        "throw-space-9": "Throw the focused window to the ninth space",
        "throw-space-8": "Throw the focused window to the eighth space",
        "throw-space-9": "Throw the focused window to the ninth space",
        "toggle-float": "Toggle the focused window between being floating and tiled"
    },

    "screens": "3",

    "cycle-layout": {
        "mod": "mod1",
    },
    "cycle-layout-backward": {
        "mod": "mod2",
    },
    "select-tall-layout": {
        "mod": "mod1"
    },
    "select-wide-layout": {
        "mod": "mod1"
    },
    "select-fullscreen-layout": {
        "mod": "mod1"
    },
    "select-column-layout": {
        "mod": "mod1"
    },
        "mod": "mod1"
    },
    "focus-screen-1": {
        "mod": "mod1"
    },
    "focus-screen-2": {
        "mod": "mod1"
    },
    "focus-screen-3": {
        "mod": "mod1"
    },
    "focus-screen-4": {
        "mod": "mod1"
    },
    "throw-screen-1": {
        "mod": "mod2"
    },
    "throw-screen-2": {
        "mod": "mod2"
    },
    "throw-screen-3": {
        "mod": "mod2"
    },
    "throw-screen-4": {
        "mod": "mod2"
    "throw-screen-4": {
        "mod": "mod2"
    },
    "shrink-main": {
        "mod": "mod1"
    },
    "expand-main": {
        "mod": "mod1"
    },
    "increase-main": {
        "mod": "mod1"
    },
    "decrease-main": {
        "mod": "mod1"
    },
    "focus-ccw": {
        "mod": "mod1"
    },
    "focus-cw": {
        "mod": "mod1"
    },
    "swap-screen-ccw": {
        "mod": "mod2"
    },
    "swap-screen-cw": {
    },
    "swap-screen-cw": {
        "mod": "mod2"
    },
    "swap-ccw": {
        "mod": "mod2"
    },
    "swap-cw": {
        "mod": "mod2"
    },
    "swap-main": {
        "mod": "mod1"
    },
    "throw-space-1": {
        "mod": "mod2"
    },
    "throw-space-2": {
        "mod": "mod2"
    },
    "throw-space-3": {
        "mod": "mod2"
    },
    "throw-space-4": {
        "mod": "mod2"
    },

        "mod": "mod2"
    },
    "throw-space-5": {
        "mod": "mod2"
    },
    "throw-space-6": {
        "mod": "mod2"
    },
    "throw-space-7": {
        "mod": "mod2"
    },
    "throw-space-8": {
        "mod": "mod2"
    },
    "throw-space-9": {
        "mod": "mod2"
    },
    "toggle-float": {
        "mod": "mod1"
    },
    "toggle-tiling": {
        "mod": "mod2"
    },
    "display-current-layout": {
        "mod": "mod1"
    "display-current-layout": {
        "mod": "mod1"
    },

    "MISC": "----------------------",
    "floating": [],
    "float-small-windows": false,
    "mouse-follows-focus": false,
    "focus-follows-mouse": true,
    "enables-layout-hud": false,
    "enables-layout-hud-on-space-change": false
}
`

**Comment by drewauff** [comment]
as much as i liek dot files for configs, this one I didnt touch.

note: seems renaming the file did the trick.
