### ISSUE TITLE
Feature Request: Easier Custom Layout Configs

### ISSUE THREAD

**Issue by rraihansaputra** [ianyh/Amethyst#1126]
EDIT: I just realized this is a duplicate of https://github.com/ianyh/Amethyst/issues/51, but last activity on that issue is on 2019, so I hope bumping this is fine.

I wanted a modification of a currently existing layout, but currently the only way this is possible is by cloning, modifying, and rebuilding the Amethyst codebase. It would be really nice if we can configure it without buliding as with Karabiner-Elements/BitBar/other Mac customizing utilities.

I've modified and read a bit of the code for the layout, I think it's possible to have Amethyst interpret a JS (or even Swift) code to be user modifiable.

As for my own experience, I have to:
- Download the old Xcode (according to the project readme), 7GB and slow from the Apple servers
- Modify the code
- Build and copy the built app to my Applications folder

to have a Binary Space Partition - Right, and another layout from 3Column-Middle with a 40% empty space at the bottom of the main pane (so I can use my laptop screen in the middle of my 43" TV).

I understand it might be hard to integrate with Amethyst as it is, and through this I also want to ask whether are there other alternatives with custom Layout Configs.

I've tried `yabai` but there's just *too much* configuration on it. Maybe there's a way to have a "default" config of yabai that's closer to Amethyst.

I still want to thank everyone that has worked on Amethyst. It's a must have for me and If it's possible to have this config it would be more powerful for all of the users.

A list of open issues regarding custom/additional layouts:
https://github.com/ianyh/Amethyst/issues/1118 Ultra Widescreen: 2:3 horizontal split, 4 columns
https://github.com/ianyh/Amethyst/issues/1100 BSP-Right (mine)
https://github.com/ianyh/Amethyst/issues/1056 BSP-Middle
https://github.com/ianyh/Amethyst/issues/1093 Vertical Shrink
https://github.com/ianyh/Amethyst/issues/1074 Widescreen Tall Mid (3 Column Middle with Vertical Split on main pane)
https://github.com/ianyh/Amethyst/issues/984 Margin only on main window

**Comment by ianyh** [comment]
FYI I did a proposed pass on custom defined layouts. I could use feedback on it, though.

**Comment by rraihansaputra** [comment]
@ianyh will take a look at it, thank you so much 🙏

**Comment by munro** [comment]
Just want to throw out I would love this too!  The thing I would like to change is have Tall always be 2 columns, rarely do I want 1 window to take up the full screen—and it would be nice to be able to see my background esp if it's a cute one :}

So Tall with 1 window would look like this:
![Screen Shot 2021-08-06 at 10 40 33 AM](https://user-images.githubusercontent.com/500774/128527976-5db7627e-7997-42ce-83c5-ac48ac169a04.png)

**Comment by peregrinator** [comment]
@ianyh I'd be interested in test driving the JS based custom layouts in your draft PR. Where do you suggest I should look to get a sense of how to create one?

**Comment by ianyh** [comment]
Got a notarized build that people can try. https://github.com/ianyh/Amethyst/pull/1134#issuecomment-1066277237

**Comment by GreenBattery** [comment]
@munro @peregrinator I managed to put together a very simple custom-layout that divides the screen into 70% and 30%. The 70% is the main pane, only takes one window, never gets divided, and the 30% pane gets divided amongst all remaining windows.

This allows me to do things like have my main browser window or IDE open  in the main pane and smaller windows like file manager, chat client, ssh session etc in the smaller pane on my 28 inch monitors. No window ever gets to be fullscreen by default in this layout, which was also desirable. 

You might like it. See attached. 

They're named `Seventy-Thirty` and `Thirty-Seventy` to indicate on which side the large pane is.
[amethyst-layouts-70-30.zip](https://github.com/ianyh/Amethyst/files/9349368/amethyst-layouts-70-30.zip)

**Comment by GreenBattery** [comment]
@ianyh not sure if worth raising a new issue for, but is there some way to get debug/console logs when working on custom layouts? Also, is each screen in a multi-monitor layout treated independently when it comes to positioning windows -- that is, is coord x 0 at the beginning of the second screen, or is it the width of the first screen?

**Comment by ianyh** [comment]
> @ianyh not sure if worth raising a new issue for, but is there some way to get debug/console logs when working on custom layouts? Also, is each screen in a multi-monitor layout treated independently when it comes to positioning windows -- that is, is coord x 0 at the beginning of the second screen, or is it the width of the first screen? 

They are relative. The screen frame gives you the correct coordinates for the screen, though, so windows are relative to that origin.

**Comment by ianyh** [comment]
And there's no good debug mechanism. You can open a GitHub feature request to track. It seems reasonable, but I'm not sure how to do it off the top of my head.

**Comment by TLenfers** [comment]
@ianyh  Thank you for implementing custom layouts.
I'd like to implement custom screen padding for a specified layout to address different monitor sizes or assign specified screen padding to connected monitors.
Unfortunately, I cannot find a command for padding in the [custom layouts documentation](https://github.com/ianyh/Amethyst/blob/development/docs/custom-layouts.md). I think this would also solve this related issue #990

**Comment by ianyh** [comment]
You could do one in the layout. Just track padding in state and pad the frames.
