### ISSUE TITLE
Move focus clockwise is reversed in 3 column middle layout

### ISSUE THREAD

**Issue by dyckia** [ianyh/Amethyst#1132]
**Describe the bug**
In the 3 column middle layout, the move focus clockwise action moves focus in counter-clockwise and counter-clockwise moves focus in clockwise. 

**To Reproduce**
Multiple windows in 3 column middle layout. 

**Expected behavior**
Given the example layout in the screenshot, the expected order when moving the focus in clockwise is 1-2-3-4, while the actual moving order is 1-4-3-2.

<img width="2560" alt="Screen Shot 2021-07-06 at 22 44 26" src="https://user-images.githubusercontent.com/23126557/124686047-f91b7700-deac-11eb-8e95-12f76d05bbdb.png">

**Versions:**
 - macOS: 11.4 (20F71)
 - Amethyst: 0.15.4
 
**Debug Info**
```
Version: 0.15.4 (91)

OS version: Version 11.4 (Build 20F71)

Has permissions: false

Screens:
	(0.0, 0.0, 2560.0, 1440.0) [(0.0, 0.0, 2560.0, 1440.0)]

Manageable applications:
	talagent (com.apple.talagent)
	Finder (com.apple.finder)
	AppSSOAgent (com.apple.AppSSOAgent)
	Google Chrome (com.google.Chrome)
	iTerm2 (com.googlecode.iterm2)
	Code (com.microsoft.VSCode)
	PDF Expert (com.readdle.PDFExpert-Mac)
	Things (com.culturedcode.ThingsMac)
	Notes (com.apple.Notes)
	storeuid (com.apple.storeuid)
	Preview (com.apple.Preview)

Configuration:
layouts: (
    tall,
    column,
    "middle-wide"
)
new-windows-to-main: 0
screen-padding-right: 0
enables-layout-hud-on-space-change: 1
enables-layout-hud: 1
screen-padding-left: 0
mod2: (
    option,
    shift,
    control
)
window-margins: 0
follow-space-thrown-windows: 1
use-canary-build: 0
window-resize-step: 5
mouse-follows-focus: 0
focus-follows-mouse: 0
mod1: (
    option,
    shift
)
window-minimum-height: 0
ignore-menu-bar: 0
float-small-windows: 1
restore-layouts-on-launch: 1
screen-padding-top: 0
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.hegenberg.BetterTouchTool";
        "window-titles" =         (
        );
    }
)
floating-is-blacklist: 1
screen-padding-bottom: 0
debug-layout-info: 1
window-margin-size: 0
window-minimum-width: 0
```

**Comment by NoisomePossum** [comment]
Just my two cents: personally my expectation for the order would be 1-4-2-3. 

However, as dyckia noted, currently the layout treats the main window as if it were still all the way to the left as in the original 3-column layout so as you're cycling through sub windows focus appears to "skip" the main window in the middle until you've gone through all the sub windows and then when you try to move off the right side of the screen from the last sub-window focus moves counter-intuitively to the left instead to focus the "first" window (the main window).

**Comment by ianyh** [comment]
I think changes would be a job for a custom layout.

**Comment by lougreenwood** [comment]
@ianyh Could you elaborate on why this should be a custom layout?

Since the layout is called `3 _column_ middle` (emphasis on "column"), and we read top-to-bottom & left-to-right, the assumption would be that cycling through windows would vertically cycle through the left column first, then the middle, then the right.

So the order would be this assuming (ignore the empty row, I didn't see how to create a table in MD without a header on GH):

|   |   |   |
|---|---|---|
| 1 | 3 | 4 |
| 2 | 3 | 5 |

Or if there are even more windows in the "wing" columns:

|   |   |   |
|---|---|---|
| 1 | 4 | 5 |
| 2 | 4 | 6 |
| 3 | 4 | 7 |
| 4 | 4 | 8 |

That seems entirely reasonable & logical to me given the expectation's set up in how this layout is named. It's not called "2 row, 3 column middle"...

Thanks 🙏!

**Comment by ianyh** [comment]
Expectation is arguable. I'm not sure I'm even the one that implemented this in the first place, so there is at least one person whose expectations don't align.

Regardless, it's implemented the way it is, so modifying it as is would change behavior unexpectedly for people already using it, which means it would need to be a new layout. I added custom layouts specifically to avoid a proliferation of native layouts that need to be maintained.
