### ISSUE TITLE
Move focus clowkwise/counter clockwise gets broken by iTerm2 on macOS Monterey Beta

### ISSUE THREAD

**Issue by reuben** [ianyh/Amethyst#1137]
**Describe the bug**
iTerm2 seems to break the moving of focus between windows, I can move focus back and forth between all other windows on my Tall Right layout (also reproduced with Tall layout) and it works fine, but as soon as I focus iTerm2 it stops working, the focus is not actually changed by the shortcut, only the mouse cursor position gets updated (I have mouse follows focus enabled). And even the mouse cursor updating is wrong, it starts skipping the iTerm2 window as I use the shortcut back and forth.

I understand macOS Monterey is in beta so bugs are expected, I'm just filing for reference :)

**Applications:**
iTerm2, Firefox Nightly, Sublime Text 4

**To Reproduce**
1. Run macOS Monterey Beta (I did not notice this behavior before updating)
2. Have iTerm2 alongside other windows in a Tall or Tall Right layout.
2. Use "Move focus clockwise" shortcut to move focus to iTerm2 window, then out of it.

**Expected behavior**
Focus moves correctly between windows.

**Versions:**
 - macOS: Monterey 12.0 Beta (21A5268h)
 - Amethyst: 0.15.4 (91) - also reproduced on latest development - 2bab3ece525a99b55c5d56bba3cbaed1e69ecbe9
 
**Debug Info**
```
Version: 0.15.4 (91)

OS version: Version 12.0 (Build 21A5268h)

Has permissions: false

Screens:
	(0.0, 0.0, 3200.0, 1800.0) [(0.0, 0.0, 3200.0, 1800.0)]
	(3200.0, 750.0, 1680.0, 1050.0) [(3200.0, 0.0, 1680.0, 1050.0)]

Manageable applications:
	talagent (com.apple.talagent)
	AppSSOAgent (com.apple.AppSSOAgent)
	Finder (com.apple.finder)
	1Password 7 (com.agilebits.onepassword7)
	ServiceLauncher (net.java.openjdk.cmd)
	Mail (com.apple.mail)
	Sublime Text (com.sublimetext.4)
	coreautha (com.apple.LocalAuthentication.UIAgent)
	Dash (com.kapeli.dashdoc)
	Element (im.riot.app)
	Microsoft Word (com.microsoft.Word)
	Signal (org.whispersystems.signal-desktop)
	Firefox Nightly (org.mozilla.nightly)
	iTerm2 (com.googlecode.iterm2)

Configuration:
mod2: (
    option,
    shift,
    control
)
window-minimum-height: 0
focus-follows-mouse: 0
float-small-windows: 1
ignore-menu-bar: 0
use-canary-build: 1
screen-padding-right: 0
screen-padding-left: 0
enables-layout-hud-on-space-change: 1
layouts: (
    "tall-right",
    fullscreen
)
window-margins: 0
screen-padding-bottom: 0
floating-is-blacklist: 1
screen-padding-top: 0
window-minimum-width: 0
follow-space-thrown-windows: 1
new-windows-to-main: 0
mod1: (
    option,
    shift
)
mouse-follows-focus: 1
mouse-swaps-windows: 0
restore-layouts-on-launch: 1
window-resize-step: 5
window-margin-size: 10
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.iCal";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.installer";
        "window-titles" =         (
        );
    },
        {
        id = "com.viscosityvpn.Viscosity";
        "window-titles" =         (
        );
    },
        {
        id = "com.sublimemerge";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.print.PrinterProxy";
        "window-titles" =         (
        );
    },
        {
        id = "com.backup42.desktop";
        "window-titles" =         (
        );
    },
        {
        id = "org.mozilla.nightly";
        "window-titles" =         (
            Opening
        );
    },
        {
        id = "com.apple.reminders";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.QuickTimePlayerX";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.backup.launcher";
        "window-titles" =         (
        );
    }
)
enables-layout-hud: 1
debug-layout-info: 0
```

**Additional context**

**Comment by reuben** [comment]
It looks like this was due to Secure Keyboard Entry, which has been changed in macOS 12 and is more restrictive. Weirdly, it does not prevent Amethyst from detecting the keystroke, as the mouse jumps clockwise/counter-clockwise, but it does prevent the focus change, so the terminal remains focused. Disabling Secure Keyboard Entry (iTerm2 menu > Secure Keyboard Entry) fixes the problem. Might be worth including in docs. In any case, closing this for now.

**Comment by nocturnalnematode** [comment]
Just want to add that Secure Keyboard Entry also breaks "focus follows mouse" in the same manner.

EDIT: When the focus is trapped this way, you can still switch in between iterm windows using the keyboard or mouse, but not to any other app.
