### ISSUE TITLE
Chrome extension drop downs do not remain open as soon as mouse moves.

### ISSUE THREAD

**Issue by trombadore-google** [ianyh/Amethyst#1141]
**Describe the bug**
When Amethyst is running, I will click on an extension in chrome, its drop down menu will pop open as expected, but as soon as I move my mouse the extension's menu will instantly close. If I disable Amethyst, this does not occur. As soon as it is enabled, this occurs.

This make it impossible for me to interact with my chrome extensions when Amethyst is enabled.

**Applications:**
Amethyst 0.15.4

**To Reproduce**
Enable Amethys 0.15.4 on macos 11.5.1 (most current versions). Open chrome and try to interact with an chrome extension that has a drop down menu once you click on it.

**Expected behavior**
I should be able to interact with chrome extension drop down menus while amethyst is enabled.

**Screenshots**
n/a

**Versions:**
 - macOS: 11.5.1
 - Amethyst: 0.15.4
 
**Debug Info**
```
Version: 0.15.4 (91)

OS version: Version 11.5.1 (Build 20G80)

Has permissions: false

Screens:
	(0.0, 0.0, 1792.0, 1120.0) [(0.0, 0.0, 1792.0, 1120.0)]
	(-4000.0, -670.0, 1440.0, 2560.0) [(-4000.0, -770.0, 1440.0, 2560.0)]
	(-2560.0, -190.0, 2560.0, 1440.0) [(-2560.0, -130.0, 2560.0, 1440.0)]

Manageable applications:
	talagent (com.apple.talagent)
	AppSSOAgent (com.apple.AppSSOAgent)
	SmartCard Pairing (com.apple.ctkbind)
	Google Chrome (com.google.Chrome)
	Slack (com.tinyspeck.slackmacgap)
	TextEdit (com.apple.TextEdit)
	iTerm2 (com.googlecode.iterm2)
	Finder (com.apple.finder)

Configuration:
enables-layout-hud-on-space-change: 1
window-minimum-width: 0
floating: (
)
screen-padding-left: 0
focus-follows-mouse: 1
screen-padding-top: 0
mod2: (
    option,
    shift,
    control
)
enables-layout-hud: 1
screen-padding-bottom: 0
ignore-menu-bar: 0
screen-padding-right: 0
mod1: (
    option,
    shift
)
floating-is-blacklist: 1
debug-layout-info: 0
new-windows-to-main: 0
restore-layouts-on-launch: 1
follow-space-thrown-windows: 1
use-canary-build: 0
window-resize-step: 5
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
window-margins: 0
mouse-follows-focus: 0
window-minimum-height: 0
window-margin-size: 0
float-small-windows: 1
```

**Comment by jittapont** [comment]
I got this problem too.

**Comment by jinnatar** [comment]
- This seems to be caused by the option "Focus follows mouse", disabling that remedied the issue for me.
- This also happens to the main Chrome "three dots" menu if the window is small enough that the popped menu goes over the window border.
- Mac OS: macOS 11.6 (20G165)
- Amethyst: 0.15.4 (91)

**Comment by trombadore-google** [comment]
@Artanicus That solution fixed all my problems!! Thank you!
