### ISSUE TITLE
Not an issue, will close it asap.

### ISSUE THREAD

**Issue by officer47p** [ianyh/Amethyst#1145]
Hey all, quick question.
Where are the website files that are hosted here at [ianyh.com/amethyst](https://ianyh.com/amethyst/)?
I need to do some pull requests there and need to find out where those files are located.
Best regards.

**Comment by ianyh** [comment]
https://github.com/ianyh/ianyh.github.io

**Comment by officer47p** [comment]
Thanks a lot 🙏 
Will close it.
