### ISSUE TITLE
[Feature] Retain main window width in 3Column layouts if no other windows are open

### ISSUE THREAD

**Issue by DanielAsher** [ianyh/Amethyst#1147]
**Is your feature request related to a problem? Please describe.**
I use 3Column Middle layout all the time for my widescreen monitor. It's fantastic! My only grip is that when I close the other two windows, leaving only the main window, it expands the main window to full width. This is undesirable because I now have to crane my head to the left just to see what I'm typing.

**Describe the solution you'd like**
I would like the width of the main screen to remain steady even when it is the only window on the screen.

**Describe alternatives you've considered**
Always leave a second window open to allow the main window to retain a comfortable width.

**Comment by 4nt0n** [comment]
I would it be helpful if you could shrink the main pane even if there is only one window.

**Comment by pmsteil** [comment]
I agree with this feature request :)  Not a big deal as I usually have MANY windows open, but on some screens I do have only one :)

**Comment by jvansant** [comment]
This would be a great feature for a widescreen monitor!

**Comment by jvansant** [comment]
Current:
![image](https://user-images.githubusercontent.com/14235171/148595165-75b43415-d2ef-440c-b5ed-dd040fbf77d8.png)

Desired functionality (without windows on the sides):
![image](https://user-images.githubusercontent.com/14235171/148595106-544d3390-78b2-4d04-ac31-1a7ba6a36999.png)
AKA:
![image](https://user-images.githubusercontent.com/14235171/148595521-38924f7a-b6c8-4a59-9e5a-9894638ecc12.png)

**Comment by ianyh** [comment]
I think you can accomplish this by extending with a custom layout.
