### ISSUE TITLE
[Question] Is this project still being maintained?

### ISSUE THREAD

**Issue by Muzosh** [ianyh/Amethyst#1149]
@ianyh,
I see some PRs already merged and some more being open, but there is no new release for almost about a year.

I would be pity to lose support and development for this amazing app, which seems to be only alternative to security intrusive and confusing yabai.

Are there any plans to keep this project alive and maintain it, maybe just handling the PRs, etc?

**Comment by ianyh** [comment]
I still work on it and use it daily. The project isn't dead. I've just been to busy to do a whole release. There were some performance sensitive things I did that I wanted to get out on beta before doing a stable release. Hopefully I can find some time for that soon.

**Comment by Muzosh** [comment]
Thats lovely to hear!
