### ISSUE TITLE
The layout HUD is not shown when monitors are arranged vertically

### ISSUE THREAD

**Issue by Henkru** [ianyh/Amethyst#1162]
**Describe the bug**
The layout HUD is not shown for a secondary screen when screens are arranged vertically.

**To Reproduce**

1. Enable `Display layout when changing layouts` option in Preferences.
2. Arrange the position of the secondary monitor to either above or below of the main screen, see the screenshot.
3. Change the layout in the secondary screen.

**Expected behavior**
The layout HUD should appear in the middle of the secondary screen. 

**Screenshots**

<img width="780" src="https://user-images.githubusercontent.com/4019880/141165393-b548d66c-d777-4430-b1c4-dee806ea210c.png">

**Versions:**

 - macOS: 12.0.1
 - Amethyst: 0.15.5

**Debug Info**

```
Version: 0.15.5 (92)

OS version: Version 12.0.1 (Build 21A559)

Screens:
	(0.0, 0.0, 1512.0, 982.0) [(0.0, 0.0, 1512.0, 982.0)]
	(-178.0, 982.0, 1920.0, 1080.0) [(-178.0, -1080.0, 1920.0, 1080.0)]

Configuration:
mod1: (
    option,
    shift
)
window-resize-step: 5
mod2: (
    option,
    shift,
    control
)
layouts: (
    tall,
    fullscreen
)
float-small-windows: 1
mouse-follows-focus: 1
window-margins: 1
follow-space-thrown-windows: 1
mouse-swaps-windows: 1
window-minimum-width: 0
enables-layout-hud: 1
new-windows-to-main: 0
mouse-resizes-windows: 1
screen-padding-right: 0
screen-padding-bottom: 0
debug-layout-info: 0
screen-padding-top: 0
enables-layout-hud-on-space-change: 0
use-canary-build: 0
window-margin-size: 10
ignore-menu-bar: 0
focus-follows-mouse: 0
floating: (
)
floating-is-blacklist: 1
window-minimum-height: 0
smart-window-margins: 0
restore-layouts-on-launch: 1
screen-padding-left: 0
```

**Additional context**
This may be Silica related issue since the reported rectangle looks weird in [here](https://github.com/ianyh/Amethyst/blob/a831dd82a9d53b8bc16c0feba2e62ed03bf09989/Amethyst/Managers/ScreenManager.swift#L316):

```
screenFrame	CGRect	(origin = (x = -178, y = -1080), size = (width = 1920, height = 1080))	
```

**Comment by coreygrunewald** [comment]
I also experience this issue with a monitor arranged vertically above my laptop screen. Thank you @Henkru for creating a PR!  🎉
