### ISSUE TITLE
Application assigned to all desktops doesn't get managed by amethyst

### ISSUE THREAD

**Issue by llimllib** [ianyh/Amethyst#1164]
edit: I updated the title to reflect the actual source of the issue, see [this comment](https://github.com/ianyh/Amethyst/issues/1164#issuecomment-969245147)

**Describe the bug**
When I open obsidian, it isn't controlled by amethyst

**Applications:**
Obsidian 0.12.19

**To Reproduce**

1. open obsidian, note that it does not follow the layout

**Expected behavior**
Obsidian follows the layout

**Screenshots**

https://user-images.githubusercontent.com/7150/141803726-d9f51234-d129-4adb-b5e1-2de1340ad09a.mov

**Versions:**
 - macOS: 12.0.1
 - Amethyst: 0.15.5
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info --include-apps
Version: 0.15.5 (92)

OS version: Version 12.0.1 (Build 21A559)

Screens:
	(0.0, 0.0, 3360.0, 1890.0) [(0.0, 0.0, 3360.0, 1890.0)]
	(3360.0, 54.0, 1512.0, 982.0) [(3360.0, 854.0, 1512.0, 982.0)]

Configuration:
window-minimum-width: 0
new-windows-to-main: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
mod1: (
    option,
    shift
)
enables-layout-hud: 1
floating-is-blacklist: 1
screen-padding-top: 0
focus-follows-mouse: 0
debug-layout-info: 1
screen-padding-bottom: 0
ignore-menu-bar: 0
mod2: (
    option,
    shift,
    control
)
window-margin-size: 11
float-small-windows: 1
window-resize-step: 5
restore-layouts-on-launch: 1
window-minimum-height: 0
follow-space-thrown-windows: 1
use-canary-build: 0
screen-padding-left: 0
window-margins: 1
screen-padding-right: 0
floating: (
)
enables-layout-hud-on-space-change: 1
mouse-follows-focus: 0

Manageable applications:
	Google Chrome (com.google.Chrome)
	iTerm2 (com.googlecode.iterm2)
	talagent (com.apple.talagent)
	Finder (com.apple.finder)
	AppSSOAgent (com.apple.AppSSOAgent)
	Spotify (com.spotify.client)
	Slack (com.tinyspeck.slackmacgap)
	Fastmail (llc.gumbs.multi.Fastmail)
	Firefox (org.mozilla.firefox)
	Obsidian (md.obsidian)
```

(for some reason, I don't get the "Manageable applications" part of the output that some other reports have, that might be useful

update: found `--include-apps` by reading the source, the issue template might want to be updated with that option)

**Additional context**
Obsidian is installed via homebrew cask, and isn't particularly modified or anything. Other applications when opened snap to the layout as expected

Also, I can repro on either screen, I just did it on the smaller screen to make the video more manageable

**Comment by Signynt** [comment]
Weird, Obsidian works just fine for me with Amethyst (I installed it via the installer and not brew though). Do you have any applications where you've disabled Amethyst for?

**Comment by llimllib** [comment]
I just installed Amethyst this morning and have not customized it in any way, so I suspect I haven't disabled Amethyst for any apps

**Comment by llimllib** [comment]
Update: I know why this happened! I forgot I had set Obsidian to be enabled on all desktops, and Amethyst wasn't getting it for that reaosn

<img width="476" alt="image" src="https://user-images.githubusercontent.com/7150/141842078-fd2670b4-12e7-4c10-8307-f98fcfe988f7.png">

Setting "Assign to" to "none" fixed the issue. I'm not sure exactly what Amethyst ought to do in this situation, so feel free to close this.

(I don't think this is _ideal_ behavior, but it's super tricky to say what exactly should happen)

**Comment by xgt001** [comment]
I had a similar issue with my browser window. Thank you for detailing the issue and mentioning the workaround. I was pulling my hair figuring out what was happening :D

**Comment by bioe007** [comment]
i get this is old/closed but how is it not a bug? 

"sticky" windows are common in lots of window and desktop managers - not just tiling ones. It seems amethyst is clearly doing the wrong thing here. 

I discovered the same bug today and this was the top/most-relevant hit, apologies for the necrobump but it seems like this is the first/only mention and should be turned into an open bug or feature request.

**Comment by bioe007** [comment]
never mind, i looked a bit better and found this here: https://github.com/ianyh/Amethyst/issues/1047

sorry for the noise.

**Comment by apasias** [comment]
Why is this closed?

**Comment by rublev** [comment]
> Why is this closed?

Yeah how do I get an "all desktops" window to not float?

**Comment by ianyh** [comment]
I didn't close it, but it is a duplicate of #1047
