### ISSUE TITLE
Is there a way to swtich to a specific Desktop?

### ISSUE THREAD

**Issue by humbienri** [ianyh/Amethyst#1165]
**Describe the solution you'd like**
I see a hotkey command to throw a given window to a specific Desktop but is there a way to switch over to a specific Desktop? No not Command+Tab. In my case, I tend to have about 6 to 8 Desktops with Firefox or Chrome windows in each of the Desktops so it's not straightforward to use Command+Tab as sometimes that doesn't actually switch me to another Desktop.

Is there a way to, say, directly switch from Desktop 1 to Desktop 6 and back 'n forth?

In advance, thank you for your time and Amethyst!

**Comment by llimllib** [comment]
just another vote for this feature: I would love to have shortcuts for "focus space 1", "focus space 2", ..etc

**Comment by llimllib** [comment]
oops, I googled and it's available in the keyboard shortcuts preference pane in OS X, just unselected by default:
<img width="661" alt="Screen Shot 2021-11-16 at 1 42 17 PM" src="https://user-images.githubusercontent.com/7150/142046151-c11afb7a-8a12-4af2-b48f-2a062d31193e.png">

**Comment by humbienri** [comment]
Awesome! Guess I should have looked for a OS specific approach first. Thanks for the info @llimllib!

**Comment by pmsteil** [comment]
Yes and if you go ahead and create the max number of spaces (16), you will then see all of them in that list so you can create hotkeys for them... 

First thing I setup on MacOS! :)

**Comment by humbienri** [comment]
I'm new to MacOS. Can you tell?! Thanks for the tidbit about the 16 maximum.
