### ISSUE TITLE
Focus top window of a screen in fullscreen layout

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#117]
When switching screens, Amethyst selects the first window in the list of windows.  This is problematic when using the fullscreen layout, as an undesired window is focused.

Some info at the bottom here (#104)

Solution would be to have each screen manager store the last focused window before switching to another screen manager.  Then when it is next focused, focus that window instead of just focusing the first window.

Steps to reproduce.

Open two windows in the fullscreen layout, have the second window that was opened focused.
Swap focus to another screen.
Swap focus back, the window on the bottom of the stack is now focused, instead of the window that was displayed.

[Trello Card](https://trello.com/c/5loGrSUL/41-amethyst-keep-track-of-last-focused-window-in-a-screen)

**Comment by ianyh** [comment]
So the focus follows mouse code does some interesting stuff for finding the top-most window which we could do to solve the fullscreen window problem, which I think is the most egregious example of this.
