### ISSUE TITLE
Layoutception

### ISSUE THREAD

**Issue by jvansant** [ianyh/Amethyst#1178]
I would like to emulate the functionality of toggling the vscode terminal and file explorer using the Mac Terminal and Finder. All while maintaining a layout to be used with all other applications. 

I believe that this would require assigning the terminal and finder applications to specific zones in a primary/container layout. Then an additional/secondary layout would need to be enabled within that primary/container to manage all other windows per usual. The primary layout would still have a set of shortcuts to give more space to the Finder/Terminal when necessary. I use the application [Thor](https://apps.apple.com/us/app/thor-launcher/id1120999687?mt=12) to use keyboard shortcuts to focus open applications and toggle applications open/hidden. With this enabling moving focus and toggling the terminal/finder open/hidden the "move focus clockwise/counter clockwise" shortcuts could be used solely to move focus between the "secondary" 3column middle layout. Here is an outline:
![3cm](https://user-images.githubusercontent.com/14235171/148589953-6406ddb8-a624-4be8-a79a-371888d66fa1.jpg)
![full](https://user-images.githubusercontent.com/14235171/148589968-6b0df74b-5d55-42e7-bd24-012ee63c7645.jpg)

I've attempted to float Terminal and Finder with a 3column layout. This is very close but the floated windows require moving around with the mouse as they tend to cover up the main windows.
![image](https://user-images.githubusercontent.com/14235171/148589766-142bf95c-a15c-47ea-ad8f-0d89de8bbe46.png)

I've also attempted to utilize just the wide layout. Although it is close, the functionality of certain shortcuts don't work in the desired way.  
- Toggling Terminal and Finder: The thor shortcuts work fine to focus windows when they are already open and in the correct layout zone. However, when an application is hidden amethyst of course moves all the windows up the stack by default. 
![image](https://user-images.githubusercontent.com/14235171/148588258-dc87cf23-ffe3-4f19-98b1-38b9d8c8aac5.png)
![image](https://user-images.githubusercontent.com/14235171/148588277-93256a9f-809a-4dfc-ada9-a86d5bcd12bd.png)
As you can see the pseudo 3 column layout I created by having two primary windows with the Wide layout crumbles when the terminal is hidden. This means the terminal and finder windows must never be hidden.
- Moving between windows: To mimic vscode I prefer to use Thor shortcuts to focus Terminal (ctrl + `) and Finder (ctrl + f). This would allow amethyst to reserver the "Move focus clockwise/counter clockwise" to the other primary windows. Of course, there is no way to leave Finder and Terminal out of this focus movement without floating them.

**Comment by slaughtr** [comment]
For what it's worth, you could get more or less the functionality you desire here by using iTerm and configuring a hotkey window. If you set the title of said hotkey window to a static value, you can set it to be ignored by Amethyst and avoid any reflows.

**Comment by ianyh** [comment]
I am going to say that this can be a custom layout, but is probably otherwise outside the scope of the application.
