### ISSUE TITLE
Switch main pane and make it the one in the center (not just fullscreen)

### ISSUE THREAD

**Issue by oscarcalderonc** [ianyh/Amethyst#1188]
**Is your feature request related to a problem? Please describe.**
I'm not sure if I'm using this incorrectly or it doesn't work in that way. Let's suppose I open

1. `browser` first
2. `text editor` second and
3. `video player` third

I can switch the layout with `mod1 + Space` and works fine. Then I switch the focus with `mod1 + k` and main pane is now the `text editor`.

If I do `mod1 + d`, `text editor` becomes fullscreen which is correct; but then when I start switching the layouts with `mod1 + Space`  to `3 Column middle` layout, I expect that the `text editor` will be the window that will be at the center as the main column; or if I switch to `Wide`, I expect `text editor` will be expanded to the whole width of the window, but no. It is `browser` the one that is still the main pane, although the focus is on `text editor`.

**Describe the solution you'd like**
That when you change focus to another window, and you change the layout, that window I switched the focus to, becomes the one in the center

**Describe alternatives you've considered**
Not sure, maybe I'm not using correctly.

**Additional context**

**Comment by martin-braun** [comment]
You change the main pane by doing `mod2 + j` or `mod2 + k` like so: https://youtu.be/GaIPWp071jM?t=521

Changing the focus won't make it the main pane, swapping the windows so the correct window is in the left main pane area makes it the main pane.

It took me a while to get it, the shortcut descriptions are hard to understand. "Swap focussed window counter clockwise" is not easy to interpret.

**Comment by oscarcalderonc** [comment]
> It took me a while to get it, the shortcut descriptions are hard to understand. "Swap focussed window counter clockwise" is not easy to interpret.

You're right, that's what I was looking for. As you said, the descriptions are a bit confusing, not so helpful to reducing the learning curve. Thank you very much
