### ISSUE TITLE
GitHub Sponsoring

### ISSUE THREAD

**Issue by martin-braun** [ianyh/Amethyst#1190]
I can't believe this awesome app is free. I wish to support development, especially through GitHub Sponsoring (because that gives a nice badge). 

Can this be made possible? :)

**Comment by max-sixty** [comment]
I would also sponsor!

**Comment by macsmister** [comment]
Bump. I would so sponsor this project with recurring payments. This project alone makes macOS bearable... otherwise I would run straight to the Fedora/SwayWM hills most likely. 😂

**Comment by ianyh** [comment]
I truly appreciate the sentiment, but I don't have a ton of time to dedicate to this so getting paid for it feels disingenuous.

**Comment by martin-braun** [comment]
@ianyh Well, this is very fair from you and I absolutely understand. If you ever want to dedicate more time to this, please change your mind. Honest work deserves honest appreciation. 

Thank you for Amethyst whatsoever. 🙏🏻

**Comment by dakyskye** [comment]
I would also sponsor! amazing software, feels very Linuxy 🤗
