### ISSUE TITLE
Throwing windows to other spaces doesn't work.

### ISSUE THREAD

**Issue by shahriarfahim870** [ianyh/Amethyst#1199]
**Describe the bug**
Nothing happens after pressing shortcut keys to throw windows to different spaces.

**Applications:**
Safari, Finder, iTerm2, Brave, VScode, etc. This happens on basically all applications I've tested except Amethyst's preferences window. 

**To Reproduce**
After setting up everything including my spaces using the docs, I press the shortcut keys, and nothing happens. Even when I avoid using remapped keys (i.e., pressing shift+control+option instead of pressing caps_lock), nothing changes. The only time the shortcuts behave as expected is when I try using the shortcuts with the Amethyst preferences window in focus. 

**Expected behavior**
The window in focus being thrown to the space specified by the shortcut in use. 

**Screenshots**
<img width="1369" alt="Screen Shot 2022-02-15 at 2 38 01 PM" src="https://user-images.githubusercontent.com/61814633/154136319-d0f64ded-cca9-4f17-8cd5-f4c3aff238bf.png">
_This is me testing whether the system is registering my key-press combinations  as I would expect using Karabiner Event Viewer. It seems like there is nothing wrong with the key-press combinations._

*caps_lock is remapped to shift+control+option
*mod1 = shift + control + option 
*mod2 = shift + control + option + command
First key combo: command + caps_lock + 2 [current shortcut for throwing to space 2]
Second key press: caps_lock + 3 [shortcuts I've tried using before]

**Versions:**
 - macOS: 12.2.1
 - Amethyst: 0.15.5
 
**Debug Info**
```
Version: 0.15.5 (92)

OS version: Version 12.2.1 (Build 21D62)

Screens:
	(0.0, 0.0, 1680.0, 1050.0) [(0.0, 0.0, 1680.0, 1050.0)]

Configuration:
restore-layouts-on-launch: 1
float-small-windows: 1
use-canary-build: 1
new-windows-to-main: 0
mouse-resizes-windows: 1
window-minimum-height: 0
window-minimum-width: 0
mouse-follows-focus: 0
screen-padding-right: 0
mod1: (
    shift,
    control,
    option
)
window-margin-size: 5
mouse-swaps-windows: 1
window-margins: 1
screen-padding-bottom: 0
floating-is-blacklist: 1
screen-padding-left: 0
window-resize-step: 5
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    bsp
)
ignore-menu-bar: 0
smart-window-margins: 1
follow-space-thrown-windows: 0
mod2: (
    shift,
    control,
    option,
    command
)
debug-layout-info: 0
focus-follows-mouse: 0
floating: (
        {
        id = "com.apple.ActivityMonitor";
        "window-titles" =         (
        );
    },
        {
        id = "com.facebook.archon";
        "window-titles" =         (
        );
    },
        {
        id = "desktop.WhatsApp";
        "window-titles" =         (
        );
    },
        {
        id = "com.flyvoip.wifiapplite";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.AppStore";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.calculator";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.iBooksX";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Chess";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.AddressBook";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Dictionary";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.FaceTime";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.findmy";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Home";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.launchpad.launcher";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Maps";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.MobileSMS";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.exposelauncher";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Music";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.news";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.reminders";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Stickies";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.TV";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.podcasts";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.VoiceMemos";
        "window-titles" =         (
        );
    },
        {
        id = "com.spotify.client";
        "window-titles" =         (
        );
    },
        {
        id = "com.TickTick.task.mac";
        "window-titles" =         (
        );
    },
        {
        id = "com.cleverfiles.DiskDrill";
        "window-titles" =         (
        );
    },
        {
        id = "com.macpaw.CleanMyMac4";
        "window-titles" =         (
        );
    },
        {
        id = "io.mpv";
        "window-titles" =         (
        );
    },
        {
        id = "ru.keepcoder.Telegram";
        "window-titles" =         (
        );
    },
        {
        id = "org.pqrs.Karabiner-Elements.Preferences";
        "window-titles" =         (
        );
    },
        {
        id = "org.pqrs.Karabiner-EventViewer";
        "window-titles" =         (
        );
    },
        {
        id = "com.avast.AAFM";
        "window-titles" =         (
        );
    },
        {
        id = "com.adguard.safari.AdGuard";
        "window-titles" =         (
        );
    },
        {
        id = "com.microsoft.teams";
        "window-titles" =         (
        );
    },
        {
        id = "org.videolan.vlc";
        "window-titles" =         (
        );
    },
        {
        id = "com.magoshare.AweUninser";
        "window-titles" =         (
        );
    },
        {
        id = "com.KevinDeKoninck.Clean-Me";
        "window-titles" =         (
        );
    },
        {
        id = "io.gechr.WhichSpace";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.calculator";
        "window-titles" =         (
        );
    }
)
enables-layout-hud-on-space-change: 0
enables-layout-hud: 1
screen-padding-top: 0

```

**Additional context**
_My environment_
My device is MacBook Air with the M1 chip. I previously used Yabai + skhd + Karabiner-elements, but I uninstalled and cleaned Yabai completely before installing Amethyst. I re-installed and re-configured skhd to only keep shortcuts unrelated to window management. On Karabiner-elements, I have caps_lock remapped to shift+control+option, and caps_lock+command remapped to shift+control+option+command. 

_Configuring shortcuts_
I've tried to configure the shortcuts in two ways to see if that would make a difference: 
1. Changing the relevant shortcuts using the GUI manually.
2. Configuring the file '/opt/homebrew/Caskroom/amethyst/0.15.5/Amethyst.app/Contents/Resources/default.amethyst', then removed '~/Library/Preferences/com.amethyst.Amethyst.plist' using terminal, and restarted Amethyst. 

_Other info_
- Remapped keys don't interfere with other shortcuts on Amethyst (e.g., moving focus, swapping focused window, changing layout, etc). All of those other actions behave perfectly as expected with the remapped caps_lock key. So, seems like using remapped keys is not causing this (combined with the fact that uninstalling Karabiner-elements did not change anything)
- I've tested whether the system is registering my key-press combinations normally using Karabiner Event Viewer(as shown on screenshot), and it seems like that they are being registered as expected.
- I used to use Amethyst in the past (on the same device on macOS Big Sur), and all the shortcuts behave perfectly as expected back then. But then I switched to Yabai+skhd after doing a clean uninstallation of Amethyst, and now switched back to Amethyst again due to Yabai being extremely buggy.   

**Steps I have taken to try to fix this (in no particular order)**
- Uninstalled Karabiner-elements and restarted the computer to see if not using remapped keys change anything
- Reinstalled Amethyst with Karabiner-elements removed and tried using default shortcuts on Amethyst without any modifications
- Uninstalled skhd completely
- Relaunching Amethyst (of course)

**Comment by ClonedOne** [comment]
It's being discussed here: https://github.com/ianyh/Amethyst/issues/1192#issue-1116787349
You could add your post there

**Comment by alexander-blackwell** [comment]
The issue is still not fixed and there is still no new release, I've checked quite a few times now.

**Comment by ianyh** [comment]
There's a prerelease. https://github.com/ianyh/Amethyst/releases/tag/v0.15.6b

**Comment by ianyh** [comment]
Duplicates #1192
