### ISSUE TITLE
Cannot Throw focus window to other spaces(desktops)

### ISSUE THREAD

**Issue by shubham-cpp** [ianyh/Amethyst#1208]
**Describe the bug**
Unable to move windows from one workspace to another.

**Applications:**
Google Chrome,Kitty and everthing else

**To Reproduce**
```bash
brew install --cask amethyst
```

**Expected behavior**
<code>Ctrl + Option + Shift + {Left,Right}</code> should throw focused window to left or right space(workspace)
Also
<code>Ctrl + Option + Shift + {1,2,3,4}</code> is also not working

**Screenshots**
I've read through readme as well as #625 
<img width="780" alt="Screenshot 2022-02-28 at 9 37 45 AM" src="https://user-images.githubusercontent.com/31388020/155922474-bcbd76c6-6e50-4f3e-8930-86f2540a5a20.png">

**Versions:**
 - macOS: 12.2.1 (21D62)
 - Amethyst: 0.15.5(92)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
```

<details>

<summary> Debug Info </summary>

```
Version: 0.15.5 (92)

OS version: Version 12.2.1 (Build 21D62)

Screens:
	(0.0, 0.0, 1792.0, 1120.0) [(0.0, 0.0, 1792.0, 1120.0)]

Configuration:
screen-padding-top: 0
follow-space-thrown-windows: 1
restore-layouts-on-launch: 1
float-small-windows: 1
window-minimum-height: 0
screen-padding-right: 0
window-margins: 0
window-margin-size: 0
enables-layout-hud: 1
focus-follows-mouse: 0
debug-layout-info: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
mod2: (
    option,
    shift,
    control
)
window-minimum-width: 0
enables-layout-hud-on-space-change: 1
ignore-menu-bar: 0
screen-padding-bottom: 0
mod1: (
    option,
    shift
)
new-windows-to-main: 0
floating: (
)
mouse-follows-focus: 0
floating-is-blacklist: 1
use-canary-build: 0
screen-padding-left: 0
window-resize-step: 5

```

</details>

**Comment by rob-226** [comment]
Duplicate of #1199 and #1184 - 'Throw Window To Spaces' not working on MacOS 12.2.x on current release (0.15.5) - awaiting release update.

**Comment by shubham-cpp** [comment]
Yes, sure 🙌

**Comment by smokracek** [comment]
This, to me, is a bit of a deal-breaker bug and I hope it can be addressed soon.

**Comment by shubham-cpp** [comment]
Hi @rob-226, after install 0.15.6(93), it seems to solve the problem.

`Ctrl + Option + Shift +{Left,Right, 1-4}` works as expected.

Great work 🙌🏾
