### ISSUE TITLE
Cannot throw to a space on a different screen

### ISSUE THREAD

**Issue by simon-weber** [ianyh/Amethyst#121]
With two displays and a space on each, throwing from one space to the other with the `mod-#` shortcut doesn't work. The grabbing icon just stays up until I click the mouse.

Throwing to the other display with eg `mod-e` does work. Is this related to #9?

[Trello Card](https://trello.com/c/Khtsvuxd/42-amethyst-cannot-throw-to-a-space-on-a-different-screen)

**Comment by ddickstein** [comment]
+1 this would be very helpful
