### ISSUE TITLE
Question: what does the "Swap focused window to counter clockwise screen" mean?

### ISSUE THREAD

**Issue by LoneFireBlossom** [ianyh/Amethyst#1214]
Hello, I'm new to Amethyst. I find it useful enough so now I try to understand all its function.
Now I can't understand the meaning of "Swap focused window to counter clockwise screen". What does **swap** mean? Dictionary says swap means **exchange**, so what is the focused window exchanged with?
I use iPad sidecar, and try to use the shortcut. I find it maybe "**throw** focused window to counter clockwise screen". But it looks like strange:
![IMG_0090](https://user-images.githubusercontent.com/50087596/156916617-d1081a25-d170-4c74-a863-8ca9f5b8ff30.gif)
Do I understand correctly?

Monterey 12.3 Beta (21E5227a)

**Comment by dustin-cowles** [comment]
@LoneFireBlossom You might stand a better chance of a reply posting in [Discussions](https://github.com/ianyh/Amethyst/discussions). Issues are generally used for reporting bugs or requesting features.
