### ISSUE TITLE
How to jump to a certain space?

### ISSUE THREAD

**Issue by gadmyth** [ianyh/Amethyst#1223]
Can I jump to a certain space using mod1 + [number] ?

**Comment by cybardev** [comment]
@gadmyth You can configure that from the MacOS System Preferences:

![image](https://user-images.githubusercontent.com/50134239/160268947-e330a48c-4c74-4f66-9330-890b73485995.png)

**Comment by gadmyth** [comment]
> @gadmyth You can configure that from the MacOS System Preferences:
> 
> ![image](https://user-images.githubusercontent.com/50134239/160268947-e330a48c-4c74-4f66-9330-890b73485995.png)

I suggest this guide picture should be included in the READE.md
