### ISSUE TITLE
Throw focused window to screen n - it doesn't "stick" there - only after retrying n times

### ISSUE THREAD

**Issue by jonasrk** [ianyh/Amethyst#1229]
**Describe the bug**
Throw focused window to screen n - it doesn't "stick" there - only after retrying n times

**Applications:**
E.g. Slack but I'm assuming most of them.

**To Reproduce**
When I try to e.g `Throw focused window to screen 1` with `mod2 + w` it moves the windows but it immediately jumps back. I keep hitting `mod2 + w` and eventually it will stick after a few times.

Not sure if relevant, but I mostly have all my windows full screen at all times.

**Expected behavior**
-
**Screenshots**
-

**Versions:**
 - macOS:  12.3.1 (21E258)
 - Amethyst: 0.15.6 (93)
 
**Debug Info**
```
Version: 0.15.6 (93)

OS version: Version 12.3.1 (Build 21E258)

Screens:
	(0.0, 0.0, 1920.0, 1080.0) [(0.0, 0.0, 1920.0, 1080.0)]
	(-1440.0, 180.0, 1440.0, 900.0) [(-1440.0, 0.0, 1440.0, 900.0)]

Configuration:
focus-follows-mouse: 0
use-canary-build: 0
enables-layout-hud: 1
window-margins: 0
screen-padding-top: 0
window-minimum-width: 0
window-resize-step: 5
mod2: (
    option,
    shift,
    control
)
new-windows-to-main: 0
ignore-menu-bar: 0
debug-layout-info: 0
floating-is-blacklist: 1
enables-layout-hud-on-space-change: 1
screen-padding-right: 0
screen-padding-left: 0
mouse-follows-focus: 0
layouts: (
    fullscreen,
    column,
    wide,
    bsp
)
window-minimum-height: 0
float-small-windows: 1
screen-padding-bottom: 0
follow-space-thrown-windows: 1
restore-layouts-on-launch: 1
mod1: (
    option,
    shift
)
floating: (
)
window-margin-size: 0
```

**Additional context**
-

**Comment by brandonkboswell** [comment]
This happens to me as well. I'm not sure the cause, but relaunching Amethyst is what I end up doing when this occurs. It's happening to me about 1-3 times per day.

**Comment by nguyendv** [comment]
This also happens to me and it's also gone when I relaunch Amethyst.

**Comment by danielxul** [comment]
I have the same issue. I also opened an issue weeks ago regarding this.

**Comment by illettante** [comment]
This might be another symptom of AXEnhancedUserInterface accessibility property interfering as seen in #1257, #1276 is the proposed fix, i have high hopes.

**Comment by max-sixty** [comment]
I've been getting this more recently when moving a window to the monitor with a menu bar. 

(Though I've had it a lot over the past few months, and don't remember that was the case prior, so possibly it's not the only / main cause)

**Comment by jonasrk** [comment]
Does anyone know if there are any fixes for this in the pipeline?
