### ISSUE TITLE
Feature Request: A shortcut to return to the last layout used

### ISSUE THREAD

**Issue by DanielAsher** [ianyh/Amethyst#1231]
**Is your feature request related to a problem? Please describe.**

Quickly going back to the last layout requires remembering which layout is active and what shortcut is required.

I often want to quickly flip to full screen layout and back.

**Describe the solution you'd like**
A shortcut to return to the last layout used

**Describe alternatives you've considered**
Using the correct shortcut

**Additional context**

**Comment by Bellavene** [comment]
Best would be a toggle for fullscreen layout

**Comment by BeansIsFat** [comment]
I agree that a toggle for fullscreen would be a very useful feature.

**Comment by ianyh** [comment]
Two questions:
1. Are unique shortcuts for each layout too many?
2. Would a toggling shortcut for layouts scratch that itch? That is to say, the command for a layout switches to that layout or switches back from that layout depending on whether or not the layout is active.

**Comment by pmsteil** [comment]
Hey guys, here is what I do as a cool workaround / configuration:

I set my hotkeys to:

CTRL+OPTION+COMMAND 2 - to use "Two Pane"
CTRL+OPTION+COMMAND 3 - to use "3 column middle"
CTRL+OPTION+COMMAND 9 - to use "Fullscreen"
CTRL+OPTION+COMMAND 0 - to use "Floating"

It is an amazing way to use Amethyst, try it!



*#end--Patrick Steil |  *infraNET <http://www.infranet.com/>

Senior eCommerce Architect

Mobile: 940-391-9250
LinkedIn:  http://linkedin.com/in/pmsteil
Schedule Meeting <https://calendly.com/pmsteil/meet>

**Comment by ianyh** [comment]
Layout toggling implemented in #1358.
