### ISSUE TITLE
"Move focus to main window" should also move focus back

### ISSUE THREAD

**Issue by rickythefox** [ianyh/Amethyst#1234]
**Is your feature request related to a problem? Please describe.**
When working in TwoPane mode I'd like to be able to easily switch between the main pane and the stack.

**Describe the solution you'd like**
There is a shortcut for "Move focus to main window" which does nothing if the focus is already on the main window. This shortcut should instead switch focus as per above.

Example: I have window A in the main pane and windows B and C in the right pane (the stack) with B on top. A and B are now visible on the screen. "Move focus to main window" moves focus between A and B. C is not affected and remains hidden behind B.

**Describe alternatives you've considered**
Tried using both the "swap focus" and the "move focus" shortcuts, none of those do what I want. 

**Additional context**
N/A

If this would be an acceptable solution I could submit a PR.

**Comment by nikonikoniko** [comment]
If I am not mistaken, PR #1241 addresses the swapping of the main window, but not the focus of the main window in the TwoPane layout.  I am still looking for a way to swap focus back and forth between the main pane and the secondary pane, without flipping through the stack.

Am I missing something, or was the focus-switching not included in that PR?

Thank you!

**Comment by brush701** [comment]
Same issue here. Two pane is great, but if the main pane is focused then moving focus cw/ccw generally doesn't select the window currently displayed on the second pane. Instead it puts focus on whatever window is at the top/bottom of the Amethyst stack, which is not usually the currently visible one. This is a significant usability problem, as toggling between panes is probably the most common action I want to take.

**Comment by rickythefox** [comment]
@brush701 agreed, create an issue please, I'll try to submit a PR if @ianyh is ok with that change.

**Comment by ianyh** [comment]
That would be a welcome contribution.
