### ISSUE TITLE
Disable Amethyst in certain desktops

### ISSUE THREAD

**Issue by StathisKap** [ianyh/Amethyst#1236]
**Is your feature request related to a problem? Please describe.**
I want to have diffent desktops for different workflows. I want amethys to work on some of those workflows but not others

**Describe the solution you'd like**
Set amethyst to always be disabled or enabled on some desktops but not others

**Describe alternatives you've considered**
Manually toggling it. But that's tedious and ruins the layout of desktops that i don't want tiled

**Comment by ianyh** [comment]
You can use the floating layout for this. Just set it for the desktop you don't want tiling enabled for.

**Comment by StathisKap** [comment]
Oh ok. Thank you a lot.
Can I set the floating layout as default, and only enable tiliing in others?

**Comment by StathisKap** [comment]
never mind. Found it. Just reordered the layouts in the list. Thanks a lot :)
