### ISSUE TITLE
Single Window Tile Options

### ISSUE THREAD

**Issue by b4rlw** [ianyh/Amethyst#1239]
**Is your feature request related to a problem? Please describe.**
When only one window is open, it seems that every layout fills the full display space by default (except for float). For ultrawide monitors, this results in a bad user experience for many applications.

**Describe the solution you'd like**
An option to tile a single window to the main pane of whatever layout is selected.

**Describe alternatives you've considered**
Put layout in float mode when working with one window.

**Additional context**
Example:
    3 column middle: one window takes up the main pane -- approximately the middle third of the display.

**Comment by ianyh** [comment]
This can be accomplished with custom layouts.
