### ISSUE TITLE
MPV opened from CLI will not tile, but when opened from MPV.app it will...

### ISSUE THREAD

**Issue by dsambrano** [ianyh/Amethyst#1253]
**Describe the bug**
When calling MPV from the command line the app doesn't get tiled (and the tile/float toggle shortcut does nothing). However, when opening it via spotlight search it does get properly tiled. 

**Applications:**
What applications are involved?
MPV video viewer 

**To Reproduce**
From the terminal open mpv with `mpv path_to_video.mov` it will not be tiled. But when opening view a spotlight search (cmd + space; shortcut) this will be properly tiled. 

mpv was installed via `brew install --cask mpv`

**Screenshots**

**Versions:**
 - macOS: 12.2.1
 - Amethyst: 0.15.6 (93)

**Comment by ianyh** [comment]
I bet it doesn't have a bundle identifier when launched via cli.

**Comment by Bellavene** [comment]
You can open it from cli with open command. What do you want to achieve at the end? Is it piped with something?

**Comment by dsambrano** [comment]
I was specifically using this package (https://github.com/whoisYoges/anime-terminal), but when it wasn't working I was doing some testing and realized if I just open mpv from with the CLI and open a local file it still doesn't get tiled with Amethyst. It only gets tiled if I open MPV via spotlight search (or equivalent) and then open the file, but that means I can't have it programmatically set.
