### ISSUE TITLE
Add favicon to website

### ISSUE THREAD

**Issue by shahmilav** [ianyh/Amethyst#1254]
## Is your feature request related to a problem? Please describe.
I use the Amethyst [website](https://ianyh.com/amethyst/) often when trying to remember keybinds, as I am still learning the software. It always seems to annoy me that there is no favicon for the website.

## Describe the solution you'd like
Add a favicon. It can be added by adding this line in the ```<head></head>``` tag:
```html
<link rel="icon" href="/images/amethyst.png">
```

## Describe alternatives you've considered**
Not have favicon?

### Before (no favicon)
<img width="435" alt="Screen Shot 2022-06-01 at 10 59 51 PM" src="https://user-images.githubusercontent.com/53659750/171543765-8e6ac709-95ef-4126-aaa6-665f3f28a5a6.png">

### After (yes favicon)
<img width="435" alt="Screen Shot 2022-06-01 at 10 59 26 PM" src="https://user-images.githubusercontent.com/53659750/171543716-3a0f295b-338a-4be3-8eca-b1b0b3224646.png">

![favicon](https://ianyh.com/images/amethyst.png) Logo makes a good favicon

**Comment by ianyh** [comment]
Added. Thanks for the idea. https://github.com/ianyh/ianyh.github.io/commit/dd11cd06be146bfb7336d62422dfe22ea1313cf3
