### ISSUE TITLE
Keymaps do not work in v0.16.0 beta via config file

### ISSUE THREAD

**Issue by antonk52** [ianyh/Amethyst#1266]
**Describe the bug**
Key mappings are not picked up from the config file

**Applications:**
Chrome+Alacritty(reproduces with other applications as well)

**To Reproduce**
- Download and launch Amethyst v0.16.0(94) from release's [assets](https://github.com/ianyh/Amethyst/releases/tag/v0.16.0b)
- Create `~/.amethyst.yml` with a key mapping from the [sample config](https://github.com/ianyh/Amethyst/blob/def9a496b121b136d97bd2c713640b6112e78b7a/.amethyst.sample.yml#L17-L20) content
  ```yml
  relaunch-amethyst:
      mod: mod2
      key: x
  ```
- Relaunch amethyst via menubar icon
- Verify that it is still v0.16.0
- Try to relaunch main by pressing <kbd>mod2</kbd> + <kbd>x</kbd>
- **not relaunched**
- Try default mapping <kbd>mod2</kbd> + <kbd>z</kbd>
- **relaunched**

**Expected behavior**
Amethyst picks up key mappings from config file and applies them

**Versions:**
 - macOS: 12.3.1
 - Amethyst: v0.16.0(94)
 
**Debug Info**
```
▲ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.16.0 (94)

OS version: Version 12.3.1 (Build 21E258)

Screens:
	(0.0, 0.0, 3840.0, 2160.0) [(0.0, 0.0, 3840.0, 2160.0)]
	(3840.0, 0.0, 1792.0, 1120.0) [(3840.0, 1040.0, 1792.0, 1120.0)]

Configuration:
focus-follows-mouse: 0
restore-layouts-on-launch: 1
mod2: (
    option,
    shift,
    control,
    command
)
use-canary-build: 1
screen-padding-bottom: 0
ignore-menu-bar: 0
screen-padding-top: 0
new-windows-to-main: 0
smart-window-margins: 1
enables-layout-hud-on-space-change: 1
debug-layout-info: 1
window-margins: 1
window-resize-step: 5
window-minimum-height: 0
floating: (
)
follow-space-thrown-windows: 1
window-margin-size: 12
screen-padding-left: 0
mouse-follows-focus: 0
mod1: (
    option,
    shift,
    command
)
enables-layout-hud: 1
floating-is-blacklist: 1
layouts: (
    tall,
    wide,
    column,
    fullscreen,
    bsp
)
window-minimum-width: 0
float-small-windows: 1
screen-padding-right: 0
```

**Additional context**
I have noticed that other options in the config are picked up such as mouse-follows-focus / focus-follows-mouse / window-margins / window-margin-size and I only ran into problems with key mappings. The debug info seem to indicate the same

**Comment by ianyh** [comment]
So this is interesting because based on my investigation this should never have worked.

**Comment by antonk52** [comment]
@ianyh can you please expand what you mean?

I am not sure wether I misread something from a sample config file or if the issue is valid and keymaps supposed to be picked up from the config file.

Thanks

**Comment by ianyh** [comment]
Oh sorry for the confusion. I verified the issue, but configuration files have always been supported with json just not really documented, and it seems like logically this bug has been around for a very long time.

**Comment by bradfordwagner** [comment]
@ianyh  thank you for the fix. I'm trying to switch to yml configs I absolutely love the feature!. Is it possible to drop a patch release? Or could you point me how to install this patch.
