### ISSUE TITLE
Support XDG Base Directory Specification for `amethyst.yml`

### ISSUE THREAD

**Issue by erikw** [ianyh/Amethyst#1268]
First of all, thanks for providing a configuration file, I really appreciate to be able to check in my configuration in a source control system.

# Background
Lately the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) has been gaining quite a steady [popularity](https://wiki.archlinux.org/title/XDG_Base_Directory#Support), even though it's been around for a long time already. The basic idea is to standardize where programs put their files e.g. all config files in a certain directory. The benefits for end users are many, including:

* No polluted $HOME/
* Can easily grep for only config files in `$XDG_CONFIG_HOME`
* Can decide where to store configurations in more complex setups (multi system setup e.g.)
* Easily wipe state by removing `$XDG_STATE_HOME` or even `$XDG_DATA_HOME`, but without destroying and configuration files.

The first point is maybe what most end users enjoy the most though.

# How
Specifically for this project, this should mean that the search for the configuration file should be done like:

1. **If** `$XDG_CONFIG_HOME` is *set*, look for `$XDG_CONFIG_HOME/amethyst/amethyst.yml`
1. **elseIf** `$XDG_CONFIG_HOME` is *unset*, use the default value for the envvar which is `$HOME/.config`. Thus, the config file to look for is at `$HOME/.config/amethyst/amethyst.yml`
1. **else** fall-back to current legacy `$HOME/.amethyst.yml`

The first two steps to can be codifed in bash like:
 `${XDG_CONFIG_HOME:-$HOME/.config}/amethyst/amethyst.yml`

**Comment by ianyh** [comment]
Seems super reasonable. Would be a good starter contribution.

**Comment by DitchComfort** [comment]
Yes I’m definitely voting for XDG based directory for the config file(s). When you have pretty much everything organized this way, my OCD freaks out when my home directory starts to get messy.
