### ISSUE TITLE
Use alt + shift + mouse-click to send the window to main panel?

### ISSUE THREAD

**Issue by ipstone** [ianyh/Amethyst#1278]
Sometimes there are a lot of movements when I am trying to send current window to the main panel - as the need to move my hands from mouse to keyboard.

I am wondering if it would be a good feature to add, such as alt+shift+click, would send the current window to the main panel? - perhaps this can be achieved with some key automations, but a builtin solution would be nice.

Thanks!

**Comment by ianyh** [comment]
I don't really have a plan to incorporate click commands. It would have to be implemented from the ground up, and there are already keyboard (swap window with main) and mouse (drag it over to the main window) solutions implemented for this.
