### ISSUE TITLE
tiled focus layout

### ISSUE THREAD

**Issue by mavwolverine** [ianyh/Amethyst#1279]
Suggestion for a large screen.

Split the screen into 4 (col) x 3(row) (could be based on space available).
Leave top center 2 x 2 empty. This the main window slot.
Arrange all windows as tiles in the remaining slots.
The window that is currently in focus, automatically moves to the main window slot. If another window is brought into focus, move the current window back to its original position, and move the new window to the main slot.

NOTE: this could be problematic if focus on mouse is enabled.

**Comment by ianyh** [comment]
This is possible with custom layouts, I think.
