### ISSUE TITLE
Window jumps to different screen when cycling through layouts

### ISSUE THREAD

**Issue by BearOutThere** [ianyh/Amethyst#1281]
**Describe the bug**
When i cycle through the selected layouts using keyboard shortcut at some point one of the application windows jumps to the next screen by itself.

**Applications:**
Any application

**To Reproduce**
1.  In Amethyst preferences select layouts in the following order:  Wide, 3Column Middle, Column, Two Pane, Row
2.  Relaunch Amethyst
3.  Start cycling through layouts using keyboard shortcut.
4.  After 3Column Middle one of the apps jumps to the next screen

**Expected behavior**
Apps should not change screens during cycling through the layouts.  They should not change screens unless explicitly made to. 

**Screenshots**

**Versions:**
 - macOS:  12.4
 - Amethyst: 0.15.6 (93)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

**Additional context**
[Screen Recording 2565-07-11 at 21.39.23.mov.zip](https://github.com/ianyh/Amethyst/files/9085066/Screen.Recording.2565-07-11.at.21.39.23.mov.zip)

**Comment by Bellavene** [comment]
Turn off "Restore layouts on launch"

**Comment by BearOutThere** [comment]
Thank you.  I misinterpreted what that setting meant.

**Comment by Bellavene** [comment]
No. It is just buggy.
