### ISSUE TITLE
I need help with custom layout

### ISSUE THREAD

**Issue by alloc33** [ianyh/Amethyst#1285]
Is there any custom layout that I can apply for these window positions or is it possible to use cycle focus with floating windows?
<img width="1440" alt="Screen Shot 2022-08-03 at 9 33 19 AM" src="https://user-images.githubusercontent.com/45129790/182505350-ca6089a2-f18a-4958-b919-d7241ac14486.png">

**Comment by cbochs** [comment]
I have been playing with custom layouts using the v0.16-beta (and recently v0.16 release) for a little bit. Here is a static 3-pane vertical layout that might help get you started:

```js
function layout() {
    return {
        name: "_Stacked3Pane",
        getFrameAssignments: (windows, screenFrame) => {
            // Layout:
            // [--1--]
            // [--2--]
            // [--3--]
            return windows.reduce((frames, window, index) => {
                return {
                    ...frames,
                    [window.id]: {
                        x: screenFrame.x,
                        y: screenFrame.y + (index / 3.00) * screenFrame.height,
                        width: screenFrame.width,
                        height: screenFrame.height / 3,
                    }
                }
            }, {})
        },
    }
}
```
