### ISSUE TITLE
Question: Is it problematic to use Amethyst with software like Alt-Tab package?

### ISSUE THREAD

**Issue by pdelfino** [ianyh/Amethyst#1286]
Hi,

Congrats for the work. Looks cool. I have a narrow experience with tilling window managers.

And I am also using this [Alt Tab software]( https://github.com/lwouis/alt-tab-macos)

Any chance of collision? Should I disable it before trying Amethyst?

Thanks

**Comment by ianyh** [comment]
Out of the box, nope no collision.

**Comment by pdelfino** [comment]
Thanks. I am closing the issue and keep up the good work!
