### ISSUE TITLE
Store settings and keybindings as a dotfile

### ISSUE THREAD

**Issue by mrafaeldie12** [ianyh/Amethyst#1289]
**Describe the solution you'd like**
It would be nice if the amethyst config and keybindings where stored as a dotfile (or something similar) that could be easily versioned, such as something stored in .config

**Comment by gsteen** [comment]
Have you seen [configuration-files.md](https://github.com/ianyh/Amethyst/blob/development/docs/configuration-files.md)

**Comment by mrafaeldie12** [comment]
Will check it out, thanks!
