### ISSUE TITLE
Should have mirrored layouts

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#129]
For example, a tall layout with the main pane on the right instead of the left.

[Trello Card](https://trello.com/c/NXNXuEyA/46-amethyst-should-have-mirrored-layouts)

**Comment by christickner** [comment]
Any chance of this coming soon? My monitor setup would really appreciate it. Thanks for an awesome app!

**Comment by fgoodman** [comment]
Would really appreciate this.

**Comment by lesniewski** [comment]
This would be great - I think I could replace slate with Amethyst if it had this.

**Comment by ianyh** [comment]
I think this is more technically feasible now that resizing behavior goes through one place. You could just invert all of the frames along one axis. I'm not sure what the configuration would look like.

**Comment by cdisselkoen** [comment]
Although we don't have a general solution for this at the moment, looking at the existing layouts many of them have mirrors available; for instance, `Tall` (the original motivation for this bug) has `Tall-Right`.  The most notable layouts missing mirrors are `Widescreen-Tall` and `Wide` (which we could have a main-on-bottom version).  Technically, layouts like `Column` and `Row` could also have mirrors, which would only matter for how the resizing-main-pane shortcuts behave.  Is there a desire to "manually" add mirrored versions of some of these layouts?  Or are we looking for a more general solution?

**Comment by ianyh** [comment]
I think a more general approach would be good. I want to avoid doubling the number of layouts.

**Comment by iandoesallthethings** [comment]
I know this issue has been sitting around for a couple years, but is there any movement on it? I'd love to have a hotkey or a checkbox to just flip a layout. (i.e. row with the main window on the bottom)

**Comment by ianyh** [comment]
I think this is either doable with custom layouts or there may be enhancements to custom layout definitions that should be a separate issue. Going to close this for now.
