### ISSUE TITLE
Amethyst float rust applications

### ISSUE THREAD

**Issue by alloc33** [ianyh/Amethyst#1298]
Amethyst ignores (or float) rust GUI applications such as Alacritty and Neovide. Is there any way to fix that?

**Comment by deevus** [comment]
Seeing this as well. Alacritty seems fine, but Neovide stays floating no matter what I do.

**Comment by alloc33** [comment]
> Seeing this as well. Alacritty seems fine, but Neovide stays floating no matter what I do.

Actually I found a solution - use Yabai. (Even if you need to disable SIP partially, it's worth it)

**Comment by alloc33** [comment]
> Seeing this as well. Alacritty seems fine, but Neovide stays floating no matter what I do.

But if you still prefer to use Amethyst - try to build Neovide from source (also depends how do you run it)

**Comment by Chris-Gillis** [comment]
I built Neovide from source because it crashed on launch downloading the binary. The Neovide window is still permanently floating. I haven't found a solution for this but if I do I'll come back here.

**Comment by alloc33** [comment]
> I built Neovide from source because it crashed on launch downloading the binary. The Neovide window is still permanently floating. I haven't found a solution for this but if I do I'll come back here.

how do you run it?

**Comment by Chris-Gillis** [comment]
‘neovide .’ In the directory I am trying to open in.

**Comment by alloc33** [comment]
if you use macOS you can try to run bundled executable which should be at this path after ```cargo bundle``` command ```.../neovide/target/release/bundle/osx/Neovide.app/Contents/MacOS/neovide```

**Comment by Chris-Gillis** [comment]
Thanks! I’ll try that when I am able to and report back.

**Comment by Chris-Gillis** [comment]
That worked perfectly! Previously I was running Neovide out of the cargo binaries in `~/.cargo/bin`
