### ISSUE TITLE
Windows always resized after throwing onto another space

### ISSUE THREAD

**Issue by noel-yap** [ianyh/Amethyst#1302]
**Describe the bug**
I used to be able to throw the active window onto another space with specified hotkeys and it would do so without resizing the window but ever since I updated, while the throwing still works, the window is maximized.

**Applications:**
This behavior occurs regardless of which application it is.

**To Reproduce**
Throw active window onto another space.

**Expected behavior**
Window is thrown onto the space and it remains the same size.

**Versions:**
 - macOS: 12.5.1
 - Amethyst: 0.16.0 (94)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```
Version: 0.16.0 (94)

OS version: Version 12.5.1 (Build 21G83)

Screens:
	(0.0, 0.0, 2560.0, 1080.0) [(0.0, 0.0, 2560.0, 1080.0)]

Configuration:
mod1: (
    option,
    shift
)
window-minimum-width: 0
mod2: (
    option,
    shift,
    control
)
enables-layout-hud: 0
window-margins: 0
mouse-follows-focus: 0
screen-padding-left: 0
ignore-menu-bar: 0
window-margin-size: 0
screen-padding-bottom: 0
floating: (
)
enables-layout-hud-on-space-change: 0
restore-layouts-on-launch: 0
debug-layout-info: 0
screen-padding-right: 0
focus-follows-mouse: 0
window-resize-step: 5
layouts: (
)
use-canary-build: 0
follow-space-thrown-windows: 1
screen-padding-top: 0
new-windows-to-main: 0
window-minimum-height: 0
floating-is-blacklist: 1
float-small-windows: 1

**Comment by dustin-cowles** [comment]
Could this be related to #1270? EDIT: and/or #1300

**Comment by noel-yap** [comment]
Yes, it looks to be a dup of https://github.com/ianyh/Amethyst/issues/1300
