### ISSUE TITLE
5 Column Middle Layout

### ISSUE THREAD

**Issue by oguzbilgic** [ianyh/Amethyst#1323]
I just switched to a 49 Inch monitor from a dual 27-inch monitor setup, my goal was to look at the middle of the screen instead of tilting my head right or left for my main window. To accomplish this with amethyst, the only possible solution is 3 column middle, however in this case, there are fewer columns than what was possible on a dual monitor setup (2 columns on each = 4), so I was wondering if it's possible to have a 5 column setup where the main window is in the middle of the screen.

**Comment by ianyh** [comment]
You can use custom layouts. https://github.com/ianyh/Amethyst/blob/development/docs/custom-layouts.md
