### ISSUE TITLE
Max number of windows per Space

### ISSUE THREAD

**Issue by whoislou** [ianyh/Amethyst#1325]
**Is your feature request related to a problem? Please describe.**

It would be lovely to predefine a default max number of windows per space.

This way if we're happy with a current layout, launching a new app doesn't disturb that flow.

**Describe the solution you'd like**

Set max windows per space in preferences (personally three is a magic number)

**Describe alternatives you've considered**
Spaces doesn't seem to offer this

**Additional context**
I'm aware that Spaces in general offers a bunch of things that users are seemingly requesting of the Amethyst devs. I get the perspectives of both but something seems lacking.

It would be fun if we could interop where needed somehow. In the case of max winds/pane scenario for example.

**Comment by whoislou** [comment]
I'll need to teach myself some Swift UI before I can get my hands dirty, it'll happen, just not too soon.

Thanks for this awesome tool btw.

**Comment by ianyh** [comment]
See #1083.

**Comment by whoislou** [comment]
Thanks, sorry still getting used to open source etiquette. Appreciate you!

**Comment by ianyh** [comment]
No worries. And thank you!
