### ISSUE TITLE
"PowerToys Fancy Zones"-like mouse control of windows

### ISSUE THREAD

**Issue by Austin1** [ianyh/Amethyst#1345]
One of the features I miss the most from Fancy Zones is the ability to left click on a menu bar of any application, then press the right mouse button and the current layout selected appears on the screen and you can essentially sling the window into the layout you've selected. As someone who is old and recently switched from Windows to Mac, my keyboard shortcut memory is abysmal and for some reason this way is more visual and intuitive to me.

You can see more specifics of how it works here: https://learn.microsoft.com/en-us/windows/powertoys/fancyzones

Here is a GIF of the action, its very quick, but the first GIF I could find showing it. https://smhn.info/wp-content/uploads/2020/12/Fancyzones.gif

**Comment by ianyh** [comment]
That seems somewhat counter to the idea of automatic tiling window management. You define a layout algorithm rather than manually adjusting window position and size. You might be happier with something like Rectangle or Magnet, which seems closer to FancyZones.
