### ISSUE TITLE
Amethyst GUI config is silently ineffective when there is yml file

### ISSUE THREAD

**Issue by yahiaelgamal** [ianyh/Amethyst#1348]
**Describe the bug**
I forgot that I had setup a yml file for amethyst config. Kept changing the preferences using the GUI but it kept disappearing

**Applications:**
What applications are involved?
NA

**To Reproduce**
- Use any .amethyst file
- open preferences
- change anything 
- relaunch amethyst
- 

**Expected behavior**
a. show a warning that there is yml file, and this what should be used
b. or, use yml file settings, then apply GUI settings. 

**Screenshots**
NA

**Versions:**
 - macOS:  Ventura
 - Amethyst:  13.0.1
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
Version: 0.16.0 (94)

OS version: Version 13.0.1 (Build 22A400)

Screens:
	(0.0, 0.0, 1352.0, 878.0) [(0.0, 0.0, 1352.0, 878.0)]

Configuration:
mod1: (
    option,
    shift
)
follow-space-thrown-windows: 1
layouts: (
    fullscreen,
    "two-pane",
    "middle-wide",
    "tall-right",
    floating
)
mouse-resizes-windows: 1
focus-follows-mouse: 0
float-small-windows: 1
use-canary-build: 0
floating-is-blacklist: 1
screen-padding-bottom: 0
window-minimum-height: 0
window-margin-size: 0
mouse-follows-focus: 1
debug-layout-info: 0
mod2: (
    option,
    shift,
    control
)
restore-layouts-on-launch: 0
screen-padding-right: 0
window-resize-step: 5
new-windows-to-main: 0
floating: (
        {
        id = "com.apple.iCal";
        "window-titles" =         (
        );
    },
        {
        id = "com.spotify.client";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.ActivityMonitor";
        "window-titles" =         (
        );
    }
)
window-minimum-width: 0
ignore-menu-bar: 0
screen-padding-top: 0
screen-padding-left: 0
enables-layout-hud: 1
window-margins: 0
mouse-swaps-windows: 1
enables-layout-hud-on-space-change: 1
```

**Comment by ianyh** [comment]
There _is_ a warning. Are you sure you didn't tell it to stop warning you?

**Comment by yahiaelgamal** [comment]
I can't be 100% sure, but I don't recall this happening on this brand new computer (that's why I was configuring it in the first place). 

I also did a `brew uninstall` and a fresh `brew install` multiple times, but the same behaviour persisted. Should a fresh install reset the warning state?

**Comment by agoodshort** [comment]
I was curious, did some digging and learned something about `brew uninstall` which I guess will help here.

In your case, you most probably received the warning and ticked "Do not show this message again", which added `"disable-dotfile-conflict-warning" = 1` in `com.amethyst.Amethyst.plist` (use `defaults read com.amethyst.Amethyst.plist` to check)

---

To my point about about `brew uninstall` => it does not delete the `plist` by default. So when you reinstalled, you kept your preferences.
However, there is a flag you can use to do a clean uninstall: `brew uninstall --zap --cask amethyst` (reference: [Cask Cookbook documentation](https://docs.brew.sh/Cask-Cookbook#stanza-zap)) which will remove your `plist`, hence reset the flag.
Some other stuff will be removed too when using `--zap` see [Amethyst Cask definition](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/amethyst.rb)

---

Based on the above, there is **in my opinion** 2 ways for you to show this warning again:
1. Edit your current `plist` to display the warning again => `defaults delete com.amethyst.Amethyst.plist disable-dotfile-conflict-warning`
2. Clean reinstall using homebrew =>`brew reinstall --zap --cask amethyst`

**Comment by yahiaelgamal** [comment]
Thanks a lot @goodshort, I didn't know about the --zap option in brew

**Comment by max-sixty** [comment]
At risk of peanut-gallery suggesting:

Rather than a silence-able pop-up, would it make sense to have this as a message on the Amethyst preferences pane?

**Comment by ianyh** [comment]
Could be reasonable depending on the design, but it's actually dismissible because people got annoyed at it popping up all the time so I can imagine people getting annoyed at it in the UI all the time.
