### ISSUE TITLE
Phantom Windows when using Arc browser

### ISSUE THREAD

**Issue by bengolds** [ianyh/Amethyst#1350]
**Describe the bug**
When using the [Arc browser](https://arc.net/), there appear to be phantom windows when tiling. 

**Applications:**
Arc browser, any other application.

**To Reproduce**
1) Open Arc browser
2) Set Amethyst to Tall layout

**Expected behavior**
The windows next to Arc tile correctly. Instead, they act as if there's an invisible 3rd window.

**Screenshots**
![CleanShot 2022-12-05 at 15 12 19@2x](https://user-images.githubusercontent.com/446007/205763455-41d4b18d-0109-4ef1-932c-58e1dc5f4e08.png)
![CleanShot 2022-12-05 at 15 10 03@2x](https://user-images.githubusercontent.com/446007/205763464-5a3bb769-aeb0-475b-8c25-e67699cf0936.png)
![CleanShot 2022-12-05 at 15 09 47@2x](https://user-images.githubusercontent.com/446007/205763469-492d7928-10fc-4514-b5a0-bf8c9a0a8a95.png)

**Versions:**
 - macOS: 13.0.1
 - Amethyst: 0.16.0
 
**Debug Info**
```
Version: 0.16.0 (94)

OS version: Version 13.0.1 (Build 22A400)

Screens:
	(0.0, 0.0, 2560.0, 1440.0) [(0.0, 0.0, 2560.0, 1440.0)]
	(2560.0, -172.0, 1440.0, 900.0) [(2560.0, 712.0, 1440.0, 900.0)]
	(-1180.0, -603.0, 1180.0, 820.0) [(-1180.0, 1223.0, 1180.0, 820.0)]

Configuration:
window-margins: 0
screen-padding-left: 0
restore-layouts-on-launch: 1
mouse-resizes-windows: 1
use-canary-build: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    "middle-wide"
)
follow-space-thrown-windows: 1
window-minimum-width: 0
screen-padding-right: 0
mouse-follows-focus: 0
ignore-menu-bar: 0
window-resize-step: 5
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.iphonesimulator";
        "window-titles" =         (
        );
    }
)
float-small-windows: 1
mod1: (
    option,
    shift
)
debug-layout-info: 1
screen-padding-bottom: 0
enables-layout-hud-on-space-change: 1
focus-follows-mouse: 0
new-windows-to-main: 0
window-minimum-height: 0
enables-layout-hud: 1
screen-padding-top: 0
window-margin-size: 0
floating-is-blacklist: 1
mod2: (
    option,
    shift,
    control
)

Manageable applications:
	talagent (com.apple.talagent)
	Notion (notion.id)
	Single Sign-On (com.apple.AppSSOAgent)
	Spotify (com.spotify.client)
	Cron (com.cron.electron)
	Dash (com.kapeli.dash-setapp)
	Finder (com.apple.finder)
	1Password (com.1password.1password)
	Tunnelblick (net.tunnelblick.tunnelblick)
	coreautha (com.apple.LocalAuthentication.UIAgent)
	UserNotificationCenter (com.apple.UserNotificationCenter)
	iTerm2 (com.googlecode.iterm2)
	Arc (company.thebrowser.Browser)
```

**Comment by laffed** [comment]
bump, confirming issue for

amethyst 0.16.0 (94)
arc 0.79.2 (36228)
mac ventura 13.0.1 (22A400)

**Comment by rutger1140** [comment]
Thanks for reporting this! I was going mental on this empty space in my grid since I've been using Arc. 😅 

Confirming for:
- Amethyst 0.16.0
- Arc 0.79.2
- MacOS Monterey 12.6

**Comment by johannesstricker** [comment]
Experiencing the same problem. This only happened lately though (~4 days ago). Before it was working fine. Any idea where this is coming from? It's driving me insane...

**Comment by deeptronos** [comment]
Bump. Arc worked well with Amethyst in the past, but this issue started to occur for me within the past few days. 

Amethyst v0.16.0
macOS Montery v12.3, running on Intel Core i7 chip
Arc 0.79.3

**Comment by jccr** [comment]
This started happening to me the moment I upgraded Arc to 0.79, where they changed the top bar hover into a triple dot menu bar on the top right corner of a window.
<img width="339" alt="image" src="https://user-images.githubusercontent.com/5132652/206821407-65e8209d-9355-46b3-8777-d6c443b592e9.png">

**Comment by jccr** [comment]
Using Preview to take a screenshot of a selected window I found the phantom window fragment that is offsetting the window's frame dimensions.

I think this is an issue with Arc itself, where each browser window has an invisible sibling along with it, causing Amethyst to treat it as a separate window to be managed.

Maybe this invisible window should be configured so it's excluded by this guard?
https://github.com/ianyh/Amethyst/blob/development/Amethyst/Model/Window.swift#L235

 
~~Has anyone filed a bug report within Arc?~~
I just submitted a bug report with this observation and hypothesis.

<img width="1680" alt="test" src="https://user-images.githubusercontent.com/5132652/206823703-66fb51bf-caee-47e4-8ba2-68c43f5adf27.png">

EDIT:
Found the invisible window portion!
It's an extra window adding padding at the top that allows you to have a bigger "drag zone" with the hand cursor.

<img width="1680" alt="test2" src="https://user-images.githubusercontent.com/5132652/206825509-2e8418b5-38a6-4a66-8957-731832adb849.png">


https://user-images.githubusercontent.com/5132652/206826058-3308d54a-28bd-4896-bf62-0770e3f823f8.mov

**Comment by johannesstricker** [comment]
Is there any way to have Amethyst ignore that window?

**Comment by devployment** [comment]
As long this window does not have it's "Window title" to be filtered on, it probably will not be doable. 

I was in contact with them about the "Little Arc" windows. They prepend the Window with "Little Arc -" in the "internal" window list. But this seems not to be part of the name/title that the floating filter acts on. 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/7137845/206987044-970ade40-40d0-443e-a713-057e322c9922.png">

I these windows would expose a name to filter on, we could just make them float. Eventually. Let's see what the come up with. At least they're aware of the issue. Just be sure to file a bug report against them. To raise awareness.

**Comment by jccr** [comment]
I made a quick unpublished fork of Amethyst that ignores windows with a frame height of 10 or less. This fixed the issue for me.

**Comment by johannesstricker** [comment]
@jccr would you mind to share the changes you made?

Ah, found it:
```
// Window.swift:240 in function shouldBeManaged

if self.frame().frame.size.height <= 10 {
    return false
}
```

**Comment by jccr** [comment]
> @jccr would you mind to share the changes you made?
> 
> Ah, found it:
> ```
> // Window.swift:240 in function shouldBeManaged
> 
> if self.frame().frame.size.height <= 10 {
>     return false
> }
> ```

Yup, that's pretty much it! 👍

Sorry I didn't get the chance to post it before.

**Comment by Corei13** [comment]
@jccr thank you for finding the workaround. It has been driving me crazy!

Can you help me build the app from a fork with your suggested changes until it's fixed upstream. I am a JS engineer and unfortunately don't have any context on how to build this myself.

**Comment by jccr** [comment]
@Corei13 
I built the app by referencing the instructions in the readme. 
Here's a summary of what I did in case it helps:
1. Ensure your Xcode is installed and up to date.
2. Clone my fork here: [jccr/Amethyst](https://github.com/jccr/Amethyst) or clone the original and modify the source with the snippet of code from the comments above.
3. Run the dev setup script mentioned in the readme: `./bin/setup.sh`
4. It will check if you have the right xcode version and give you a warning if you don't (this is ok, I ignored the warning as I'm using a later version than it expects)
5. It will also check if you have `ruby` and `rbenv` installed, if not you can use brew to install them.
6. As a final step, it will start doing CocoaPods dependency setup. This failed for me on my M1 mac with sporadic segfaults but I kept running the script until it succeeded.
7. Open the `Amethyst.xcworkspace` project file in Xcode, go to `Product > Build` in the menu bar, wait for a successful build, then go to `Product > Show Build Folder in Finder` and copy the Amethyst.app from that location inside a Debug folder into your general Applications folder.

If you wish, for your convenience I made a release with a downloadable zip of my Amethyst.app from my Build Folder output here: https://github.com/jccr/Amethyst/releases/tag/ignore-short-windows

**Comment by rutger1140** [comment]
@jccr Great! 🤩 

I can confirm both the change in the code as your fork run smoothly and fixes the issue on my M1 macOS 12.6 machine.

💯

**Comment by bengolds** [comment]
This seems fixed in the newest version of Arc!

**Comment by carlos-algms** [comment]
It's happening to me, it started this month. 
<img width="1164" alt="image" src="https://github.com/ianyh/Amethyst/assets/4634613/ead198f1-1368-49f4-9981-791c987af9ed">
