### ISSUE TITLE
Can't work with alacritty

### ISSUE THREAD

**Issue by theFG1998** [ianyh/Amethyst#1353]
**Describe the bug**
I can't toggle the float state of alacritty. Also I can't see the Amethyst icon on the menu bar. Actually everything works well when I first downloaded Amethyst yesterday, but today morning I open my computer, strange things happened.
**Applications:**
alacritty 0.11.0 (8dbaa0b) 

**To Reproduce**
1. open alacritty
2. press Alt+shift+t to toggle float state

**Expected behavior**
the alacritty float state has been changed

**Screenshots**
The iterm2 and other application works well, only alacritty broken, **can't control the float state of it.**
<img width="1504" alt="Screenshot 2022-12-18 at 10 22 44" src="https://user-images.githubusercontent.com/66351806/208278347-2b2d200b-063c-466a-b136-f660560667a3.png">

**Versions:**
 - macOS: 13.1 (22C65)
 - Amethyst: 0.16.0 (94)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```

```
Version: 0.16.0 (94)

OS version: Version 13.1 (Build 22C65)

Screens:
	(0.0, 0.0, 1512.0, 982.0) [(0.0, 0.0, 1512.0, 982.0)]

Configuration:
ignore-menu-bar: 0
debug-layout-info: 0
screen-padding-left: 5
use-canary-build: 0
enables-layout-hud-on-space-change: 1
restore-layouts-on-launch: 1
enables-layout-hud: 1
floating-is-blacklist: 0
screen-padding-top: 5
follow-space-thrown-windows: 1
window-margins: 1
screen-padding-bottom: 5
float-small-windows: 1
window-minimum-height: 0
mod1: (
    option,
    shift
)
window-minimum-width: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
smart-window-margins: 1
mod2: (
    option,
    shift,
    control
)
focus-follows-mouse: 0
window-margin-size: 5
floating: (
)
mouse-follows-focus: 0
new-windows-to-main: 0
window-resize-step: 5
screen-padding-right: 5

Manageable applications:
	NetEaseMusic (com.netease.163music)
	Single Sign-On (com.apple.AppSSOAgent)
	Google Chrome (com.google.Chrome)
	Safari (com.apple.Safari)
	talagent (com.apple.talagent)
	Finder (com.apple.finder)
	Shadowrocket (com.liguangming.Shadowrocket)
	iTerm2 (com.googlecode.iterm2)
	Alacritty (org.alacritty)
```
**Additional context**
Although the alacritty showed up in the manageable list, but can't control it.

**Comment by agoodshort** [comment]
I am using Alacritty and Amethyst daily for the past month now and haven't faced any issue so far, however I am not using the float state toggle.
I tried to reproduce your issue and everything worked as expected.

>  Also I can't see the Amethyst icon on the menu bar.

Sounds like your Amethyst simply crashed and you have to restart it.

**Comment by rrybarczyk** [comment]
I am also having this issue on Amethyst v0.17.0 and Alacritty v0.11.0 on OSX Monterey v12.6.3.

If I open a single Alacritty instance, Amethyst picks it up. But if I open multiple Alacritty instances, Amethyst only picks up the first and none of the others. In the past, if I close the additional Alacritty instances, restart Amethyst, and reopen the multiple Alacritty instances, it would work. But now this fix no longer works.

**Comment by ianyh** [comment]
Can you try 0.18.0? I put it different process launch detection, but thinking about it there could still be some conflicts.

**Comment by rrybarczyk** [comment]
Works with v0.18.0! Thank you!

The only gotcha is that you need to do it in this order:

0. Amethyst can be running but doesn't have to be
1. Open up 1st Alacritty instance
2. Start/restart Amethyst
3. Open up 2nd Alacritty instance

If you open up the second terminal instance and try to restart Amethyst after, the second terminal instance will not be picked up. It is a very easy work around though.
