### ISSUE TITLE
wrong version number in macOS download 0.16.1

### ISSUE THREAD

**Issue by suschizu** [ianyh/Amethyst#1361]
hello - I think you forgot to update the info.plist here:

https://github.com/ianyh/Amethyst/releases/download/v0.16.1/Amethyst.zip

the app still contains 0.16.0 (instead of 0.16.1)

<img width="358" alt="Screenshot 2023-01-10 at 18 56 00" src="https://user-images.githubusercontent.com/16004333/211627534-b0e11266-6f2f-431e-ae03-0b2a6e90ceef.png">

**Comment by cesan3** [comment]
Trying to install returns error: 
```
==> Downloading https://github.com/ianyh/Amethyst/releases/download/v0.16.1/Amethyst.zip
curl: (22) The requested URL returned error: 404
```

**Comment by ianyh** [comment]
I deleted it so that people would stop downloading the wrong version, but haven't made it back to my personal computer yet.

**Comment by lougreenwood** [comment]
I'm also getting SHA256 mismatch when upgrading using home-brew, could be related?

```
❯ brew upgrade amethyst
==> Upgrading 1 outdated package:
amethyst 0.16.0 -> 0.16.1
==> Upgrading amethyst
==> Downloading https://github.com/ianyh/Amethyst/releases/download/v0.16.1/Amethyst.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/10115880/4f106e35-6f75-4f5b-8ffc-7e1a25bc6
######################################################################## 100.0%
==> Purging files for version 0.16.1 of Cask amethyst
Error: amethyst: SHA256 mismatch
Expected: a60857ef84f426c01693101a01a439348858aa3f3d7e8d19a91b713d384967f3
  Actual: 52663893e6547d2dd85ba15b871ec222ce4f62dc7150e5ff20d592f9b85a47c5
    File: /Users/admin/Library/Caches/Homebrew/downloads/2fb00ee1d12c789be911968beb21914bc8c779534cf8624cde10c8600de565f9--Amethyst.zip
To retry an incomplete download, remove the file above.
```

**Comment by ianyh** [comment]
Okay, should be addressed with https://github.com/Homebrew/homebrew-cask/pull/139417

**Comment by ianyh** [comment]
Cask change was merged FYI.

**Comment by suschizu** [comment]
great thanks for the fast fix @ianyh  
I can confirm that download 0.16.1 now contains the correct version number :) 

<img width="232" alt="Screenshot 2023-01-12 at 09 51 56" src="https://user-images.githubusercontent.com/16004333/212021228-d98d7144-6f43-4fab-a8a1-d2cf2ced4508.png">
