### ISSUE TITLE
Iphone Emulator is NOT wrapped up completely

### ISSUE THREAD

**Issue by retrotechie** [ianyh/Amethyst#1365]
**Describe the bug**
When I work on Flutter projects, I realize the Iphone Emulator and maybe Android Emulator (not tested yet) is not wrapped up completely in the window tile area. The top and 2 sides are good  but the bottom is NOT resize automatically based on the window margins.

**Applications:**
Iphone Emulator

**To Reproduce**
Simply turn on and off `Window Margins` in `Preferences` and notice the bottom of Iphone Emulator.

**Expected behavior**
The entire Iphone Emulator should be tiled and resized based on `Window Margins`.

**Screenshots**
- `Window Margins` OFF

![Screenshot 2023-01-13 at 2 42 21 PM](https://user-images.githubusercontent.com/107520616/212432448-94ff90bc-7fc6-467e-af78-b54069f83e68.png)

- `Window Margins` ON with `30px`
The emulator is NOT resized but pushed to the right by the terminal window. 

![Screenshot 2023-01-13 at 2 44 16 PM](https://user-images.githubusercontent.com/107520616/212432662-bda821b0-c707-45a1-a605-28105d895353.png)

**Versions:**
 - macOS: 13.1 22C65 arm64
 - Amethyst: 0.16.1 (95)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info

Version: 0.16.1 (95)

OS version: Version 13.1 (Build 22C65)

Screens:
	(0.0, 0.0, 1920.0, 1080.0) [(0.0, 0.0, 1920.0, 1080.0)]
	(1920.0, 113.0, 1496.0, 967.0) [(1920.0, 0.0, 1496.0, 967.0)]

Configuration:
mouse-swaps-windows: 1
window-margin-size: 30
new-windows-to-main: 0
enables-layout-hud: 1
follow-space-thrown-windows: 1
window-minimum-width: 0
use-canary-build: 0
mod2: (
    option,
    shift,
    control
)
window-minimum-height: 0
screen-padding-top: 0
floating: (
)
screen-padding-bottom: 0
mouse-resizes-windows: 1
enables-layout-hud-on-space-change: 1
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
restore-layouts-on-launch: 0
screen-padding-left: 0
focus-follows-mouse: 0
float-small-windows: 1
smart-window-margins: 0
ignore-menu-bar: 0
window-margins: 1
screen-padding-right: 0
mouse-follows-focus: 0
mod1: (
    option,
    shift
)
debug-layout-info: 0
floating-is-blacklist: 1
window-resize-step: 5
```

**Additional context**

**Comment by ianyh** [comment]
Is the iOS simulator actually resizable that way in general? Have you tried a smaller simulated device, for example?

**Comment by retrotechie** [comment]
I have tried to resize the simulator with the size smaller than window area and it didn't scale up to match up. I guess Amethyst doesn't affect to simulators scalability but only changing their positions.

**Comment by ianyh** [comment]
I played with this a bit, by the way, and it seems like a quality of the simulator. Changing the frame via AX seems to just not affect the actual dimensions of the simulated device.
