### ISSUE TITLE
Make "Swap focused window with main window" usable when main window is focused

### ISSUE THREAD

**Issue by rickythefox** [ianyh/Amethyst#1377]
Currently the `mod1 + enter` shortcut doesn't do anything when the main window is already focused. I think it's a shame as it's a very convenient shortcut.

My proposal is to use the shortcut to swap the main window with the previous main window. This way you can easily toggle between two windows while working.

@ianyh would love to hear your thoughts on this.

**Comment by ianyh** [comment]
It's a good idea. I think there's an issue tracking it somewhere.

**Comment by rickythefox** [comment]
I will submit a PR.
