### ISSUE TITLE
Selectively enable amethyst for a subset of desktops or monitors

### ISSUE THREAD

**Issue by dlschmidt** [ianyh/Amethyst#1381]
**Is your feature request related to a problem? Please describe.**
Sometimes I would just need amethyst on one desktop and disable it for other ones.
I think it is quite useful to not use amethyst on every desktop / monitor.

**Describe the solution you'd like**
Possibly a shortcut to toggle the activation of amethyst on a desktop or a list of checkboxes in the amethyst settings.

**Comment by ianyh** [comment]
You can use the floating layout on spaces you don't want Amethyst to mess with.

**Comment by dlschmidt** [comment]
Thank you very much!
