### ISSUE TITLE
window-max-count to use hide functionality instead of minimize

### ISSUE THREAD

**Issue by dlvhdr** [ianyh/Amethyst#1383]
**Is your feature request related to a problem? Please describe.**
Currently, when setting the `window-max-count` to 1 for example, every app that swaps the main (and only) window, will minimize it.
The minimize animation in Mac (even with reduced animation) is slow.
Using `cmd+h` to hide an app is instant.

**Describe the solution you'd like**
Instead of minizing apps to keep the `max-window-count` in check, use hide (cmd+h).

**Describe alternatives you've considered**
This one.

**Additional context**

https://user-images.githubusercontent.com/6196971/213871474-d89976f5-ea93-4e45-a619-867e366d6087.mov

**Comment by ianyh** [comment]
Hiding is application-level, not window-level. This would not work if you had multiple windows in the same application.

**Comment by dlvhdr** [comment]
Right... maybe it's worth adding a max number of apps setting. Should I open a new issue for it?

**Comment by ianyh** [comment]
I'm not sure that makes sense. If you have an application with more windows than your maximum window count there's no way to display any of them given the upper limit on windows.
