### ISSUE TITLE
Windows do not take up space near the Dock

### ISSUE THREAD

**Issue by simon-weber** [ianyh/Amethyst#141]
I have a gap wherever the dock is located. For example, with the dock on the right:
![dock_gap](https://f.cloud.github.com/assets/950506/2430160/4c109e3c-acbe-11e3-8604-c5d006d86687.png)

I haven't been able to fix this. I've tried:
- always floating the dock: strangely, this makes the gap larger
- setting ignore-menu-bar to true and false: neither seem to have an effect
- moving the dock to different sides of the screen

I'm on Mavericks and the most recent release.

[Trello Card](https://trello.com/c/iIdHTLBx/47-amethyst-windows-do-not-take-up-space-near-the-dock)

**Comment by OJFord** [comment]
This is not just iTerm2, and occurs wherever the dock is positioned.

It's not really an Amethyst bug, it happens without it too, but it would certainly be a nice feature to add a negative margin of however many pixels the gap is on whichever side the dock is!

**Comment by ianyh** [comment]
As of 10.12 this appears to no longer be the case.
