### ISSUE TITLE
illegal date format

### ISSUE THREAD

**Issue by mnkhprre** [ianyh/Amethyst#1418]
<img width="471" alt="Ekran Resmi 2023-02-10 19 11 08" src="https://user-images.githubusercontent.com/54448793/218140991-9d16de6b-2686-48c0-a821-561f5a1a3c4a.png">

i am using Ventura 13.2 
and my yabai version is 4.0.4

i couldn't find a solution for it.

**Comment by ianyh** [comment]
You might have the wrong repository.
