### ISSUE TITLE
Add additional keyboard shortcuts to `amethyst.yml`

### ISSUE THREAD

**Issue by majjoha** [ianyh/Amethyst#1421]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to map all shortcuts listed in the "Shortcuts" tab in the Settings using the `amethyst.yml` configuration file. I had a look at https://github.com/ianyh/Amethyst/blob/a817bd7ea76778e5124eebbb269a284acee73841/Amethyst/Preferences/UserConfiguration.swift#L102-L134 which seems to define quite a few, but I am specifically looking for the option to redefine "Select Tall layout", "Select Wide layout", "Select Fullscreen layout", and "Select Column layout".

**Describe the solution you'd like**
It would be amazing if all shortcuts could be specified in the `amethyst.yml` file.

Thank you for an amazing app!

**Comment by nolith** [comment]
I was looking for the same option.

Will it be possible to temporarily use the GUI to define those shortcuts? Or will they just mess up with the text file config?

Thank you

**Comment by majjoha** [comment]
Personally, I've been adding them manually once Amethyst is (re)started. When the app opens, it will load the configuration from your `amethyst.yml` file, and then you can configure and apply settings on top of it manually through the GUI, but it would, of course, be nice to have all of them in the configuration file instead.

**Comment by vicmunoz** [comment]
All those shortcuts are currently available with 0.19 version. Have a look at https://github.com/ianyh/Amethyst/blob/development/docs/configuration-files.md#command-keys

Only pending shortcuts, if I'm not wrong, are "Select xxxx layout"

**Comment by majjoha** [comment]
You are absolutely right regarding the missing shortcuts related to selecting layouts, and these are the ones that I am also mentioning in the issue above. :-)

**Comment by sebastianst** [comment]
Would also love to see configurability of shortcuts for direct layout selection.

**Comment by ianyh** [comment]
This actually is already possible. Adding to the documentation.

**Comment by majjoha** [comment]
Amazing. Thanks!
