### ISSUE TITLE
[Questing] Using the "Tall" split, can the horizontal split also be adjusted in size?

### ISSUE THREAD

**Issue by 10bn** [ianyh/Amethyst#1424]
![image](https://user-images.githubusercontent.com/46263124/219011931-881a426e-593b-4fd6-99dd-1ae590ee4863.png)

Hi Guys, I turned on the feature that the mouse can be used to resize the windows. This though works only for the vertical split. Is there an optiton to also ajust the hoizontal split?

**Comment by glibsm** [comment]
Something like this is only currently possible with a custom layout. Secondary panes in Tall layout get equal heights: https://github.com/ianyh/Amethyst/blob/c48f35a8421c7c11f116b9fb804ef9281d9f908a/Amethyst/Layout/Layouts/TallLayout.swift#L68

It's an interesting idea to perhaps add a setting for expanding/shrinking secondary pane, but it requires changes in each layout where it's applicable.

Out of curiosity, with your example, what would you expect happen when there are 3 secondary windows?

**Comment by ianyh** [comment]
It requires a more complicated data structure than just a simple list, which is what most of the layouts are based around.

**Comment by ianyh** [comment]
This can be accomplished with a custom layout.
