### ISSUE TITLE
Can't use certain shortcuts even though they are not bound to anything

### ISSUE THREAD

**Issue by ajeetdsouza** [ianyh/Amethyst#1442]
**Describe the bug**

I'm trying to assign the keyboard shortcut for "Throw focused window to space 6" to `Shift-Cmd-6`. However, this does not work - it tells me that the shortcut is already in use for a system-wide shortcut. I'm seeing a similar error with some other keys:

- Shift-Cmd-`
- Cmd-Esc

However, nothing happens when I use `Shift-Cmd-6`, and I can't see the shortcut in System Settings either. I believe it's used for taking screenshots of the touchbar on older MacBooks, but I don't have a touchbar on mine.

To debug, I tried to assign `Shift-Cmd-6` to another action in System Settings. It normally warns you when a shortcut has a conflict, but there was no warning here - meaning it's probably not being used for anything else.

How do I get Amethyst working with this shortcut?

**Applications:**

None

**To Reproduce**

Assign any action in Amethyst to `Shift-Cmd-6`.

**Expected behavior**

Since the keyboard shortcut is not in use, I would expect this to work with Amethyst.

**Screenshots**

NA

**Versions:**
 - macOS: Ventura 13.2 (MacBook Pro M1 16-inch 2021)
 - Amethyst: 
 
**Debug Info**

```
use-canary-build: 0
enables-layout-hud-on-space-change: 1
restore-layouts-on-launch: 1
window-resize-step: 5
mouse-follows-focus: 1
debug-layout-info: 0
screen-padding-left: 0
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.tinyspeck.slackmacgap";
        "window-titles" =         (
            "Huddle with.*"
        );
    }
)
window-minimum-width: 0
focus-follows-mouse: 0
screen-padding-top: 0
window-minimum-height: 0
mouse-swaps-windows: 1
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
window-max-count: 0
enables-layout-hud: 1
screen-padding-right: 0
screen-padding-bottom: 0
ignore-menu-bar: 0
window-margin-size: 0
floating-is-blacklist: 1
window-margins: 0
float-small-windows: 1
```

**Additional context**
NA

**Comment by Huguesmmm** [comment]
This is not an amethyst related problem but a mac related problem. The solution would be that you change in your setting the use of the `cmd` + `shift` + 6 shortcut (in this case that you remove the use of this shortcut), but as I know this is currently impossible with MacOS Ventura.

**Comment by Huguesmmm** [comment]
It is possible to change others system wide setting like `cmd` + `shift` + 5 in the Keyboard -> Keyboard shortcut -> screenshot for exemple and then you can use it in amethyst but it is specially not possible with `cmd` + `shift` + 6.

**Comment by ianyh** [comment]
Thanks for digging in to that. I think I will close this as it seems for this specific command it's not possible.
