### ISSUE TITLE
"Throw focused window to space left/right" throws to primary display/only works on primary display

### ISSUE THREAD

**Issue by OmriSama** [ianyh/Amethyst#1455]
**Describe the bug**

`Throw window to space left/right` seems to not be working on any non-primary monitors.

I have three monitors, arranged horizontally with the leftmost one being the primary one.

![image](https://user-images.githubusercontent.com/10534779/223840212-8971257c-5e5a-4481-8809-b53e57d02ef9.png)

When trying to throw windows between spaces in any of the non-primary monitors, the window gets moved to the current space in the primary (left-most, in this case) monitor. Once it's in the primary monitor, the Throwing functionality works fine.

`Throw focused window to space n` works fine.

**Versions:**
 - macOS: Version 12.6.3 (21G419)
 - Amethyst: Version 0.18.0 (100)
 
**Debug Info**
```shell
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info --include-apps
Version: 0.18.0 (100)

OS version: Version 12.6.3 (Build 21G419)

Screens:
        (0.0, 0.0, 1920.0, 1080.0) [(0.0, 0.0, 1920.0, 1080.0)]
        (3840.0, 0.0, 1920.0, 1080.0) [(3840.0, 0.0, 1920.0, 1080.0)]
        (1920.0, 0.0, 1920.0, 1080.0) [(1920.0, 0.0, 1920.0, 1080.0)]

Configuration:
new-windows-to-main: 0
window-minimum-width: 0
use-canary-build: 1
window-minimum-height: 0
restore-layouts-on-launch: 1
mouse-follows-focus: 1
mouse-swaps-windows: 1
window-resize-step: 5
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
window-margins: 0
screen-padding-right: 0
floating: (
)
mod2: (
    option,
    shift,
    control
)
enables-layout-hud: 0
screen-padding-bottom: 0
focus-follows-mouse: 0
window-margin-size: 0
floating-is-blacklist: 1
screen-padding-top: 0
follow-space-thrown-windows: 1
mod1: (
    option,
    shift
)
enables-layout-hud-on-space-change: 0
mouse-resizes-windows: 1
screen-padding-left: 0
debug-layout-info: 0
float-small-windows: 1
window-max-count: 0
ignore-menu-bar: 0

Manageable applications:
        talagent (com.apple.talagent)
        AppSSOAgent (com.apple.AppSSOAgent)
        Finder (com.apple.finder)
        Slack (com.tinyspeck.slackmacgap)
        Gmail (com.google.Chrome.app.fmgjjmmmlfnkbppncabfkddbjimcfncm)
        Google Chrome (com.google.Chrome)
        zoom.us (us.zoom.xos)
        WezTerm (com.github.wez.wezterm)
        Code (com.microsoft.VSCode)
        Firefox (org.mozilla.firefox)
```

**Comment by ianyh** [comment]
This is fixed in 0.19.0, which is currently in beta.

**Comment by OmriSama** [comment]
@ianyh Wow! Thanks for the swift reply. How can I participate in the 0.19.0 beta?

**Comment by ianyh** [comment]
I happened to be looking at my phone when the notification came through. 😅

In the Debug section of Preferences you can select the option to get development builds, or you can download from the release page. https://github.com/ianyh/Amethyst/releases/tag/v0.19.0b2
