### ISSUE TITLE
[question] some window tile manager capabilities

### ISSUE THREAD

**Issue by azinsharaf** [ianyh/Amethyst#1461]
I am considering to switch to Amethyst (after Parallels coherence feature implementation) and I hope I can use the capabilities below in Amethyst. 

Is there any command to focus to different spaces? (similar to Cmd -1 on mac setting)

Is there any command to focus next and previous spaces? (I wouldn't use cmd-arrow keys in mac setting because I think using arrow-keys is not efficient.) 

Is there any command to focus to the recent space? (I use this a lot).

Is there any command to maximize a window and restore the size again?

Is there any command to rotate the windows in a space? so the bottom right window becomes main window on the left of the space. 

Is it possible to use an specific application to an specific space? I prefer to have this option in the config file instead of using "This Desktop" option in macos setting.) because i have to redo it if i delete the Macos spaces.

Is it possible to add the excluded apps in config file? 

Thanks!

**Versions:**
 - macOS: 13.2.1
 - Amethyst: 0.19.0

**Comment by ianyh** [comment]
> I am considering to switch to Amethyst (after Parallels coherence feature implementation) and I hope I can use the capabilities below in Amethyst.
> 
> Is there any command to focus to different spaces? (similar to Cmd -1 on mac setting)

No, but there is an open issue tracking it. As a note, you can configure those system commands.

> 
> Is there any command to focus next and previous spaces? (I wouldn't use cmd-arrow keys in mac setting because I think using arrow-keys is not efficient.)

No, but there is also an open issue tracking this. I think you can also configure the system command, though.

> 
> Is there any command to focus to the recent space? (I use this a lot).

I'm not sure what you mean by this.
> 
> Is there any command to maximize a window and restore the size again?

No, but you can use the fullscreen layout for this.
> 
> Is there any command to rotate the windows in a space? so the bottom right window becomes main window on the left of the space.

No.
> 
> Is it possible to use an specific application to an specific space? I prefer to have this option in the config file instead of using "This Desktop" option in macos setting.) because i have to redo it if i delete the Macos spaces.

Not currently, no.
> 
> Is it possible to add the excluded apps in config file?

This should be supported, but may be incomplete.
> 
> Thanks!
> 
> **Versions:**
> 
>     * macOS: 13.2.1
> 
>     * Amethyst: 0.19.0

**Comment by ianyh** [comment]
I'm going to close this for now since it isn't necessarily tracking a particular issue and is more of a series of questions.

**Comment by azinsharaf** [comment]
Thank you so much for answering them.
