### ISSUE TITLE
Starting a Zoom.us call with "Zoom.us.app" causes Amethyst to crash immediately.

### ISSUE THREAD

**Issue by mattviasat** [ianyh/Amethyst#1490]
**Describe the bug**
Amethyst is running and I can see it's icon in the top bar.
I open a link to a Zoom.us call, this starts **Zoom.us.app** and opens the call in the app. 
This causes Amethyst to crash immediately.  The icon disappears, and a crash report is made in the console app (attached).

Note that starting  **Zoom.us.app**  without also starting a call does not cause Amethyst to crash.

I suspect this has to do with the horrible way that the Zoom app behaves. It likes to do it's own windowing and take control of the screen. See [this thread for some details](https://community.zoom.com/t5/Meetings/Zoom-keeps-stealing-focus/m-p/51838).
 
**Applications:**
Zoom.us.app - 5.13.11

**To Reproduce**

1. Run Amethyst
2. Open a Zoom call while the Zoom app is not running. Opening the zoom app without starting a call does not cause this behavior. I am also able to restart Amethyst after it has crashed but while zoom is running. 

**Expected behavior**
Amethyst should not crash when zoom.us starts a call. Ideally Amethyst could control Zoom, but I suspect that the zoom app is designed to make that impossible.

**Screenshots**
![Screenshot 2023-04-25 at 9 28 24 AM](https://user-images.githubusercontent.com/129442476/234311817-b023ed1b-ee3d-4063-b97d-bbd9ea7cccff.png)

**Versions:**
 - macOS: 13.3.1
 - Amethyst: 0.19.0
 
**Debug Info**
```
Version: 0.19.0 (103)

OS version: Version 13.3.1 (Build 22E261)

Screens:
	(0.0, 0.0, 2560.0, 1080.0) [(0.0, 0.0, 2560.0, 1080.0)]

Configuration:
mod1: (
    option,
    shift
)
new-windows-to-main: 0
debug-layout-info: 0
window-max-count: 0
screen-padding-right: 0
mouse-follows-focus: 0
use-canary-build: 0
window-minimum-width: 0
layouts: (
    fullscreen,
    "two-pane"
)
window-minimum-height: 0
screen-padding-top: 0
follow-space-thrown-windows: 1
window-margins: 0
screen-padding-left: 0
enables-layout-hud: 1
ignore-menu-bar: 0
restore-layouts-on-launch: 1
floating-is-blacklist: 1
screen-padding-bottom: 0
window-margin-size: 0
window-resize-step: 5
mod2: (
    option,
    shift,
    control
)
float-small-windows: 1
focus-follows-mouse: 0
enables-layout-hud-on-space-change: 1
floating: (
)

Manageable applications:
	iTerm2 (com.googlecode.iterm2)
	Slack (com.tinyspeck.slackmacgap)
	Microsoft Outlook (com.microsoft.Outlook)
	Sublime Text (com.sublimetext.4)
	System Settings (com.apple.systempreferences)
	Activity Monitor (com.apple.ActivityMonitor)
	Cisco AnyConnect Secure Mobility Client (com.cisco.anyconnect.gui)
	Finder (com.apple.finder)
	Firefox (org.mozilla.firefox)
	Weather (com.apple.weather)
	Docker Desktop (com.electron.dockerdesktop)
	Console (com.apple.Console)
```

**Additional context**
Here is the Console Crash Report
[ameth-crash.log](https://github.com/ianyh/Amethyst/files/11323679/ameth-crash.log)

**Comment by llimllib** [comment]
I'm seeing the same thing, and it's easily reproducible - if there's anything I can do to help debug I'd be happy to do so

**Comment by iandoesallthethings** [comment]
It's happening to me too, same versions, so at least it's consistent!
