### ISSUE TITLE
Persistent Application State

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#151]
This could solve #150.  Idea is that information about the current state of Amethyst persists through application restarts.  Things like the current layout for each space and the number of windows in and size of master pane

[Trello Card](https://trello.com/c/Ohoq2K73/50-amethyst-persistent-application-state)

**Comment by timvisher** [comment]
I really like this idea. FWIW, and I have no idea how accessible/possible this is to you as developers, but the way that OS X Desktop Wallpaper Preferences are saved is that every display has a uuid. Preferences and state are saved for each uuid. I'm assuming when the display changes, something internal to the system updates the uuid that is currently active and things work along.

Maybe something like that is accessible to Amethyst?

**Comment by leonardt** [comment]
I believe we are using the uuids for screens to assign screen managers (https://github.com/ianyh/Amethyst/blob/master/Amethyst/AMWindowManager.m#L105), so I think that could used as a key for mapping screens to their saved layout.

For the case of layouts changing, I see one case to handle which is when a screen is saved in a layout that is then removed from the list of layouts.  In this case, Amethyst should then just apply the default layout.

For a changing list of screens, we'll have to be sure to drop managers for deleted screens, and add new ones for new screens.  One system for this I could envision is on boot, Amethyst checks each screen against a dictionary of saved layouts.  If screen's uuid isn't present, then it is new and assign it the default layout.  This doesn't handle the case of a deleted space, which perhaps we can check on app close. (I.e, refresh the dictionary with the current state, removing any saved layouts for active and deleted screens, then adding the states of the active screens.)

**Comment by ianfixes** [comment]
The more I use Amethyst, the more I dread restarting my computer to restart updates. 

Use case: I have about 10 desktops, each with their own layout.  This layout changes depending on whether I'm using the laptop screen or an external display with the laptop closed (e.g. the same desktop might be "Tall" when just the laptop screen is available, but "Widescreen Tall" when docked. Amethyst currently handles the switch flawlessly, unless/until I restart it).

I've resorted to writing down my layout settings before I restart.  So I'm upvoting this issue.  How can I help?

**Comment by Slus** [comment]
> The more I use Amethyst, the more I dread restarting my computer to restart updates.
> 
> Use case: I have about 10 desktops, each with their own layout. This layout changes depending on whether I'm using the laptop screen or an external display with the laptop closed (e.g. the same desktop might be "Tall" when just the laptop screen is available, but "Widescreen Tall" when docked. Amethyst currently handles the switch flawlessly, unless/until I restart it).
> 
> I've resorted to writing down my layout settings before I restart. So I'm upvoting this issue. How can I help?

@ianfixes  Do you mind sharing what you've done?

**Comment by ianfixes** [comment]
I literally write it down on a note card with a pen before I restart.

**Comment by ianfixes** [comment]
> Some interesting complications to consider with this:
> 
> * What if we relaunch and find the list of layouts has changed?
> * What if we relaunch and find the list of screens has changed?

I'd add to this: @ianyh  do full-screened apps interfere with the list of screens?

Also @ianyh, what would you think of relaxing this feature request to simply "save state" and "load state" menu item actions?  That would put us in a better position to do error messages, e.g. "you need to create more screens, ignore/cancel", as well as give us more wiggle room on getting the implementation to work perfectly.  (In other words, persistent state implies that you have only one chance -- app launch -- to correctly apply a saved state, after which the saved state is replaced by the current state.  Tying it to user action gives us some potential to retry.) 

As far as layouts changing, could we just match by name?  I'd envision a JSON structure to hold the saved config, and one of the entries would be the list of layouts that were active when the state was saved.

**Comment by ianyh** [comment]
I think the solution is probably closer to making `WindowManager` conform to `Codable` so we can just archive it directly.

**Comment by ianfixes** [comment]
`Codable` looks cool, I can read up on that.

I'm curious whether you want to support both this use case and #787 at the same time

**Comment by ianyh** [comment]
I think you would want to cascade the codability so you could also encode the screen managers and layouts to the extent that it is possible, so it would support #787.

**Comment by ianfixes** [comment]
Is there any property of a running application window (this terminal window in particular vs _that_ terminal window in particular) available to Amethyst that would persist across launches?

**Comment by ianyh** [comment]
Hm, my reading of that issue was about layouts and parameters, which are independent of actual windows. If we did want to try to persist ordering we might be able to encode window ids maybe with app id as well? I’m not sure off the top of my head if window ids are global or local.

We’re never going to be able to get it perfect because a lot of things could change between launches, so we can start with the basic best effort and improve from there. I think the MVP here is persisting window manager, screen managers, and layouts to the extent that we can decode them at launch and still have something meaningful.

**Comment by ianfixes** [comment]
Your reading is correct.  I keep overthinking this.

Implementing #785 first would greatly help me in the testing of this feature.  Is that a possibility?  I'm very inexperienced with GUI stuff in Swift/Xcode.

**Comment by mwoffenden** [comment]
+1
