### ISSUE TITLE
Zotero (bibliography manager) ignore amethyst

### ISSUE THREAD

**Issue by danieltomasz** [ianyh/Amethyst#1516]
**Describe the bug**
Zotero (bibliography manager)  (often) is not tilled, also other app launched after zotero ignore tilling and go full screen (1st app), if I resurface Zotero and start another app, it usually tile to 1/2 or 1/4 screen on top of Zotero, but the previous apps are invisible

**Applications:**
What applications are involved?

Zotero
**To Reproduce**
Launch Zotero

**Expected behavior**

Zotero will behave like other app
Zotero is aligned 
**Screenshots**

**Versions:**
 - macOS: 13.4
 - Amethyst: 0.19 (103)

**Comment by danieltomasz** [comment]
The problem is with the stable version which uses really old version of firefox (<60) as a base (the beta, which is still month from the release seems to be working ok, it is using modern Firefox  102 as a base)

**Comment by ianyh** [comment]
Sounds like this is probably out of scope for Amethyst, but you could try 0.20.0b3 if you're feeling adventurous.

**Comment by danieltomasz** [comment]
Thanks, it helped!
