### ISSUE TITLE
`disable-screen-padding-on-inbuilt: true` not respected?

### ISSUE THREAD

**Issue by adudenamedruby** [ianyh/Amethyst#1517]
**Describe the bug**
I set the screen padding to some values, and re-launch Amethyst. The padding is respected on both my laptop screen and the external monitor.
Then, in my `amethyst.yml` file, I make the following change and set the inbuilt display padding to `true`. 

```
# disable screen padding on in-built display
disable-screen-padding-on-inbuilt: true
```
I save the file, and re-launch Amethyst.

However, if I'm just on my laptop screen, this isn't actually happening, and the screen padding remains. When I open the visual preferences (I don't change anything, just to see), I see that this option is not enabled. (see screenshot).

For reference, I'm using a dock to attach to one external monitor, when I am using the external monitor.

**Applications:**
Any that are open.

**To Reproduce**
See bug description.

**Expected behavior**
When I'm using my laptop without an external monitor attached, the screen padding should be 0 on all sides.

**Screenshots**
<img width="1009" alt="Screenshot 2023-06-28 at 7 34 15 AM" src="https://github.com/ianyh/Amethyst/assets/11182210/87b790e3-a5a5-46dc-a61f-d4c17fac7264">

**Versions:**
 - macOS: 13.4.1 (Build 22F82)
 - Amethyst: 0.19.0 (103)
 
**Debug Info**
```
Screens:
	(0.0, 0.0, 1512.0, 982.0) [(0.0, 0.0, 1512.0, 982.0)]

Configuration:
screen-padding-top: 10
mouse-follows-focus: 0
enables-layout-hud-on-space-change: 0
smart-window-margins: 1
new-windows-to-main: 0
ignore-menu-bar: 0
window-margin-size: 7
screen-padding-bottom: 10
mouse-swaps-windows: 0
mouse-resizes-windows: 0
floating: (
    "com.apple.systempreferences"
)
window-minimum-width: 0
layouts: (
    tall,
    fullscreen,
    "shifting-pane"
)
mod1: (
    option
)
debug-layout-info: 0
window-max-count: 0
use-canary-build: 0
enables-layout-hud: 1
screen-padding-right: 20
mod2: (
    option,
    shift,
    control
)
floating-is-blacklist: 1
restore-layouts-on-launch: 1
window-resize-step: 5
follow-space-thrown-windows: 1
window-minimum-height: 0
screen-padding-left: 20
float-small-windows: 1
window-margins: 1
focus-follows-mouse: 0
```

**Additional context**
I'm not sure why in the debug info lists two screens, seemingly.
```
Screens:
	(0.0, 0.0, 1512.0, 982.0) [(0.0, 0.0, 1512.0, 982.0)]
```

The debug info was printed when I was on my laptop without an external screen connected.

**Comment by ianyh** [comment]
The documentation was wrong.
