### ISSUE TITLE
follow-space-thrown-windows: false being ignored

### ISSUE THREAD

**Issue by lalithsuresh** [ianyh/Amethyst#1519]
**Describe the bug**

I have a `.amethyst.yml` file where I've set `follow-space-thrown-windows: false`. The setting also appears as disabled on the GUI's preferences page.

However, when I throw windows to another space, amethyst switches to that space, so the setting seems to not work.

If it helps, my keybinds for throwing to another space are `option+shift+<num>`, and for switching to another space are `option+<num>`.

**Applications:**
What applications are involved?

Happens with all application windows I throw.

**To Reproduce**

* set `follow-space-thrown-windows: false`
* throw a window to another space

**Expected behavior**

Amethyst does not follow thrown spaces when `follow-space-thrown-windows: false`.

**Screenshots**

**Versions:**
 - macOS: Ventura 13.2
 - Amethyst: 0.16.1 (95)
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

```
➜  ~ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.16.1 (95)

OS version: Version 13.2 (Build 22D49)

Screens:
	(0.0, 0.0, 3440.0, 1440.0) [(0.0, 0.0, 3440.0, 1440.0)]

Configuration:
window-margin-size: 0
layouts: (
    tall,
    fullscreen,
    wide,
    column
)
screen-padding-right: 0
follow-space-thrown-windows: 0
floating-is-blacklist: 1
float-small-windows: 1
screen-padding-top: 0
debug-layout-info: 0
mouse-follows-focus: 0
floating: (
)
mod1: (
    option
)
screen-padding-left: 0
screen-padding-bottom: 0
window-minimum-width: 0
ignore-menu-bar: 0
use-canary-build: 0
restore-layouts-on-launch: 1
mod2: (
    option,
    shift
)
focus-follows-mouse: 0
window-minimum-height: 0
window-margins: 0
enables-layout-hud: 1
window-resize-step: 5
new-windows-to-main: 0
enables-layout-hud-on-space-change: 0
```

**Additional context**

**Comment by ianyh** [comment]
This has been fixed since 0.16.1, I think. Please upgrade.
