### ISSUE TITLE
Throw focused window to distant Space shifts one Space

### ISSUE THREAD

**Issue by alexgenaud** [ianyh/Amethyst#1520]
**Describe the bug**
"Throw focused window to space 4" (from space 1) will appear to move to space 2. In fact, it will move the window to space 4, then shift space 4 to space 2 and reorder subsequent spaces.

**To Reproduce**
“Throw focused window to space N” does not work quite right for me. Rather, it behaves a bit more like “Throw focused window to space left” and “right” (with a twist). Instead of throwing to the numbered space, it only moves one space immediately left or right of the current space.

“Throw focused window to space left” (and “right” and specifically “space 1”) work as expected. However, throwing to and from any other distant space (like from Desktop 3 to Desktop 6) seems to throw the window to the correct space, but then move the entire space adjacent to the current space and then shift other spaces. So, throwing the focused window from Desktop 3 to Desktop 6, will merge the focused window with existing windows in Desktop 6, then rename Desktop 6 to Desktop 4 and reorder all Desktop’s sequentially. Thus the focused window will seem to have moved only one space and numerous other windows and spaces will have shifted around.

**Expected behavior**
If viewing Desktop 3 and "modifiers-6" is pressed, then I expect the focused window to be moved to Desktop 6. I do not expect spaces (Desktops) to shift around. If I later press Control-6 (set with Mission Control), I expect to "be in" Desktop 6 and see the moved window in Desktop 6.

**Versions:**
 - macOS: M2 Ventura 13.4.1
 - Amethyst: 0.19.0 (130)

 
**Additional context**
Note, I’ve redefined the shortcuts shift-control-left, shift-control-right, shift-control-n because they correspond to control-1, control-2, … control-9, control-0 in System Settings > Keyboard Shortcuts > Mission Control > Switch to Desktop 1, …9, 0.

**Comment by ianyh** [comment]
Make sure you have `Automatically rearrange Spaces based on most recent use` disabled as per the Readme.

**Comment by alexgenaud** [comment]
Solved:

Desktop & Dock > (bottom) Mission Control > Automatically rearrange Spaces based on Most recent use

set NO/OFF
