### ISSUE TITLE
Fullscreen Toggle Keybinding

### ISSUE THREAD

**Issue by bergmul** [ianyh/Amethyst#1531]
**Is your feature request related to a problem? Please describe.**

It would be really nice to be able to toggle fullscreen on the currently selected window. This allows users to quickly focus a window and move back into their usual workflow.

**Describe the solution you'd like**
- Think floating toggle but for fullscreen mode instead.
- When toggling the first time, the currently focussed window is fullscreened, when toggling again, it switches back to the previously selected layout.

**Describe alternatives you've considered**

The expected behaviour is possible with two different workflows which are not as good as having the toggle.

1. One can only activate the fullscreen and one desired layout (e.g. tall) and get the expected behaviour by cycling through layouts (default: mod1 + space). Downside: This only works conveniently with 2 layouts and practically only with very few. The more layouts are selected, the larger the deviation from a fullscreen toggle.
2. One can get the behaviour by switching to the fullscreen layout (default: mod1 + d) and the previously selected layout (e.g. tall: mod1 + a) directly. Downside: This requires different buttons and the user to use a different "back" button depending on the previously used layout. The workflow is therefore not as seamless.

**Additional context**

This feature is available in many popular tiling wm's:

- i3 (mod + f): [docs](https://i3wm.org/docs/refcard.html)
- bspwm (super + m): [cheat sheet]( http://la-familia-grande.de/index.php?site=bspwm)
- awesomewm (mod + f): [docs](https://awesomewm.org/apidoc/sample%20files/rc.lua.html)
- dwm (via patches): [patch1](https://dwm.suckless.org/patches/fullscreen/), [patch2](https://dwm.suckless.org/patches/actualfullscreen/)
- xmonad (via multi toggle): [superuser link](https://superuser.com/questions/238190/how-can-i-set-my-caps-lock-key-to-toggle-fullscreen-mode-in-xmonad/238454)

**Comment by ianyh** [comment]
0.20.0 adds toggling to the select layout commands so that you can select fullscreen and then toggle back to the previous layout with the same command. Is that sufficient?

**Comment by bergmul** [comment]
That's perfect! :)

Tested in 0.20.0 beta 4 and it works nicely. Thanks! :)
