### ISSUE TITLE
Window thrown to a space loses focus

### ISSUE THREAD

**Issue by dzanotto** [ianyh/Amethyst#1567]
**Describe the bug**
When a window is thrown to a space with "Follow thrown windows between spaces" enabled, the window loses focus.

**Applications:**
Every application

**To Reproduce**
1. Set up at least two spaces
2. On the first space open at least one window and focus it
3. On the second space open a window and focus it
4. Throw the window to the first space using the keyboard shortcut
5. The focus switches from the window being moved to the one previously focused on the destination space

**Expected behavior**
The window thrown to the destination space should keep the focus

**Versions:**
 - macOS: Sonoma 14.0
 - Amethyst: 0.20.0 (108)

**Comment by cyberthirst** [comment]
I've been experiencing too (even before Sonoma). Currently on the same versions as OP and the bug persists.

**Comment by LouisKraemer** [comment]
Same here, can reproduce each time. Can provide additional informations if needed.

**Comment by cyberthirst** [comment]
Probably related to this recent commit? https://github.com/ianyh/Amethyst/commit/4d0e820beb25f4bdb89088326a470a9132d89ccb

I can see that the **focus** function was modified. Seems very messy haha :D Don't really know how it should behave without further debugging.

**Comment by dzanotto** [comment]
I think it's not related to that commit.
Plus, I can reproduce the same behaviour on Sonoma even with older versions (I've tried backwards until 0.15.6, and I'm sure that that version was working before Mac OS update)

**Comment by MichalMoravik** [comment]
Same issue here, any update on this please?

**Comment by ianyh** [comment]
This is weird. I did a bunch of testing, and it seems like the function just doesn't behave correctly anymore. It still loses focus for every case I tried; disabling following to the space, disabling the new raise code, disabling raising at all, etc. Nothing seems to work. It seems like yabai sidesteps it with the Dock injection, but I'm not sure how to do it here.

**Comment by ianyh** [comment]
Could someone(s) look at the video in the PR? I could use feedback on how janky is too janky. https://github.com/ianyh/Amethyst/pull/1586

**Comment by dzanotto** [comment]
> This is weird. I did a bunch of testing, and it seems like the function just doesn't behave correctly anymore. It still loses focus for every case I tried; disabling following to the space, disabling the new raise code, disabling raising at all, etc. Nothing seems to work. It seems like yabai sidesteps it with the Dock injection, but I'm not sure how to do it here.

Additional information: yabai works even without Dock injection (so without disabling System Integrity Protection).
Right now I've installed yabai together with Amethyst as a workaround, using yabai only to throw windows between spaces.

**Comment by dzanotto** [comment]
> Could someone(s) look at the video in the PR? I could use feedback on how janky is too janky. #1586

To be honest, the behaviour in the video appears to be quite "distracting"... sorry :)

**Comment by ianyh** [comment]
> > This is weird. I did a bunch of testing, and it seems like the function just doesn't behave correctly anymore. It still loses focus for every case I tried; disabling following to the space, disabling the new raise code, disabling raising at all, etc. Nothing seems to work. It seems like yabai sidesteps it with the Dock injection, but I'm not sure how to do it here.
> 
> 
> 
> Additional information: yabai works even without Dock injection (so without disabling System Integrity Protection).
> 
> Right now I've installed yabai together with Amethyst as a workaround, using yabai only to throw windows between spaces.

Interesting! I'll take a closer look.

**Comment by ianyh** [comment]
I tested yabai, and I still see the flickering. I think you need the scripting addition for it to work totally correctly. @dzanotto do you have sa configured?

**Comment by dzanotto** [comment]
> I tested yabai, and I still see the flickering. I think you need the scripting addition for it to work totally correctly. @dzanotto do you have sa configured?

No, I don't have scripting addition configured.

https://github.com/ianyh/Amethyst/assets/12510099/128c917e-41a6-4ae0-b8bc-173191df34e2

In the attached video you can see the following:
- moving form space x to space x+1 (standard Mac OS behaviour)
- moving back from space x+1 to space x (standard Mac OS behaviour)
- throwing a window from space x to space x+1
  - moving the window is done by skhd calling "yabai -m window --space next --focus"
  - tiling the windows is done by Amethyst

I don't see the flickering that was apparently present in your video, but I may be wrong.

**Comment by ianyh** [comment]
Thanks for confirming for me! I'll keep fiddling with it.

**Comment by ianyh** [comment]
Okay, yabai actually _does_ lose focus on space changes, but seemingly only if you move to a space that the window has not yet appeared on and _without `--focus`_. That is, if you move the window, and then manually traverse to the space yourself, then the window loses focus.

**Comment by ianyh** [comment]
Okay, I think I figured out what was happening. Silica's focus code was performing an application activate in addition to a raise action. Moving _and following_ windows seems to behave correctly now.

**Comment by dzanotto** [comment]
Hi @ianyh, I've tried to build Amethyst from source code and I still get the old behaviour. Am I missing something?

**Comment by ianyh** [comment]
I'll double check that I didn't mess up the merge or something.

**Comment by ianyh** [comment]
Hm. It seems to be inconsistent now for me, and I'm not sure why.

**Comment by asmvik** [comment]
If you claim that yabai is working correctly, this is how it works:

1. User executes command to move a window to another space. (`yabai -m window --space next`)
2. If the window to be moved is currently focused ("has key-input")
 a) Is this the last window on this space -> focus finder process with no window id
 b) Not last window on this space -> focus the next window in focus order on this space
3. Move the window to the target space

Now in yabai I allow for chaining commands, so the comment earlier used `yabai -m window --space next --focus`, which basically makes yabai add a step 4. to the above list, that changes the focus back to the window. It might seem redundant to first remove focus, just to refocus again, but I found that to work more reliably.

Not sure if this is related to your issue here, but figured I'd mention it.

**Comment by ianyh** [comment]
Thanks, @koekeishiya!

I figured this out finally. I think it's actually the code for detecting changes in tabs being a little overzealous when spaces change.

**Comment by ianyh** [comment]
Okay, after tearing my hair out for some time and disabling basically everything that Amethyst does other than moving windows between spaces, and the loss of focus persists. There must be some race condition with moving a window to a new space and focusing the window to trigger the space change.

**Comment by ianyh** [comment]
@dzanotto could you try the branch in #1591 when you get a chance? I need more data points for my own sanity.

**Comment by dzanotto** [comment]
> @dzanotto could you try the branch in #1591 when you get a chance? I need more data points for my own sanity.

Hi @ianyh, I've tried the branch "window-focusing" and it works!
Thanks for putting so much effort in it :)

**Comment by ianyh** [comment]
Thanks!
