### ISSUE TITLE
Custom layout window IDs changing randomly since Sonoma

### ISSUE THREAD

**Issue by joliss** [ianyh/Amethyst#1570]
**Describe the bug**
In my custom layout, the window IDs that Amethyst passes as the first argument to `getFrameAssignments` have been changing randomly since I updated macOS from 13.6 to 14.1 Sonoma.

**Applications:**
Repros with just Chrome windows, and also with iTerm and VS Code.

**To Reproduce**
In your custom layout, print the first argument like so:

```js
    getFrameAssignments: (windows, screenFrame, state) => {
      console.log("getFrameAssignments: " + JSON.stringify(windows, null, 2));
      return;
    }
```

Enable the "Show debug info: About layouts" setting, and restart Amethyst from the command line like so:

```
/Applications/Amethyst.app/Contents/MacOS/Amethyst test --log
```

Then activate the custom layout and repeatedly change focus between different windows to repeatedly trigger `getFrameAssignments`.

**Expected behavior**
The set of window IDs printed to the terminal should be the same with each call.

**Screenshots**
I took a screen recording where I just repeatedly press Cmd+` to toggle focus between two Chrome windows. As you watch the IDs being printed on the left side, you can see the IDs seem to be changing semi-randomly.
https://github.com/ianyh/Amethyst/assets/524783/5301186a-0dfb-423a-a0a6-ae703cfd50d9
(YouTube mirror: https://www.youtube.com/watch?v=paRBM9TXRWs)

**Versions:**
 - macOS: 14.1
 - Amethyst: 0.20.0
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info --include-apps
Version: 0.20.0 (108)

OS version: Version 14.1 (Build 23B74)

Screens:
	(0.0, 0.0, 3008.0, 1692.0) [(0.0, 0.0, 3008.0, 1692.0)]
	(-2560.0, 252.0, 2560.0, 1440.0) [(-2560.0, 0.0, 2560.0, 1440.0)]

Configuration:
screen-padding-top: 0
window-minimum-height: 0
mouse-follows-focus: 0
mouse-resizes-windows: 1
use-canary-build: 0
enables-layout-hud: 1
mod1: (
    option,
    shift
)
float-small-windows: 1
restore-layouts-on-launch: 1
new-windows-to-main: 0
window-max-count: 0
screen-padding-bottom: 0
floating: (
        {
        id = "com.hegenberg.BetterSnapTool";
        "window-titles" =         (
        );
    },
        {
        id = "com.hegenberg.BetterTouchTool";
        "window-titles" =         (
        );
    }
)
window-margin-size: 0
mod2: (
    option,
    shift,
    control
)
layouts: (
    floating,
    jo,
    "two-pane"
)
window-resize-step: 5
mouse-swaps-windows: 1
follow-space-thrown-windows: 1
focus-follows-mouse: 0
enables-layout-hud-on-space-change: 1
floating-is-blacklist: 1
screen-padding-right: 0
debug-layout-info: 1
window-minimum-width: 0
screen-padding-left: 0
ignore-menu-bar: 0
window-margins: 0

Manageable applications:
	Finder (com.apple.finder)
	Parallels Desktop (com.parallels.desktop.console)
	Endel (com.endel.endel)
	Google Chrome (com.google.Chrome)
	iTerm2 (com.googlecode.iterm2)
	System Settings (com.apple.systempreferences)

```

**Comment by ianyh** [comment]
The ids are not intended to be stable, but rather a way to tell the system which frame applies to which of the provided windows. They are based on the ids that the operating system uses, though, which we don't have control over. It sounds like they stopped being stable in Sonoma.

**Comment by joliss** [comment]
Ah! So I guess there's no more way to track window identity across calls to `getFrameAssignments`?

For example, the `subset.js` sample [uses window.id](https://github.com/ianyh/Amethyst/blob/e6f7a5d63e8829dae6d88ed4a4c3dc5c60158672/AmethystTests/Model/CustomLayouts/subset.js#L47), and I'm assuming it's broken in Sonoma now? In my own custom layout, I get windows jumping around randomly because their IDs keep changing.

A workaround I could imagine would be just treating all windows as anonymous and recovering their state from their frame positions.

But if you could find a way to pull the necessary data from macOS to provide some kind of consistent identity for each window, that would make writing custom layouts much easier I think!

**Comment by vjraitila** [comment]
I ran into the same issue. My custom layout is optimized for wide screens and 3 columns. But it also tracks the IDs of individual windows I have temporarily "zoomed" i.e. to temporarily span more than one column. That is sadly broken now and I've yet to find a workaround.
