### ISSUE TITLE
Send desktop to display

### ISSUE THREAD

**Issue by b0lle** [ianyh/Amethyst#1578]
**Is your feature request related to a problem? Please describe.**
I want to keep my desktops clean. Each application in my setup is assigned to a specific desktop. When using multiple monitors, the current solution only allows to move applications to other desktops or monitors. This shuffles the application <-> desktop relation and results in the usage of few desktops with much more applications than one can handle.

**Describe the solution you'd like**
I want to move a desktop to a monitor (display), including all applications living in the desktop.

**Describe alternatives you've considered**
I have used yabai, which supports this feature. Unfortunately the application was a little bit buggy on my system.

**Comment by ianyh** [comment]
Interesting. The space manipulation operations in yabai require dock injection, so that's probably not feasible. I could think about bulk window operations; e.g., move all of the windows on this screen to this other screen.

**Comment by b0lle** [comment]
I think it should be possible to keep the desktop numbers after moving all the windows. (edit: renamed spaces to desktop, which seems to be more accurate)

**Comment by ianyh** [comment]
I'm not sure what you mean by spaces numbers.

**Comment by b0lle** [comment]
ah ok, I edited my feature request to be more precise.
The monitor is the hardware which we use for human visualization.
The desktops are shown when you press ctrl + up and are numerated (this is what I called spaces). Applikations are living on desktops.

**Comment by ianyh** [comment]
Okay, yeah, you're asking for the space manipulation stuff, which, as I said, is not feasible for Amethyst because those APIs require the dock injection which requires disabling SIP.

**Comment by b0lle** [comment]
thats too bad :(
