### ISSUE TITLE
[Feature Request] Add shortcut to throw focused window to the fifth screen

### ISSUE THREAD

**Issue by x-ji** [ianyh/Amethyst#1584]
Now that Mac has been supporting maximum 5 displays for a while, it would make sense to add a shortcut to throw the focused window to the fifth screen. It seems that the current shortcut config supports up to 4 screens.

**Comment by x-ji** [comment]
I can also give it a try if somebody helps to point me to the right direction 🙏 .

**Comment by ianyh** [comment]
@x-ji take a look at HotKeyManager. It constructs the screen commands.

**Comment by x-ji** [comment]
@ianyh Thanks. Opened a PR at https://github.com/ianyh/Amethyst/pull/1627
