### ISSUE TITLE
Margins and/or frames

### ISSUE THREAD

**Issue by MartinAyla** [ianyh/Amethyst#160]
Would be nice to have an option for margins around windows, could be used to add some distance between windows to avoid shadow overlap (ie. SizeUp has a Margin ability).

Not nearly as important as margins, but 1px frames or similar could be nice to.

Like we have on many Linux WM's.

Thanks guys for a great OS X WM :-)

[Trello Card](https://trello.com/c/ldM4BZ5y/51-amethyst-margins-and-or-frames)

**Comment by ianyh** [comment]
This got implemented in #298 !
