### ISSUE TITLE
Shrinking and Expanding Main Panel Not Working

### ISSUE THREAD

**Issue by mick-io** [ianyh/Amethyst#1600]
**Describe the bug**
When I press the hotkeys for shrinking and expanding the main panel, There is no response.

**Applications:**
Firefox, Alacritty, everything else

**To Reproduce**
Can't offer much help here. The same problem happens reguardless of number of panels or layout

**Expected behavior**
When I press `option + shift + H || L` I expect the selected pane to increase or decrease in size respectively.

**Screenshots**

**Versions:**
 - macOS: Sonoma 14.3
 - Amethyst: 0.20.0
 
**Debug Info**
```
Version: 0.20.0 (108)

OS version: Version 14.3 (Build 23D56)

Screens:
	(0.0, 0.0, 1800.0, 1169.0) [(0.0, 0.0, 1800.0, 1169.0)]
	(-3440.0, 0.0, 3440.0, 1440.0) [(-3440.0, -271.0, 3440.0, 1440.0)]

Configuration:
mouse-resizes-windows: 0
mod1: (
    option,
    shift
)
use-canary-build: 0
float-small-windows: 1
restore-layouts-on-launch: 0
disable-padding-on-builtin-display: 1
window-minimum-width: 0
ignore-menu-bar: 0
debug-layout-info: 1
mouse-follows-focus: 1
window-margin-size: 10
screen-padding-top: 5
mod2: (
    option,
    shift,
    control
)
screen-padding-left: 5
screen-padding-right: 5
smart-window-margins: 1
window-resize-step: 5
new-windows-to-main: 1
window-max-count: 4
screen-padding-bottom: 5
window-minimum-height: 0
enables-layout-hud-on-space-change: 1
floating-is-blacklist: 1
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
window-margins: 1
enables-layout-hud: 1
focus-follows-mouse: 0
floating: (
)
follow-space-thrown-windows: 1

Manageable applications:
	Firefox (org.mozilla.firefox)
	Alacritty (org.alacritty)
	Finder (com.apple.finder)
	Keybase (keybase.Electron)

```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

**Additional context**

I've tried restarting Amethyst, and my computer. I've toggled different options and tried to find an error log, but nothing came up.

**Comment by mick-io** [comment]
Issue resolved by updating my system settings.

**Comment by gwtaylor** [comment]
> Issue resolved by updating my system settings.

Do you remember which setting you updated to fix this? Recently this has started to happen to me. It only happens on my main display, while shrink & expand work fine on my secondary and tertiary displays. It is also happening only in Column layout, not Wide or Tall.

**Comment by gwtaylor** [comment]
I've also noticed that in "Arrange Displays" moving the menu bar off of my external display and onto my laptop display fixes the problem. So it seems to occur only when my main external display is marked as primary monitor (menu bar) and in column layout. Column layout on my other external display and my laptop display, even when they are marked as primary, doesn't trigger the issue.

**Comment by gwtaylor** [comment]
In case others encounter this issue, doing a full reset of Display Preferences resolved the issue for me:

1. Disconnect the external monitor.
2. Open Terminal and run the following command to reset macOS's display preferences:
```bash
sudo rm /Library/Preferences/com.apple.windowserver.plist
```
3. Reboot your Mac and reconnect the external monitor.
