### ISSUE TITLE
Amethyst Causes Android Emulator flickering in mac m2 pro

### ISSUE THREAD

**Issue by Arsh-78** [ianyh/Amethyst#1602]
**Describe the bug**
Constant Window Resizing in MacBook M2 pro while using Android Emulator
**Applications:**
Android Emulator

**To Reproduce**
1. Install Amethyst
2. Get Android Emulator from Android Studio
3. Launch Emulator wside by side with another application

**Expected behavior**
Either the emulator gets tiled in available space or keeps floating without resizing

**Screenshots**
![2024-02-16 12 25 53](https://github.com/ianyh/Amethyst/assets/76211430/72b8fccb-38c1-47b4-b778-51ab1a41b1bd)

**Versions:**
 - macOS: Sonoma 14.3
 - Amethyst: 0.20.8
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info [--include-apps]
```
Note: `--include-apps` will list your manageable applications, but is optional if you don't want to list that.

**Additional context**

**Comment by ThaNivek** [comment]
Same thing here.

**Comment by Arsh-78** [comment]
Anyone Facing this issue refer #1388
