### ISSUE TITLE
Unable to set backspace (or delete) as shortcut key in config

### ISSUE THREAD

**Issue by harish-prakash** [ianyh/Amethyst#1628]
**Describe the bug**
Setting mod1+delete in the preferences window works as a valid shortcut but setting `mod1` + `delete` in the config file does not work

**Applications:**
Everything

**To Reproduce**
- Open `~/.config/amethyst/amethyst.yml`
- Set the following property
  ```
  select-fullscreen-layout:
    mod: mod1
    key: delete
  ```

**Expected behavior**
`mod1` + `delete` becomes a valid shortcut consistent with the ui-only behavior

**Screenshots**

**Versions:**
 - macOS: Sonoma 14.4.1
 - Amethyst: 0.20.0 (108)

**Comment by ianyh** [comment]
This will be added when 0.21.0 is released. You can download the beta now if you would like.
