### ISSUE TITLE
Move window to next/prev space

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#164]
Space IDs get a bit confusing to remember with multiple spaces and multiple monitors.  Would be nice to be able to just move a window to the next/previous space.

[Trello Card](https://trello.com/c/T5ZkdNFZ/52-amethyst-move-window-to-next-prev-space)

**Comment by adbl** [comment]
+1 !

**Comment by metalseargolid** [comment]
+1

**Comment by nodar-chkuaselidze** [comment]
+1

**Comment by Pitometsu** [comment]
I see https://github.com/ianyh/Amethyst/pull/458 implementation, but there no keys for it in preferences. Is it deprecated feature. It would be pretty useful. Could you reopen this feature request, please, if current version miss this functionality. AFAIK SizeUp have such functionality, so it should be possible.

**Comment by ianyh** [comment]
It looks like it is incorrectly left out of the in-app preferences. It is `mod2+left` and `mod2+right` by default. I'll open a separate issue to address them not being in preferences.

**Comment by ianyh** [comment]
Opened #660
