### ISSUE TITLE
Does not find latest version when checking for updates from Amethyst

### ISSUE THREAD

**Issue by acidghost** [ianyh/Amethyst#1644]
Version 0.21.0 has been released but the XML Amethyst gets new versions from has not been updated.

- https://ianyh.com/amethyst/appcast.xml
- https://github.com/ianyh/ianyh.github.io/blob/64ea29694b2f83d3c5a201dbbd01255c8a662ee4/amethyst/appcast.xml

**Comment by kolchurinvv** [comment]
I ran a brew update last night - it found it even though I can add that it was late compared to when the version has been released

**Comment by acidghost** [comment]
Homebrew checks GitHub directly https://github.com/Homebrew/homebrew-cask/blob/9a2e34b419b44bbb4cad8dc4d762062ad96228ba/Casks/a/amethyst.rb#L19-L22.

You got it slightly later than the GitHub release because Homebrew livecheck does not run automatically from a centralized location. Formula maintainers have to ultimately trigger the update.

In my case I'm trying to update from Amethyst itself, i.e. from the dropdown menu, then "Check for Updates...".
