### ISSUE TITLE
Ability to throw window to next/prev screen

### ISSUE THREAD

**Issue by z1645444** [ianyh/Amethyst#1666]
**Is your feature request related to a problem? Please describe.**

Searched for:

- throw window to next screen
- throw window to close screen
- replace "throw" into "move" and search over again

And I got nothing. So seems like not related to any others.

**Describe the solution you'd like**

Now we have throw window to screen 1/2/3/4. I want Amethyst get the ability to throw window to next/prev screen.

I should give some cases to help you guys get what I mean. Above all, let's assume that we have 3 monitors.

case1: on screen 1, throw to next screen, expect throwed to screen 2;
case2: on screen 2, throw to next screen, expect throwed to screen 3;
case3: on screen 3, throw to next screen, expect throwed to screen 1;
case4: on screen 1, throw to next screen, expect throwed to screen 3;

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by phillipvanheerden** [comment]
Isn't this what "Throw focused window to space left" and "Throw focused window to space right" do? I might be misunderstanding, but those do what you describe. 

On that note, since my update to MacOS `14.5 (23F79)` (running Amethyst `0.21.0 (110)`), those shortcuts no longer work for me.

**Comment by liozur** [comment]
> On that note, since my update to MacOS `14.5 (23F79)` (running Amethyst `0.21.0 (110)`), those shortcuts no longer work for me.

Not work for me too : (

**Comment by phillipvanheerden** [comment]
https://github.com/ianyh/Amethyst/issues/1643

Looks like this has been fixed already, I had to reinstall Amethyst though (ala `brew install --cask amethyst`). Works again now (on Amethyst `0.21.1 (111)`)!

**Comment by Deichscheich** [comment]
> #1643
> 
> Looks like this has been fixed already, I had to reinstall Amethyst though (ala `brew install --cask amethyst`). Works again now (on Amethyst `0.21.1 (111)`)!

Oh wow, thank you for that hint @phillipvanheerden. Reinstalling did the job for me, after spending a lot of time trying to figure out what went wrong.

**Comment by z1645444** [comment]
> Isn't this what "Throw focused window to space left" and "Throw focused window to space right" do? I might be misunderstanding, but those do what you describe.
> 
> On that note, since my update to MacOS `14.5 (23F79)` (running Amethyst `0.21.0 (110)`), those shortcuts no longer work for me.

Throw to screen is not throw to space. Space is like a desktop, but screen is like a monitor on your MacBook.

**Comment by blue-3** [comment]
> > #1643
> > Looks like this has been fixed already, I had to reinstall Amethyst though (ala `brew install --cask amethyst`). Works again now (on Amethyst `0.21.1 (111)`)!
> 
> Oh wow, thank you for that hint @phillipvanheerden. Reinstalling did the job for me, after spending a lot of time trying to figure out what went wrong.

interestingly, that did not work for me - but seems to have worked for some others. 
intel mac
macos 14.5

**Comment by MoonKraken** [comment]
> #1643
> 
> Looks like this has been fixed already, I had to reinstall Amethyst though (ala `brew install --cask amethyst`). Works again now (on Amethyst `0.21.1 (111)`)!

this worked for me after struggling with this for weeks, thank you so much!

**Comment by corneliushennch** [comment]
> #1643
> 
> Looks like this has been fixed already, I had to reinstall Amethyst though (ala `brew install --cask amethyst`). Works again now (on Amethyst `0.21.1 (111)`)!

Throwing windows to other spaces still doesn't work for me after updating to Amethyst `0.21.1 (111)`. I am running macOS `12.7.6 (21H1320)`on an Intel MacBook.
