### ISSUE TITLE
Option to whitelist tiled windows

### ISSUE THREAD

**Issue by glacials** [ianyh/Amethyst#171]
I treat the `floating` array as a blacklist for programs that don't cooperate well with resizing, or that always have my full attention (like games). It'd be nice to be able to swap this behavior to whitelist style, where I have to add programs to a list in order for them to be tiled.

Thanks!

[Trello Card](https://trello.com/c/dTrr0fVL/53-amethyst-option-to-whitelist-tiled-windows)

**Comment by kavika13** [comment]
@ianyh - I have been using Amethyst for a while now, and I'm finally giving up because I'm spending more time blacklisting and futzing than I am saving at this point. Whitelists IMO are a much better option, as I really only want my dev environment to tile.

**Comment by kavika13** [comment]
@ianyh - I have been using Amethyst for a while now, and I'm finally giving up because I'm spending more time blacklisting and futzing than I am saving at this point. Whitelists IMO are a much better option, as I really only want my dev environment to tile. I think this feature is badly needed.

**Comment by MaThGo** [comment]
Please implement this #200 is a dealbreaker for my workflow.
Otherwise I've to resort to KWM or the unstable ChunkWM.

**Comment by axs221** [comment]
@ianyh I can take a look at this one. I am thinking a checkbox in the Floating section that says "Float all except selected". I haven't looked at where the list is used, but I'm guessing it won't be difficult to invert the check.

**Comment by axs221** [comment]
@strflw I will have a PR up for this soon. As for #200, if you have upgraded to the latest iTerm2 there is a chance iTerm2 will work with Amethyst properly with the built-in iTerm2 "No Title Bar" setting. See #200 for more information, and it would be helpful to know if you can still reproduce at that point.
