### ISSUE TITLE
Manually resizing a window should possibly adjust layout parameters

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#180]
e.g., if I have two windows tiled side by side and I resize the left window to be larger in width, the layout should adjust to maintain that ratio.

[Trello Card](https://trello.com/c/Sxgbnsys/56-amethyst-manually-resizing-a-window-should-possibly-adjust-layout-parameters)

**Comment by ifreecarve** [comment]
I think #617 might be a duplicate of this.  Should probably add the word "mouse" to this title though.

**Comment by ianyh** [comment]
I'll close this in favor of that issue.
