### ISSUE TITLE
Excel disables Amethyst

### ISSUE THREAD

**Issue by stylerw** [ianyh/Amethyst#182]
For some reason, whenever I open Microsoft Excel, the Amethyst icon turns grey, and Amethyst just gives up on life until restarted.  That seems like a bug.

[Trello Card](https://trello.com/c/mODUdXkh/57-amethyst-excel-disables-amethyst)

**Comment by ianyh** [comment]
This would be a good issue for someone with Excel to take on. Should be straightforward to reproduce if it's still an issue.

**Comment by brandonkal** [comment]
I have Excell and I haven't seen this issue in the current version.

**Comment by ianyh** [comment]
Now that I think about it I use excel at work and have never encountered this. It’s also been more than half a decade in this so I’m comfortable closing.

**Comment by brandonkal** [comment]
Time flies.
