### ISSUE TITLE
when using with parallels, changing layout doesnt trigger vm resolution change

### ISSUE THREAD

**Issue by shlomiv** [ianyh/Amethyst#193]
When using parallels, and changing the layout, say from tall to columns, the vm becomes streched, and is only fixed when I manually resize the vm window

[Trello Card](https://trello.com/c/B7B3IOaR/63-amethyst-when-using-with-parallels-changing-layout-doesnt-trigger-vm-resolution-change)

**Comment by ianyh** [comment]
This is very old and I'm not sure we can make external apps respond better to window frame changes. If it's still a significant issue let me know.
