### ISSUE TITLE
window resizing when switching spaces

### ISSUE THREAD

**Issue by charle5** [ianyh/Amethyst#207]
os x 10.9.3
amethyst 0.8.6

when switching spaces application windows get wonky and resize

http://youtu.be/97FGTprVuMw

kindly lemme know if there's anything i'm doing wrong, or if there's anything i can do to help fix.

[Trello Card](https://trello.com/c/jBERfaSw/70-amethyst-window-resizing-when-switching-spaces)

**Comment by ianyh** [comment]
I believe the fix for #254 should also apply here.
