### ISSUE TITLE
~1 second delay when switching between windows; unbearably slow at random times

### ISSUE THREAD

**Issue by viclib** [ianyh/Amethyst#209]
There is a ~1 second delay when switching between windows, which makes the experience very frustrating. At random times (usually when I don't use the app for a few minutes), the lag is unbearable, taking around 8s for it to react. Also, when I open Firefox, it pretty much never detects it. I have to relaunch Amethyst. Great idea, but terribly buggy. 

I'm using a freesh install of OSX 10.9.4 on a new macbook. Not sure which Amethyst version, it doesn't show, but I just downloaded it on the official site.

[Trello Card](https://trello.com/c/UIrIYKo5/71-amethyst-1-second-delay-when-switching-between-windows-unbearably-slow-at-random-times)

**Comment by spieden** [comment]
I'm running a build with some logging inserted to try and narrow down where these hangs come from. Observed one so far:

2015-04-13 15:58:46:766 Amethyst[38965:30b] moveFocusClockwise->enter
2015-04-13 15:58:46:767 Amethyst[38965:30b] moveFocusClockwise->gotFocusedWindow
2015-04-13 15:58:52:785 Amethyst[38965:30b] moveFocusClockwise->gotScreenWindows

Trying to dig in deeper.

**Comment by ianyh** [comment]
I've done some more digging and it looks like the major problem is this method on `SIWindow`:
```obj-c
- (BOOL)isActive {
    if ([[self numberForKey:kAXHiddenAttribute] boolValue]) return NO;
    if ([[self numberForKey:kAXMinimizedAttribute] boolValue]) return NO;
    
    CGWindowID windowID;
    AXError error = _AXUIElementGetWindow(self.axElementRef, &windowID);
    if (error != kAXErrorSuccess) {
        return NO;
    }
    
    CFArrayRef windowDescriptions = CGWindowListCopyWindowInfo(kCGWindowListOptionOnScreenOnly, kCGNullWindowID);
    BOOL isActive = NO;
    for (NSDictionary *dictionary in (__bridge NSArray *)windowDescriptions) {
        CGWindowID otherWindowID = [dictionary[(__bridge NSString *)kCGWindowNumber] intValue];
        if (otherWindowID == windowID) {
            isActive = YES;
            break;
        }
    }
    
    CFRelease(windowDescriptions);
    
    return isActive;
}
```

More specifically, `CGWindowListCopyWindowInfo` appears to be a non-trivially expensive call, and this method gets called a lot so it builds up.

**Comment by spieden** [comment]
That's encouraging. There's a lot of variability in the duration and frequency of the hangs I experience. Do you think the cost of this call also varies with external factors in the accessibility APIs?

**Comment by ianyh** [comment]
There are definitely external variables. I expect part of it is some
internal caching and it gets pushed out after using a bunch of other stuff.

**Comment by spieden** [comment]
Hmm, could we try a hack where a background thread tries to keep that cache warm? I do think I experience it more after prolonged idle periods.

**Comment by Ahti** [comment]
Would there be a way to speed up this process by optionally (and unsupportedly) using private api instead of the accessibility framework?

**Comment by ianyh** [comment]
As far as I know, private API wouldn't really help here. I don't know at what level the caching is happening.

I think the actual solution here is keeping our own cache of the window info list, and refreshing it whenever windows change. Then we can inject it into the calls that need it.

It's not ideal, though. One of the things I like about that method on `SIWindow` is it's relatively stateless. It can be computed fairly reliably. Introducing our own cache adds a point of failure if we miss a change somewhere. But I suppose that's always the trade off when it comes to performance.

**Comment by SrVictorMaia** [comment]
Is anyone working on this? I don't understand the seemingly lack of concern with this issue, it in my opinion completely destroys the workflow when using amethyst, which, other than that, is a very great app.

**Comment by ianyh** [comment]
Yeah. I plan on doing this, I just haven't really had the time to do so. It's pretty high on my list, though.

**Comment by ianyh** [comment]
Initial work on caching a few high volume is calls is pretty promising so far. Feeling snappy. I'll live with it for a bit longer to see if it pans out.

**Comment by Ahti** [comment]
nice :+1:

**Comment by MaiaVictor** [comment]
(y) /2

**Comment by ianyh** [comment]
Okay. Going to close this for now and it can get reopened if there's still problems.

**Comment by spieden** [comment]
Oh man, thank you so much. My quality of life just went up like ten points. =)

**Comment by ianyh** [comment]
I'm happy to hear it. :smile:
