### ISSUE TITLE
Grid layout

### ISSUE THREAD

**Issue by kennethlove** [ianyh/Amethyst#214]
It would be nice to have a layout that evenly distributes windows in a grid instead of just rows or columns.

[Trello Card](https://trello.com/c/1Nz3E6Di/72-amethyst-grid-layout)

**Comment by benmosher** [comment]
:+1:

**Comment by gkop** [comment]
Thanks for the tip @benmosher . Any idea how to fix the main-panel count at 2 across Amethyst restarts?

**Comment by ianyh** [comment]
Not possible yet, unfortunately. See #151

**Comment by mdbootstrap** [comment]
Is it possible to achieve basic greed layout? 4 windows, same size?

**Comment by ianyh** [comment]
If you have 4 windows you can use, for example, the tall layout and increase the main pane count to 2.

**Comment by nahtnam** [comment]
What @ianyh said worked for me. Go to wide and press `option + shift + ,`!

**Comment by ianyh** [comment]
I think this should be possible with custom layouts now. #1134

**Comment by edgimar** [comment]
> I think this should be possible with custom layouts now. [#1134](https://github.com/ianyh/Amethyst/pull/1134)

It does seem to work with custom layouts: see the dynamic grid layout implementation in https://github.com/ianyh/Amethyst/issues/1819.
