### ISSUE TITLE
iTerm constantly resizing

### ISSUE THREAD

**Issue by thomaskern** [ianyh/Amethyst#216]
I have a second external monitor (24", 1920x1280) in vertical mode. I position 2 iterm windows there. The layout is 'Rows'.

What happens now is that the windows constantly resize. If i give focus to the bottom one, it increases its height and overlaps with the top window and vice versa.

The "solution" is to put a third window there temporarily (Chrome in my case) and after the resizing is done, throw the third window to the other screen. Now both iterm windows are at exactly have the size and don't consistently try to resize themselves.

I am running Amethyst 0.8.6.

[Trello Card](https://trello.com/c/6WJ5evfY/73-amethyst-iterm-constantly-resizing)

**Comment by om2c0de** [comment]
If someone else has problems with Iterm2 resizing - there is the option in Iterm2 menu Preferences -> Advanced -> Resize smoothly (should be - "on")..and Amethyst will work well with it.
