### ISSUE TITLE
Focus Follow mouse fails for Messages.app

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#226]
Steps:
Enable focus follows mouse
Open two safari windows and Messages.app
Focus will switch to safari windows on mouse movement but won't switch to messages.app

Versions:
Amethyst: 0.9.1
OSX: 10.10 PB 4

[Trello Card](https://trello.com/c/BEMZPq8I/76-amethyst-focus-follow-mouse-fails-for-messages-app)

**Comment by ianyh** [comment]
@leonardt @robbiet480 This still true?

**Comment by marcusdarmstrong** [comment]
Yes, I'm currently experiencing it with 0.9.10 on OS X 10.11.2. I think there's something pretty funky Apple is doing with the Messages app window, as it also fails to get "picked up" by Amethyst when I open the app... I have to have it open and then restart Amethyst to get it to tile.

**Comment by ianyh** [comment]
Sounds like a symptom of #49
