### ISSUE TITLE
switch to Preferences Window using command-tab

### ISSUE THREAD

**Issue by brandondrew** [ianyh/Amethyst#228]
It is nice that Amethyst is **_not**_ in the Dock normally.  This is a **_very**_ good thing.  

But it would be nice if it would show up in the Dock (and therefore the <kbd>command</kbd><kbd>tab</kbd> menu) when the Preferences window is open.  This would make it easier to get back and forth between the Amethyst Preferences and other app windows when trying out different preferences, or when trying out (that is, learning) different keystrokes.

[Trello Card](https://trello.com/c/z7oqgO59/78-amethyst-switch-to-preferences-window-using-command-tab)

**Comment by ianyh** [comment]
Two things:
 - The preferences window is now floating
 - The preferences window can be opened by launching Amethyst while it is running
