### ISSUE TITLE
Focus follows mouse + Mouse follows focus causes weirdness when moving windows

### ISSUE THREAD

**Issue by leonardt** [ianyh/Amethyst#240]
Swapping windows around with both focus follows mouse and mouse follows focus enabled causes weirdness.

I will get steps to reproduce this when I get time, but I think it has to do with when the windows are swapped, focus follows mouse triggers on the new window, but the logic to move the mouse with the swapped window also triggers (~~in what appears to be a non deterministic order but I may be wrong about that, I'll have to test it more~~ I think it is the focus follows mouse triggers after the window swap focus, so the mouse remains in the current window?).

My intuitions says a simple fix would be to disable focus follows mouse when swapping windows and enable it after the operation is done.

This is on 0.9.4b on 10.10 PB 6 (Would be good to check if this is an issue on mavericks as well once I get some reproduction steps up).

[Trello Card](https://trello.com/c/xq6Kvgya/82-amethyst-focus-follows-mouse-mouse-follows-focus-causes-weirdness-when-moving-windows)

**Comment by ianyh** [comment]
We should just disable mouse-follows-focus in preference for focus-follows-mouse.

**Comment by ianyh** [comment]
I think this was fixed by #1013.
