### ISSUE TITLE
Moving window to another monitor causes it to not tile in some cases

### ISSUE THREAD

**Issue by caskolkm** [ianyh/Amethyst#242]
(0.9.4b) When i move a window to a other monitor screen with a different resolution:
- the window doesn't resize.
  ![screen shot 2014-10-17 at 09 43 24 2](https://cloud.githubusercontent.com/assets/2329830/4675803/52fcb5d4-55d1-11e4-8760-e166614c46fb.png)
- sometimes the window drops back to de first monitor screen.

[Trello Card](https://trello.com/c/q6m2doNk/83-amethyst-moving-window-to-another-monitor-causes-it-to-not-tile-in-some-cases)

**Comment by ianyh** [comment]
I think this is covered by #9.
