### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by caskolkm** [ianyh/Amethyst#254]
based on #235 running yosemite and amethyst 0.9.4: look at the menu bar..

![screen shot 2014-10-24 at 13 30 08](https://cloud.githubusercontent.com/assets/2329830/4769374/15ef24bc-5b79-11e4-945d-8b06f1e123ae.png)

[Trello Card](https://trello.com/c/YE0NCdFb/93-amethyst-fullscreen-mode)

**Comment by ianyh** [comment]
Okay, new theory:

Looking at the reflow calls on my machine the sequence is as follows:
* Start fullscreen
* Finish fullscreen
* Triggers space change
* Reflow
* Reflow

However, as explained in #177 , shifting GPUs can trigger reflows. If the fullscreen transition animation triggers a GPU shift you could run into the following sequence of events:
* Start fullscreen
* Reflow
* Finish fullscreen
* Trigger space change
* Reflow
* Reflow

This might explain why it happens to some people and not others, and the sequence of events would cause the observed effects. Going to see if I can figure out a way to patch things up.

**Comment by Hultner** [comment]
Well I've got an 13" rMBP so at least my machine is experiencing the problem with a single GPU.

**Comment by girvo** [comment]
Same here, only have one GPU :(

**Comment by drumstick23** [comment]
I've two GPU's

**Comment by ianyh** [comment]
Well, it was a nice theory while it lasted.

**Comment by ianyh** [comment]
Released a beta so that I can test something. Let me know if there's any change.

**Comment by drumstick23** [comment]
still the same bug: steps to reproduce it: Multiple virtual desktops, add a single application to one of the virtual desktops, set fullscreen mode, remove the virtual desktop where the app was before fullscreen mode

**Comment by drumstick23** [comment]
Note: no more problems with the menu bar!

**Comment by drumstick23** [comment]
![screen shot 2015-01-11 at 19 11 47](https://cloud.githubusercontent.com/assets/2329830/5696200/b7b68274-99c5-11e4-8223-82f3f6c3b036.png)

**Comment by drumstick23** [comment]
this bug will not happen if you don't remove the virtual desktop where the app was before fullscreen mode

**Comment by ianyh** [comment]
Still can't reproduce. Could somebody possibly give me a screencast of the bug? That might be helpful in diagnosing. I'm glad the menu bar wonkiness isn't happening anymore. I've got one more thing I want to try.

**Comment by drumstick23** [comment]
Look what i got for you: https://www.dropbox.com/s/x023czim0cpwtfv/Amethyst-Bug.mov?dl=0

**Comment by girvo** [comment]
I swear this is the bug from hell!

**Comment by drumstick23** [comment]
yes it is!

**Comment by jmkII** [comment]
I'm getting this bug when I:

**Comment by FuDesign2008** [comment]
I met this problem, too.
MacBook Pro (13-inch, Early 2011)  + OS X Yosemite v 10.10. 2 + amethyst 0.9.4

**Comment by Hultner** [comment]
I haven't had this problem for a while now. Don't seem to be able to trigger it easily either, however as a consequence of this bug I haven't used fullscreen as much lately but I'm slowly converting back to my old workflow and will update if I experience the bug again. 
@ianyh Great work on making spaces and full screen a lot more stable and more usable these past months. I were almost on the verge of dropping Amethyst from my setup for a while there when it was a to big of an inconvenience in my workflow but now I'm back full on again. Keep the great work up!

**Comment by ianyh** [comment]
Anyone try this on 10.10.3 yet?

**Comment by leonardt** [comment]
I've been using it since yesterday and no problems yet, will report back if any occur

**Comment by caskolkm** [comment]
I've been using it since a couple of days, and i can't reproduce it. will report back if any occur

**Comment by ianyh** [comment]
I can now successfully reproduce on my machine with El Capitan installed! Now I just have to get Amethyst actually building with the OS version change.

**Comment by sebroeder** [comment]
> I can now successfully reproduce on my machine with El Capitan installed! Now I just have to get Amethyst actually building with the OS version change.

Are there any new APIs in El Capitan to manipulate full screen windows? I am asking because the new split screen mode is implemented on top of full screen mode and if there aren't any APIs for it, it would mix really badly with Amethyst (I am avoiding full screen mode completely at the moment on Yosemite for this reason).

**Comment by ianyh** [comment]
I've been working on reverse engineering the APIs they are using. I haven't gotten very far yet. On first glance it doesn't look like they added much in the way of API, but the behaviors of the APIs might have changed.

**Comment by jez** [comment]
For what it's worth, this happens for me reliably when

- I have two windows open on my Desktop 1
- I make one of them full screen
- I swipe up and reorganize my desktops
- I click on the app I just made full screen

I've attached a [quick screencast][1] here where I run through it a couple times.

> OS X 10.10.3, Amethyst 0.9.4

[1]: https://youtu.be/cUDzyIrlU5M

**Comment by jez** [comment]
My workaround has been to click on any space that _isn't_ the app I just made full screen, and then from there swipe over to the full screen app. It's a bit of a nuisance, but it works.

**Comment by ianyh** [comment]
@jez Thanks for the steps. Alas, I still can't reproduce. Would you be willing to share your system specs?

**Comment by jez** [comment]
What are you looking for?

- OS X 10.10.3
- Amethyst 0.9.4
- MacBook Air, June 2013

**Comment by ianyh** [comment]
Yeah, that is the information I wanted. I'll see if I can reproduce on my Air.

**Comment by zmingee** [comment]
Just wanted to drop a line and say I have the same issue here. Willing to do testing/debugging to help out. 
* OS X 10.10.5
* Amethyst 0.9.4
* Macbook Pro (Retina, 15-inch, Late 2013) w/ Nvidia GeForce GT 750M


![screen shot 2015-10-03 at 10 15 50 am](https://cloud.githubusercontent.com/assets/6311084/10263322/1e8c90ac-69b8-11e5-91eb-0f29a3a27bd6.png)

**Comment by zmingee** [comment]
Also, side note, I've noticed that if you set the app to always be floating, it seems to keep the issue from popping up.

**Comment by ianyh** [comment]
Progress! I think I may have actually figured this out. You can look at the relevant commit, but the rough idea is that in some cases you can get windows from multiple spaces on screen and if reflow happens in that case it reflows as if everything were on the same space. I think I've got a fix for it. I'll send it out in a development build when I get a chance.
