### ISSUE TITLE
Add a layout that does binary space partitioning

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#255]
https://github.com/baskerville/bspwm

[Trello Card](https://trello.com/c/1I2olDSh/94-amethyst-add-a-layout-that-does-binary-space-partitioning)

**Comment by Rnhmjoj** [comment]
This would be great. +1

**Comment by spencersteers** [comment]
Pulled down your PR and I am loving the layout. Thanks for the awesome work!

**Comment by ianyh** [comment]
Happy to hear it! Let me know if you run into any problems. I think there's still some instability.
