### ISSUE TITLE
Outlook randomly switches float mode

### ISSUE THREAD

**Issue by gprimosch** [ianyh/Amethyst#260]
I have an issue that appears only with MS Outlook, where it will randomly float, and then go back under Amethyst control. 

I can't identify a cause, such as switching spaces. Outlook just floats, windows rearrange, and after a few  seconds unfloat back to where it was before. The issue appears to happen once a day at least. 

I will update this issue if I can find additional details to reproduce it.

[Trello Card](https://trello.com/c/HCQZGS0l/99-amethyst-outlook-randomly-switches-float-mode)

**Comment by logorrhea** [comment]
Disabling `float-small-windows` seems to have fixed this issue for me. Nothing was floating properly for me previously, but now they are as long as I have them in the float list.

**Comment by ianyh** [comment]
I'm going to say #182 also applies here and it's 5 years old anyway. If issue is encountered again please open a new issue.
