### ISSUE TITLE
Shortcuts pane blank in Yosemite

### ISSUE THREAD

**Issue by AnthonBerg** [ianyh/Amethyst#261]
In v0.9.4, the Shortcuts pane is blank. Everything works perfectly though.

![screen shot 2014-10-28 at 19 04 50](https://cloud.githubusercontent.com/assets/49295/4815268/62a630e8-5ed5-11e4-918b-24e8547d0cc2.png)

[Trello Card](https://trello.com/c/N1VzPQAr/100-amethyst-shortcuts-pane-blank-in-yosemite)

**Comment by ianyh** [comment]
I think this should actually be fixed in 0.10. I was doing something wrong with table views.
