### ISSUE TITLE
Assign shortcuts to specific layouts

### ISSUE THREAD

**Issue by thatdutchguy** [ianyh/Amethyst#262]
Instead of having to cycle through layouts to get to the one you want, it would be nice to also have the ability to switch to a specific layout using a shortcut.

[Trello Card](https://trello.com/c/2vlNXfFU/101-amethyst-assign-shortcuts-to-specific-layouts)

**Comment by ianyh** [comment]
There are shortcuts now for each layout, which I think accomplishes the task here.
