### ISSUE TITLE
Some keyboard shortcuts not working

### ISSUE THREAD

**Issue by JensRantil** [ianyh/Amethyst#273]
**Background:** Just installed Amethyst 0.9.4 using brew cask. I have MacOSX Yosemite installed and my laptop has a Swedish keyboard/locale if that helps. I haven't made any keyboard shortcut modifications whatsoever.

**Problem:** I am running I've never user xmonad before, but it seems like there are a few keyboard shortcuts that are only working in some occasions:
- Alt+Shift+,/. - has only worked occasionally. Doesn't work now.
- Alt+Shift+H/L - has occasionally worked. Doesn't work now.

**Additional:**
- Some keyboard shortcuts that works:
  - Alt+Shift+J/K to switch between windows.
  - Alt+Shift+Space to change layouts.

I am testing all of this using two windows; Chrome and iTerm. I've also tested this using five windows; one Chrome and the rest iTerms.

[Trello Card](https://trello.com/c/NWhb7OXQ/110-amethyst-some-keyboard-shortcuts-not-working)

**Comment by JensRantil** [comment]
Might definitely be. I'll see if I can't recreate this, if I switch to an English keyboard layout (btw, Swedish keyboard layout is not that different from English if you'd like to give it a try).

**Comment by ncraike** [comment]
Not sure if this is the same bug under the hood, but I'm experiencing a problem where I can't get any keyboard shortcut to work for "Switch to float layout". I've assigned keyboard shortcuts to other layouts, and they work fine, and I can select the float layout by cycling through the available layouts, but if I can't get any shortcut for switching directly to the float layout to work.

**Comment by pik** [comment]
I seem to be having the same issue as @JensRantil mentioned (running 10.10.3). I can add keycode output if this might be useful.

**Comment by ianyh** [comment]
@pik keycode output would be great!

**Comment by ianyh** [comment]
This may be the same issue as #352

**Comment by matt0089** [comment]
I found setting keybindings wasn't working for me for changing to the `Tall` layout.

The fix was to add the `Tall` layout back to the list of layouts in the `Layouts` tab of the Amethyst settings window.  I had removed it from the list previously.

This should work for the other layouts also.

Thank you @ianyh for a great window manager 🚀
