### ISSUE TITLE
Postbox app doesn't float after adding to .amethyst

### ISSUE THREAD

**Issue by rusikf** [ianyh/Amethyst#276]
After adding Postbox app like this:
```
hell:~ ruslan$ osascript -e 'id of app "Postbox"'
com.postbox-inc.postbox
```
I adding postbox to .amethyst, exit postbox, relaunch amethyst and open postbox again.
.amethyst:
```
{
	"floating": [
		"com.apple.finder",
		"it.bloop.airmail",
		"com.adiumX.adiumX",
		"com.github.GitHub",
    "uk.co.opencommunity.vienna2",
    "com.postbox-inc.postbox"
	]
}


```
Another apps like Github works fine. 
OS X Yosemite 10.10.1
Suggestion: May be dash in postbox name cause this error

[Trello Card](https://trello.com/c/MOfL8l4o/113-amethyst-postbox-app-doesn-t-float-after-adding-to-amethyst)

**Comment by ianyh** [comment]
Tested it and it seems to be working for me. Are you getting any errors on Console.app when launching Amethyst?

**Comment by drumstick23** [comment]
@rusikf did you test it by adding the application with the prefpane? 
![screen shot 2015-01-13 at 13 14 26](https://cloud.githubusercontent.com/assets/2329830/5720561/1f4cbd84-9b26-11e4-8608-05a06decfe60.png)

**Comment by rusikf** [comment]
I changed my mac with the same hard drive(previous is on repair) and it seems works now
I don't know what cause this problem :smile:
