### ISSUE TITLE
Empty space between windows.

### ISSUE THREAD

**Issue by viclib** [ianyh/Amethyst#278]
It seems impossible to fill the whole screen with applications. For some reason, OSX won't allow me to increase the size of the terminal further (notice the empty space below it) and the size of chrome further (notice the empty space on its left size). Is there any way to improve this behavior?

http://i.imgur.com/OdiOf9r.jpg

[Trello Card](https://trello.com/c/SVv5XLKv/115-amethyst-empty-space-between-windows)

**Comment by simon-weber** [comment]
Maybe this is an artifact of how the terminal resizes itself? See eg https://github.com/ianyh/Amethyst/issues/141#issuecomment-39701436.

**Comment by ianyh** [comment]
Yeah, I'm pretty sure this is a quality of OS X and I know of no way to get around it.
