### ISSUE TITLE
Focus doesn't fully switch with Focus Screen

### ISSUE THREAD

**Issue by TreyBlancher** [ianyh/Amethyst#280]
I have two key combinations:

Ctrl + W:  Focus screen 1
Ctrl + E:  Focus screen 2

(Ctrl is my mod1, which I have mapped to the Windows key on my Microsoft Keyboard).  These work, Amethyst will give focus to the desired display.  However, I also have Ctrl+Left and Ctrl+Right defined in the OS X System preference, under Mission Control, for swapping to the left or right space.  If I press Ctrl+W or Ctrl+E, the window on my desired display appears to have full focus, but Ctrl+Left or Ctrl+Right will switch the space on the other display (the last one to have focus).  The only solution I have for this is to click on my desired display, and then Ctrl-Left/Right work on the space that I want.

[Trello Card](https://trello.com/c/CTejXxux/117-amethyst-focus-doesn-t-fully-switch-with-focus-screen)

**Comment by ianyh** [comment]
OS X decides which screen to switch spaces on based on the position of the cursor, not the window that is focused. It's pretty easy to test yourself. Select a window on one screen, move your cursor to the other screen without clicking anything, hit `Ctrl+Left/Right`.

Amethyst has a feature called `mouse-follows-focus` which helps with this. It'll move your cursor over when you focus a window. So if you focus a window on a different screen your cursor will move with it, making the shortcuts work how you expect them to.

**Comment by TreyBlancher** [comment]
Thanks for the update, that did the trick!  I feel sheepish for not trying that 
sooner.

Thanks,

Trey

**Comment by ianyh** [comment]
No worries! Glad I could help.
