### ISSUE TITLE
Iterm2 tmux integration bug

### ISSUE THREAD

**Issue by rnhmjoj** [ianyh/Amethyst#281]
I have found another bug with iTerm2: tmux integration is completely unusable with amethyst. :(
Go to preferences -> general -> select "open tmux windows as native windows".
Now start a session with `tmux -CC`.
If you create two or more windows then when changing focus all the windows randomly starts to flash white and resize.

[Trello Card](https://trello.com/c/zM6RMI6z/118-amethyst-iterm2-tmux-integration-bug)

**Comment by ianyh** [comment]
That sounds fun. I'll take a look when I get a chance.

**Comment by Rnhmjoj** [comment]
I tried this again today: the issue seems gone.
It was probably due to a bug in iTerm (i'm using the nightly builds).
There are some strange paddings when using tmux though.
