### ISSUE TITLE
Any way to work with "Tab Outliner"'s Chrome extension?

### ISSUE THREAD

**Issue by viclib** [ianyh/Amethyst#285]
Tab outliner is a chrome window that is supposed to replace Firefox's Tree Style Tabs. The only problem is it is a separate window, so it gets consumed by Amethyst, when it was supposed to be placed on chrome's side.

[See example.](http://i.imgur.com/UgwzDbh.png)

Is there any way to make this work with Amethyst? Maybe a special case?

[Trello Card](https://trello.com/c/ymjRPfYo/120-amethyst-any-way-to-work-with-tab-outliner-s-chrome-extension)

**Comment by ianyh** [comment]
Is the window a different process? Can you find the process name? If it's a separate process from chrome, you could try adding it to the floating list.

**Comment by rootscript** [comment]
@ viclib
It shows up in the OS X Activity monitor as 'Google Chrome Helper'.
In Chrome Browser, you can find it by going to the Menu > Window > Task Manager.
It show up as Task 'Extension: Tabs Outliner'
 7465 ??         0:02.66 /Applications/Google Chrome.app/Contents/Versions/44.0.2403.157/Google Chrome Helper.app/Contents/MacOS/Google Chrome Helper --type=renderer --enable-deferred-image-
....
Hope that helps you get further.

**Comment by ianyh** [comment]
I think the only option here is floating it. You can float it by title if you want to try that, but at a fundamental level that extension is trying to manage windows which is always going to collide with Amethyst.
