### ISSUE TITLE
Amethyst does not recognise AppCode (IntelliJ) start.

### ISSUE THREAD

**Issue by SebastianKeller** [ianyh/Amethyst#286]
Hey, 

whenever i open up AppCode (specialised IntelliJ for Objectice-C) Amethyst does not recognise it. (No new alignment etc.) If i do restart Amethyst, everything works fine.

Thank You!

**Comment by leonardt** [comment]
I think this falls under https://github.com/ianyh/Amethyst/issues/49

Current workaround is to use mod+t to have it tile (should be simpler than restarting Amethyst).
I remember an idea that certain applications don't seem to respond to accessibility API actions until after their start up, so when Amethyst does the initial placement of the window it's ignored (although I'm not sure if this actually the issue)

**Comment by ianyh** [comment]
Yup. @leonardt is correct.
