### ISSUE TITLE
mod1 and mod2 can't be altered via ~/.amethyst

### ISSUE THREAD

**Issue by timvisher** [ianyh/Amethyst#290]
I have overridden mod1 and mod2 for awhile in my .amethyst file but a fresh install via brew cask is currently overriding those, it would seem.

My .amethyst file is here: https://github.com/timvisher/bash_configuration/blob/master/dotfiles/amethyst

[Trello Card](https://trello.com/c/a8mPhRXU/122-amethyst-mod1-and-mod2-can-t-be-altered-via-amethyst)

**Comment by timvisher** [comment]
ping :)

**Comment by ianyh** [comment]
Hm. A cask install shouldn't actually change anything. Do you have in-app preferences set? I don't think that should affect anything, but it would be useful information.

**Comment by timvisher** [comment]
![preferences](https://cloud.githubusercontent.com/assets/34676/6250536/823834da-b75c-11e4-9afe-d3590b872464.png)
![preferences](https://cloud.githubusercontent.com/assets/34676/6250550/932b6302-b75c-11e4-82ae-7666be1492a4.png)

**Comment by timvisher** [comment]
Note I haven't edited this manually, afaict. It just shows up that way.

**Comment by ianyh** [comment]
Can you try changing one of them manually to use the `mod` you expect and see if that works?

**Comment by timvisher** [comment]
![screenshot_2_18_15__12_09_pm](https://cloud.githubusercontent.com/assets/34676/6252275/0ab8da6c-b767-11e4-9268-c4900fc97a8b.png)

**Comment by timvisher** [comment]
I can't find anything in System Preferences→Keyboard→Shortcuts that uses it already.

**Comment by timvisher** [comment]
This could be a separate issue but it also seems to be ignoring the fact that i'm asking it to ignore adium.

**Comment by ianyh** [comment]
Hm. Is it `.amethyst` or `amethyst`?

**Comment by timvisher** [comment]
`~/.amethyst`

**Comment by timvisher** [comment]
@ianyh ping :)

**Comment by ianyh** [comment]
@timvisher it looks like `.amethyst` doesn't override in-app preferences like I thought it did. I just tried your amethyst file and my preferences are still sticking.

**Comment by ianyh** [comment]
Ah, I see the problem. It's not overriding for custom modifiers.

**Comment by timvisher** [comment]
:yey: :bug: !

**Comment by ianyh** [comment]
Okay! Interim solution:
* Quit Amethyst
* `rm ~/Library/Preferences/com.amethyst.Amethyst.plist`
* Restart Amethyst

You can copy that file somewhere else before you delete it just in case something important gets lost, but if you're working off of a `.amethyst` file you should be fine.

**Comment by timvisher** [comment]
OMG IM SO HAPPY! Want me to leave this issue open until it gets resolved?

**Comment by ianyh** [comment]
Yes. It's still a problem that custom modifiers don't override in-app preferences.
