### ISSUE TITLE
Build dependencies / 'RACEXTKeyPathCoding.h' file not found

### ISSUE THREAD

**Issue by AnthonBerg** [ianyh/Amethyst#291]
I've got cocoapods set up and xcodebuild starts going pretty well, but I get *'RACEXTKeyPathCoding.h' file not found* from ReactiveCocoa.

> The following build commands failed:
> 	ProcessPCH /var/folders/pd/4wgbgdks2_10fz3hfcc9jw9r0000gn/C/com.apple.DeveloperTools/6.1.1-6A2008a/Xcode/SharedPrecompiledHeaders/Amethyst-Prefix-gfhucalerkpqhphhmvsjidcwawrv/Amethyst-Prefix.pch.pch Amethyst/Amethyst-Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> 
> In file included from /Users/videntifier/src/Amethyst/Amethyst/Amethyst-Prefix.pch:8:
> In file included from /Users/videntifier/src/Amethyst/Amethyst/AMPrefixImport.h:12:
> /Users/videntifier/src/Amethyst/Pods/Headers/Public/ReactiveCocoa/ReactiveCocoa/ReactiveCocoa.h:9:9: fatal error: 
>       'RACEXTKeyPathCoding.h' file not found
> #import "RACEXTKeyPathCoding.h"

(I have a decent theoretical understanding of programming but am not up to speed on Mac development these days - forgive me if this a stupid question. Any hints on where to look would be most well appreciated. Wanted to try to make a "reverse tall" layout and make a pull request :) thanks!)

**Comment by ianyh** [comment]
Ugh. The dev environment is super temperamental. I think I may need to remove ReactiveCocoa. The Pod isn't officially supported as far as I know and it seems to consistently give people headaches trying to get set up. I'll try to patch things up when I get a chance.

**Comment by AnthonBerg** [comment]
OK! I saw some info about how ReactiveCocoa didn't like being set up as a Pod; I have no problems setting it up the canonical way, I'll try that I think.

**Comment by ianyh** [comment]
I've updated the dev environment to install ReactiveCocoa through Carthage, which should be a lot more stable, build-wise. Let me know if you still run into trouble.

**Comment by pradeepb28** [comment]
i updated my cocoa pods to 1.0 and throws me the same error. How can I resolve this issue?

**Comment by ianyh** [comment]
Have you tried running `rake setup`? This issue was based on a now out of date method of dependency management.
