### ISSUE TITLE
Is there any way to always float an app based on window title?

### ISSUE THREAD

**Issue by viclib** [ianyh/Amethyst#292]
I want to always float an app which is actually the result of compiling a Gloss (Haskell) program. As such, it isn't an actual fixed app with a path. Can I still always float it?

[Trello Card](https://trello.com/c/spnnqhsQ/123-amethyst-is-there-any-way-to-always-float-an-app-based-on-window-title)

**Comment by ianyh** [comment]
I think there was an issue open for this somewhere, but I can't find it. The answer is no, but I've considered adding something like that. Is there a reason you want title-level rather than application-level?

**Comment by deiga** [comment]
Most apps produce mutliple windows, like settings popups etc. It would be great to be able to float these minor windows and not float the whole app! :)

**Comment by ifreecarve** [comment]
Has this issue been resolved via the functionality shown here?

![screen shot 2017-07-18 at 8 13 18 am](https://user-images.githubusercontent.com/583459/28316500-22f837e0-6b91-11e7-8ad5-4455c1f272d2.png)

**Comment by ianyh** [comment]
No. That is about floating applications, not windows.

**Comment by ifreecarve** [comment]
Can you add something to the README about the terminology?  A lot of these terms (Spaces, frames, windows, displays, applications, etc) are ambiguous and I'd like to understand them better in an Amethyst context.  

(If you reply here I'll submit a PR with those definitions.)

**Comment by ianyh** [comment]
@ifreecarve Happy to. I'm a little steeped in the terminology, so it's easy to lose sight of what they might look like to a new user/developer.

 - *Desktop*: A space full of windows on a screen. There can be multiple, and they are accessible from Mission Control. In previous versions of macOS they were called *spaces*.
 - *Frame*: The combination of position and size of a window.
 - *Window*: This is pretty self-explanatory, I think.
 - *Display*: Also called a *screen*, it is the physical device displaying desktops and windows, be it a laptop screen or an external monitor.
 - *Application*: Should be self-explanatory as well.
 - *Layout*: An algorithm used to size and position windows on a screen.

Are there any other ones that are particularly confusing/misleading/etc?

**Comment by ifreecarve** [comment]
I am somewhat confused on the distinction between an application and a window.  I would have thought that an application is just a process, which may or may not have windows... but how does an application float, as opposed to the application having a window that floats?  Am I missing something obvious here?

**Comment by ianyh** [comment]
You are correct in that an application is a process that owns potentially many windows. An application "floats" in the sense that its windows are floating by *default*, but can be forced to tile.

**Comment by ianyh** [comment]
Per #740, next version you'll be able to specify window titles for an application that will be automatically floated.
