### ISSUE TITLE
add option to hide icon in macOS status bar

### ISSUE THREAD

**Issue by neonfrontier** [ianyh/Amethyst#299]
Just a suggestion i thought of. :)

[Trello Card](https://trello.com/c/JAMAIByQ/128-amethyst-add-option-to-hide-icon-in-osx-top-bar)

**Comment by sebroeder** [comment]
I would love to have this option, too.

**Comment by ianyh** [comment]
That seems tricky. How would you expect that to behave?

**Comment by neonfrontier** [comment]
Sure, I imagine it would just remove the with maybe an option to press a hot key to bring it up again. I don't consider it to be super important though..! I'm currently using bartender to hide mine.

**Comment by ianyh** [comment]
@danielbmarques that's a pretty good idea. Can you open another issue to track it, though?

**Comment by jbernardo95** [comment]
+1 to hide the icon 😉

**Comment by jbernardo95** [comment]
I have a PR to make this possible here: https://github.com/ianyh/Amethyst/pull/1583
