### ISSUE TITLE
is there any way to improve performance?

### ISSUE THREAD

**Issue by Ahti** [ianyh/Amethyst#305]
This is more a question than an actual issue: Is it possible to improve amethysts performance?

In my normal usage, I find it pretty disruptive that I have to wait for the focus to change, layout to apply, window to reposition or focus to keep up with my mouse movement.

So, is there anything that can be done to improve this or are the wait times due to the OSX window manager taking it's time to apply changes?

[Trello Card](https://trello.com/c/8llzPPCN/134-amethyst-is-there-any-way-to-improve-performance)

**Comment by ianyh** [comment]
Yeah, this has been discussed in #209. There's probably some work to be done, but some of it is limited by the accessibility framework.

**Comment by ianyh** [comment]
Going to close this as duplicate.
