### ISSUE TITLE
Any way to add the Chrome developer tools to the list of windows not managed by Amethyst?

### ISSUE THREAD

**Issue by fullofcaffeine** [ianyh/Amethyst#307]
I often want to have Chrome in my Amethyst layout setup, but it's annoying to have the developer tools being managed by Amethyst since I often have 2 or 3 open, and I run out of space (and they break my current layout). I can float them with the Shitf+option+T shortcut, but I'd love to make this process automatic. Any ways to do that?

[Trello Card](https://trello.com/c/FlSI3RRe/136-amethyst-any-way-to-add-the-chrome-developer-tools-to-the-list-of-windows-not-managed-by-amethyst)

**Comment by ianyh** [comment]
There's been a request out for floating by window title, which might help here #292.

**Comment by ianfixes** [comment]
Is this the same as #99?

**Comment by ianyh** [comment]
Per #740, next version you'll be able to specify window titles for an application that will be automatically floated.
