### ISSUE TITLE
Opera Search Bar gets tiled

### ISSUE THREAD

**Issue by kallekrantz** [ianyh/Amethyst#308]
The search window in Opera and Opera Beta is getting automatically picked up by Amethyst and gets tiled. 
![screenshot 2015-05-21 12 38 38](https://cloud.githubusercontent.com/assets/2708253/7746916/874e5182-ffb6-11e4-9738-80f955a35733.png)

Is there any way of identifying the search window name in order to put it in the .amethyst as an ignored window?

And thanks so much for amethyst, I use it daily and it is such a great piece of software!

[Trello Card](https://trello.com/c/kpxcb081/137-amethyst-opera-search-bar-gets-tiled)

**Comment by ianyh** [comment]
Huh. Interesting.

**Comment by seraph** [comment]
Any workarounds for this? It's quite disorienting...

**Comment by ianyh** [comment]
Unfortunately the search dialog in Opera is just a normal window. The only distinguishing feature is that it doesn't have a title bar, and I'm not sure universally floating windows without title bars is correct. I will note that this could be fixed by #292. You could just tell it to float that window based on the title.

**Comment by cedric-romain** [comment]
Having the same issue... My workaround is to add Opera to the ignored windows and then always toggle it away from float manually upon restart

**Comment by anoxic** [comment]
Also having the same issue.
![amethyst-opera](https://cloud.githubusercontent.com/assets/1300459/26325199/953b1060-3efb-11e7-84f4-f9d4511ae3ce.png)

**Comment by daphen** [comment]
Still no work around for this?

**Comment by ianyh** [comment]
Per #740, next version you'll be able to specify window titles for an application that will be automatically floated.

**Comment by benortiz** [comment]
Thank you for the work on this! I see the option under to specify a window title for an application, but putting nothing in there for the blank title didn't prevent it from being tiled. Do you have any tips for what should go in the settings?

![image](https://user-images.githubusercontent.com/681189/52088992-466bbf80-2562-11e9-8331-fa8528c6eaed.png)

**Comment by ianyh** [comment]
Looks like the actual window title is `Address bar drop down`.

**Comment by benortiz** [comment]
Thank you @ianyh!
