### ISSUE TITLE
Always open app in certain space?

### ISSUE THREAD

**Issue by tuananh** [ianyh/Amethyst#309]
I'm new to Objective-C but I want to add this feature for personal use. Can you help me point to where can I quickly get started?

[Trello Card](https://trello.com/c/p2gJQcLm/138-amethyst-always-open-app-in-certain-space)

**Comment by leonardt** [comment]
I believe you can go to the dock, right click, options and set assign to this desktop.  However, I'm not sure if this is a feature built in or some app I'm using provides it.  Let me know if it's not available for you I can try and track down which app is providing it.

**Comment by tuananh** [comment]
@leonardt that's exactly what i need. it works as expected. thanks a bunch :+1:
