### ISSUE TITLE
amethyst should have a "float all except..." mode

### ISSUE THREAD

**Issue by bradleeedmondson** [ianyh/Amethyst#310]
I'm using amethyst happily on OS X 10.10.3, but I mostly just want to tile lots of Chrome windows while floating everything else.

Would it be possible to add a mode to amethyst that floats everything except the specifically chosen apps? This would be the inverse of the current behavior, where everything is tiled except the apps specified in the "Floating:" list.

[Trello Card](https://trello.com/c/mzJnhjJ8/139-amethyst-amethyst-should-have-a-float-all-except-mode)

**Comment by ianyh** [comment]
Yup. Already a ticket for it. #171
