### ISSUE TITLE
Query: Accessing any space from any display

### ISSUE THREAD

**Issue by simonjbeaumont** [ianyh/Amethyst#311]
I am a long-time XMonad user and still use it on my work machine. It has three displays and the best feature for me is to be able to bring any app (given I tend to run one per space) to the screen under my mouse with a single shortcut.

It seems that on OSX the spaces on each display are in independent sets and are numbered as such. Is there any workaround you know of that would allow me to access space A on any desktop. I was hoping that Amethyst would but it doesn't seem so. Would it be a feature-request that you'd consider?

[Trello Card](https://trello.com/c/uyYdomsX/140-amethyst-query-accessing-any-space-from-any-display)

**Comment by ianyh** [comment]
It's something that has been requested before (see #121), and I would like to get it done. I use three screens and this bites me all the time.

**Comment by ianyh** [comment]
Done in #1209
