### ISSUE TITLE
Focus Screen Not Working?

### ISSUE THREAD

**Issue by porkloin** [ianyh/Amethyst#316]
.amethyst commands for focus screen aren't working for me. My .amethyst file can be found at https://gist.github.com/porkloin/40ee71c4d64612f1cd77.

Not sure if part of my problem is the fact that I've tried to set up mod3 - is there support for more than mod1 and mod2? Otherwise I'm stumped.

[Trello Card](https://trello.com/c/2kEodeSp/145-amethyst-focus-screen-not-working)

**Comment by ianyh** [comment]
@porkloin we don't currently support `mod3`. You can open an issue to request support for it, though. It might be reasonable.
