### ISSUE TITLE
Request Support for Mod3 (and more)

### ISSUE THREAD

**Issue by porkloin** [ianyh/Amethyst#317]
Support for further modkeys would be useful, and put Amethyst at feature parity for keybindings with a lot of other Linux Tiling WMs. I switch between my home machine (AwesomeWM) and my work machine (Amethyst) and would love to be able to mirror my keybinding setup from Awesome on my work machine.

[Trello Card](https://trello.com/c/MOcMvs8I/146-amethyst-request-support-for-mod3-and-more)

**Comment by ianyh** [comment]
@porkloin I'm not as familiar with AwesomeWM as I am with some others. Does it have arbitrary numbers of mod characters or is it just more of them?

Also would #343 do what you want to increase the space of shortcuts?

**Comment by porkloin** [comment]
Basically the way it works in Awesome is you can define as many modkeys as you'd like. It uses lua scripts for configuration, and each of the modkeys is just a Lua variable that then gets fed into different WM functions or methods. So basically any key can be a "modkey" - it's just a reference to that key, and the arguments the method takes are keys, i.e. expandMain(mod3, shift, h) [not in any way close to how it looks in Lua, FYI].  Perhaps Amethyst is like this too, but I'm just not aware of how to configure it.

The use case I'm really looking to solve is this: I have mod1 + shift + h bound to throw to screens window counter-clockwise, mod1 + h bound to increase/decrease main pane size, and I would _like_ to have mod1 + ctrl + h throw _focus_ counter-clockwise. This is entirely selfish because I am trying to get my Awesome and Amethyst setups to have the same bindings :)

Oh yeah, and from what I can tell #343 doesn't seem to necessarily be asking for the same thing, rather wanting some kind of vim-style mode shifting?

**Comment by ianyh** [comment]
Okay. That is definitely not supported with the dotfile. You can do it in the in-app preferences because you define arbitrary shortcuts. It doesn't really have a concept of modifiers.

I'm not entirely sure what to do about dotfiles. I kind of want to phase them out.

**Comment by rjuer** [comment]
Hi, is it still a possibility to add more mod keys? I currently use a total of four mod keys (configured via the in-app preferences). It would be great to configure this exclusively via the config file. While I'm aware that the total number of mod keys is a rather arbitrary number, I think an increase to four or five would be a reasonable number to give enough flexibility (of course unless someone sees the need for more or is aware of this need). I'd be happy to contribute.

**Comment by ianyh** [comment]
I think it could be a reasonable addition to configuration files.
