### ISSUE TITLE
"Focus screen $n" activates background window of same app (Chrome) instead of focusing on the foreground window.

### ISSUE THREAD

**Issue by wolf0403** [ianyh/Amethyst#318]
When "Focus screen 1" using Amethyst while screen 1 is in Full screen mode with multiple Chrome windows stacked, Amethyst activates a background Chrome window instead of activating the tope windows currently on screen 1 before the move.

I tried toggle on / off "Mouse follows focused windows" and had no luck. "Focus follows mouse" is off.

Could this be fixed somehow?

Thanks!
Ryan

[Trello Card](https://trello.com/c/iC3aHUkr/147-amethyst-focus-screen-n-activates-background-window-of-same-app-chrome-instead-of-focusing-on-the-foreground-window)

**Comment by ianyh** [comment]
Yeah, this is a known problem. See #245

**Comment by jacksonfylle** [comment]
When you focus screen 1, amethyst "Focus the main window on the first screen". So if the foreground windows (full screen mode) is not the main window it won't work. What you can do is : "swap-main" the foreground window and "focus-screen-1".
