### ISSUE TITLE
Wildcard support for floating list

### ISSUE THREAD

**Issue by deiga** [ianyh/Amethyst#320]
Hey,

I'd love to be able to add "unity.*" to my floating list and that would float all apps with an app id starting with unity.

I can even help implementing this, if you can give me pointers as to where I should be looking for it :)

[Trello Card](https://trello.com/c/5dRrFo6h/149-amethyst-wildcard-support-for-floating-list)

**Comment by ianyh** [comment]
@deiga take a look at https://github.com/ianyh/Amethyst/blob/development/Amethyst/AMConfiguration.m#L409
