### ISSUE TITLE
"Focus screen $n" can not focus empty screen (with no window)

### ISSUE THREAD

**Issue by wolf0403** [ianyh/Amethyst#321]
I'm relying on "focus screen $n" to move my mouse to a given screen. Apparently if the screen has no open window, "focus screen $n" does nothing.

[Trello Card](https://trello.com/c/QnJZTtbE/150-amethyst-focus-screen-n-can-not-focus-empty-screen-with-no-window)

**Comment by ianyh** [comment]
Huh. I hadn't considered wanting to move the mouse to an empty screen, but I suppose if you're trying to get it to be the primary screen for the purposes of space switching it would be pretty useful.
