### ISSUE TITLE
El Capitan support (?)

### ISSUE THREAD

**Issue by brettneese** [ianyh/Amethyst#325]
Does Amethyst work with El Capitan support out of the box? If not, what is needed?

I'm afraid to upgrade without hearing field reports. ;-)

[Trello Card](https://trello.com/c/l1ooRQTp/154-amethyst-el-capitan-support)

**Comment by ianyh** [comment]
Last time I tested it there was one issue with full screen mode (beyond the existing irksome ones), which has since been fixed in `development`. I haven't tested the hiding menu bar yet.

**Comment by ianyh** [comment]
I am planning on doing the upgrade soon, though, and can give a more thorough report then.

**Comment by wolf0403** [comment]
Floating seems working fine. :-) 
Amethyst does not yet seems to be aware of 10.11's Split View and may result in chaos with those windows in split-view.

**Comment by ianyh** [comment]
I _think_ that split view should reduce to full screen view. Which is to say that it _should_ be correctly ignored, but may suffer from #254.

**Comment by brettneese** [comment]
I'm already having problems with #254, so may be worth a shot.

**Comment by ianyh** [comment]
Tested collapsing the menu bar and it doesn't play well.

**Comment by ianyh** [comment]
I take it back. This actually does work. It just has some weirdness with small frame changes.

**Comment by wolf0403** [comment]
0.9.5 solved the splice view problem for me (mentioned above). Thanks for the update!
