### ISSUE TITLE
swap focused window screen shortcuts not working

### ISSUE THREAD

**Issue by edrex** [ianyh/Amethyst#336]
The shortcuts to `swap focused window screen` (`clockwise`/`counter-clockwise`) aren't working for me. The target window is moved/resized and then rapidly returns to its original position without changing frames.

`OS X 10.10.3 (14D136)`
## mission control shortcuts:

<img width="390" alt="mission control shortcuts" src="https://cloud.githubusercontent.com/assets/14615/10620237/cd1c1326-772e-11e5-8e5d-1caf566f56c4.png">
## amethyst shortcuts:

<img width="521" alt="amethyst shortcuts" src="https://cloud.githubusercontent.com/assets/14615/10620238/cd1cd28e-772e-11e5-8b28-0444a8460880.png">

[Trello Card](https://trello.com/c/SX6NPOGX/164-amethyst-swap-focused-window-screen-shortcuts-not-working)

**Comment by ianyh** [comment]
What version are you on?

**Comment by edrex** [comment]
That was an impressively fast response. Are you in fact a bot? :grinning: 

Sorry for the omission, Amethyst 0.9.5

**Comment by ianyh** [comment]
Heh. I happened to be checking when the notification came in. Just good timing. Though setting up a bot that asks for a version number isn't a bad idea. :wink: 

By default those shortcuts are for `Shrink/Expand main frame`. Can you check to see if they still are? If you have two shortcuts triggering the same event it would probably come up with two frames and set them one after the other.

**Comment by edrex** [comment]
I felt like I had the default values for the shortcuts but maybe I have some left over from a previous release.  Here's the full list:

<img width="524" alt="screen shot 2015-10-20 at 1 46 46 pm" src="https://cloud.githubusercontent.com/assets/14615/10620637/16ff60c2-7731-11e5-8b84-4349ab09768a.png">

**Comment by ianyh** [comment]
Oh, I see. It looks like you just changed the mappings for the modifiers. Next question: do you have `Displays have separate Spaces` enabled as shown below in the Mission Control preferences?

![screen shot 2015-10-20 at 4 52 28 pm](https://cloud.githubusercontent.com/assets/212270/10620803/18e9d04c-774b-11e5-8433-d65139ca4e1b.png)

**Comment by edrex** [comment]
Yes, the only difference there is I have

:ballot_box_with_check:   Group windows by application

**Comment by edrex** [comment]
Hmm I just tried resetting my preferences with 

```
mv ~/Library/Preferences/com.amethyst.Amethyst.plist ~
```

but it didn't seem to change the key bindings

**Comment by ianyh** [comment]
Do you have a dotfile?

**Comment by edrex** [comment]
i don't seem to have `~/.amethyst` or anything like that.

**Comment by ianyh** [comment]
Had to go offline and I am no longer at a multi-monitor set up. I'll get back to this when I get a chance.

**Comment by stylerw** [comment]
I'm having the same issue, except for me, "Swap focused window to [counter]clockwise screen" just causes Amethyst to crash, with any keystroke assigned.  It's just like a "Crash Amethyst" button.  Which is a shame, because it's a useful keystroke :) 

Anything I can do to help?  No .amethyst file, I'm setup through the preferences panel.

**Comment by ianyh** [comment]
@stylerw that crash is actually fixed now in 0.10!

@edrex are you still encountering this problem?
