### ISSUE TITLE
0.9.6 crashes when switching from Tall to Float on my Yosemite

### ISSUE THREAD

**Issue by wolf0403** [ianyh/Amethyst#340]
I have only Tall and Float enabled. Amethyst starts in Tall and when I switch to Float Amethyst dies silently. Roll back to 0.9.5 and it worked just fine. OS X 10.10.5

[Trello Card](https://trello.com/c/g7D6rir0/168-amethyst-0-9-6-crashes-when-switching-from-tall-to-float-on-my-yosemite)

**Comment by ianyh** [comment]
I see why it's happening. Should actually convert to swift. Type safety would have saved me here. :cry: Also tests.

**Comment by bisho** [comment]
I have the same issue. Also noticed that 0.9.6 seems to be much slower, takes quite a bit to start abd changing layout the first time on a  workspace takes several seconds. After that it improves a bit, but still feels slower than 0.9.5.

**Comment by ianyh** [comment]
Incurred some performance overhead to fix #254. It brought up the min time, but another change brought the max time down drastically. Still considering ways to bring the min time back down.
