### ISSUE TITLE
Outlook 2011 doesn't resize properly and interferes with other apps on the same screen, while using Amethyst

### ISSUE THREAD

**Issue by beginrescueend** [ianyh/Amethyst#341]
First of all, thank you very much for Amethyst!  I finally get a tiling window manager I can use, for Mac!

I have Yosemite and Amethyst 0.9.6 (27), plus Outlook 2011.

Outlook generally takes the left half of the screen and messes up the right pane, so that other apps resize improperly.

I do have a 3 screen setup (from left to right: Samsung HDMI 1920x1080 on HDMI, Dell Ultrasharp 34 on Thunderbolt -> DisplayPort, and Late 2013 Mac Book Pro w/ Retina), so as a workaround, I move Outlook to my laptop monitor, by itself.

If Outlook is on its own monitor, it still wants to be on the left half of the screen, but at least it doesn't mess up other apps.

Thanks

[Trello Card](https://trello.com/c/EyIIy2ns/169-amethyst-outlook-2011-doesn-t-resize-properly-and-interferes-with-other-apps-on-the-same-screen-while-using-amethyst)

**Comment by ianyh** [comment]
That's really strange. This only happens with Outlook?

**Comment by beginrescueend** [comment]
So far, yes, only with Outlook.

**Comment by beginrescueend** [comment]
I just got the latest update to Outlook 2011 (14.5.7 / 151005) and it seems to be behaving more sanely.

Coincidence?  Bug fix i update?  Restart of Outlook, while Amethyst was running (this was not the first restart of Outlook, though)?

I'll try to let you know, in a short while, if this comes back or not...

**Comment by beginrescueend** [comment]
I have found a new app that causes confusion for Amethyst - VirtualBox.

It may not be resize-friendly.

**Comment by beginrescueend** [comment]
That, too, cleared up.

It appears that some apps are less well-behaved than others, but they eventually "work".

Last night, I turned off two of my monitors (see above for configuration).  My apps all went to the laptop screen.

When I turned both monitors back on, all the windows tried to go back to their respective original monitor/screen.  However, Amethyst wouldn't respond.

So, I did a "Relaunch Amethyst" and all is well.  This includes both Outlook 2011 and VirtualBox 5.0.4, which resizes well, now.

One clue, however, concerning VirtualBox: it competes for the "mod 1" key.

**Comment by beginrescueend** [comment]
As for Outlook 2011, it definitely seems to prefer to be on the left-hand side of the screen and it definitely wants to resize email windows, if the panes are small.

So, while I have things working well in Amethyst, there is some manual maneuvering to get Outlook, VirtualBox, and iTerm2 working and cooperating with other apps.

Again, thanks for a great app!

**Comment by ianyh** [comment]
This is great. Thanks for all of the thorough info! I'll try to dig in more when I get a chance.

**Comment by beginrescueend** [comment]
Welcome and thank you!

BTW, I also saw the "Floating Layout" crash in 0.9.6.  

This definitely seems fixed in 0.9.7.  Nice!

Thanks!

**Comment by ifreecarve** [comment]
I did a lot of testing on this related to #627 and couldn't reproduce this issue.  Tried now with iTerm2 and Outlook; the only strange behavior I see is that Outlook maintains a minimum height, which can cause the iTerm window to over/underlap it.  

Resizing the font size in iTerm2 did not trigger a reflow of the window, but on a focus change the window resized as normal.

**Comment by ianyh** [comment]
Might be related to #182, but I think Microsoft apps on macOS have changed a lot in recent years.
