### ISSUE TITLE
Amethyst stopped working after deleting layouts

### ISSUE THREAD

**Issue by gwerbin** [ianyh/Amethyst#344]
I'm on OS 10.11.1 and installed Amethyst with Homebrew Cask.

I just installed Amethyst, and it worked with no problems. Then I went into settings and added the "floating" layout with the "+" button, then removed the others with the "-" button, thinking I would start with a "fresh" list and ease into the program. Then the Menu Bar icon disappeared and the app won't start again. The Amethyst logo shows up for a tiny instant, and a space on the menu bar appears, but then it disappears again after a few seconds.

I've restarted my computer, I've removed and re-added Amethyst to the "Allow the apps below to control..." window, and I've reinstalled Amethyst. None of those worked. I guess something broke when I deleted all the default profiles, but I don't have any idea how to diagnose. Or fix, for that matter... I'd like to actually use the program!

[Trello Card](https://trello.com/c/bD3HUOsJ/172-amethyst-amethyst-stopped-working-after-deleting-layouts)

**Comment by ianyh** [comment]
This is a side-effect of #340. There's a bug in the floating layout that is causing a crash. :cry: 

In the meantime try running
```bash
$ defaults remove com.amethyst.Amethyst layouts
```
and then relaunching. That should reset your list of layouts.

**Comment by ianyh** [comment]
Okay, released 0.9.7 which fixes that crash, so you should be good after an update. Sorry for the trouble.

**Comment by gwerbin** [comment]
Thanks! glad to see it fixed.
