### ISSUE TITLE
Ctrl-Shift-Space can't be used even after removed

### ISSUE THREAD

**Issue by treyharris** [ianyh/Amethyst#345]
Because I'm an Emacs user, option-shift is a combo that I have mapped to nearly every key Amethyst uses. So I tried to change mod1 from option-shift to ctrl-shift. This worked except for ⌃⇧Space, which Amethyst reported was set in the global preferences. I couldn't find it in System Preferences at first because it wasn't in the ones it had set, but then I found it by enabling Chinese trackpad handwriting input. That made it possible to remap it to something else. I did so, but Amethyst _still_ won't let me set ⌃⇧Space as a key, it still says it's bound globally.

[Trello Card](https://trello.com/c/jLvvKS5y/173-amethyst-ctrl-shift-space-can-t-be-used-even-after-removed)

**Comment by ianyh** [comment]
I think that an update to `MASShortcut` fixed this problem. I'll try to get it updated soon.

**Comment by ianyh** [comment]
This should be fixed in the change for #352

**Comment by cmal** [comment]
I alse found `M-s` cannot be used in Emacs even change mod1 in  `~/.amethyst`.
