### ISSUE TITLE
In preferences, text in the layouts/floating lists is too narrow to edit

### ISSUE THREAD

**Issue by brettneese** [ianyh/Amethyst#350]
![image](https://cloud.githubusercontent.com/assets/504279/11158794/20117c48-8a20-11e5-8915-501c82a16415.png)

Not actually *impossible* to use, but very cumbersome. :P

That text should definitely expand to the whole box.

[Trello Card](https://trello.com/c/2QiuKOVy/177-amethyst-in-preferences-text-in-the-layouts-floating-lists-is-too-narrow-to-edit)

**Comment by ianyh** [comment]
Thank you for opening this. I've noticed it and keep forgetting about it. 😩
