### ISSUE TITLE
Keys in .amethyst different from the keys I actually have to use

### ISSUE THREAD

**Issue by pikajude** [ianyh/Amethyst#357]
Simplified .amethyst:

```
{
  "mod1": [
    "option"
  ],
  "expand-main": {
    "mod": "mod1",
    "key": "w"
  }
}
```

To actually `expand-main`, I have to press option + comma, not w. Why is that?

I have noticed that `w` in QWERTY corresponds with `,` in Dvorak, but don't have any idea what that has to do with my setup, since I'm not using Dvorak.

**Comment by ianyh** [comment]
That's very strange. What keyboard are you using?

**Comment by pikajude** [comment]
It's very weird, yeah. Dvorak is my layout on boot, but I switch to QWERTY at work. I'm just using my laptop keyboard, so nothing weird with external keyboards.

If I revert to 0.9.7 the problem goes away.

**Comment by ianyh** [comment]
Oh, I see what's happening.

The hotkeys are getting set using Dvorak, but they are stored using hardware-level information, ignoring software level information like specific keyboard mappings. In 0.9.8, we updated to MASShortcut 2.something, from 1.something, and that was one of the big changes. This is, unfortunately, somewhat necessary to actually support different keyboards. For example, the Spanish keyboard has a mapped key for ñ, which doesn't exist on the US keyboard, so if you set a command using ñ and switch to a US keyboard it's not clear to me what the right behavior would be. See: https://github.com/shpakovski/MASShortcut/issues/31

Not sure what the solution here is.

**Comment by pikajude** [comment]
But that means I would be able to pick my hot keys and then switch keyboard layouts with impunity right?

**Comment by ianyh** [comment]
Sorry, I'm having trouble resolving the antecedent for "that." What would allow you to do that?

**Comment by pikajude** [comment]
"That" being the upgrade of MASShortcut. As in, in Amethyst =< 0.9.7, the keyboard layout I have set when I start Amethyst is the one it uses for the entire session, even if I switch layouts. Whereas apparently in 0.9.8 the layout will be only set once (per boot, I guess) and persist through Amethyst restarts?

**Comment by pikajude** [comment]
That being the upgrade of MASShortcut

**Comment by ianyh** [comment]
It looks like there is a bug that is preventing the dotfile from overriding existing preferences. See #358 

Is that the problem?

**Comment by pikajude** [comment]
Yes that is exactly my problem, so I'll say this issue is a duplicate.
