### ISSUE TITLE
.amethyst not working on 0.9.8?

### ISSUE THREAD

**Issue by silenevega** [ianyh/Amethyst#358]
I am a fresh new user for Amethyst and try to customize the shortcuts with .amethyst.
However, it cannot work on my Mac OS X 10.11.1. 
None shortcut I can trigger, please give me some suggestions if possible.

PS: Before trying custom shortcut with .amethyst, I set in Preferences.
Below is my setting for .amethyst :

```
{
    "mod1": [
        "option"
    ],
    "mod2": [
        "option",
        "shift"
    ],

    "select-tall-layout": {
        "mod": "mod1",
        "key": "a"
    },
    "select-widescreen-tall-layout": {
        "mod": "mod1",
        "key": "s"
    },
    "select-fullscreen-layout": {
        "mod": "mod1",
        "key": "d"
    },
    "select-column-layout": {
        "mod": "mod1",
        "key": "f"
    },

}
```

**Comment by m2habert** [comment]
Same here @ OS 10.9.5... But I discovered that if I load Amethyst 0.9.6 with altered .amethyst file then close it, new settings will stick when activating 0.9.8... 

Check it out if it works on your end.

**Comment by ianyh** [comment]
Yeah, looking at it now there's a bug with updating hotkeys that causes them to get locked in place. This is only an issue if you use the dotfile, which I don't anymore, so I missed this one. Really need #217

**Comment by m2habert** [comment]
¿But what about the [mod1-w] ≈ "focus main window" ? Don't recall reading about that as a feature before...

**Comment by silenevega** [comment]
@m2habert Thanks for the comment. I created an empty dotfile, relanuching Amethyst, and moving back the dotfile which I customized. The main functions, Layout, can be triggered, except for mod1 + keys that is what I want to do. Probably, I misunderstood your meaning.

@ianyh Thanks for the reply such as I knew this is a bug. Expect for the next update.

**Comment by m2habert** [comment]
@silenevega No, what I meant was: Turn off your version of Amethyst (obviously)  + Download older version (0.9.6) + Do what you want with dot-file. testing with older version + As soon as you're happy, quit older version and activate present version =

= your intendend preferences should stick.

**Comment by m2habert** [comment]
( 
 interesting, just notice the "bug" label... GitHub should have a label also for "temp sol", as it would bring some peace of mind to users and improve searching.
)
