### ISSUE TITLE
Amethyst default hotkeys not working in 0.9.8

### ISSUE THREAD

**Issue by jellevandenhooff** [ianyh/Amethyst#360]
I just installed Amethyst 0.9.8, and none of the hotkeys worked. I have a default ANSI keyboard layout, and default US locale. I tried fixing things by installing my .amethyst (didn't work), and then by manually mapping keys (did work, but did not cover e.g. switching monitors). Restarting things didn't help.

I fixed my problem by downgrading to 0.9.7. I am running OS X 10.11 (15A284).

Thanks for the awesome app!

**Comment by lox** [comment]
I'm also having this issue on 10.11.1 (15B42). Installed via `brew cask install amethyst`

**Comment by ianyh** [comment]
@jellevandenhooff @lox can you check to see if you're still seeing the behavior on 0.9.9?

**Comment by jellevandenhooff** [comment]
0.9.9 works great. Thanks for fixing!

**Comment by ianyh** [comment]
Happy to see it working for you!
