### ISSUE TITLE
Relaunch amethyst with a hotkey

### ISSUE THREAD

**Issue by travs** [ianyh/Amethyst#361]
I had a look through the issues but couldn't find anything with this suggestion, so apologies if it's already been covered.

I find my self often having to relaunch amethyst from the menu, for example, when I "un-minimize" an application's window. Would be easier if there was a keyboard-driven way to do this.

[Trello Card](https://trello.com/c/herYb2Fu/181-amethyst-relaunch-amethyst-with-a-hotkey)

**Comment by JasonJAyalaP** [comment]
+1
I constantly relaunch because of firefox. It's ironic that there's no way to keep my tiling window manager working without the mouse!

**Comment by sdvim** [comment]
+1

**Comment by gwerbin** [comment]
+1

In the meantime, it seems like this is [possible with AppleScript](http://stackoverflow.com/a/16497564/2954547)

**Comment by yusefnapora** [comment]
Yeah, this would be great.  It's also possible with a one-liner bash script:

```bash
#!/bin/bash

killall Amethyst && open -a Amethyst
```

save that somewhere (I put mine in `~/bin/relaunch-amethyst`) and make it executable with `chmod +x <filename>`.  Then you can bind it to a keystroke with your favorite tool.

**Comment by gwerbin** [comment]
Good call. Could use Karabiner/Seil for that

**Comment by JasonJAyalaP** [comment]
Thank you, yusefnapora! Good temporary solution. I just created an Alfred workflow.

[Relaunch Amethyst.alfredworkflow.zip](https://github.com/ianyh/Amethyst/files/523481/Relaunch.Amethyst.alfredworkflow.zip)

**Comment by erikw** [comment]
This is a problem for me too as I use an external monitor which I connect/disconnect several times per day. Quite often Amethyst don't keep up to speed, especially by maximizing windows. Thus I need to relaunch the application manually.

* Best solution: Amethyst is snapper to resize windows
* Intermediation solution: keyboard shortcut for Amethyst menu bar icon > Relaunch Amethyst
