### ISSUE TITLE
Chrome app Google Hangouts always floating under El Capitan

### ISSUE THREAD

**Issue by mattiasr** [ianyh/Amethyst#365]
Upgraded to El Capitan and my Chrome app Google Hangouts is always floating now, unable to change with mod1+t

using Amethyst 0.9.8 (30)

can be reached on irc if you want quick feedback.

[Trello Card](https://trello.com/c/ip0lD5c9/182-amethyst-chrome-app-google-hangouts-always-floating-under-el-capitan)

**Comment by mattiasr** [comment]
on accident i found it it works on my built in display but not on my extra monitor.

**Comment by cpitt** [comment]
I've observed the same thing

OSX: 10.11.6
Amethyst: 0.10.1

Can also confirm that it floats on external monitors, but appears to tile on built in display

**Comment by ianyh** [comment]
I think this may have been a symptom of #49. It's a race so it's possible that a built in display was optimized enough to beat it, but an external display lost it. Regardless, this should be fixed now. Please reopen if it still happens
