### ISSUE TITLE
Switching spaces causes Amethyst to trigger layout

### ISSUE THREAD

**Issue by landaire** [ianyh/Amethyst#370]
I just installed Amethyst about 10 minutes ago and when I switch spaces the HUD shows up with the current layout and readjusts my windows. Is there a way to disable this or is this normal behavior?

**Comment by ianyh** [comment]
That sounds like the normal behavior. Amethyst is a tiling window manager in the sense that it manages all of your windows for you, rather than providing mechanisms for you to manage them yourself. So you configure parameters and just let it do its thing.

What behavior were you expecting?

**Comment by landaire** [comment]
Ah, I see. This was my first time trying out a window manager like this so I guess I was expecting it to only do its thing when I explicitly tell it to. I'll keep giving it a try though, thanks!

**Comment by ianyh** [comment]
Out of curiosity, is there something I could have done that would have helped understanding beforehand?

**Comment by landaire** [comment]
I think it was my idea of what a tiling window manager is. I was thinking it's there when you need it and actually use it and not "your windows are always going to be managed by Amethyst when this is on".

**Comment by ianyh** [comment]
Would something like "automatic tiling window manager" have been clearer?

**Comment by landaire** [comment]
I think that would actually. And FYI I've been using it since yesterday and have no problems since I now understand its purpose a little more.

**Comment by ianyh** [comment]
I'm going to close this out for now. Let me know if you have any more questions.
