### ISSUE TITLE
Shortcut to "Re-evaluate windows"

### ISSUE THREAD

**Issue by stylerw** [ianyh/Amethyst#371]
It's often the case that a new window will be generated by an App and Amethyst won't catch it.  Particularly R (the stats app) and MS Office tend to be missed.  My current solution is a keybinding to kill Amethyst and restart (at which point it notices and grabs those windows), but I'd love a quicker way to ask Amethyst to look around and detect any new windows.

For what it's worth, this isn't fixed by changing the layout, or switching the focus.

[Trello Card](https://trello.com/c/u3tukab4/183-amethyst-shortcut-to-re-evaluate-windows)

**Comment by ianyh** [comment]
Oftentimes if a window isn't captured it can be forced into tiling by toggling whether or not it's floating (`mod1+t` by default).

See #49 for more details on the issue. I think there's an issue open for the "just refresh everything" thing, but I can't find it at the moment so I'll keep this one open.

**Comment by stylerw** [comment]
I'd much prefer a universal keystroke, because in a keyboard based workflow depending heavily on switching windows in Amethyst, it's sometimes hard to grab a new window which just appeared and focus it enough to toggle floating.  

And often, apps generate multiple untrackables.  Either way, thanks for your ongoing work :)

**Comment by hub-cap** [comment]
This would be awesome. I relaunch amethyst multiple times a day to do this same thing. I just tried the `mod1+t` and it did not help me.

**Comment by ianyh** [comment]
Yeah, I think having a command for this would solve a lot of immediate problems. Slated for the next release.
