### ISSUE TITLE
Can't switch layouts when an application without a window is open

### ISSUE THREAD

**Issue by jjoh** [ianyh/Amethyst#378]
When I close the last window of an app, and the app stays open, alt+shift+space cannot be used to change layouts for the current space. I have to switch to some other app, with a window open (or Finder) to be able to change layouts. (Otherwise really enjoying Amethyst so far. :) )

[Trello Card](https://trello.com/c/CCou1aDa/186-amethyst-can-t-switch-layouts-when-an-application-without-a-window-is-open)

**Comment by ianyh** [comment]
Huh. I wonder if I broke something with how we manage available windows. I'll look into it. Thanks!

**Comment by ianyh** [comment]
This should be fixed in 0.10! Let me know if it's not.
