### ISSUE TITLE
Amethyst should have a "maximize floated window" action

### ISSUE THREAD

**Issue by dhgwilliam** [ianyh/Amethyst#38]
It would be very convenient if I could manage floated window geometry with Amethyst, in particular, maximizing the window. It might also be beneficial to have the maximize command float a window if it's not already floated, saving the user a keypress or two.

[Trello Card](https://trello.com/c/FJ6Q9HPT/21-amethyst-amethyst-should-have-a-maximize-floated-window-action)

**Comment by ianyh** [comment]
I think I'm going to close this out. There are much better applications for manipulating individual windows, and I'd like to make sure development is focused on making sure Amethyst does what it does well.
