### ISSUE TITLE
Glitches and missing shortcuts in the prefs window

### ISSUE THREAD

**Issue by jeromenerf** [ianyh/Amethyst#389]
Context : 

- osx 10.11.2
- US locale
- dvorak layout
- amethyst 0.10b2

When I open the the pref window : 

- I can only see & set 12 shortcuts out of the 21 listed in the README, so I can't override some existing mappings (related to #319)
- The first binding (Cycle layout forward) is displayed as (Alt Shift symbols) and "XXX"  instead of "space"
- It seems I can't use "TAB" or "ESC" in shortcuts, to cycle through windows for instance

[Trello Card](https://trello.com/c/qvFgTWHW/190-amethyst-glitches-and-missing-shortcuts-in-the-prefs-window)

**Comment by ianyh** [comment]
Do you use a dotfile?

**Comment by nd0ut** [comment]
The same problem. 

- 10.11.3
- 0.10b2
- US locale
- US and Russian layouts

![image](https://cloud.githubusercontent.com/assets/670959/14068929/f657aeb0-f499-11e5-9c87-c1b65b9c8772.png)

Also I found some strange hotkeys for changing to specific layout like `shift+alt+[a,s,d] -> [tall, wide, fullscreen` which I can't find in readme or prefs.

> Do you use a dotfile?
No. I can't find any info about dotfile.

**Comment by ianyh** [comment]
FYI I figured out the problem with not displaying all of the shortcuts. I have not yet quite tracked down the XXX problem. I think I know what it is. At a guess it's trying to localize the glyphs and failing to do so when switching keyboards. That is, you set a shortcut with the Russian layout to a character that doesn't exist in the US layout. See #352. Are you using a dotfile?

**Comment by jeromenerf** [comment]
@ianyh I am not using a dotfile. I use the dvorak intl layout though.

**Comment by ianyh** [comment]
Great. Thank you.

**Comment by ianyh** [comment]
Sorry, this got closed by a pull request, but isn't actually done.

**Comment by ianyh** [comment]
Actually, the XXX thing should be already fixed. I think it was a problem with the MASShortcut bundle.

**Comment by ianyh** [comment]
See the above PR for explanation, but this should be fixed. For the using tab and escape as shortcut keys, that's actually a current limitation of MASShortcut. I think I know how to patch it and I'll try to get to it. Can you open a separate issue for it, though?
