### ISSUE TITLE
1Password big password view

### ISSUE THREAD

**Issue by MoritzFago** [ianyh/Amethyst#390]
If you say show big password in 1Password, the window gets "managed" by Amethyst, due the fact that 1Password uses the alt key to toggle this view you can't use the shortcut to allow the window to float. How can i make the window float?

[Trello Card](https://trello.com/c/y1t4yJBh/191-amethyst-1password-big-password-view)

**Comment by ianyh** [comment]
Hm. I use 1Password and I'm not sure what you mean by "big password". Can I get a screenshot?

Also, what version of Amethyst?

**Comment by MoritzFago** [comment]
yes you can, it's the window with the big letters in it, basically the only non-blared window

<img width="1639" alt="1pw pw window" src="https://cloud.githubusercontent.com/assets/4459068/12590767/d99c9926-c464-11e5-9f0e-3a0ea0a478cb.png">

it is the latest version 0.9.10 (32)

**Comment by ianyh** [comment]
Hm. A brief test on mine seems to let do the floating manually, but you make applications float windows by default. 
<img width="449" alt="screen shot 2016-01-27 at 10 25 26 pm" src="https://cloud.githubusercontent.com/assets/212270/12634132/e8998dc2-c544-11e5-8ab7-09303e3741e5.png">
It's the list under floating. The UI isn't super clear.

**Comment by MoritzFago** [comment]
the problem is, i don't want to let 1Password float, i want everything except this password window to behave like all other windows.

**Comment by ianyh** [comment]
You can float windows with the title "Large Type".
