### ISSUE TITLE
Weird Chrome Issue

### ISSUE THREAD

**Issue by jclusso** [ianyh/Amethyst#391]
Somehow Amethyst causes the URL bar to do weird things. Sometimes the URL bar will be so big that it pushes the extensions on the right out of the Chrome window all together. I've fairly certain it's Amethyst because when I restart Chrome it will do it over and over. To get it to fix itself you have to usually close Chrome and restart Amethyst.

![screen shot 2016-01-26 at 1 59 30 am](https://cloud.githubusercontent.com/assets/622516/12574495/37a8f426-c3d2-11e5-9944-16a115d09b0b.png)

[Trello Card](https://trello.com/c/Ctxl4FFa/192-amethyst-weird-chrome-issue)

**Comment by Fetz** [comment]
:+1: I have the same issue (I don't know if something could be fixed since all other apps looks like they handle correctly the resize)

**Comment by ianyh** [comment]
What versions of Chrome and Amethyst?

**Comment by Fetz** [comment]
Chrome 47.0.2526.111 (64-bit), Amethyst 0.9.10 (32)

**Comment by Fetz** [comment]
I just updated to Chrome 48.0.2564.82 (64-bit), I will let you know if I can replicate the bug

**Comment by ianyh** [comment]
Hm. Weird. I'm actually on the same version of Chrome you were previously on and I was unable to reproduce, but I'm also running 0.10b, so something potentially got fixed along the way. Glad you aren't running into it anymore.

@jclusso any info?

**Comment by jclusso** [comment]
I updated to version Version 48.0.2564.82 (64-bit) last night. I'll post if it happens again. I'm not sure if I was updated before or after I took that screenshot.

**Comment by ianyh** [comment]
Sure thing.

**Comment by ralphholz** [comment]
I am on Chrome 50.0.2661.94 (64-bit) and this bug occurs there, too. However, it is super-erratic and relatively rare. Will be hard to reproduce.

**Comment by ianyh** [comment]
Chrome's UI structure has changed so much that I think this can be closed and reopened if encountered again.
