### ISSUE TITLE
focus-follow-mouse works only with second monitor attached

### ISSUE THREAD

**Issue by MoritzFago** [ianyh/Amethyst#398]
Mac OS 10.11.2
MacBook Pro Retina late 2013

[Trello Card](https://trello.com/c/HljsGMs4/196-amethyst-focus-follow-mouse-works-only-with-second-monitor-attached)

**Comment by ianyh** [comment]
Without a computer at the moment, but will try to test this soon.

**Comment by danieka** [comment]
I can reproduce this on:
MacBook Pro (Retina, 15-inch, Mid 2015)
OS X El Capitan 10.11.6
Intel Iris Pro 1536 MB
I can switch between windows on my secondary display (which is attached through HDMI) and from my laptop display to my secondary display.
I can not switch focus from secondary to laptop display. I can not switch focus between windows on my laptop display.

I will happily troubleshoot this if given some hints on what to look for.

**Comment by vlerenc** [comment]
Similar issue on my side (MacBook Pro late 2016, macOS 10.12.3 (16D32), two monitors, was trying tall and floating). The feature doesn't work on monitor 1, but works perfectly on monitor 2 (including moving the mouse from monitor 1 to monitor 2; moving it back to monitor 1 or any movement on monitor 1 yields no focus change).

That feature would be totally awesome (being used to *nix). Sad, Macs don't have it, so if you have any clues how to make it work, that would be really much appreciated! Thanks a lot in advance!

**Comment by ianyh** [comment]
Fixed by https://github.com/ianyh/Amethyst/pull/630
