### ISSUE TITLE
No such module 'Silica' !

### ISSUE THREAD

**Issue by andreaspada** [ianyh/Amethyst#407]
Hi, I'm try to setup a working development local tree, to test some ideas, but I receive that message right after the first tree cloning:

No such module 'Silica', which is called by ColumnLayout.swift. Any idea how I can solve that?

Thanks,
Andrea

**Comment by ianyh** [comment]
Have you run `rake setup` to initialize all of the dependencies?

**Comment by andreaspada** [comment]
Yes, I ran it and nothing happens... I reinitialized the branch some 
times, clean XCode install, fresh 10.11.3... nothing happens.


Ian Ynda-Hummel wrote:
>
> Have you run |rake setup| to initialize all of the dependencies?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ianyh/Amethyst/issues/407#issuecomment-185905482>.
>

-- 
   -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
         www.andreaspada.com

**Comment by ianyh** [comment]
What's the output when you run it?

**Comment by andreaspada** [comment]
None!

Ian Ynda-Hummel wrote:
>
> What's the output when you run it?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ianyh/Amethyst/issues/407#issuecomment-186240491>.
>

-- 
   -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
         www.andreaspada.com

**Comment by ianyh** [comment]
Do you have Carthage and CocoaPods installed?

**Comment by andreaspada** [comment]
Yes, from brew...

'brew install carthage'
'brew cask install cocoapods'

Ian Ynda-Hummel wrote:
>
> Do you have Carthage and CocoaPods installed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ianyh/Amethyst/issues/407#issuecomment-186241505>.
>

-- 
   -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
         www.andreaspada.com

**Comment by andreaspada** [comment]
Ok, now it's working... something went wrong the first time I installed 
cocopods. Sorry!

Ian Ynda-Hummel wrote:
>
> Do you have Carthage and CocoaPods installed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ianyh/Amethyst/issues/407#issuecomment-186241505>.
>

-- 
   -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
Andrea Spada :: Liuteria d'Autore
         www.andreaspada.com

**Comment by ianyh** [comment]
No worries. Glad you got it working.
