### ISSUE TITLE
Crashing when trying to focus a screen with no windows

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#408]

**Comment by ipstone** [comment]
I am a new user of Amethyst, but I am a little confused of the term "screen" - does it refer to physical monitor, or just referring to another 'screen' like other tiling windows? 

- the reason I am confused is that when I try to focus to screen 2 - nothing happened (I am on Mac OS El Captain) ... are there indicators on the desktop to show that I am on screen 1, screen 2, screen 3 etc?

Thanks

**Comment by rdlester** [comment]
Yes, "screen" refers to physical monitor.

You're thinking of what OSX refers to as "spaces". OSX can often clear out spaces so there's only one, at which point "switch to space 2" (Ctrl-2) will do nothing. You'll have to go into Expose and add another space.
