### ISSUE TITLE
App Ignore List

### ISSUE THREAD

**Issue by yepengfan** [ianyh/Amethyst#410]
Hi there,

Thanks for developing so great app. Amethyst works just perfect to meet all my needs.

Only thing I would like to suggested is whitelist. I am a long-time user of fantastical 2. It provides small float window for users to add, edit or delete events & reminders from top menu bar. It also works really really good.

While combining all those tools together, the Amethyst will resize and reposition fantastical 2 window, which makes the windows messy. There might be a better way than just app whitelist, but if the fantastical 2 can be ignored by Amethyst. It would be a really good solution.

Cheers

**Comment by timvisher** [comment]
Is the Floating section of the Preferences not working for you? The most confusing bit of that is that you need to use the bundle id of the application. I wrote a small script for grabbing that for an application that may help you.

https://gist.github.com/b54f82eecdd3c9859aee

Called like:

```
3291 @ 03-10 06:46:14: 👊
tvisher@timvisher-rjmetrics.home:~/Downloads
🐱  bundle-id ~/Applications/VLC.app
+$ path=/Users/tvisher/Applications/VLC.app
++$ basename /Users/tvisher/Applications/VLC.app
+$ path=VLC.app
+$ path=VLC.app
+$ osascript -e 'id of app "VLC.app"'
+$ perl -ne 'chomp and print'
org.videolan.vlc
```

**Comment by yepengfan** [comment]
Hi @timvisher 

Thanks for your timely reply. The floating function is what I am after exactly! It meets my need. 

The script is great, but I cannot find a place to manually add the bundle id to amethyst. I still select the app manually from the prompt window. Everything works just perfect!
