### ISSUE TITLE
increase / decrease height of selected window?

### ISSUE THREAD

**Issue by hems** [ianyh/Amethyst#413]
I love when i have my text editor on the left side and my browser and terminal on the right side, but splitting the right side in 50% vertically isn't very optimal since my terminal only uses a few lines.

is there a way of decreasing the height of focused window?

[Trello Card](https://trello.com/c/DlinoBI2/202-amethyst-increase-decrease-height-of-selected-window)

**Comment by ianyh** [comment]
This isn't currently possible unfortunately. It's far from impossible to implement, but might require expanding the capabilities of layouts, as I think you would need another command(s) to adjust the height of the current window in either direction.

I feel like something similar to this has been requested for, but upon brief searching I'm not seeing the relevant issue.

**Comment by Srdgh** [comment]
(FYI) Looks like you might be thinking about issue #82 (On Trello: https://trello.com/c/SrfCUoBR).

**Comment by ianyh** [comment]
Oh good catch! Thanks @Srdgh. @hems I'm going to close this to avoid duplicates.
