### ISSUE TITLE
Swap focused window to clockwise screen (mod2+l) crashes Amethyst

### ISSUE THREAD

**Issue by raizyr** [ianyh/Amethyst#414]
Amethyst version 0.10b2 (34)
Two monitors side by side.

Steps to reproduce:

Start with a focused window on the right screen.  Use mod+l and Amethyst stops running.
Start with a focused window on the left screen.  Use mod+l and the window moves to the right screen.   Use mod+l again and Amethyst stops running.

In constrast starting with a window on the left screen and using (mod+h) to "Swap focused window to counter clockwise screen" works with the window moving around the "clock" to the right screen.

[Trello Card](https://trello.com/c/f4wSMi1k/203-amethyst-swap-focused-window-to-clockwise-screen-mod2-l-crashes-amethyst)

**Comment by scrapbird** [comment]
I've been having this issue as well using version 0.9.10 (32)

**Comment by ianyh** [comment]
Yeah, it's been around for a while it looks like. It's slated for the next release.

**Comment by scrapbird** [comment]
Awesome, thanks for the response :+1:
