### ISSUE TITLE
Amethyst no longer builds in Travis

### ISSUE THREAD

**Issue by rbong** [ianyh/Amethyst#417]
Building with travis is broken again. I pushed an empty file and the build failed. [Here is the log](https://travis-ci.org/rbong/Amethyst/builds/118522219).

One issue is that the git commit hash for MASShortcut is no longer valid-
`fatal: reference is not a tree: d70129eebebb2249a27bfbac8019c8a93a51c08a`

Using the same version of MASShortcut with a different commit number fixes this problem, but creates more. [Here is the log from that build](https://travis-ci.org/rbong/Amethyst/builds/118523745).

Not sure what the problem here is-
`error: /Users/travis/Library/Developer/Xcode/DerivedData/Amethyst-clkrchmfzdovvdatqnolrwumpiep/Build/Products/Debug/MASShortcut/MASShortcut.bundle: No such file or directory`

I do not have any of the issues that travis has after running the same commands. I have completely unrelated problems, the same as #407. I will try to find what's different on my system so I can continue to investigate.

**Comment by ianyh** [comment]
I had to muck with my fork of `MASShortcut`. I ended up rebasing without thinking about it hard enough to realize it would break the locked version in the Podfile. I've got a PR open to hopefully fix the dependencies.
