### ISSUE TITLE
wide-tall Auto-Layout Bug with Multiple Monitors

### ISSUE THREAD

**Issue by AzureTwilight** [ianyh/Amethyst#431]
**REPRODUCE**:
I use Amethyst with built-in display and an external monitor under horizontal arrangement, both with several windows open. When I set the layout to *wide-tall*, the layout will be set regarding the two displays as one single large space, instead of two separate spaces.

**OTHER**:
Also did few tests with other layouts under both horizontal and vertical arrangements, and found no problem with them. With the older version, 0.9.10, the auto-layout worked fine without anything like this.

Thanks for this excellent WM!

[Trello Card](https://trello.com/c/GHliFNUl/209-amethyst-wide-tall-auto-layout-bug-with-multiple-monitors)

**Comment by ianyh** [comment]
@AzureTwilight what layout are you talking about? `wide-tall` doesn't exist. Do you mean `widescreen-tall`?
