### ISSUE TITLE
Incorrect scaling in fullscreen and wide layouts

### ISSUE THREAD

**Issue by Phrohdoh** [ianyh/Amethyst#434]
Amethyst 0.10 (36)
OS X 10.11.2

I don't know what other information is necessary.

Wide:
![screen shot 2016-04-23 at 8 15 41 pm](https://cloud.githubusercontent.com/assets/4861023/14764954/45d76244-0991-11e6-960e-770d999e0665.png)

Fullscreen:
![screen shot 2016-04-23 at 8 20 13 pm](https://cloud.githubusercontent.com/assets/4861023/14764955/45da82bc-0991-11e6-9921-e427b3cc0a13.png)

Let me know if I can provide something helpful!

[Trello Card](https://trello.com/c/9OyukTpK/211-amethyst-incorrect-scaling-in-fullscreen-and-wide-layouts)

**Comment by ianyh** [comment]
Whoa. What application is that?

**Comment by Phrohdoh** [comment]
Firefox Developer Edition: 47.0a2 (2016-04-24)

**Comment by ianyh** [comment]
Hm. I can't seem to reproduce this in 48.0a2.

**Comment by ianyh** [comment]
It's been years so I'm not sure this issue is still valid. Closing, but let me know if you still see it.
