### ISSUE TITLE
Windows not scaled when thrown to other workspace

### ISSUE THREAD

**Issue by ralphholz** [ianyh/Amethyst#436]
This happens in column layout, since version 0.10 (not before):

When I throw a scaled window to another workspace where it is the sole window, it will not be auto-upscaled to fill the screen, but remain at the same size it had on the old workspace (where it was sharing the screen space with, e.g., another window).

Cmd-N to create a new window of the same application and immediately closing it will trigger the auto-upscale. 

[Trello Card](https://trello.com/c/GlMTtSIb/213-amethyst-windows-not-scaled-when-thrown-to-other-workspace)

**Comment by ianyh** [comment]
Does this only happen with the column layout?

**Comment by ralphholz** [comment]
I just checked. It also happened with

* Row
* Floating

For the latter, I had my layout at Rows, then switched Floating and created a new window, and threw that to a new workspace. It resized there as if it was in Rows.

It does not happen in full screen (as expected).

BTW - many thanks for amethyst either way. It makes my life as a Mac user a lot easier.

**Comment by ianyh** [comment]
Having played with this a bunch today it looks like it happens in other layouts as well, but is somewhat dependent on the configuration of windows.

@ralphholz question: would #371 help in the short term?

**Comment by ralphholz** [comment]
In the short term, yes.

Anything about fixing the underlying problem that I can help with as a user?

**Comment by badfilms** [comment]
This doesn't appear to be resolved. In addition to thrown windows not scaling (if, for example, a column split goes to an empty space), the "Force windows to be reevaluated" command does nothing.

**Comment by ianyh** [comment]
To double check, you're on 0.14.0b?

**Comment by badfilms** [comment]
Sorry I missed the memo about the development build and was still on 0.13.
