### ISSUE TITLE
Amethyst forgets about minimized windows when relaunched

### ISSUE THREAD

**Issue by airways** [ianyh/Amethyst#438]
It appears that minimized windows present when Amethyst is started are ignored.

Version: 0.10

Step to Reproduce

1. Open multiple windows in various programs, Safari, Terminal, Sublime, etc. Which applications are used do not appear to be important.

2. Minimize half of the windows. Restore them, observe that Amethyst correctly identifies the restored window and accommodates it on the layout.

3. Re-minimize several windows.

4. Relaunch Amethyst.

5. Restore a minimize window. Amethyst no longer reacts and the window overlaps other windows on the screen until Amethyst is relaunched again.

[Trello Card](https://trello.com/c/wkxG3jdj/215-amethyst-amethyst-forgets-about-minimized-windows-when-relaunched)

**Comment by ianyh** [comment]
Oh, gross. Thanks for the report.
