### ISSUE TITLE
Latest app / cask not working on OS X 10.9.5 Mavericks

### ISSUE THREAD

**Issue by briatte** [ianyh/Amethyst#445]
The Web page says that

> Amethyst now is only supported on OS X 10.9+

but the latest app and cask are 10.10+ only.

![screen shot 2016-05-19 at 08 55 07](https://cloud.githubusercontent.com/assets/322533/15385081/69a98068-1d9f-11e6-8a77-6e67b670f6d9.png)

**Comment by ianyh** [comment]
Ugh. My sincerest apologies. I had to drop 10.9 support in 0.10. I thought I had updated the README but I clearly failed to do so. I'll update it posthaste and see what I can do about brew cask versioning.

**Comment by briatte** [comment]
No worries at all.

Side question: is it possible, with Amethyst, to remove the "shadow border" that OS X forces on the left of every window?

Example:

![screen shot 2016-05-19 at 09 00 29](https://cloud.githubusercontent.com/assets/322533/15391440/7cf3a8ca-1dc1-11e6-8d6a-69df64c2ac58.png)

I am looking for an application that would resize the window to 100% fullscreen, forcing the shadow out of the screen, as in:

![screen shot 2016-05-19 at 09 03 23](https://cloud.githubusercontent.com/assets/322533/15391464/95793766-1dc1-11e6-8ab7-2039afb6e247.png)

As you can see, I have tried Spectacle, but it does not solve the "shadow" issue, so I keep seeing a strip of my desktop picture on the left of all my screens.

**Comment by ianyh** [comment]
Is your dock positioned on the left? That's usually how you end up with that sliver of space.

**Comment by briatte** [comment]
Yep, that's where my Dock is. Isn't there any way to have the Dock on the left _and_ to get rid of the sliver?

**Comment by ianyh** [comment]
https://github.com/caskroom/homebrew-cask/pull/21475

**Comment by ianyh** [comment]
@briatte can you open a separate issue for the Dock sliver thing?
