### ISSUE TITLE
Switching to screen in Full layout focuses wrong window

### ISSUE THREAD

**Issue by adamwg** [ianyh/Amethyst#466]
I have two screens, one of which is on a space using the Full layout with two windows open (Emacs and iTerm2). I have Emacs focused and therefore it is on top. If I switch spaces on this screen all is well - when I switch back Emacs is still focused and on top. However, if I switch to the other screen (via keyboard shortcut) then switch back, iTerm2 becomes focused and is moved on top.

**Comment by adamwg** [comment]
Oh, I wonder if this is fixed by #461. I will try to figure out how to build a development version and try it.

**Comment by ianyh** [comment]
Yeah, this should be fixed by #461. Going to close this. Let me know if you still have trouble building development.
