### ISSUE TITLE
Amethyst Loses Track of Windows

### ISSUE THREAD

**Issue by felixge** [ianyh/Amethyst#467]
This is related to, but maybe different from #392.

I'm a new user of amethyst and I frequently notice amethyst "losing track" of windows. I.e. I'll have a window that I can bring up with Cmd+Tab, but amethyst doesn't assign a space to it. Hitting Shift+Opt+T to toggle float mode doesn't bring it back either. The window is not reachable via Shift+Cmd+J/K. The only way to get the window "back into the fold" is by hitting Cmd+W and reopening it (sucks if the window has useful state). Another way to bring it back is to restart Amethyst.

I'll try to pay closer attention to my workflow to see if I can create better steps to reproduce the problem. I'm usually using the tall layout.

[Trello Card](https://trello.com/c/Uz1FjJfl/219-amethyst-amethyst-loses-track-of-windows)

**Comment by cjthompson** [comment]
I noticed a similar issue. It seems to be related to when I either minimize an application or set an application to full screen and then restore the window back.

**Comment by benmosher** [comment]
I see this some of the time when "hiding" windows with `Command-H`. I think it works some of the time, but it definitely fails a lot of the time. Same remedies apply: either quit and re-open or relaunch Amethyst (and lose my Amethyst state).

Supporting show/hide would be great, it's a cool way to cycle things "off screen" quickly.

**Comment by benmosher** [comment]
New observation: just got into this issue and was going to let it just be. 

When I switched spaces and then switch back, the lost window was recognized by Amethyst again, and positioned properly. Could be a workaround?

**Comment by glibsm** [comment]
In addition to hiding, similar thing happens with minimizing the window.
One even quicker work-around is to toggle tiling on and off for the rogue window (cmd-shift-t twice)

**Comment by felixge** [comment]
I'm on 0.11.0b3 now, and while the reported workarounds above work sometimes, the only reliable workarounds for me are:

* Close/Reopen the App/Window
* Restart Amethyst

The new "Force Windows to be reevaluated" shortcut (Alt+Cmd+Z) only works intermittently for me.

**Comment by sunapi386** [comment]
I noticed this too, upon closing and relaunching AppCode. I have to restart Amethyst for the window to be captured again
