### ISSUE TITLE
Move focused to space X just moves mouse arrow to status bar

### ISSUE THREAD

**Issue by esbenp** [ianyh/Amethyst#468]
I do not know if missed some setup step, but whenever I run move focused to space 1/2/3/x my mouse just moves to the window bar (where the close, expand and minimize buttons are). I am running 0.10.1 on OSX 10.11.5

Did I miss some setup step?

**Comment by ianyh** [comment]
Do you have the system commands set up? It's in `SystemPreferences.app` under Keyboard > Shortcuts > Mission Control. The switch desktop shortcuts need to be enabled.

**Comment by esbenp** [comment]
Ah, perfect, thanks! I missed that step.
