### ISSUE TITLE
Allow different margins on edges of screen

### ISSUE THREAD

**Issue by airways** [ianyh/Amethyst#469]
It would be great to allow different margins on each edge of the screen vs. what is between windows. This would allow setting a custom margin for the top, left, right, or bottom outside edge of the screen.

The use case for this is as a nice little reserved "tray" like area for desktop icons to remain visible.

[Trello Card](https://trello.com/c/vlRbPPGo/220-amethyst-allow-different-margins-on-edges-of-screen)

**Comment by ianyh** [comment]
Makes sense.

**Comment by cyril-bouthors** [comment]
Hi guys,

I've been using SizeUp for a year now for this purpose: http://www.irradiatedsoftware.com/sizeup/

It works pretty fine.

Hope this help

**Comment by deecewan** [comment]
hey @cyril-bouthors - thanks for the hint. I was using Magnet before this. I am after a tool that will automatically resize and position the windows as I add or remove them.
