### ISSUE TITLE
Resize focus window instead of "main"

### ISSUE THREAD

**Issue by OJFord** [ianyh/Amethyst#471]
Would be good to be able to resize the currently focussed window instead of some arbitrary "main" window.

This is particularly frustrating with 3 (or more) windows open, since you only have one axis of movement, and can't do something like this:

```
+====+==========+
|    |          |
|    |          |
|    |          |
|    |          |
+====+==========+
|               |
+===============+
```

[Trello Card](https://trello.com/c/UNhIMZZJ/222-amethyst-resize-focus-window-instead-of-main)

**Comment by ianyh** [comment]
With #464 I added the ability for layouts to maintain state based on window changes, and I'm thinking of moving them to a model of generic commands. So, for example, instead of having a command that is specifically for making the main pane larger, you have `command 1

**Comment by papanikge** [comment]
yes. please do this. if I understand correctly this is also what I want. With 3 windows (one to the right as a column and two more, row-ed, in the left side column) there should be functionality to alter the size of the two row-ed window. now one can only change the "main" (big) window in the right side column. Thanks..! :)

**Comment by daphen** [comment]
This is what I came here for. If I have the "tall" layout, I'd like to be able to change the vertical height of one of the windows to the right. They're always evenly spaced right now.

**Comment by Bloumbs** [comment]
> This is what I came here for. If I have the "tall" layout, I'd like to be able to change the vertical height of one of the windows to the right. They're always evenly spaced right now.

Would also really love this!

**Comment by AriaFallah** [comment]
I'd also really appreciate having this. Is there anything blocking it that we could help with?

**Comment by ianyh** [comment]
In principle yes, but it may want to wait for #51

**Comment by loadedsith** [comment]
My favorite feature of chunkwm is the resize with modifiers: if you hold a specific key combo then when you click and drag window (anywhere on the window) it resizes the window.

The setting in chunkwm (if that's helpful...) is: 

> chunkc set mouse_resize_window           \"alt shift 1\"

**Comment by ianyh** [comment]
I think this is probably superseded by custom layouts.
