### ISSUE TITLE
Resizing applies to every desktop

### ISSUE THREAD

**Issue by OJFord** [ianyh/Amethyst#472]
As far as I can tell, this _isn't_ the same as #436.

_Actual_:
If I have two desktops open, each with two windows in `tall` layout, and in one desktop I grow/shrink a window with SHIFT+OPT+H/L, then switching to the other desktop will re-render it with that sizing - even if I had previously set it to a different non-even sizing.

_Expected_:
That I could switch between two desktops and maintain different split sizing in each.

[Trello Card](https://trello.com/c/fK7hayYe/223-amethyst-resizing-applies-to-every-desktop)

**Comment by ianyh** [comment]
Do you have displays have separate spaces turned on? It's in system preferences somewhere, but I'm on my phone and can't remember exactly where.

**Comment by OJFord** [comment]
Apologies - that wasn't clear. I'm using a Macbook with only the builtin display, but switching between virtual desktops. (And actually I do have that turned on anyway - in 'Mission Control'.)

**Comment by ianyh** [comment]
Yeah. The logic for screens switches on that flag, and I was concerned there was a bug somewhere in that logic beyond having separate screens. I'll try to take a look when I get a chance.

**Comment by ianyh** [comment]
Do you have space reordering turned off?

**Comment by ianyh** [comment]
I think this is fixed with recent changes in how we handle spaces.
