### ISSUE TITLE
Focus follows mouse fails when floating window spawns off-mouse

### ISSUE THREAD

**Issue by OJFord** [ianyh/Amethyst#473]
With focus-follows-mouse enabled, opening an application that will (or is small enough to) float is a bit of a nightmare when the application may appear off-mouse; immediately disappear behind the already-open window(s).

Solutions might be:
- Introduce a delay, which might be annoying under other circumstances
- Use mouse-follows-focus when opening a floating window, snapping mouse to that new window and thus keeping it in-view

[Trello Card](https://trello.com/c/hSt0m2Jz/224-amethyst-focus-follows-mouse-fails-when-floating-window-spawns-off-mouse)

**Comment by ianyh** [comment]
There has been a suggestion for having floating windows stay on top of other windows. I can find the issue later. This problem is also really bad with the preferences window. You end up not being able to turn focus follows mouse off (though I've added a shortcut to toggle it now).

**Comment by OJFord** [comment]
I haven't used Amethyst for years, so from my perspective this can be closed (feel free), but I suppose I'll leave it open courtesy to the three 👍🏻s..!

(I have no idea if it's still relevant/a problem though.)

**Comment by maertsen** [comment]
I think #1243 is a dup of this issue.

**Comment by OJFord** [comment]
> I think #1243 is a dup of this issue.

Yes that does look like a duplicate, but has more discussion; as I said previously I haven't used Amethyst for ages, don't even have a Mac atm, so I'll close this one in favour of discussion there for those it affects.
