### ISSUE TITLE
BSP occasionally has phantom windows taking up spaces

### ISSUE THREAD

**Issue by gprimosch** [ianyh/Amethyst#483]
Even though I have only one window open, BSP is still allocating half the space on the screen for a nonexistent second window. When I cycle through other layouts, like **tall**, the problem goes away, but returns when I come back to BSP. The problem goes away for BSP when I relaunch amethyst.

[Trello Card](https://trello.com/c/YnAZyPyd/231-amethyst-bsp-occasionally-has-phantom-windows-taking-up-spaces)

**Comment by ianyh** [comment]
Can you try running in log mode and seeing if you can reproduce?
```bash
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --log
```
This should output debug data on the bsp tree operations.

**Comment by gprimosch** [comment]
Just seeing this. Does the log get written to a file or just std out?

**Comment by ianyh** [comment]
When run that way it writes to stdout.

**Comment by rgabbard** [comment]
@gprimosch : I am also seeing this problem. I can consistently recreate it as follows:

1. Have three windows open - IntelliJ IDEA, Chrome, and a terminal.
2. Run Amethyst from the terminal.
3. Change layout to binary space partitioning.
3. From IntelliJ IDEA, make some change and hit Command-K to bring up the floating "Commit Changes" dialog.
4. Close that dialog.
5. There is now an empty "slot" in the BSP layout.

Unfortunately, I don't have time to get this down to a minimal example at the moment.  I suspect the only part of the process which is important is the trigger of creating the dialog.

I tried running Amethyst with `/Applications/Amethyst.app/Contents/MacOS/Amethyst --log` but got no output.

Amethyst version: 0.13.0 (70)
Mac OS X version: 10.14

**Comment by rgabbard** [comment]
I also tried enabling "Show debug info: About Layouts" but still didn't get any debug logging.

**Comment by rgabbard** [comment]
It may also be worth mentioning that if I cycle through other layouts and return to BSP, the phantom window slot is still there.

**Comment by ZaymonFC** [comment]
This is also happening to me. Windows don't regrow to fill empty space in BSP mode. (Which is a shame because I love BSP mode).

**Comment by ianyh** [comment]
Can somebody test this with 0.14.4? I made some changes to the layout and can't reproduce this.

**Comment by ZaymonFC** [comment]
Works for me! @ianyh 🎉

**Comment by ianyh** [comment]
Okay, going to call this closed for now.

**Comment by ChrisKeefe** [comment]
@ianyh, this issue persists (or has re-emerged) for me in `0.16.0`, on MacOS Monterey. I'm running a single external monitor, with the laptop closed. The issue is BSP-specific (Tall works as expected, for example). I've tried un-checking "Float small windows", but that makes no difference. Ghosts seem to accumulate and persist. Re-launching Amethyst (while still in BSP) fixes the problem temporarily. When I navigate away from the virtual desktop and return to it, the host windows reappear and the layout breaks.

**Comment by 0ceanlight** [comment]
I'm also having this issue on MacOS Monterey with Amethyst v0.16.1 (and had it on v0.16.0). I'm just running it on a laptop. Empty spaces appear after closing a window or moving it to another desktop. 

Sometimes restarting Amethyst fixes it temporarily, but after switching back and forth to a desktop, the phantom windows are still there. Putting windows on fresh desktops gets rid of the phantom windows. 

Running the following while recreating the issue produces no output.

```$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --log```

**Comment by marcusbuffett** [comment]
Just +1 here, also having this issue, don't think this should be closed

**Comment by ianyh** [comment]
This issue is 5 years old, and other ones have since been opened.
