### ISSUE TITLE
Amethyst can't manage Slack.app windows

### ISSUE THREAD

**Issue by timvisher** [ianyh/Amethyst#484]
Sorry if this is a known issue but at some point Amethyst stopped managing my Slack window. Is there anything I can do to help get that fixed?

[Trello Card](https://trello.com/c/9smkWbk2/232-amethyst-amethyst-can-t-manage-slack-app-windows)

**Comment by ianyh** [comment]
What version are you on?

**Comment by joelbrewster** [comment]
I'm using the brew install Slack.app (non-appstore) and Amethyst manages windows as intended.

**Comment by ianyh** [comment]
Hey @timvisher, any update?

**Comment by timvisher** [comment]
Sorry bout that! 

Slack `Version 2.0.3 (3512)`
Amethyst `0.10.1 (37)` (it might be nice to make this copyable from the Amethyst menu :) )

I installed Slack from the App Store.

**Comment by alexkrolick** [comment]
Pretty sure this is fixed - partly on Slack's side by removing lower limit on window width

**Comment by timvisher** [comment]
I don't see any change in this behavior yet. I can't 'capture' the window via the Toggle Float shortcut either.

Slack: 2.6.3 Beta Channel (via app store)
Amethyst: 0.11.2 (45)

**Comment by ianyh** [comment]
I think this may have actually been a symptom of #49

**Comment by timvisher** [comment]
Want me to reopen if the next update doesn't fix the issue?

**Comment by ianyh** [comment]
Yes, please.

**Comment by timvisher** [comment]
👍
