### ISSUE TITLE
Non intuitive window order

### ISSUE THREAD

**Issue by m2habert** [ianyh/Amethyst#492]
I don't get the concept behind the ordering of windows between the diferent layouts:

¿Should it not follow the left › right and/or top › bottom paradigm?

"Row" and "Column" both, obviously, are like that.
"Wide" is consistent with this logic as well: in the case of 4 windows, windows 2, 3 and 4 are moved to bottom, from L to R
"Widescreen Tall" keeps it also: win 2 - 3 - 4 on the right, top to bottom

But when it comes to my favorite, "Tall Right", every "smoothness" goes out the, uh, window, as now the 2nd window is not in  the "second best position" (is actually at the worst) and cycling becomes counter-intuitive (we read from top to bottom ALWAYS, including in most of the amethyst layouts).

"Middle Wide" is even weirder: on the left we have window 2 and 3 from bottom to top; then on the right, if we had a 5th win: it is TOP to BOTTOM!!!

Wouldn't it better to keep it always "top-to-bottom" consistent? 
I really miss that behaviour as I always go back and forth between main (n.1) window and window 2...

Thanks
![screen shot 2016-09-16 at 03 01](https://cloud.githubusercontent.com/assets/7454005/18576794/2262e85a-7bbb-11e6-9fb0-19862fb13dcf.png)

[Trello Card](https://trello.com/c/kceWyJbv/236-amethyst-non-intuitive-window-order)

**Comment by ianyh** [comment]
The row and column layouts are the top-to-bottom and left-to-right behaviors, respectively. Most of the other layouts work on clockwise basis, unless they have a special algorithm like bsp. The layout behavior mostly comes from xmonad, and is unlikely to change for the currently implemented layouts as they are based on the order of windows in an array, not their positions. A custom layout could override this, but I don't think implementing any such layouts is on the horizon for me. I would eventually like to have an extension system for user-defined layout algorithms, and I'm usually happy to incorporate new layouts implemented by the community.

See #51
