### ISSUE TITLE
Amethyst creating double windows in fullscreen Youtube

### ISSUE THREAD

**Issue by gprimosch** [ianyh/Amethyst#493]
I am pretty sure that Amethyst is the cause of this error, but I could be wrong.

**Steps to Reproduce**:
1. Have amethyst running (0.11.0b3)
2. Open Youtube in Chrome.
3. Play a video in full screen mode.
4. Wait about 10 seconds; I now see two duplicate copies of the playing video, each on one side of the screen, scaled appropriately as if they were two windows. The left "window" has working Youtube controls (minimize, bitrate, etc), but the right side just mirrors the video portion.
5. I can return to windowed mode and then back to full screen mode and the problem recurs. It also recurs if I restart Chrome.

When I quit out of Amethyst, the problem goes away.

[Trello Card](https://trello.com/c/Nsno8ku3/237-amethyst-amethyst-creating-double-windows-in-fullscreen-youtube)

**Comment by gprimosch** [comment]
FYI, I just upgraded to Sierra, and now Amethyst locks up YouTube in full screen mode. I can't exit out of full screen mode like I could with the previous release.

**Comment by talee** [comment]
Same issue here after upgrading to Sierra. I think it's any HTML video, rather than just YouTube. The key to repro being to have to watch the video for a little while like mentioned above.

**Comment by ianyh** [comment]
Yikes. I'll try to take a look.

**Comment by burntcookie90** [comment]
this is still occurring for me on 0.11.0b4(41)

**Comment by ianyh** [comment]
Okay, I'll take another look. Specifically with YouTube?

**Comment by burntcookie90** [comment]
Yep

**Comment by ianyh** [comment]
What browser?

**Comment by burntcookie90** [comment]
Google Chrome Version 54.0.2840.98 (64-bit)

**Comment by ianyh** [comment]
Thanks. Will take a look when I get a chance.

**Comment by ianyh** [comment]
@burntcookie90 is your issue the double window thing or the hard lock thing?

**Comment by burntcookie90** [comment]
@ianyh i'm seeing the double window issue in fullscreen

**Comment by ianyh** [comment]
What OS are you on?

**Comment by burntcookie90** [comment]
OSX 10.11.4

**Comment by ianyh** [comment]
So it works on Sierra, but not El Capitan, but I don't have an El Capitan machine to test on. Ugh.

**Comment by burntcookie90** [comment]
Ah, don't worry about it, idk if supporting older OSes is necessary. I'll probably just update to Sierra this weekend..

**Comment by ianyh** [comment]
Yeah. I'm doubting my capacity for supporting multiple OSes at this point. Might have to narrow it down.

**Comment by burntcookie90** [comment]
I come from the Android world, trust me I understand. I'm willing to disregard this until I up to Sierra, no worries.
