### ISSUE TITLE
minimum size for tiled window?

### ISSUE THREAD

**Issue by da0ist** [ianyh/Amethyst#494]
<img width="1440" alt="screen shot 2016-10-06 at 12 26 32 pm" src="https://cloud.githubusercontent.com/assets/7945846/19167608/493f9692-8bc1-11e6-9554-2f2bb7af41bc.png">

Can you make it so apps that actually resize like terminal.app have a minimum size so they pop onto the screen like slack does in this picture?

[Trello Card](https://trello.com/c/lbmRAREy/238-amethyst-minimum-size-for-tiled-window)

**Comment by ianyh** [comment]
Supercedes #495

**Comment by axs221** [comment]
@ianyh I would like to help with this one. It works well if I add a minimum size inside the TallLayout reduce method. I can add a global configuration setting. Here is a video showing it working with it hard-coded to 500px minimum:

https://cl.ly/0H373T2p3f3F
