### ISSUE TITLE
Idea for a "cascade" layout

### ISSUE THREAD

**Issue by jbiatek** [ianyh/Amethyst#496]
Something resembling old school Windows, but Amethyst could do it dynamically:

http://www.infobarrel.com/media/image/278.gif

Obviously, this really only lets you see one window at a time, making it similar to the full screen layout. The advantage is that by cascading them, you can easily switch between windows using the mouse, which full screen makes more difficult (especially without a trackpad to trigger Mission Control). It also gives you constant visual feedback about what other windows are present in that space without taking up much room. In full screen layout, the hidden windows can suffer from "out of sight, out of mind". 

The use case I'm thinking of is managing a space that consists mostly of mouse-based apps, like email, to-do list, and calendar. For those tasks, I'm using the mouse a fair amount (so I don't necessarily want to be forced to use the keyboard to switch apps), I want all these apps near each other, but I really only need to see one at a time so it'd be nice to have them take up more than half or a quarter of the screen. A cascade view would be perfect for that. Like any user who even considers something like Amethyst, I am a heavy keyboard and keyboard shortcut user, but some tasks just call for a mouse, and a layout like this could make Amethyst useful for those tasks too. 

Another thought I had is, since there isn't really a "main" window in this layout, the commands for resizing the main window could instead increase or decrease the amount of padding that each window has. Increasing the padding would show more of each window. I don't have any clue as to whether that makes sense or even is possible with how layouts are written though, I was just trying to think of what I would expect to happen with this layout. 

[Trello Card](https://trello.com/c/zYIy1E56/239-amethyst-idea-for-a-cascade-layout)

**Comment by Superpencil** [comment]
Yes this would be ideal when windows don't fit comfortably on the screen, cascade them and allow swapping by clicking the edge

**Comment by ianyh** [comment]
I think this can be done with custom layouts now. #1134
