### ISSUE TITLE
User-defined layouts through an extension

### ISSUE THREAD

**Issue by tchapi** [ianyh/Amethyst#51]
Great work !
What about a config file for creating new custom layouts easily ?

Thanks

[Trello Card](https://trello.com/c/Vx9e7umC/23-amethyst-configuration-file-for-layouts)

**Comment by r-obert** [comment]
I guess the preferred language would be Swift, right?

**Comment by ianyh** [comment]
Not necessarily. Swift is compiled, so of it were used to build an extensible layout system we would have to include a compiler. The thing that comes to mind is actually JavaScript as there is native support via the JavaScriptCore framework (https://developer.apple.com/documentation/javascriptcore).

**Comment by r-obert** [comment]
Wow yeah. Looks very nice.

**Comment by micimize** [comment]
along the lines of what @tchapi was saying, we could implement a parser for a subset of [i3 layout config](https://i3wm.org/docs/layout-saving.html)

**Comment by ianyh** [comment]
See my comment here, but I have a proposed solution in the above linked PR. https://github.com/ianyh/Amethyst/issues/1126#issuecomment-877842473
