### ISSUE TITLE
Missing darkmode icon

### ISSUE THREAD

**Issue by j6s** [ianyh/Amethyst#510]
If darkmode is enabled, the icon is still black. I could be mistaking, but I think there used to be a white icon.

---

- OSX Version: 10.12
- Amethyst version: 0.11b4

---

![screen shot 2016-11-14 at 2 10 44 pm](https://cloud.githubusercontent.com/assets/3374170/20265956/2ee93574-aa74-11e6-89ee-cc72245dd13d.png)

![screen shot 2016-11-14 at 2 10 52 pm](https://cloud.githubusercontent.com/assets/3374170/20265955/2ee83d90-aa74-11e6-8ae9-01e64145b72b.png)

**Comment by ianyh** [comment]
You are correct. Looks like it got lost in the Swift migration.
