### ISSUE TITLE
Illegal hardware instruction on 10.12.2 Beta

### ISSUE THREAD

**Issue by pikajude** [ianyh/Amethyst#520]
System info:

![img](https://i.imgur.com/caSrSwR.png)

```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst
zsh: illegal hardware instruction  /Applications/Amethyst.app/Contents/MacOS/Amethyst
```

```
$ lldb /Applications/Amethyst.app/Contents/MacOS/Amethyst
(lldb) target create "/Applications/Amethyst.app/Contents/MacOS/Amethyst"
Current executable set to '/Applications/Amethyst.app/Contents/MacOS/Amethyst' (x86_64).
(lldb) run
Process 56279 launched: '/Applications/Amethyst.app/Contents/MacOS/Amethyst' (x86_64)
Process 56279 stopped
* thread #1: tid = 0x146a028, 0x0000000100039cf7 Amethyst`___lldb_unnamed_symbol888$$Amethyst + 8727, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100039cf7 Amethyst`___lldb_unnamed_symbol888$$Amethyst + 8727
Amethyst`___lldb_unnamed_symbol888$$Amethyst:
->  0x100039cf7 <+8727>: ud2
    0x100039cf9 <+8729>: ud2
    0x100039cfb <+8731>: ud2
    0x100039cfd <+8733>: movq   %r12, %rdi
```

Nothing related to Amethyst in console.app

[Trello Card](https://trello.com/c/S8ZAP3Rl/245-amethyst-illegal-hardware-instruction-on-10-12-2-beta)

**Comment by ianyh** [comment]
Thanks for the report! I'll try to upgrade a machine and test this.

**Comment by ianyh** [comment]
@pikajude can you still reproduce this? I upgraded a machine of mine and it seemed to be working fine.

**Comment by pikajude** [comment]
@ianyh still happens.

**Comment by sublimator** [comment]
This is bugging me too ... I upgraded cause of the chrome return from fullscreen youtube bug I vaguely recall was an issue ... and then ...

**Comment by wilhuff** [comment]
I'm seeing this too (on 10.12.2 release) but I am seeing a crash report.

[Amethyst_2017-01-26-155411_mcg-macbookpro.crash.zip](https://github.com/ianyh/Amethyst/files/733965/Amethyst_2017-01-26-155411_mcg-macbookpro.crash.zip)

**Comment by ianyh** [comment]
@wilhuff do you have a dotfile?

**Comment by wilhuff** [comment]
Indeed

[amethyst.txt](https://github.com/ianyh/Amethyst/files/751429/amethyst.txt)

**Comment by ianyh** [comment]
It looks like your entry for `display-current-layout` being empty is causing the crash.

**Comment by wilhuff** [comment]
Removing that entry does avoid the crash.

**Comment by ianyh** [comment]
@pikajude @sublimator do either of you have dotfiles?

**Comment by sublimator** [comment]
Yeah, will gist mine when I'm back on my machine

**Comment by ianyh** [comment]
Great. If it's the same thing it should be a relatively easy fix.

**Comment by sublimator** [comment]
https://gist.github.com/sublimator/933bee5509b555bbb1da90ec8df116e9

That's my .dotfile. I use it in a weird way though, cause after upgrading at one time, (it *seemed*) the default and .dotfile stuff merging wasn't working properly, and while I was in a rush I just found some work around to get it working again. I vaguely recall messing around with some generated plist files also ... 

```shell
➜  ~ rm /Applications/Amethyst.app/Contents/Resources/default.amethyst 
➜  ~ ln -s $HOME/.amethystian /Applications/Amethyst.app/Contents/Resources/default.amethyst     
```

Note above: *I don't actually have a ~/.amethyst file*, but rather just overwrote the defaults.

Anyway for the moment, I've simply rolled back my version to `0.9.10` and things are working well enough for me, so I've postponed further investigation . 

However, I'm happy to try and help. I couldn't imagine using OSX without Amethyst.

**Comment by ianyh** [comment]
@sublimator that dotfile has the "screens" key as a string instead of a number.

**Comment by ianyh** [comment]
Looks like the dotfile used to use a string. Yikes. Okay.

**Comment by sublimator** [comment]
Good catch!
