### ISSUE TITLE
floating apps does not work, file picker crashes app

### ISSUE THREAD

**Issue by hermannsblum** [ianyh/Amethyst#527]
I use Airmail 3 in fullscreen mode.

Since the newest update, Amethyst will always resize any message-composer windows. This never happened before. My settings file looks like this:

    {
        "floating": [
            "com.apple.systempreferences",
            "*Airmail*",
            "*airmail*",
            "Airmail 3.app",
            "Airmail 3"
        ]
    }

None of these settings seem to work. Additionally, I tried to set the preferences via the UI, but selecting any app as floating will crash Amethyst and leave the settings unchanged.

[Trello Card](https://trello.com/c/EwbpysPS/247-amethyst-floating-apps-does-not-work-file-picker-crashes-app)

**Comment by ianyh** [comment]
See #522 for the crash. I'll double check that floating actually works.

**Comment by ianyh** [comment]
Fix for the crash is deployed. Floating seemed to be working, so I expect that with Airmail their bundle identifier possibly just doesn't have the word airmail in it.

**Comment by hermannsblum** [comment]
Awesome, thanks!
