### ISSUE TITLE
floating wildcards don't work everywhere

### ISSUE THREAD

**Issue by hermannsblum** [ianyh/Amethyst#531]
Following #527, after the crash fix, I found out that the actual identifier for Airmail is `it.bloop.airmail2`. 

Therefore, the wildcard `*airmail*` should have worked. However, windows still get resized until I include the exact identifier as above.

[Trello Card](https://trello.com/c/tjL1hUvJ/248-amethyst-floating-wildcards-don-t-work-everywhere)

**Comment by ianyh** [comment]
Hm. Okay. Thanks for following up on this!
