### ISSUE TITLE
Row layout not working even after restart

### ISSUE THREAD

**Issue by ddickstein** [ianyh/Amethyst#532]
I'm running **Amethyst 0.11.1** on **Mac OS X 10.12.2 Sierra**, and I'm having trouble adding new layouts.  I went to `Amethyst > Preferences > General > Layouts` and added `row`, added a shortcut to it with &#8997;&#8679;2, and restarted my machine as suggested, but no luck - the shortcut doesn't work.  My other layout shortcuts for the default layouts all work correctly (listed below in case helpful / relevant, inspired by tmux).

|shortcut|layout|working?|
|---|---|---|
|&#8997;&#8679;1|column|yes|
|&#8997;&#8679;2|row|no|
|&#8997;&#8679;3|wide|yes|
|&#8997;&#8679;4|tall|yes|
|&#8997;&#8679;Z|fullscreen|yes|

[Trello Card](https://trello.com/c/fUx77jtm/249-amethyst-row-layout-not-working-even-after-restart)

**Comment by ianyh** [comment]
Yeah, it seems to be a problem with selecting the row layout specifically. I tested a different shortcut for row layout, and ⌥⇧2 for a different layout. Only the latter worked. Thanks for the thorough report.

Though, when the preferences say restart it actually means restarting the application not your computer. So sorry about that. 😩 I can change the language to relaunch, which would be in keeping with the menu option for it.

**Comment by ianyh** [comment]
This was fixed by #623
