### ISSUE TITLE
Backup Amethyst Preferences

### ISSUE THREAD

**Issue by jayfunk** [ianyh/Amethyst#535]
I re-formatted my machine and I have a second machine with my desired configs on it. Is there a simple way to access the preferences and configuration for backup? 

[Trello Card](https://trello.com/c/GnJcqkRZ/252-amethyst-backup-amethyst-preferences)

**Comment by ianyh** [comment]
I wouldn't call it simple, but the plist file for the in-app preferences is located at `~/Library/Preferences/com.amethyst.Amethyst.plist`. You can copy it to the same place on the new machine.

**Comment by benjamreynolds** [comment]
I wonder what the complexity of making the configuration into a `.rc` file that is more easily sharable and can be easily commited to a set of dotfiles would be. 

@ianyh Thoughts?

**Comment by ianyh** [comment]
Amethyst technically already uses a dotfile, it's just quasi-deprecated.

Brief history: I used dotfiles originally as an expedient solution (as opposed to building out an in-app preferences interface). It was originally designed with the `xmonad`-style of commands using modifiers, but that's not really how it works now. Each command has its own key shortcut, they just have defaults that fall along the modifiers-based lines.

Amethyst will still look for a `~/.amethyst` file, but it will override anything you've set in the in-app preferences, and there's enough of an impedance mismatch that trying to support both as they are doesn't really make sense. The in-app preferences won out. The dotfile logic could probably be updated to just get rid of the idea of `mod`s, but I kind of feel like in-app preferences should be the default, with dotfiles being kind of a power-user feature.

There is an issue somewhere about syncing between a dotfile and in-app preference changes.

**Comment by ianyh** [comment]
#331

**Comment by benjamreynolds** [comment]
Are there any guidelines, documentation, or examples of what a `.amethyst` file would look like? Ive never really used `xmonad`.

**Comment by benjamreynolds** [comment]
Id love some documentation / details on the two configurations methods in the README. I'll submit a PR if I get it all figured out.

**Comment by ianyh** [comment]
It's a JSON file. Here's the internal one that defines the default set of preferences:

https://github.com/ianyh/Amethyst/blob/development/Amethyst/default.amethyst

**Comment by benjamreynolds** [comment]
Thanks @ianyh!

**Comment by ianyh** [comment]
Closing in favor of #301

**Comment by benjaminbauer** [comment]
Since #301 does not look like it will happen soon: Is there a way to **dump the current settings into a json structure**, that can be used as a dotfile? I tried `defaults export com.amethyst.Amethyst.plist -`, but there is a lot of stuff in there that just changes over time by using the app w/o doing any changes to the settings.
