### ISSUE TITLE
Dragging a tab out from a Chrome window to create a *new* Chrome window creates a "tabless" Chrome window (+ alignement issues)

### ISSUE THREAD

**Issue by Adnn** [ianyh/Amethyst#539]
Hi,

  I am using release 0.11.1, as installed through Homebrew, on OS X Sierra (10.12.2)

The problems can be reproduced as follow:
* Open a Chrome window, then open >= 2 tabs in it
* Drag one of those tabs out  of the Chrome window, but not onto another Chrome window

The expected  result would be a *new* Chrome window, with the dragged tab as its first (and only) tab.
The result I am getting is a *new* Chrome window, but without the tab bar, and not any way to create new tabs in it. For example, pressing Cmd+t **replaces** the current page (the one that was dragged from the first Chrome window).

Also, the "in dragging" behaviour is a bit weird (as the moved out tab "jumps" far while the tiling behaviour is triggered, but the mouse cursor does not follow it).

[Trello Card](https://trello.com/c/4shAeOJi/255-amethyst-dragging-a-tab-out-from-a-chrome-window-to-create-a-new-chrome-window-creates-a-tabless-chrome-window-alignement-issues)

**Comment by ianyh** [comment]
Yikes. It looks like they started creating an actual window when dragging tabs out. I don't think that used to be the case. This definitely used to work correctly.

**Comment by ianfixes** [comment]
I'm not sure this is still an issue for Chrome `Version 69.0.3497.100 (Official Build) (64-bit)` and Amethyst `0.12.x`

**Comment by Adnn** [comment]
Thank you for picking this up,

Indeed, I cannot seem to reproduce this issue with my current setup (Chrome ` 70.0.3538.67`).

**Comment by jivanpal** [comment]
Not reproducible on the following:

- macOS Catalina 10.15
- Chrome 78.0.3904.70
- Amethyst 0.14.2 (76)

I expect this was a bug in Chrome itself that has been resolved, as I recall seeing similar odd behaviour with Chrome version ~60 to ~70 in Sierra / High Sierra / Mojave, even without Amethyst installed.
