### ISSUE TITLE
What's needed for focus follows mouse?

### ISSUE THREAD

**Issue by ScottOaks** [ianyh/Amethyst#543]
I realize that this feature is experimental, but I cannot get it to work at all. The only preferences I have changed from default is to remove all layouts except floating, and enable focus follows mouse. Is there some other dependency I am missing here?

I guess it might not work for certain apps, but it has not worked for the ones I have tried, which are terminal, realvnc, and safari.

[Trello Card](https://trello.com/c/xIC2BFJG/256-amethyst-what-s-needed-for-focus-follows-mouse)

**Comment by ianyh** [comment]
It should definitely work for those apps. I just tried it, though, and it is definitely behaving erratically. Do you have any external displays? Does it work with any layouts besides floating?

**Comment by ScottOaks** [comment]
It is not working with any of those apps on just my primary display (macbook pro early 2015). Though also today I've hooked up two external monitors, but no difference.

However, I've switched from realvnc to Mac ScreenSharing, and it does sort of work among the different windows of that app (though not reliably -- e.g., it will change the focus when moving from window A to B, but not from B to A). So at least I'm on the write path in the config. Though also, still not from ScreenSharing to any other app.

Using tall layout doesn't change the situation.

**Comment by vlerenc** [comment]
Same issue on my side (two monitors, was trying tall and floating). The only window that gets the focus for me i iTerm2. That's it. No other app gets the focus for me.

That feature would be totally awesome (being used to *nix). Sad, Macs don't have it, so if you have any clues how to make it work, that would be really much appreciated!

**Comment by koekeishiya** [comment]
@ianyh I ran into what could be the same problem a long time ago, when I did focus-follows-mouse, see [issue](https://github.com/koekeishiya/kwm/issues/442) for reference.

In short, having the Dock always visible caused the window-server to always report an (invisible ?) window in the first index, with the same size as the primary display resolution. The window has `kCGWindowOwnerName` set to `Dock` and the invisible window has `kCGWindowName` set to` `Dock`, and I used that information to simply ignore it.

**Comment by ianyh** [comment]
@koekeishiya Thank you so much! I would have spent ages trying to track that down.

**Comment by vlerenc** [comment]
Yes, I came to the same conclusion when thinking about the differences between the "monitors". After switching to show/hide dock it started to work for me also on monitor 1 (with the now usually hidden dock).

If I may, is it possible on macOS (I am new to it) to implement the feature also without auto-raise? Coming from Unix environments, I always used focus-follows-mouse, but never auto-raise as this is often breaking certain interactions with new windows/dialogs that pop up over a window your mouse happens to be over.

Being able to selectively enable or disable auto-raise would be really awesome.
