### ISSUE TITLE
Mouse jumping with Focus Follows Mouse

### ISSUE THREAD

**Issue by trey-pindrop** [ianyh/Amethyst#544]
I upgraded Amethyst to 0.11.1 (44), and decided to try Focus Follows Mouse again.  So far, it appears to be working except for one thing.  I have designated a few Mac apps to be floating (calculator, dictionary, and system preferences).

The problem I have is that even if the mouse never leaves the border of the floating window of these apps, the mouse jumps to the center of the full-screen tiled app beneath it, thus causing the floating app to disappear (because auto-raise seems impossible to disable).

I thought it may have been a function of Keyboard Maestro, as many of my macros move the mouse to the center of the full-screen tiled window, but even with it disabled the floating windows disappear before I think they should.

With Keyboard Maestro I can configure these floating windows to have the mouse centered within them, which does help address this problem.  But the floating windows disappear before I can click on some parts of the window.  It's as if Amethyst is considering the boundary for Focus Follows Mouse to be within the borders of the window.  This makes using these floating apps very difficult indeed.

[Trello Card](https://trello.com/c/MT7z37Zr/257-amethyst-mouse-jumping-with-focus-follows-mouse)

**Comment by ianyh** [comment]
Do you also have mouse following focus enabled?

**Comment by trey-pindrop** [comment]
I did have Mouse Follows Focused Window.  I disabled it and it still appears to
change focus anyway.  I've noticed that if I have one full-screen window hidden
by another full-screen window on top of it, the focus will hide the window I
want to have focus and raise the other window.  It definitely doesn't seem to
honor window borders.

I thought I got a clue, if the mouse goes over some text in the window, the
focus would switch.  But that hasn't been totally reproducible.

**Comment by vlerenc** [comment]
Same issue on my side (two monitors, was trying tall and floating). The only window that gets the focus for me i iTerm2. That's it. No other app gets the focus for me.

That feature would be totally awesome (being used to *nix). Sad, Macs don't have it, so if you have any clues how to make it work, that would be really much appreciated!

**Comment by trey-pindrop** [comment]
With the latest stable build (0.11.3) this looks resolved.  Floating windows allow me to move the mouse within the borders of the window, and do not disappear until the mouse cursor moves outside the floating window's border.
