### ISSUE TITLE
Config file for shortcuts / preferences

### ISSUE THREAD

**Issue by tylerfowle** [ianyh/Amethyst#545]
it would be great if settings were defined in a .config file rather than within the app preferences.
this would allow for backing up and syncing between machines using github.
also, imo, easier shortcut mapping.

cheers! great work btw.

[Trello Card](https://trello.com/c/1boW63Pg/258-amethyst-config-file-for-shortcuts-preferences)

**Comment by benjamreynolds** [comment]
I just had a similar thought. Check out #535 for a quick and dirty low-down on this. TL;DR it can.

**Comment by ianyh** [comment]
This will be accomplished by #301
