### ISSUE TITLE
small windows not floating

### ISSUE THREAD

**Issue by prog666** [ianyh/Amethyst#558]
After update to 0.11.2 setting `Float small windows` doesn't work for WebStorm. You can test it by clicking Cmd + Shift + F in webstorm 

[Trello Card](https://trello.com/c/FJuAAZSt/261-amethyst-small-windows-not-floating)

**Comment by ianyh** [comment]
So the window find window is being tiled when it was not being tiled before? I wonder if this is a symptom of #49.

**Comment by prog666** [comment]
yes, it was not being tiled before and now it being tiled. Annoying me so much

**Comment by ianyh** [comment]
Do you happen to know exactly how big the window is? It's pretty big in AppCode.

**Comment by prog666** [comment]
It's not actually small, but i don't want it to tile, and it didn't tile before

**Comment by ianyh** [comment]
Yeah, I think it not tiling before was a bug. It seems like #171 would fix your problem when implemented.

**Comment by ianyh** [comment]
Or possibly what I mean is #99.

**Comment by daphen** [comment]
I have a similar problem in Opera.
When setting floating small windows to on, Amethyst stops caring about Opera completely.
I need floating windows to be set to on, in Opera because it opens another window when typing in the address field which manages the search engines.

**Comment by ianyh** [comment]
Per #740, next version you'll be able to specify window titles for an application that will be automatically floated.

**Comment by camplowell** [comment]
I know this is an old issue, but *the title fits my problem far too perfectly. Here's a screenshot of the issue:
![Amethyst float small windows not working](https://user-images.githubusercontent.com/50926659/171773268-6a1a14a3-cd30-42e7-95c4-762f102403eb.png)
