### ISSUE TITLE
Amethyst won't start at all

### ISSUE THREAD

**Issue by oyvindeh** [ianyh/Amethyst#561]
I have Amethyst on OS X Sierra (10.12.3), and it won't start at all. No error messages. It's installed through Homebrew. It was originally installed on an older version of OS X, and have stayed through updates. I have not used it lately, so I don't know when it stopped working. I've tried reinstalling it without success.

**Comment by RaphaelVacation** [comment]
Running sierra 10 12 3 too, same issue, also using brew cask to manage the package.
tried

brew cask uninstall
brew cask reinstall

without success.

I think this software is great, I use it for the mouse focus feature. It functioned on my system fine for about a week in the first install.

**Comment by ianyh** [comment]
Does running it manually produce anything useful? It would be something like

```bash
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst
```
The path may be slightly different if cask puts applications somewhere else.

**Comment by Phvacan** [comment]
the path was correct for me. It replied:

`Illegal instruction: 4`

**Comment by ianyh** [comment]
Sounds like an empty optional was force unwrapped somewhere. Do either of you have a dotfile I can take a look at?

**Comment by Phvacan** [comment]
I know they are for configuration but I have never done one myself. I want to help, where can I find one?

**Comment by ianyh** [comment]
If you don't have a dotfile then you have the default one that's in the application bundle, which should be fine, but just to check can you send me
```
$ cat /Applications/Amethyst.app/Contents/Resources/default.amethyst
```
and
```
$ defaults read com.amethyst.Amethyst
```
?

**Comment by Phvacan** [comment]
here
[com.amethyst.Amethyst.txt](https://github.com/ianyh/Amethyst/files/883164/com.amethyst.Amethyst.txt)
[default.amethyst.txt](https://github.com/ianyh/Amethyst/files/883163/default.amethyst.txt)

**Comment by ianyh** [comment]
Yeah. That all looks fine. Can you send me
```
$ defaults export com.amethyst.Amethyst -
```
I'm going to try to recreate your state locally.

**Comment by Phvacan** [comment]
here
[export-com.amethyst.Amethyst.txt](https://github.com/ianyh/Amethyst/files/883229/export-com.amethyst.Amethyst.txt)

**Comment by ianyh** [comment]
Okay, that worked! At least it's crashing for me now.

**Comment by Phvacan** [comment]
haha awesome. let me know if I can help with something else.

**Comment by ianyh** [comment]
@Phvacan So, you somehow have no layouts, which is why it's crashing (#488).

Steps for a quick fix:
  1. Run
```
$ echo "{\"layouts\":[\"floating\"]}" > ~/.amethyst
```
  2. Launch Amethyst
  3. Run
```
$ rm ~/.amethyst
```
  4. Relaunch Amethyst

Then you should be able to set whatever layouts you want in Preferences.

@oyvindeh Do you think you could have the same problem?

**Comment by Phvacan** [comment]
Worked for me, thanks! I remember removing the layouts to avoid my windows getting tiled after login. Floating works just fine though.

**Comment by oyvindeh** [comment]
It works for me as well 🥇

**Comment by ianyh** [comment]
Okay. Going to mark this as duplicate, then.
