### ISSUE TITLE
Throw to next space doesn't show up in preferences

### ISSUE THREAD

**Issue by ericychoi** [ianyh/Amethyst#566]
I feel like I am missing something quite obvious here, I installed Amethyst with Homebrew and for the life of me I cannot find a way to throw current window to the next space.  According to the documentation this is supported?  Can someone help me?

[Trello Card](https://trello.com/c/RLT5Oyeq/267-amethyst-throw-to-next-space-doesn-t-show-up-in-preferences)

**Comment by ianyh** [comment]
It's <kbd>ctrl</kbd>+<kbd>opt</kbd>+<kbd>shift</kbd>+<kbd><kbd>left</kbd>/<kbd>right</kbd></kbd>. It appears to not be in preferences, which is definitely a bug.

**Comment by ericychoi** [comment]
So ctrl+opt+shift+2 (or any number) works for me, not left / right.  Is there a reason that this particular feature wouldn't work?  outdated version? I noticed homebrew gave me 0.10.1(37).

**Comment by ericychoi** [comment]
I am on El Capitan if that helps

**Comment by ianyh** [comment]
It's possible that the command was included in 0.11.0.

**Comment by ianyh** [comment]
Yeah, looks like it didn't land until 0.11.0 (#458).

**Comment by ericychoi** [comment]
Any way to get through homebrew? Or which way do you recommend to install
that version?

**Comment by ianyh** [comment]
It requires macOS 10.12, unfortunately.

**Comment by ianyh** [comment]
This was incorrectly closed by a PR.

**Comment by ianyh** [comment]
I can't at this time back support macOS versions earlier than 10.12.
