### ISSUE TITLE
Can't create keybinds containing punctuation characters

### ISSUE THREAD

**Issue by kayex** [ianyh/Amethyst#567]
Hello!

Is there a reason that creating key bindings with punctuation characters (`.` and `,` specifically) is not supported?

I'm using Dvorak, and would love to map "focus screen" for my three monitors to `option-shift-,`, `option-shift-.` and `option-shift-p` respectively, which would allow me to switch screens with the same physical motion as if I was using Qwerty with the default bindings. But when I try to remap the keys using the menu bar preference pane, I'm only able to successfully bind `option-shift-p` while the bindings containing punctuation characters fail to register.

Really great app otherwise, it has been a boon for my productivity under OS X!

**Comment by ianyh** [comment]
<kbd>option</kbd>+<kbd>shift</kbd>+<kbd>.</kbd>/<kbd>,</kbd> are actually already in use for increasing/decreasing main pane count. If you go to those commands and clear them (or remap them) it should make the punctuation available again.

**Comment by kayex** [comment]
Ah, of course. Remapped those and now it seems to be working fine.

However, I don't seem to find anywhere to bind `Focus screen 3` through the preference pane. I only see the bindings for `Focus screen 1` and `Focus screen 2`. Is there any other way that I can bind `Focus screen 3` (by editing the config files directly or similar)?

Thanks!

**Comment by ianyh** [comment]
Them not appearing is tracked in #566. Closing as a duplicate.
