### ISSUE TITLE
Pause/Stop Resizing Feature Request

### ISSUE THREAD

**Issue by alexymik** [ianyh/Amethyst#568]
There are a few situations where I would like to pause Amethyst (say, needing to go into Time Machine).

Would it be possible to add a "Pause" function to the menu and/or a hotkey combination so windows are not resized? Currently I am quitting and restarting Amethyst, which is a bit annoying since I have different layouts on multiple monitors which get reset.

Thanks

**Comment by ianyh** [comment]
There is actually a command for toggling tiling globally. It's <kbd>control</kbd>+<kbd>option</kbd>+<kbd>shift</kbd>+<kbd>t</kbd>. The Amethyst icon in the status bar will gray out when tiling is disabled.

**Comment by alexymik** [comment]
Ah, didn't realize that's what that meant. Great, thanks!

**Comment by mwoffenden** [comment]
Many people don't use command keys as they are too cryptic and hard to remember.

Please consider adding Pause/Resume as a menu bar option.
