### ISSUE TITLE
rake setup fails

### ISSUE THREAD

**Issue by vkz** [ianyh/Amethyst#570]
>rake setup
```
Installing SwiftyJSON (3.1.1)

[!] Error installing SwiftyJSON
[!] /usr/local/bin/git clone https://github.com/SwiftyJSON/SwiftyJSON.git /var/folders/1c/6v22mx7n7z13mw9dv9hz_j8r5hvc8_/T/d20170418-98842-1y0rxmq --template= --single-branch --depth 1 --branch v3.1.1

Cloning into '/var/folders/1c/6v22mx7n7z13mw9dv9hz_j8r5hvc8_/T/d20170418-98842-1y0rxmq'...
warning: Could not find remote branch v3.1.1 to clone.
fatal: Remote branch v3.1.1 not found in upstream origin
```

Solved by grepping `SwiftyJSON` and removing relevant lines from `podfile.lock`. I have no idea what I'm doing here. Sorry if that's not proper solution but I just wasted 40min fighting the sh*tshow that is Ruby ecosystem. Presently I have no room for more build tools in my life. Hope this helps.

[Trello Card](https://trello.com/c/tceKFp5E/269-amethyst-rake-setup-fails)

**Comment by ianyh** [comment]
Does it work if you run `pod repo update` before `rake setup`?

**Comment by ianyh** [comment]
I suppose technically it should be `bundle exec pod repo update`, but either should work.

**Comment by vkz** [comment]
makes no difference. Getting same error. And that's on another machine, too. So, definitely reproducible

**Comment by ianyh** [comment]
This should be fixed in `development` now. You can see the relevant commits referenced above.

**Comment by vkz** [comment]
confirmed fix. Thank you.
