### ISSUE TITLE
Support 10th space in mod2 + [n]?

### ISSUE THREAD

**Issue by dennistang** [ianyh/Amethyst#594]
Hi, love using Amethyst! I was curious about if there were a specific reason why the `mod2 + [n]` shortcut doesn't support a 10th space where macOS supports it via `ctrl + 0`?

Perhaps I'm odd but I like having a specific application in the last space in my ten space setup.

Looks like the code change required to support that is very straight-forward so I could submit a PR if there isn't something I'm missing for it to be done in the first place.

Thanks!

**Comment by ianyh** [comment]
The only reason is I didn't know macOS gave a default option for it as I had apparently never actually created a 10th space so it didn't show up when I tested originally. It should be a relatively straightforward change. The only complicated bit would be getting the mapping from 10 to 0 correct as a lot of the places that use the numbers assume a simple mapping from the space number to the command that gets run, but hopefully those places are fairly isolated. If you open a PR I'd be happy to review it.

**Comment by dennistang** [comment]
Sure thing! I'll take a swing at it.
