### ISSUE TITLE
atom editor not opening in fullscreen when amethyst is working

### ISSUE THREAD

**Issue by davidmasp** [ianyh/Amethyst#597]
Normally I just click a text file to open it with atom and if I left atom in fullscreen last time I was on that folder, the atom window re-starts at fullscreen but it gets halted with the rolling cursor and it never ends. I have to force quit the app (atom) then close athemyst and reopen atom. After that I can reopen athemyst with no problem. This only happens in atom and I guess it have to be the reopening in fullscreen. I know amethyst has also a fullscreen mode but some times I just move the whole thing to the top. If anyone knows how to stop this reopen in fullscreen with atom that would be great also!

btw, thanks for your great work!

[Trello Card](https://trello.com/c/MBa1TPsJ/275-amethyst-atom-editor-not-opening-in-fullscreen-when-amethyst-is-working)

**Comment by ianyh** [comment]
What version are you on?

**Comment by davidmasp** [comment]
`0.11.2`

**Comment by ianyh** [comment]
Oh, is this an issue with the macOS fullscreen and not just a maximized window?

**Comment by davidmasp** [comment]
Hi, I forgot about this lately. I just check and everything seems to be working fine and as expected. Not sure if an atom or amethysts update fixed the issue.

Thanks anyway!

**Comment by davidmasp** [comment]
I still have the `0.11.2` for amethyst so I guess I changed something in the atom configuration.
