### ISSUE TITLE
Amethyst won't tile iterm2 windows that have no title bar.

### ISSUE THREAD

**Issue by gusberinger** [ianyh/Amethyst#602]
When I set the window style to no title bar, Amethyst will suddenly ignore all iterm windows. Here are my Amethyst settings
![](https://user-images.githubusercontent.com/7536330/27413937-edf4b938-56c3-11e7-9f15-8a33f829e0f5.png)

**Comment by ianyh** [comment]
Yeah, this is a pretty common issue. #200

**Comment by ianyh** [comment]
Closing this as a duplicate.
