### ISSUE TITLE
[Feature request] Tile right to left

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#609]
On Windows I use a tiling windows manager named [Plumb](http://palatialsoftware.com/plumb/) -- and it has a "tile right to left" option.

Basically new windows show up on the right.

Would be nice to see this in Amethyst.

**Comment by ianyh** [comment]
Try the `tall-right` layout. I think it does what you want.

**Comment by ianyh** [comment]
@mwoffenden Did this work for you?

**Comment by mwoffenden** [comment]
It seems to, however, it piles up multiple windows all on the right, leaving only one window on the left.  Any way to get windows to tile more uniformly across the screen?

**Comment by ianyh** [comment]
@mwoffenden Possibly the `column` layout?

**Comment by ianyh** [comment]
I'm going to close this for now. Please reopen if you still have questions.
