### ISSUE TITLE
YouTube videos split in Chrome

### ISSUE THREAD

**Issue by filib** [ianyh/Amethyst#616]
## System

 - **0.11.0b4**:
 - **El Capitan (10.11.6)**:

## What's the problem?

When I am watching a Youtube video with Amethyst running, it will split screen the video and duplicate the video side by side. I've experienced this over the last few months in various Amethyst releases.

## How can it be reproduced?

Open a YouTube video in Chrome and hit fullscreen. After a few minutes it will split the screen and duplicate the video. I'm watching multiple videos in different tabs and the one that splits is 1440p.

## What applications are involved?

Chrome and Amethyst.

## Has anything fixed it, even temporarily?

Closing Amethyst whilst running YouTube videos in fullscreen.

## Screenshots

![screen shot 2017-07-10 at 13 31 04](https://user-images.githubusercontent.com/802389/28018178-2346c69e-6574-11e7-83cc-b5a3ee538526.png)

**Comment by ianyh** [comment]
I wasn't able to reproduce this on 0.11.3, and we unfortunately only support macOS 12.0 and later.
