### ISSUE TITLE
Mouse drag-drop window to different panes

### ISSUE THREAD

**Issue by bitwiseman** [ianyh/Amethyst#618]
## System

 - **Amethyst version**: 0.11.2
 - **macOS version**: 10.12.5

## What's the Feature Request?
When I drag a window over a window in another pane, I want Amethyst to swap the windows between those two panes.  We can move windows to different panes (forward and back) by keyboard.  Now the mouse could be used to do the same thing.

[Trello Card](https://trello.com/c/VfmWeHIY/277-amethyst-mouse-drag-drop-window-to-different-panes)

**Comment by ifreecarve** [comment]
Enabling this would take the user experience from "convenient" to "magical".  

I'd expect this feature to work such that the window being dragged is swapped with whatever window is under the cursor when the drag operation completes.

**Comment by ianyh** [comment]
The main hurdle with this and #617 is in detecting window movement. We don't really respond to windows changing size and position except to treat it semantically as a trigger for reflowing. The problem with responding to those events is making sure that we don't hit an infinite loop when we are the source of the window change.

One thought I had early on with that is checking if the frame matched what we were about to set, but there are tons of edge cases in which the frame we set isn't respected; e.g., Terminal window sizes are actually in units of cursor size.

Another thought is to listen and drop a window change event when we trigger one ourselves. The Accessibility APIs happen across applications, so you can't really be sure you matched the events correctly, but it seems like collisions with _other_ applications would be rare. I haven't thought hard yet about how frequently we perform frame changes, and I haven't tested how asynchronous it is.
