### ISSUE TITLE
If there are only 2 windows, "Swap focused window with main window" should work no matter which is focused

### ISSUE THREAD

**Issue by ifreecarve** [ianyh/Amethyst#620]
## System

 - **Amethyst version**: 0.11.2 (45)
 - **macOS version**: 10.12.5

## What's the feature request?

In the normal case, the "Swap focused window with main window" command doesn't do anything if the main window is focused.  Presumably this is because several non-main windows might exist, and it wouldn't be clear which one of them needed to be swapped with the main window.

But when there are only 2 windows, the swap operation should work regardless of which one is focused.  This is especially important since the "main" window may not be the largest window when there are only 2 windows.

**Comment by ianyh** [comment]
This might just be a special case of #66
