### ISSUE TITLE
Cannot move windows between spaces

### ISSUE THREAD

**Issue by parzydlo** [ianyh/Amethyst#625]
## System

 - **Amethyst version**: 0.11.3 (49)
 - **macOS version**: 0.12.6 Beta (16G18a)

## What's the problem?
Windows cannot be moved between spaces using mod2+[n] and mod2+left/right combos. The only effect they have is moving the cursor to the top-left corner of the screen for ~1 second. This happens on a single-screen setup with a default Amethyst configuration.

## dotfile (if you have one)

```
{

}
```

**Comment by ianyh** [comment]
You need to enable the system keyboard shortcuts for changing desktops. See this section of the README: https://github.com/ianyh/Amethyst#setting-up-spaces-support

**Comment by parzydlo** [comment]
I'll make sure to go through the readme first in the future. Thanks.

**Comment by ianyh** [comment]
No worries. :)
