### ISSUE TITLE
Option Key as mod key is not working well.

### ISSUE THREAD

**Issue by winguse** [ianyh/Amethyst#631]
## System

 - **Amethyst version**: 0.11.3 (49)
 - **macOS version**: 10.12.5

## What's the problem?

I set the option key as the major mod key, which not working well (but not all of them):

Works well: `option + k`, `option + j`
Works incorrect: `option + b`, `option + f`, `option + t`

## How can it be reproduced?

I've attached my configuration file.
[com.amethyst.Amethyst.plist.zip](https://github.com/ianyh/Amethyst/files/1167084/com.amethyst.Amethyst.plist.zip)

Copy and replace it into `~/Library/Preferences/com.amethyst.Amethyst.plist`

## What applications are involved?

No related to other application, I think.

## Has anything fixed it, even temporarily?

No.

## dotfile (if you have one)

No.

## Screenshots

<img width="512" alt="config" src="https://user-images.githubusercontent.com/1443504/28487879-c4713704-6ecd-11e7-9536-683ce8bb33ba.png">

**Comment by ianyh** [comment]
It looks like for the failing ones you either don't have a command set for it or it's set for a command to select a layout that you don't use.

**Comment by winguse** [comment]
oh shit, I found it, I need to add those layout into general -> layouts. (I remove it by mistake).

Sorry for my fault.

**Comment by winguse** [comment]
oh, not actually. I enabled all the layouts now, but it still failed to switch to

bsp by `option + b`,
middle-wide by `option + shift + w`,
tall-right by `option + shift + t`,

**Comment by ianyh** [comment]
Possibly related to #603

**Comment by ianyh** [comment]
This should be fixed in the 0.11.4 beta.
