### ISSUE TITLE
Add global tiling toggle to the status bar menu

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#635]
I like to keep Amethyst running on startup, but occasionally I need to suspend it briefly.  At the moment, the only option is to exit and later restart.

Suspend/resume on the menu bar right click menu would therefore be very helpful.

[Trello Card](https://trello.com/c/BTA2SQUn/283-amethyst-app-suspend-resume)

**Comment by ianyh** [comment]
You can globally disable and reenable tiling. It's <kbd>shift</kbd><kbd>ctrl</kbd><kbd>option</kbd><kbd>t</kbd> by default. The status bar icon is grayed out when tiling is disabled.

**Comment by mwoffenden** [comment]
I don't try to remember cryptic shortcuts, it would drive me crazy.  Can we get a simple menu item to do this?

**Comment by ianyh** [comment]
I've tried to avoid a proliferation of commands available through the status bar menu. I could possibly be convinced that putting the global tiling toggle in there is worth it, but there are things at the other end of spectrum where I really don't think they should be (e.g., focus follows mouse), and I want to be careful with it.

**Comment by mwoffenden** [comment]
I understand your concerns since I do a fair amount of UI design myself.  However I do think that the status bar menu is fairly short at this time, so adding a new (and very useful) item should be fine.  Considering the use case, I think that most users would benefit greatly from the pause feature being easily accessible.

On the other hand, "check for updates" need not be on the main context menu, and could be tucked away in Preferences.
