### ISSUE TITLE
Add configuration option for new windows to float by default?

### ISSUE THREAD

**Issue by jashmenn** [ianyh/Amethyst#639]
I'd like to add an option (under Misc.) to float new windows by default.

I'm happy to write it and submit a pull requested, but I wanted to check first: if I wrote this (and it was up to par, etc.) is it something you would want to merge?

**Comment by ianyh** [comment]
You could accomplish this by using `*` as a floating app identifier. That is more than a little arcane, though. I don't think I'm totally opposed to the idea of having a specific option for it, but it feels very close in behavior to disabling tiling entirely. Do you have any ideas on how to reconcile those? I could probably be convinced that it's sufficiently distinct to keep them separate.

**Comment by jashmenn** [comment]
Ah interesting! Putting `*` in the app identifier gives me the behavior I want -- I can still opt-in specific windows, but new windows are floating by default. Neat! 

I'll close this for now as `*` seems like an easy solution.

**Comment by ianyh** [comment]
👍
