### ISSUE TITLE
"Do not tile windows that wont resize down"

### ISSUE THREAD

**Issue by LanderN** [ianyh/Amethyst#641]
In #62 you said:
> "You would also run into issues with minimum sizes. If my Xcode window "resists resize" because it's being tiled into a small space does that mean it should float by default? Because that's not the behavior I want."

That seems to be the behaviour I do want 🙂 
I dislike it when windows that are obviously too large to fit into its space are crammed into some corner with just a tiny bit of the window visible.

I propose this solution: if the window is too large for its space, try to place it in the main pane (Tall layout), if it is also too large for the main pane, float the window.

This way, windows will never be tiled into panes that are too small. It sacrifices predictability, though, so I would disable it by default and leave it as an option. Maybe the "first try to tile in the main pane" behavior should be optional too.

Just a suggestion, I would understand if you don't like this idea!

**Comment by ianyh** [comment]
Clarification: are you suggesting that a window should get swapped to the main pane when it no longer fits in its assigned frame?

**Comment by LanderN** [comment]
Yes, that is what I meant. There are of course a lot of edge cases to
consider (what if the window in the main pane is also too large for
example). So an option to float windows that are too large might be a good
start.

**Comment by ianyh** [comment]
Yeah, I really don't think it's a good idea, even as an option. I think it fundamentally breaks deterministic aspects of how windows are managed. The referenced issue is actually about whether or not to float windows _when they are opened_.

**Comment by LanderN** [comment]
I can see your point, I guess it would be too confusing and possibly irritating for most. Thanks for your response and keep up the good work on this application! 👍
