### ISSUE TITLE
Unable to build with Xcode 9 beta 6

### ISSUE THREAD

**Issue by 20015jjw** [ianyh/Amethyst#648]
## System

 - **Sierra / XCode 9 Beta 6**:

## What's the problem?
I'm unable to build from my current environment. I've successfully completed `.bin/setup.sh` and have set swift language version to Swift 4 in XCode 9 Beta 6. However, I'm getting this error message:

`________/Amethyst/AppKit.NSControl.StateValue:10:23: 'onState' has been explicitly marked unavailable here`

![image](https://user-images.githubusercontent.com/1016134/30270215-9e3f0746-96a0-11e7-9acc-c135d254688c.png)

## How can it be reproduced?

```
git clone ___
git branch -> *development
./bin/setup.sh (multiple times)
```
then open xcode workspace and hit build.

**Comment by ianyh** [comment]
The APIs changed slightly between beta versions. This should be fixed now.
