### ISSUE TITLE
Amethyst doesn't readjust if Rambox app is shown / closed

### ISSUE THREAD

**Issue by rpensek** [ianyh/Amethyst#649]
## System

 - **Amethyst version**: 0.11.4.52
 - **macOS version**: 10.12.6 (Sierra)
- **Rambox version**: 0.5.12

## What's the problem?
Amethyst doesn't seem to realign / resize windows if Rambox is closed or in some occasions also when opened. If I restart Amethyst it works every time.

## How can it be reproduced?
Install Rambox app and simply open it, play with window layouts and close it. Observer that there is desktop (free) space where Rambox app was before. It also keeps empty space for it when changing the layout as if it was still there. Sometimes Amethyst figures it out and fixes itself after a minute or two.

## What applications are involved?
Rambox (check version above)

## Has anything fixed it, even temporarily?
Only by relaunching Amethyst manually through its menu option. Also "mod1 + z - force windows to be reevalulated" shortcut doesn't seem to work (it does nothing).

## dotfile (if you have one)

```
{

}
```

## Screenshots

[Trello Card](https://trello.com/c/EK7IWPCD/288-amethyst-amethyst-doesnt-readjust-if-rambox-app-is-shown-closed)

**Comment by ifreecarve** [comment]
I was able to reproduce this easily on my branch.  Amethyst handles minimizing and restoring Rambox with no problems.  Same for quitting.  

However, when the Rambox application window is closed, it appears that it does something abnormal: it leaves an empty space behind, regardless of resizing/swapping other windows.  Rambox will automatically re-show its window (in that empty space) if you cmd-Tab to it.  

I'm not sure if this is a misuse of window behavior by Rambox (i.e. something intended as a "feature"), or a valid use case that Amethyst should support.  

`struct FrameAssignment` (and possibly others) seem to have a reference to a valid `SIWindow` for Rambox, even when that application window has been closed.  

There's an additional wrinkle to this: in some cases, you can open or close a window to cause Amethyst to automatically reflow.  If that happens, the empty space goes away and cmd-tabbing to restore the Rambox window will result in Rambox being unmanaged -- it just floats.

**Comment by rpensek** [comment]
@ifreecarve you're right. I do think however that it's best to fix this issue on Amethyst level as there may be a lot more of other applications which misuse such window behaviour, especially now with lots of "native" web apps on horizon. I think wmail (now Wavebox) had such issue as well, but they fixed it in a couple of updates later.

Waiting for fix on each app level rather than solving this on Amethyst would in the end mean either for user to wait for fix or remove / replace the app with something else (in case they want to keep using Amethyst).

**Comment by ianyh** [comment]
Maybe Amethyst is stalling trying to perform actions on the window.

**Comment by ianyh** [comment]
Can no longer reproduce this.
