### ISSUE TITLE
Commands for moving windows between adjacent spaces not in preferences

### ISSUE THREAD

**Issue by ianyh** [ianyh/Amethyst#660]
## System

 - **Amethyst version**: 0.11.4
 - **macOS version**: 10.3.1

## What's the problem?

The commands for throwing windows to spaces left and right exist, but are not in the preferences window.

## dotfile (if you have one)

```
{

}
```

## Screenshots

[Trello Card](https://trello.com/c/yRYmHHHD/297-amethyst-commands-for-moving-windows-between-adjacent-spaces-not-in-preferences)

**Comment by Pitometsu** [comment]
@ianyh could you point me to moving window functions location in the sources to let me do hotfix by myself?

**Comment by ianyh** [comment]
@Pitometsu 

This is where we bundle up the commands to display in the preferences UI. https://github.com/ianyh/Amethyst/blob/development/Amethyst/Events/HotKeyManager.swift#L307
And this is responsible for actually displaying them. https://github.com/ianyh/Amethyst/blob/development/Amethyst/Preferences/ShortcutsPreferencesViewController.swift#L14
The code for actually making the UI react to and apply changes to the stored data is in this file, which can be edited via Interface Builder in Xcode. https://github.com/ianyh/Amethyst/blob/development/Amethyst/Preferences/ShortcutsPreferencesViewController.xib

The last one can be annoying if you haven't used Interface Builder before so let me know if you hit snags with that part.
