### ISSUE TITLE
What app do you use to generate blank windows?

### ISSUE THREAD

**Issue by jez** [ianyh/Amethyst#668]
(This isn't actually an issue.)

What app generates the blank windows in this screenshot from the README?

I'd love to have something that renders blank windows to force other windows to be smaller.

![](https://camo.githubusercontent.com/293d1eae524f78ba1e50edae51fc7261830acd37/687474703a2f2f69616e79682e636f6d2f616d6574687973742f696d616765732f77696e646f77732e706e67)

Also: thanks for Amethyst by the way! Invaluable tool 👌

**Comment by jez** [comment]
I threw together my own app: https://github.com/jez/spacer

It's slightly different from the screenshots above: it renders transparently.
For anyone who stumbles on that and wants something different, it's a one-line change to make the background solid.

**Comment by ianyh** [comment]
Cool. I'll take a look when I get a chance. It might not be the right thing to include in Amethyst itself, but it might be worth linking as a related app.
