### ISSUE TITLE
No longer possible to turn off "start on login"

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#673]
## System

 - **Amethyst version**: 0.11.4
 - **macOS version**:10.13.2

## What's the problem?

- No longer possible to turn off "start on login"

## How can it be reproduced?

- Try to turn it off

[Trello Card](https://trello.com/c/PxMrwHem/306-amethyst-no-longer-possible-to-turn-off-start-on-login)

**Comment by ianyh** [comment]
Nice catch. APIs must have changed.

**Comment by mwoffenden** [comment]
Your welcome.  

And might I interest you in adding an _option to suspend tiling_ (versus having to exit and restart)?

Right before "relaunch" would be a really nice spot.

**Comment by ianyh** [comment]
https://github.com/ianyh/Amethyst/pull/667 🙂

**Comment by JonathanHuot** [comment]
I'm also affected by this issue, I'm not able to disable "start on login".

**Comment by ianyh** [comment]
Yeah. The way login items work changed and I haven’t had time to make it do the right thing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ianfixes** [comment]
Recommend changing the quoted part of the issue title to read "Start **Amethyst** on Login" (my emphasis) for better searchability -- it's the actual UI text.
