### ISSUE TITLE
Enter/Exit Full Screen causes Amethyst to brake arrangement of windows

### ISSUE THREAD

**Issue by LukaPitamic** [ianyh/Amethyst#674]
## System

 - **Amethyst version**: 0.11.4(52)
 - **macOS version**: 10.13.2

## What's the problem?
Going Fullscreen and back (green button - traffic light) causes Amethyst to put window on top of all existing windows and not to restore previous arrangement. 
Attached video:
https://www.youtube.com/watch?v=ebYpfEzbDIg

## What applications are involved?
I've tried with bunch of them. In the video above: Safari and iTerm2

## Has anything fixed it, even temporarily?
The only way I found is to restart Amethyst every time I exit Full Screen

## dotfile (if you have one)
none, all of the settings are as default

```
{

}
```

## Screenshots
https://www.youtube.com/watch?v=ebYpfEzbDIg

[Trello Card](https://trello.com/c/fFmrQQrS/307-amethyst-enter-exit-full-screen-causes-amethyst-to-brake-arrangement-of-windows)

**Comment by LukaPitamic** [comment]
Is it just me, or no-one uses full-screen toggle

**Comment by ianyh** [comment]
No, I'm definitely seeing this. I think something might have changed in macOS and it's messing up how windows are handled with fullscreen transitions.

**Comment by LukaPitamic** [comment]
When window gets full-screen it leaves the desktop. And the windows get rearranged correctly if switching desktops by decrementing number of windows. However when coming back(exit-full-screem) to the Desktop, number of windows remains the same instead if increment back.

**Comment by eplanet** [comment]
I'm having the same issue, I use frequently the fullscreen mode (Control + Command + F), then when I switched it back to normal mode, it stays "fullscreen".

The workaround I use now, is throwing that window to another workspace and then back to the current, then it gets reintegrated correctly. I suppose Amethyst just needs to "watch" for the fullscreen exit events so that it can rearrange consequently.

**Comment by bpourriahi** [comment]
##### system
macos 10.13.4
amethyst 0.12.0 (57)
chrome 67.0

##### steps to reproduce:
- Open two chrome windows on a screen (A and B), then full screen youtube with one of them (B). Then exit full screen. 
- After exiting full-screen on B, click on A before clicking on B (to ensure this broken behavior - it usually happens regardless of which window is selected). 
- A will go full-size and ignore the existence of window B.

##### workaround
Opening a new window on the screen or moving either screen from one space to the other fixes the issue.

**Comment by ianfixes** [comment]
I'm having trouble reproducing this issue on Chrome 69 and my development branch

**Comment by emptyflask** [comment]
Same issue. After exiting a fullscreen Youtube video in Chrome, I can no longer use Amethyst to control the layout without restarting it.
