### ISSUE TITLE
Amethyst quits when removing layout that isnt there

### ISSUE THREAD

**Issue by natestemen** [ianyh/Amethyst#683]
## System

 - **Amethyst version**: 0.11.4
 - **macOS version**: 10.13.3

## What's the problem?
Amethyst crashes when clicking "-" in the **Layouts** menu under preferences.

## How can it be reproduced?
Open Preferences and click the button circle below.
![screen shot 2018-02-09 at 2 36 14 pm](https://user-images.githubusercontent.com/12703123/36046396-bfca5c26-0da6-11e8-8368-c5da0a488831.png)

## What applications are involved?
 - Amethyst

## Has anything fixed it, even temporarily?
No

[Trello Card](https://trello.com/c/vJzuN9Nr/311-amethyst-amethyst-quits-when-removing-layout-that-isnt-there)

**Comment by ianyh** [comment]
Is this only when there’s no layout in the list highlighted?

**Comment by natestemen** [comment]
exactly, yes.

**Comment by ianyh** [comment]
Fixed in #708
