### ISSUE TITLE
Amethyst is able to send a window to the nth space without shortcut ctrl + n

### ISSUE THREAD

**Issue by Vonfry** [ianyh/Amethyst#691]
## System

 - **Amethyst version**:  `amethyst: 0.11.4 (homebrew cask)`
 - **macOS version**: `10.13.3 (17D102)`

## What's the problem?
In readme:

> Amethyst is only able to send a window to the nth space if the shortcut ctrl + n is enabled

But it also __works__ for me if ___without___ `ctrl + n`. I only want to use `Amethyst` on a special desktop and don't use it on others.

[Trello Card](https://trello.com/c/8ZJ7PYa2/314-amethyst-amethyst-is-able-to-send-a-window-to-the-nth-space-without-shortcut-ctrl-n)

**Comment by ianyh** [comment]
I think I'm a bit confused. What is the issue here?
