### ISSUE TITLE
Safari Tabs causing overflow and not resizing to fit.

### ISSUE THREAD

**Issue by TokenChingy** [ianyh/Amethyst#692]
## System

 - **Amethyst version**: 0.11.4 (52)
 - **macOS version**: 10.13.3

## What's the problem?
Safari tabs causes the window to overflow and not resizing to fit.

## How can it be reproduced?
Open a more than one tab in Safari.

NOTE: I do have margins set to 32px.

## What applications are involved?
Safari.

## Has anything fixed it, even temporarily?
Nope.

## dotfile (if you have one)

```
{

}
```

## Screenshots

[Trello Card](https://trello.com/c/II0CVyK2/315-amethyst-safari-tabs-causing-overflow-and-not-resizing-to-fit)

**Comment by ianyh** [comment]
I've seen this happen before, but have since been unable to reproduce.

**Comment by ianyh** [comment]
Closing this as stale. There have been a lot of Safari versions since then.
