### ISSUE TITLE
[Support] How to find sub-window identifiers?

### ISSUE THREAD

**Issue by rudedogg** [ianyh/Amethyst#701]
## System

 - **Amethyst version**: 0.12.0
 - **macOS version**: 10.13.4

## What's the problem?
How can I figure out the window identifier of an Apps sub-window(s)? I'd like to make the commit dialog of AppCode floating.

I ran `osascript -e 'id of app "AppCode"'` which returns `com.jetbrains.AppCode`. I tried adding `com.jetbrains.AppCode.*` hoping it would make all sub-windows floating, but that didn't seem to work. I also looked through Activity Monitor but couldn't find anything other than the `AppCode` process. 

Is there a tool/command to get the identifiers of all open windows so I can get the correct value?

**Comment by ianyh** [comment]
You want just `com.jetbrains.AppCode` no `.*`. It's the identifier for the application as a whole process, the windows don't have identifiers based off of it.

**Comment by rudedogg** [comment]
@ianyh Thanks for the reply. I see! I wish there was a way I could just target the Commit/Tips windows in AppCode.

Xcode doesn't have this problem because it uses [sheets](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/Sheets/Concepts/AboutSheets.html) for the dialogs. I guess this is more of an AppCode issue and I should contact them.

I dropped the window size to have it be caught by the `small windows` setting, but it's not really usable at that size. If you have any ideas for a workaround let me know!

**Comment by rudedogg** [comment]
@ianyh Out of curiosity, do you think it's possible to make the floating windows be "filtered" by name? Not asking for you to do it or anything, just curious if it's possible (maybe I can do a PR). 

The syntax could maybe be `"com.jetbrains.AppCode > "Commit Changes"`. So only windows for the `com.jetbrains.AppCode` id with the window title `"Commit Changes"` would be floating.

**Comment by ianyh** [comment]
There’s an open issue for filtering by window title. I’m on a phone, though, so I can’t find it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rudedogg** [comment]
Thanks for the reply, found some related ones at https://github.com/ianyh/Amethyst/issues/292, https://github.com/ianyh/Amethyst/issues/99, https://github.com/ianyh/Amethyst/issues/307

**Comment by ianyh** [comment]
Oh, thanks for looking them up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
