### ISSUE TITLE
Enhancement Middle-Wide Layout

### ISSUE THREAD

**Issue by jorgelaranjo** [ianyh/Amethyst#702]
## System

 - **Amethyst version**: 0.12.0(57)
 - **macOS version**: 10.13.3

# Enhancement
Would it be possible to make the `middle-wide` layout always put the window on the middle and create those two other `columns` left and right automatically, as empty space?
This is specially important when working with wide and ultra wide monitors, I'd say.

Happy to help change that part of code to allow for a new `middle-middle layout`

Possibly making this particular one always return >2 ?

`let secondaryPaneCount = round(Double(windows.count - 1) / 2.0)`

**Comment by ianyh** [comment]
Duplicate of #83
