### ISSUE TITLE
Switching to a screen with multiple windows changes the focused window in column, tall, or wide layouts

### ISSUE THREAD

**Issue by mjkelly** [ianyh/Amethyst#703]
Hi! Thanks for writing Amethyst. I've been using a Mac for work after several years of various tiling WMs (ion3, awesome), and this has me pretty excited.

## System

 - **Amethyst version**: 0.12.0 (57)
 - **macOS version**: 10.13.3

## What's the problem?

Switching screens *to* a screen with `column`, `tall` or `wide`  layout changes the focus of the windows.

I've seen it happen with `fullscreen`, but not consistently.

## How can it be reproduced?

1. On screen 1, create one window of application A.
2. On screen 2, create 2 windows of application B.
3. Set the layout of screen 2 to `tall`.
4. Focus the first-created window of application B.
5. Move focus to screen 1 (via amethyst keyboard shortcut), then move focus to screen 2 (also via amethyst keyboard shortcut). 

I'd expect the focused window on screen 2 to be the previously focused window from step (4). However, regardless of what window was in focus in step (4), amethyst will always focus the same window in step (5).

If the focus doesn't change, focus the *other* window in screen 2, then switch focus back to screen 1, then again to screen 2. The focus should change.

In comparison, if you cmd-tab between the two applications, the focus is preserved.

### Notes

Amethyst pretty reliably picks the first-created window to focus, when screen 2 is in the `tall` layout. It's a different window in `wide` and `column`, but it will be consistent in a given layout.

I have not reproduced this consistently with `fullscreen`.

It also works if you swap screen 1 and 2 above. (E.g. return focus to screen 1.) I don't have more than 2 screens so I can't test with that. :)

## What applications are involved?

I've tested this with:
-  application A = Chrome and application B = Terminal
- application A = Chrome and application B = Chome (same app)

However, my note about the behavior being different if you cmd-tab doesn't apply if application A == application B. 

No other applications are open.

## Has anything fixed it, even temporarily?

Not that I can find. I tried quitting all other applications, and restarting.

## dotfile (if you have one)

None

## Screenshots

n/a

Thank you!

**Comment by mjkelly** [comment]
I should probably also mention why this matters to me: I commonly find myself switching back and forth between two windows on separate screens -- I'll have chrome or slack open on one screen, and I'll be working in a terminal on the other screen. I'll flip back and forth between the two as I paste output into slack, copy commands from chrome, etc.

Thanks again!

**Comment by ianyh** [comment]
Yeah, we don’t keep track of last focused window on a screen. It seems pretty reasonable to do so at some point.

Thanks for the thorough report!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mjkelly** [comment]
Thanks! I'll keep an eye out.

**Comment by Lukas-Stuehrk** [comment]
From what I see, adding support for tracking the last focused window on a screen shouldn't be that hard:

There's already the `ObserveApplicationNotifications` class which listens to the `kAXFocusedWindowChangedNotification`. This class also has access to the `WindowManager`. We could extend the code that handles the `kAXFocusedWindowChangedNotification` notification to keep track of the focused window per screen. My idea would be to get the screen manager via the window manager's `focusedScreenManager` method. And then keeping track of the focused window is only a diligent but routine piece of work.

I think I could implement such a change. Please let me know if there's something from the design perspective speaking against it. That's what I found out when looking in the code for about 15 minutes, so there might be much better approaches.

Thank you also from my side for providing such a nice app. And kudos for open-sourcing so one can contribute.

**Comment by reuben** [comment]
I still reproduce this problem on 0.14.0... Should I open a new issue?

**Comment by Lef-F** [comment]
I am getting this issue on 0.14.0 when I switch from a screen with `fullscreen` layout to a screen with any layout. Should I open a new issue? Thanks!
