### ISSUE TITLE
Amethyst unresponsive

### ISSUE THREAD

**Issue by ddickstein** [ianyh/Amethyst#704]
I just got a new computer and Amethyst is not working for me. I tried restarting the machine but it doesn't seem to help. I'm not sure if it was never working on the new machine and I'm only now noticing or if it had been working and stopped.

## System
 - **Amethyst version**: 0.12.0 (57)
 - **macOS version**: 10.13.4

## What's the problem?
Amethyst is unresponsive. None of my keybindings seem to do anything.

## How can it be reproduced?
Run Amethyst. Pressing key combinations to change layout (or anything else) are ignored.

## What applications are involved?
Any

## Has anything fixed it, even temporarily?
No

## dotfile (if you have one)
None

**Comment by ddickstein** [comment]
I see Accessibility in System Preferences but I don't see any mention of Amethyst there.

**Comment by ddickstein** [comment]
Found it. Under Security & Privacy -> Privacy -> Accessibility. Thanks!

**Comment by ianyh** [comment]
Glad you got it working.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
