### ISSUE TITLE
Focus Follows Mouse focuses wrong window

### ISSUE THREAD

**Issue by mdagosta** [ianyh/Amethyst#706]
By the way I love having an Xomand replacement on the mac. It was the nail in the coffin for moving off my antiquated linux setup. Thanks! Hope this bug report helps.

## System

 - **Amethyst version**: 0.12.0 (57)
 - **macOS version**: 10.13.4
- 2 screens of different sizes, bug exists on both

## What's the problem?

When I have "Focus follows mouse" enabled and am using the Tall layout with 3 windows, Amethyst is focusing the wrong window. Specifically, with 2 windows on the right, the mouse-over _focuses the bottom right window when I mouse-over on the top right_.

## How can it be reproduced?

Configure one tall window on the left (I have a web browser), and two windows on the right (I have 2 iTerms). Mouse Focus on the left, then mouse focus on the **top right** without clicking. For me, it then actually focuses the **bottom right** window.

You can trigger an even worse version of this bug by switching the web browser to the top right. Because the focus moves beneath the mouse, you can't even click any links below a certain height.

## What applications are involved?

Chrome, Firefox, iTerm, Emacs, others... 

## Has anything fixed it, even temporarily?

I haven't figured anything out. I've disabled the feature for now. I tried a few previous versions but they all exhibit this behavior. I think the last version it worked for me was 11.5 and now I can't go back to it...

**Comment by ianyh** [comment]
I think I’m a little confused. That is how that feature works. What are you expecting to happen?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdagosta** [comment]
When I mouse over the top right window, I was expecting the top right window to focus, not the bottom right.

**Comment by ianyh** [comment]
Oh, okay. Thank you for the clarification and for the report!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdagosta** [comment]
It's a pleasure. Thanks for making Amethyst!!

**Comment by mdagosta** [comment]
Huzzah! Thanks Ian! Can’t wait for the next release now.
