### ISSUE TITLE
Tile last n focused windows, hide the rest

### ISSUE THREAD

**Issue by piccolbo** [ianyh/Amethyst#710]
Is it possible to have the layout refreshed on focus change, and have the last n focused windows only tile the screen, possibly with the one in focus taking the main position? Or is it beyond the purview of Amethyst, or even tiling wms in general?

```
|------------------------------|
|              |               |
|              |  prev focus   |
|   focus      |               |
|              |---------------|
|              |  one before   |
|              |  prev focus   |
|              |               |
|------------------------------|
```

Thanks

## System

 - **Amethyst version**:
0.12.0
 - **macOS version**:
10.13.4

**Comment by ianyh** [comment]
That sounds feasible, but would be a new layout and would need to be implemented on its own.

**Comment by ianyh** [comment]
#1083
