### ISSUE TITLE
Amethyst-latest.zip is 404

### ISSUE THREAD

**Issue by kennethgillen** [ianyh/Amethyst#711]
## System
n/a

## What's the problem?
http://ianyh.com/amethyst/versions/Amethyst-latest.zip as [linked to from top level repo README](https://github.com/ianyh/Amethyst/blame/development/README.md#L17) is currently 404ing. 
 
## How can it be reproduced?
```
2018-05-18 10:25 kenny$ curl -v http://ianyh.com/amethyst/versions/Amethyst-latest.zip 2>&1 >
/dev/null | grep HTTP
> GET /amethyst/versions/Amethyst-latest.zip HTTP/1.1
< HTTP/1.1 404 Not Found
```

**Comment by ianyh** [comment]
Thanks for catching this.
