### ISSUE TITLE
Option to switch to last focused window?

### ISSUE THREAD

**Issue by bpourriahi** [ianyh/Amethyst#722]
Is there a way to change focus to the previous window with a single keystroke?

The use case is to repeatedly change focus between two specific windows.

Hope this question is ok here - appreciate the awesome work!

**Comment by mutantcornholio** [comment]
What's the problem with cmd-tab?

**Comment by bpourriahi** [comment]
Nothing. :D Just thought there might be an Amethyst way. 

Thanks for answering.
