### ISSUE TITLE
can't seem to ignore apps on latest beta build

### ISSUE THREAD

**Issue by tuananh** [ianyh/Amethyst#723]
## System

 - **Amethyst version**: 0.12.1b (59)
 - **macOS version**: Mojave 10.14 Beta (18A293u)

## What's the problem?

Ignore window option doesn't seem to work

## dotfile (if you have one)

```
{

}
```

**Comment by tuananh** [comment]
it seems the option is in reversed.

if i choose "always float except those listed", it will work

**Comment by wbowling** [comment]
Same thing happening for me with 0.12.1b (59) on High Sierra 10.13.4. Changing to `except those listed` will float every window and the other option is floating none, the list seems to be ignored

**Comment by tuananh** [comment]
@wbowling yeah it works for awhile for me and then stop working again.

**Comment by fullmetalsheep** [comment]
A small screencast showing whats happening. 

In my case, 'Automatically float all applications except those listed' does not have any effect whatsoever, whereas 'Automatically float applications listed' works.

I'm on OSX 10.13.5, if that helps.

![2018-06-20 23 32 12](https://user-images.githubusercontent.com/23723926/41668918-0f13f4ce-74e3-11e8-9165-87252ac77d23.gif)
