### ISSUE TITLE
Feature Request: Can Amethyst reflect changes without relaunching?

### ISSUE THREAD

**Issue by fullmetalsheep** [ianyh/Amethyst#724]
## System

 - **Amethyst version**:
Any
 - **macOS version**:
Any

## What's the problem?
It gets quite cumbersome to relaunch amethyst to reflect small changes, i.e: blacklist items. Is there any chance that Amethyst would be able to reflect on changes on real time, without having to relaunch?

Thanks :)

**Comment by ianyh** [comment]
I think layouts are the only thing that don't take effect without relaunching. Are there specific options that aren't working? If so, I think that is a bug with those options.

**Comment by fullmetalsheep** [comment]
Thanks for your quick response,

Yes from what I've noticed, its the 'Floating' apps list that isn't working. In my case, 'Automatically float all applications except those listed' does not have any effect whatsoever, whereas 'Automatically float applications listed' works. However, it still requires a relaunch of amethyst.
