### ISSUE TITLE
Dock is ignored when mounted to sides

### ISSUE THREAD

**Issue by mboevink** [ianyh/Amethyst#729]
## System

 - 0.12.0 (57)
 - 10.13.5:

## What's the problem?
When the dock is mounted to one of the screens sides, the tiling manager puts the window under it.

## How can it be reproduced?
Using fullscreen mode, set the dock to either left or right of the screen.

## What applications are involved?
Any

<img width="1110" alt="screen shot 2018-06-25 at 08 29 16" src="https://user-images.githubusercontent.com/3157750/41824333-ed8b35c0-7851-11e8-80de-fcb0e657b531.png">

Cheers

**Comment by ianyh** [comment]
By fullscreen mode do you mean the macOS fullscreen mode or the Amethyst fullscreen layout?

**Comment by mboevink** [comment]
Apologies - I mean any time Amethyst changes the window size to 100% regardless of column, fullscreen, wide etc mode.

**Comment by ianyh** [comment]
Got it. This seems to be working for me. It looks like you're on macOS 10.14. Maybe something changed. I'm going to upgrade my laptop to 10.14 soon and I'll test it again then.

**Comment by ianyh** [comment]
Oh, actually you said in the ticket that you're on 10.13.5. I'll give this a bit more thought.

**Comment by mboevink** [comment]
I'm still using 10.13.5, just with the dark theme enabled. Are you sure you have tried moving the dock to one of sides?

**Comment by ianyh** [comment]
Yeah. It works every time for me on the left. It works sporadically on the right. It seems like reflow events are triggering for the Dock changes, but we ignore some small changes to account for some macOS window sizing peculiarities so it's possible that the frame changes from the Dock are being ignored as a result of that.

**Comment by ianyh** [comment]
Oh wait, do you have `Ignore menu bars` enabled in preferences? That ignores the Dock.

**Comment by mboevink** [comment]
Legend! Thank solved it, thank you.

**Comment by ianyh** [comment]
I can't believe I didn't think of it sooner. 😅
