### ISSUE TITLE
Restore window layout after restart

### ISSUE THREAD

**Issue by mutantcornholio** [ianyh/Amethyst#730]
If I restart Amethyst (or if Amethyst crashes :D), window layout resets to "fullscreen" on each display.

Maybe it should drop layout config for each desktop on disk and load it on start?

**Comment by ianyh** [comment]
Duplicate of #151

**Comment by mutantcornholio** [comment]
Oh, totally. Sorry.

**Comment by ianyh** [comment]
No worries.
