### ISSUE TITLE
eclipse is not tiled in mac

### ISSUE THREAD

**Issue by alburthoffman** [ianyh/Amethyst#737]
## System

 - **Amethyst version**:
0.12.0

 - **macOS version**:
macOS High Sierra
Version 10.13.6

## What's the problem?
Eclipse (Photon Release 4.8.0) is not able to be tiled. no matter which layout u choose. 

## How can it be reproduced?
install Eclipse (Photon Release 4.8.0) and try different layouts in Amethyst

## What applications are involved?
Eclipse (Photon Release 4.8.0)

## Has anything fixed it, even temporarily?
nope.

**Comment by alburthoffman** [comment]
Not sure if any other users meet this and how they got it fixed?

**Comment by ianyh** [comment]
It has historically had trouble with java apps. See #379. I can try to reproduce this, but I don't have eclipse.

**Comment by alburthoffman** [comment]
yeah. restart Amethyst will work
