### ISSUE TITLE
Hiding window with cmd+h breaks tiling for this window when reappearing.

### ISSUE THREAD

**Issue by uloco** [ianyh/Amethyst#741]
## System
 - **Amethyst version**:
0.21.1 (61)
 - **macOS version**:
10.13.6 (17G65)

## What's the problem?
After pressing `cmd+h` to hide a window (not minimize), the window is hidden and the remaining windows are tiled correctly. But after opening the closed window with `cmd+tab` the windows do not get rearranged. Forcing with `cmd+z` works though.

**Comment by ianyh** [comment]
I thought there was already an issue for this, but I can't find it. 😮

**Comment by alburthoffman** [comment]
might be something broken?

I'm running Amethyst 0.12.0(57) in macOS 10.13.6, and tried the steps above. Amethyst works as expected.

**Comment by uloco** [comment]
Here a gif to show what is happening. It happens with any application on my machine.

![aug-27-2018 11-53-58](https://user-images.githubusercontent.com/8818340/44653747-dc1d8480-a9ef-11e8-9a3e-20a2f656b83e.gif)

**Comment by ianyh** [comment]
Thanks for the gif! That’s pretty neat.

Yeah, I thought I had fixed the hiding thing, but it might have regressed or I may have missed it somewhere.

**Comment by AlecBenzer** [comment]
> Forcing with `cmd+z` works though.

For me it seems not even "Force windows to be reevaluated" fixes it. I need to minimize (not hide) the window and restore it to get Amethyst to "find" it again.

**Comment by stevencorona** [comment]
I'm also having this issue. Has anyone found a work-around besides minimizing?

**Comment by ianyh** [comment]
Switching between spaces would also fix it as a workaround.

**Comment by ianyh** [comment]
I think #662 is the root cause of this.
