### ISSUE TITLE
Feature Request: layouts restore when restarting

### ISSUE THREAD

**Issue by alburthoffman** [ianyh/Amethyst#743]
When restarting system or Amethyst, it will start from the first layout in the configuration again.
since Mac will try reopening the applications, the screen becomes a little messy.

Do we have any plan to support this? if yes but without resources, I think I can contribute with it. Thx

**Comment by ianyh** [comment]
It's planned, but I haven't had time for it. This would be a good place to contribute. Duplicate of #151
