### ISSUE TITLE
Unable to float windows by title if the title is set after the window is created

### ISSUE THREAD

**Issue by nicolasmartin3d** [ianyh/Amethyst#748]
## System

 - **Amethyst version**: 0.12.2b2
 - **macOS version**: 10.13.6

## What's the problem?
Unable to float windows by window title when said window is created by a shell (e.g iTerm).
I don't know if it is a bug or un an unsupported feature.

**Comment by ianyh** [comment]
Does it work for other windows?

**Comment by nicolasmartin3d** [comment]
I don't know, I never had the need for such a feature besides for windows created by the terminal.

**Comment by nicolasmartin3d** [comment]
I tried to test this, but actually, it seems I can't enter window title for any applications besides the first one .. it seems to be a different bug ?

**Comment by ianyh** [comment]
Okay. Thanks for the report.

**Comment by arfoll** [comment]
Having the same issue - I can't float my android emulator since it seems to have no valid bundleID:

```

51) "qemu-system-x86_64" ASN:0x0-0x139139:
    bundleID=[ NULL ]
    bundle path=[ NULL ]
    executable path="/Volumes/brendan_SC480/android/prebuilts/android-emulator/darwin-x86_64/qemu/darwin-x86_64/qemu-system-x86_64"
    pid = 27399 type="Foreground" flavor=2 Version=[ NULL ]  fileType="????" creator="????" Arch=x86_64
    parentASN="iTerm2" ASN:0x0-0xf00f:  (inferred)
    checkin time = 2018/09/13 13:27:16 ( 7 minutes, 28.5727 seconds ago )
```

**Comment by dapicester** [comment]
Is this released yet? I still experience this problem with version `0.14.3 (79)` from homebrew cask.

**Comment by ianyh** [comment]
The solution is heuristic. Please open a separate issue with specifics.

**Comment by dapicester** [comment]
@arfoll Please see my https://github.com/ianyh/Amethyst/issues/795#issuecomment-632463954 in the other issue, I've been able to float the android emulator.
