### ISSUE TITLE
Focusing on the wrong window, when switching screen

### ISSUE THREAD

**Issue by hotpxl** [ianyh/Amethyst#753]
## System

 - **Amethyst version**: 0.12.1 (61)
 - **macOS version**: 10.13.6 (17G2208)

## What's the problem?
When I switch between screens, and when I switch to a screen using Tall layout, I expect to focus on the main window, but sometimes it focuses on another one.

It happens undeterministically.

## How can it be reproduced?
1. Using Tall layout, open a couple of windows, make sure only one window is in the main pane, the rest is stacked on the right.
2. Switch to another screen using shortcut
3. Switch back to the screen using shortcut

Now sometimes the focus is on the wrong window, instead of the main one, it focuses on some window that's stacked.

## What applications are involved?
Often it would lose focus on Chrome and instead focus on Slack. But that's my experience. I don't use a lot of different apps.

## Has anything fixed it, even temporarily?
Nope. Restart Amethyst alleviates the issue.

**Comment by ianyh** [comment]
At some point we started tracking the last focused window on a screen, so switching to a different screen would not necessarily always focus the main window.

**Comment by hotpxl** [comment]
Ok. Thanks for the explanation!
