### ISSUE TITLE
Focus Follows Mouse not working with Google Chrome 69+

### ISSUE THREAD

**Issue by qayshp** [ianyh/Amethyst#754]
## System

 - **Amethyst version**: 0.12.2b3 (64)
 - **macOS version**: 10.13.6

## What's the problem?
FFM no longer switches to Google Chrome windows in Chrome 69+.
If a Chrome window is focused, and you hover over another Chrome window, focus is not moved.
If you are focused on another app and hover over a Chrome window, focus is not moved.
If you have Chrome focused and hover over a window from another app, focus leaves Chrome and you must use a click or the keyboard to move it back.
 
## How can it be reproduced?
Install latest stable Google Chrome and beta release of Amethyst.

## What applications are involved?
Google Chrome v69+

## Has anything fixed it, even temporarily?
Nope.

## dotfile (if you have one)
Nope.

## Screenshots
Nope.

**Comment by zacharydenton** [comment]
I discovered a workaround:

1. Go to <chrome://flags/#views-browser-windows>
2. Change the "Use Views browser windows instead of Cocoa" setting to Disabled.
3. Relaunch Chrome

**Comment by qayshp** [comment]
Thanks! Tried that and it works like a charm again!

Any idea if we should report this as an issue with the feature in Google Chrome, or work on it here, or both?

**Comment by ianyh** [comment]
I think this is probably an Amethyst bug, but I haven’t had a chance to dig in yet.

**Comment by vespakoen** [comment]
The suggested workaround doesn't work anymore, anyone aware of a new workaround for the latest stable google chrome?

**Comment by zacharydenton** [comment]
It looks like the code has been completely removed from Chrome (last update - Jan 9 2019): https://bugs.chromium.org/p/chromium/issues/detail?id=832676

@ianyh Perhaps the CRs linked in that bug provide a hint toward fixing this?

**Comment by ianyh** [comment]
On further investigation the issue actually seems to be window titles not matching. `CGWindowListCopyWindowInfo` reports tab names, but accessibility reports tab names followed with ` - Google Chrome`.
