### ISSUE TITLE
"Automatically float all applications except those listed" still tiles all applications

### ISSUE THREAD

**Issue by bradleyjkemp** [ianyh/Amethyst#758]
## System

 - **Amethyst version**: 0.12.2b3 (64)
 - **macOS version**: 10.13.6

## What's the problem?
I've set up in options to float all applications except listed and put an empty list of exceptions, however all my windows are still tiled automatically.

## How can it be reproduced?
Switch to "Automatically float all applications except those listed", do not put any exceptions in the list.

## What applications are involved?
All applications I try.

## Has anything fixed it, even temporarily?
Nope, tried relaunching to no effect.

## Screenshots
![image](https://user-images.githubusercontent.com/9093713/47082115-8baef000-d204-11e8-8bd2-bc5a266e5c25.png)

**Comment by ianyh** [comment]
I think the logic only activates if there is at least one thing listed—it started out as only a blacklist and whitelisting was added later. If you put something in as an app identifier that won’t be matched like `-` or something it might start working, but it seems reasonable that we should handle the empty list as valid for a whitelist.

**Comment by bradleyjkemp** [comment]
Hmm that's odd. I tried your suggestion but had the same behaviour of everything being tiled. Then when I re-opened the preferences the list of applications supposed to be tiled had doubled (every element in the list was now there twice).

**Comment by ianyh** [comment]
Fun. It's not an ideal solution, but does relaunching Amethyst fix it? Some preferences won't take effect until the app is relaunched.

**Comment by bradleyjkemp** [comment]
Nope :(
Now got the following option (and have relaunched) but still everything gets tiled:
![image](https://user-images.githubusercontent.com/9093713/47086587-d71bcb00-d211-11e8-93b3-c9ce2e5c4b1f.png)

**Comment by ianyh** [comment]
Alright, I'll have to dig a little deeper to see what's going on then.

**Comment by indigoviolet** [comment]
confirmed for me too
