### ISSUE TITLE
3-column layouts don't honor mouse-based window resizes of secondary/tertiary windows

### ISSUE THREAD

**Issue by ianfixes** [ianyh/Amethyst#759]
## System

 - **Amethyst version**: `v0.12.2b3`
 - **macOS version**: `10.13.6 (17G65)`

## What's the problem?
Resizing a secondary/tertiary window in the new 3-column layout implementation sets the width for the secondary + tertiary windows _combined_.  In other words, after you complete the resize operation the secondary + tertiary windows jump to 1/2 of what you desired.

Main-window resizing is unaffected

## How can it be reproduced?

1. open 3 windows
2. choose any of the new 3-column layouts
3. resize one of the non-main windows

## Screenshots

![oct-17-2018 07-25-03 amethyst 3 column bug](https://user-images.githubusercontent.com/583459/47083439-90f94400-d1de-11e8-9ea8-e098163f689e.gif)

Sorry for not capturing the mouse pointer in that gif :(

**Comment by ianyh** [comment]
Oh that’s a good catch. Seems kind of tricky to handle, right?

**Comment by ianfixes** [comment]
It's not too tricky to handle, it's just that when the 3-column view got refactored the `scaleFactor` code was broken

**Comment by ianfixes** [comment]
For posterity, I have an interesting technique for mouse-based resizes: I added a `ResizeRules` struct to frame assignments.  All this does is say "this is whether I'm the main window, and this is the scale factor that made me this size".  That way, if the window gets resized, I can just do the reverse calculation on the old & new sizes plus the old scaleFactor to get the new scaleFactor.

So all you need to do is apply the proper scaleFactor during frame assigment... in this case, it was being set unconditionally to that of the main window (which is twice as large as the others) https://github.com/ianyh/Amethyst/blob/216da9b468ecf357c4b053ba772156877e414619/Amethyst/Layout/ThreeColumnLayout.swift#L174
