### ISSUE TITLE
How to float Chrome apps?

### ISSUE THREAD

**Issue by tuananh** [ianyh/Amethyst#781]
## System

 - **Amethyst version**: 0.12.2 (66)
 - **macOS version**: 10.14.1

## What's the problem?

Adding Chrome apps to floating list doesn't work

## dotfile (if you have one)

```
{

}
```

**Comment by ianyh** [comment]
Can you give an example of an app to test?

**Comment by tuananh** [comment]
You can try this https://chrome.google.com/webstore/detail/authy-chrome-extension/fhgenkpocbhhddlgkjnfghpjanffonno?hl=en

**Comment by loadedsith** [comment]
I made my way here looking for a way to exempt this one extension window in Chrome:

https://chrome.google.com/webstore/detail/fast-tab-switcher/jkhfenkikopkkpboaipgllclaaehgpjf

**Comment by ianyh** [comment]
I actually tested this with window titles and Fast Tab Switcher. When the window is first created the title is empty. 😱

**Comment by ianyh** [comment]
So I think this duplicates #748.
