### ISSUE TITLE
Error: Calling the `accessibility_access` stanza is disabled! There is no replacement.

### ISSUE THREAD

**Issue by WarmlindAlbin** [ianyh/Amethyst#783]
## System

 - **Amethsyt version is none since it isn't installed**:
 - **Latest macOS Mojave**:

## What's the problem?
I can't install Amethyst. I copy and paste the `brew  cask install amethyst` and it gives me this: 

Error: Calling the `accessibility_access` stanza is disabled! There is no replacement.
Please report this to the homebrew/cask tap:
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/amethyst.rb:21

## How can it be reproduced?
Type in the command `brew  cask install amethyst`. I haven't touched anything else.
## What applications are involved?
Amethyst
## Has anything fixed it, even temporarily?
No.

## Screenshots
![terminal](https://user-images.githubusercontent.com/43311141/50606850-75413800-0ec7-11e9-9a22-050669f97e90.png)

**Comment by ianyh** [comment]
Looks like the stanza was removed already in https://github.com/Homebrew/homebrew-cask/pull/53066, but the cask wasn't updated to a new version until December. Maybe you have an out of date cask room? What does `brew cask info amethyst` give you?

**Comment by ianyh** [comment]
Going to close this as I think the cask is correct now.
