### ISSUE TITLE
Default layout on start

### ISSUE THREAD

**Issue by bpatram** [ianyh/Amethyst#787]
## System

 - **Amethyst version**: 0.12.2 (66)
 - **macOS version**: 10.14.2

## What's the problem?
Feature suggestion! When I start Amethyst (or restart after it crashes) it'll rearrange my windows to the first layout option in the list (or whatever I set last). Sometimes this is quite frustrating as I have 3 monitors and it's quite jarring to have all my windows be re-arranged immediately without my control.

I'd love to be able to make Amethyst start in a default layout each time (in my case I would set the default to floating as not to affect my active windows), then later use hotkeys to switch to a suitable layout when needed.

There are a number of other requests similar to this, however those are requesting more complex logic based on screen dimensions or specific spaces (#293, #302, #150). 

## How can it be reproduced?

1. Start Amethyst and let it rearrange your windows. 
1. Close Amethyst then rearrange your windows into something unique. 
1. Start Amethyst and see all windows rearrange to first/last set layout.

## What applications are involved?
N/A 

## Has anything fixed it, even temporarily?
N/A

## dotfile (if you have one)

```
{

}
```

**Comment by ianyh** [comment]
It sounds like #151 would solve this.
