### ISSUE TITLE
Can Amethyst remember Layout on re-launch?

### ISSUE THREAD

**Issue by pale2hall** [ianyh/Amethyst#789]
## System

 - **Amethyst version**: 0.120.0 (I'm not on 0.12.2 because it doesn't seem to work on my system at all)
 - **macOS version**: 10.14.3
## Monitor Setup
- closed 2018 MacBook Pro
- 1080p HDMI monitor
- 4k DP monitor
-1080p HDMI Monitor ( 90deg Rotated )

## Can Amethyst remember layout on re-launch?

Is there any way, or plans, to allow Amethyst to remember which layout I prefer for each monitor when I relaunch it?  I relaunch fairly often due to tiny bugs, **I'm not complaining**, but It would be nice if Amethyst went back to Rows on my Vertical monitor, for example.

**Comment by Slus** [comment]
I would also like this as I move with my laptop a lot and unplug my monitors often. Thanks!

**Comment by pale2hall** [comment]
Actually, if there is a way to apply a layout via a shell script that would be enough.  I could make a little launcher for it, and click it to re-apply my 'work layout'.

**Comment by sixty4k** [comment]
https://github.com/ianyh/Amethyst/issues/151

**Comment by pale2hall** [comment]
> #151

Good connection.  I searched, but didn't find that open issue before opening mine.

**Comment by ianyh** [comment]
Going to close this as a duplicate.
