### ISSUE TITLE
Unable to remove an app from the "floating" list

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#799]
## System

 - **Amethyst version**: 0.12.2
 - **macOS version**: 10.14.3 

## What's the problem?

Unable to remove an app from the "floating" list

## Screenshots

<img width="308" alt="screenshot_2249" src="https://user-images.githubusercontent.com/6774346/53684742-29e8b180-3cdf-11e9-9914-6996977107fd.png">

**Comment by ianyh** [comment]
That button is to add/remove window titles, not applications. There are buttons in the bottom left of the list of app ids for adding/removing apps.

**Comment by mwoffenden** [comment]
Not so fast ... the buttons are there but there's a positioning issue:

<img width="308" alt="screenshot_2251" src="https://user-images.githubusercontent.com/6774346/53703938-2b040680-3de5-11e9-871b-ac43330dba1f.png">

**Comment by ianyh** [comment]
Is the issue that they aren’t functional or that they are hard to see because of the number of entries?

**Comment by mwoffenden** [comment]
They function but the picture clearly shows them placed incorrectly from a UI perspective.

**Comment by ianyh** [comment]
Yeah, that makes sense. Could you open a separate issue for that, though?
