### ISSUE TITLE
Support for horizontal window resizing, not just vertical

### ISSUE THREAD

**Issue by gprimosch** [ianyh/Amethyst#82]
One feature I would like is to be able to proportionally resize a window within the left or right columns. 

Example:
I have two windows in my left (primary) column, each taking 50% of the space. 
I then press mod2 + j to resize the focused window to be 70% of the column.

Likewise, if I have three windows open in my right (secondary) column, they start out as each having 33% of the window. After pressing mod2 + j, I resize the top one to be 50%, so the remaining two windows have 25% each.

[Trello Card](https://trello.com/c/SrfCUoBR/28-amethyst-support-for-horizontal-window-resizing-not-just-vertical)

**Comment by Fandekasp** [comment]
This is a feature I would very much like to see as well. Coming from i3, this missing feature is perturbing :)

**Comment by vespakoen** [comment]
This is what I miss most from using xmonad on linux, would love to see this happen!

**Comment by ifreecarve** [comment]
There doesn't seem to be a data structure in place for subdividing the areas, just a single "ratio" as defined by the protocol.

As an attempt, here is a snippet that I considered during development of #627 (but was eventually scrapped in favor of the `ResizeRules` struct).

```swift
/*
 A tiling window manager must have some concept of constraint:
  a "primary" frame boundary bisects the entire screen, with
  successive boundaries bisecting less than or equal distances
  (e.g. BSP would bisect the full screen, 1/2, then 1/4...
   but a column layout would bisect full, full, full, etc)

 This data set captures the "rank" of a frame, and each constraint.
  - a "primary" frame on a layout like "Tall" will be [horizontal]
  - a "secondary" frame on a layout like "Tall" will be [horizontal, vertical]
  - a "secondary" frame on a layout like "Column" will be [horizontal, horizontal]
  - a "tertiary" frame on a layout like "Middle" will be [nil, horizontal, horizontal]

 Note that in practice, the only values that matter are the max-indexed horizontal
 and vertical values. Hence, values are optionals.
   i.e. [horizontal, horizontal, horizontal] equates to [_, _, horizontal]
        [vertical, vertical, horizontal, horizontal] -> [_, vertical, _, horizontal]

 Additionally, we include the number of frames in that frame rank -- there may be multiple
 primary or secondary or tertiary frames sharing the same space.
 */
typealias FrameConstraint = (unconstrainedDimension: UnconstrainedDimension?, frameCount: Int)
typealias RankedConstraintList = [FrameConstraint]

```

**Comment by afincato** [comment]
+1 for adjusting height of tiles!

**Comment by Mcilie** [comment]
bump

**Comment by albingroen** [comment]
Would definitely love to see this feature as well!

**Comment by erdostom** [comment]
Would love to see this!

**Comment by andreasvirkus** [comment]
Big ➕

**Comment by paolomainardi** [comment]
Well, a big ➕ by me too, coming from i3 it seems an essential feature to have, are there any workaround ?

**Comment by vespakoen** [comment]
Yabai supports this feature (https://github.com/koekeishiya/yabai)

**Comment by paolomainardi** [comment]
Thanks a lot @vespakoen i'll give it a try!

**Comment by vespakoen** [comment]
Here is my (old) config that mimics monad a bit in case it's useful: https://github.com/koekeishiya/yabai/issues/295

**Comment by ianyh** [comment]
I think this should be possible now with #1134.

**Comment by majjoha** [comment]
Has anyone had success implementing this using a custom layout? Bonus points if you are using a tall layout for it.

**Comment by ianyh** [comment]
For what it's worth, I think this is a case for a more fully featured binary space partitioning, which _is_ possible with a custom layout, but yabai is bsp out of the box.

It would be interesting if someone did do full bsp as a custom layout, but I think I will close this as it is probably outside of the scope of the native app.

**Comment by mkalpakis** [comment]
Is there any plan to make a place to collect user-created custom layouts? I am interested in a fully featured binary space partitioning, but don't have the understanding to make one myself, nor can I find any configs that others have made, that I can at least slightly modify.

**Comment by ianyh** [comment]
I don't have any current plans, but I could be convinced by a critical mass.
