### ISSUE TITLE
Question: How to use .amethyst file floating 

### ISSUE THREAD

**Issue by MarioRicalde** [ianyh/Amethyst#827]
I found the default file which I added to my home directory, I have confirmed it loads.

I'm wondering if I can define Applications directly into the `floating` array so that it's portable across devices?

**Comment by ianyh** [comment]
The `floating` array takes a list of bundle IDs, which are portable across devices.

**Comment by ianyh** [comment]
This comment describes how to get the bundle ID. https://github.com/ianyh/Amethyst/issues/410#issuecomment-194809978
