### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by ulope** [ianyh/Amethyst#829]
## System

 - **Amethyst version**: 0.13.0
 - **macOS version**: 10.14.4

## What's the problem?

Amethyst frequently (a few times a week) crashes and needs to be restarted manually.

## How can it be reproduced?

Unsure, normal usage. 
Although, sleep / wake and connecting / disconnecting external displays seem to trigger it sometimes.

## What applications are involved?

No specific ones.
Default set I use most days:
- Safari
- PyCharm
- Sublime Text
- iTerm2

## Has anything fixed it, even temporarily?

Restarting brings it back to life until the next crash

## Crash reports

https://gist.github.com/ulope/74b157c5898b22b499b60a190b83a9da

**Comment by ianyh** [comment]
I think this category of crashes should be fixed by the most recent version. If you encounter more on 0.14.0+ please open another issue.
