### ISSUE TITLE
Creative Cloud Apps like Photoshop and Premier don't respond to Amethyst

### ISSUE THREAD

**Issue by pale2hall** [ianyh/Amethyst#831]
## System

 - **Amethyst version**: 12 and 14
 - **macOS version**: 10.14.5 (And Earlier)

## What's the problem?
Can't resize Adboe Creative Cloud apps like Photoshop and Premier

## How can it be reproduced?
Self explanatory.

## What applications are involved?
See Above

## Has anything fixed it, even temporarily?
Not that I've seen.

**Comment by ianyh** [comment]
Debugging note: looks like the windows have a subrole of `AXFloatingWindow`.

**Comment by ianyh** [comment]
This seems to have been fixed. Lightroom, at least, works fine.
