### ISSUE TITLE
Activate tiling for only some screens?

### ISSUE THREAD

**Issue by mwoffenden** [ianyh/Amethyst#834]
## System

 - **Amethyst version**: 0.14.0
 - **macOS version**: 10.14.5

## What's the problem?

Want to be able to activate tiling only on selected screens.  In my use case, I need tiling (sometimes, but not always) on just the main screen -- but not a second or third screen.  

This new feature should also have a simple toggle to turn tiling on or off by screen.

**Comment by voltaireodactyl** [comment]
Came here just to request this. as well. Would make Amethyst perfect for me at least!

**Comment by kiryph** [comment]
Afaik, layouts are stored per screen. What about using the layout 'Floating' for those screens?

**Comment by ianyh** [comment]
Yeah, I think using the Floating layout is the solution here.

**Comment by mwoffenden** [comment]
Actually, this the floating layout is not the solution.  The actual request is to disable tiling for an entire screen, and this is a very different use case.

**Comment by ianyh** [comment]
Using the floating layout for a screen disables tiling for the entire screen. Am I missing something?

**Comment by mwoffenden** [comment]
How would I use the floating layout for a screen?  I do not see that in preferences.

**Comment by ianyh** [comment]
It’s just another layout. Add it to your list of layouts and then switch to that layout on that screen.

**Comment by mwoffenden** [comment]
I thought that layouts applied to all screens.  Would you explain precisely (step by step) how I would switch to a layout on a screen?

**Comment by ianyh** [comment]
If you bring the mouse cursor on to a screen and cycle the layout it will change the layout for that particular screen.

**Comment by mwoffenden** [comment]
This is not, however, the same as turning **off** tiling for a certain screen -- which is what I need.

**Comment by ianyh** [comment]
Changing a screen to the full screen layout will prevent windows from being tiled.

**Comment by mwoffenden** [comment]
Ok, will try that.

**Comment by mwoffenden** [comment]
It didn't work.  On screen 2 I tried to set the layout to floating.  But when I relaunched the app, everything tiled again across both screens.

What I need is the following:

1. On screen 1 have tiling ON.
2. On screen 2, tiling is completely disabled.

**Comment by ianyh** [comment]
Relaunching the app resets the layout selections.

**Comment by mwoffenden** [comment]
Is it possible that a future release would allow users to persist layout selections (per screen)?

**Comment by ianyh** [comment]
Yes. #151
