### ISSUE TITLE
Switching to space clarification

### ISSUE THREAD

**Issue by mr337** [ianyh/Amethyst#835]
## System

 - **Amethyst version**: 0.14.0
 - **macOS version**: 10.14.5

## What's the problem?
Unable to switch to space/desktop via shortcuts.

Reading the doc unclear if Amethyst is able to move to different Desktops. I assume so but have not been able to get it to switch desktops.

I see that I can focus to screens but unclear if that is different from desktops or spaces. New mac user here.

I am able to throw windows to a space no problem so I believe the spaces support is correct. I can map moving to a desktop to get the same effect outside of Amethyst but break throwing a window to a space per the docs.

## How can it be reproduced?
1. Install Amethyst
2. Enable accessibility
3. Enable shortcuts of ctrl + n
4. Can't move to spaces

## What applications are involved?
Any

## Has anything fixed it, even temporarily?
Sadly not :(

## dotfile (if you have one)
NA

## Screenshots
<img width="1329" alt="Screen Shot 2019-06-04 at 5 48 35 PM" src="https://user-images.githubusercontent.com/413937/58918705-032c8380-86f1-11e9-8a88-647f70744682.png">

**Comment by ianyh** [comment]
Amethyst itself does not provide any commands for moving spaces, but you can use the system ones to do so. You may also be interested in the discussion in #845.
