### ISSUE TITLE
Check for update still stays on 0.13.0

### ISSUE THREAD

**Issue by binarious** [ianyh/Amethyst#837]
## System

 - **Amethyst version**: 0.13.0
 - **macOS version**: 10.14.5

## What's the problem?
"Check for update" should provide version 0.14.0, but still says "Amethyst 0.13.0 is currently the newest version available.". 0.14.0 is on GitHub since 10 days.

**Comment by Jc2k** [comment]
Just noticed this here too

**Comment by jkdf2** [comment]
[Website also](https://ianyh.com/amethyst/) lists 0.13.0.

**Comment by ianyh** [comment]
Fixed by https://github.com/ianyh/ianyh.github.io/commit/ca4438e7f02efe95eab9321fe76fdf9f29f09190
