### ISSUE TITLE
Still crashing

### ISSUE THREAD

**Issue by ulope** [ianyh/Amethyst#839]
## System

 - **Amethyst version**: 0.14.0 (72)
 - **macOS version**: 10.14.4

## What's the problem?
Amethyst still crashes pretty often in what feels to be the same way as described in #829.

## Crashlog:

https://ds.ulo.pe/LvODIZIr5M.crash

**Comment by tom-wolters** [comment]
I love this app, so first of all - thank you for creating it. 
I experience these crashes also, most often when the CPU is maxed out it seems Amethyst crashes due to memory issues or something

**Comment by ulope** [comment]
@ianyh Does it help to submit more crash logs or is the one above sufficient?

**Comment by mabunday** [comment]
As a workaround to this issue I created a LaunchAgent script that restarts Amethyst if it's killed. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>com.mabunday.keepAmethystAlive</string>
    <key>RunAtLoad</key>
    <true />
    <key>KeepAlive</key>
    <true />
    <key>ProgramArguments</key>
    <array>
      <string>/Applications/Amethyst.app/Contents/MacOS/Amethyst</string>
    </array>
  </dict>
</plist>
```

**Comment by ianyh** [comment]
I think this specific crash is now fixed by #847 and out in the 0.14.1 beta. Others should get opened as separate issues.

**Comment by ianyh** [comment]
@ulope more crash logs are generally a good idea. The logs I've gotten are actually not all the same crash.

**Comment by srnnkls** [comment]
> As a workaround to this issue I created a LaunchAgent script that restarts Amethyst if it's killed.

Better this way:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>com.amethyst.keepalive.plist</string>
		<key>RunAtLoad</key>
		<true />
		<key>KeepAlive</key>
		<dict>
			<key>SuccessfulExit</key>
			<false/>
		</dict>
		<key>Program</key>
		<string>/Applications/Amethyst.app/Contents/MacOS/Amethyst</string>
	</dict>
</plist>
```

This allows the user to manually quit Amethyst e.g. for updates.
