### ISSUE TITLE
GNUCash application doesn't resize at all

### ISSUE THREAD

**Issue by 53SWYj3cV8nKsSr** [ianyh/Amethyst#846]
## System

 - **Amethyst version**: 0.14.0
 - **macOS version**: 10.14.5

## What's the problem?
The GNUCash application doesn't resize when its opened. It seems like Amethyst doesn't even know it's there.

## How can it be reproduced?
Download the macOS version of GNUCash using `brew cask` or head over to GNUCash's github and download the latest macOS release version. Then just open the application and the problem should occur.

## What applications are involved?
GNUCash

## Has anything fixed it, even temporarily?
No, I haven't found anyway to fix it.

## dotfile (if you have one)
N/A

## Screenshots
N/A

**Comment by ianyh** [comment]
I think GNUCash is X11. See #196.
