### ISSUE TITLE
Current layout name is shown even for fullscreen apps

### ISSUE THREAD

**Issue by Jabher** [ianyh/Amethyst#849]
## System

 - **Amethyst version**:
0.14.0
 - **macOS version**:
10.14.5
## What's the problem?
When swiping between workspaces, current layout name is shown even when app is working in fullscreen mode.
## How can it be reproduced?
swipe between fullscreen apps
## What applications are involved?
any, currently - Chrome, IntelliJ IDEA
## Has anything fixed it, even temporarily?
no

**Comment by ianyh** [comment]
Duplicate of #559
