### ISSUE TITLE
closed windows are sometimes not detected

### ISSUE THREAD

**Issue by simon-weber** [ianyh/Amethyst#85]
I can replicate this by:
- opening chrome
- opening iterm2 (iterm2 now has focus)
- closing my iterm session with ^d (iterm2 window closes)

After doing this, I expect chrome to have focus, but it does not. Doing one clockwise switch gives chrome focus, making it seem that Amethyst thought iterm2 was still supposed to have it. Doing another switch keeps focus on chrome.

[Trello Card](https://trello.com/c/FURmgHGl/30-amethyst-closed-windows-are-sometimes-not-detected)

**Comment by ianyh** [comment]
Closing. See https://github.com/ianyh/Amethyst/pull/591
