### ISSUE TITLE
No longer working after setting blacklist apps

### ISSUE THREAD

**Issue by alexymik** [ianyh/Amethyst#855]
## System

 - **Amethyst version**: 0.14.1b
 - **macOS version**: 10.14.5 (18F132)

## What's the problem?

After years of mostly uneventful use, I added my IDE (JetBrains) to the application blacklist.

After doing so, Amethyst will no longer recognize or resize windows. I tried clearing out the blacklist and reinstalling but can't get it to recognize any windows.

## How can it be reproduced?

Unsure; try adding applications to the blacklist.

## What applications are involved?

Amethyst, RubyMine, PHPStorm

## Has anything fixed it, even temporarily?

Tried reinstalling and a few other misc troubleshooting items. Can't get it working again.

**Comment by ianyh** [comment]
@alexymik do you still need help setting this up?

**Comment by ianyh** [comment]
I'm going to close this. Let me know if you still have the issue.
