### ISSUE TITLE
Is it possible to rearrange the list of layouts?

### ISSUE THREAD

**Issue by taylorkline** [ianyh/Amethyst#887]
I want to rearrange the list of layouts as I cycle through. I also want Wide to be on top so that it is the default layout when Amethyst restarts.

Is it possible to rearrange, rather than deleting and adding back in your desired order?

This should be tagged as a question.

## System

 - **Amethyst version**: `0.14.2`
 - **macOS version**: `10.14.6`

## Screenshots

![Layout arrangement](https://user-images.githubusercontent.com/2641739/65175451-819b0000-da18-11e9-8629-b3b02e30b42a.png)

**Comment by ianyh** [comment]
Possible, but I didn’t want to deal with it at the time. It would be a good contribution!
