### ISSUE TITLE
Catalina: Cannot start Amethyst

### ISSUE THREAD

**Issue by bristi** [ianyh/Amethyst#893]
## System

 - **Amethyst version**: 0.14.2 (from homebrew)
 - **macOS version**: 10.15 Catalina

## What's the problem?

When trying to start Amethyst I am told "can’t be opened because Apple cannot check it for malicious software".

## How can it be reproduced?

* Install Amethyst, eg `brew install amethyst`
* Start Amethyst using Spotlight or Finder

## What applications are involved?

None

## Has anything fixed it, even temporarily?

No.

## dotfile (if you have one)

None

## Screenshots

In danish, sorry, but wording in english is described under "What's the problem" above.

<img width="419" alt="Skærmbillede 2019-10-09 kl  16 34 20" src="https://user-images.githubusercontent.com/576430/66491284-c0b9ef80-eab2-11e9-932b-9842b83c87b1.png">

**Comment by ianyh** [comment]
Can you try right clicking on the app in Finder and choosing the Open option?

**Comment by frealmyr** [comment]
Installation went fine on my Mac with Catalina 10.15, to run "unauthorized applications" you will need to manually approve it from Security settings.

![Screenshot 2019-10-16 at 12 03 46](https://user-images.githubusercontent.com/29174850/66909496-2820f380-f00d-11e9-88a1-3d7e5896d302.png)

![Screenshot 2019-10-16 at 12 03 58](https://user-images.githubusercontent.com/29174850/66909512-2ce5a780-f00d-11e9-852a-b6a76dabb2c5.png)

![Screenshot 2019-10-16 at 12 04 05](https://user-images.githubusercontent.com/29174850/66909520-2fe09800-f00d-11e9-9d36-0b2e0cefbaf9.png)

**Comment by dannyfritz** [comment]
For what it is worth, I'm on Catalina and running developer builds and haven't had a problem. However, I don't think being on the developer branch actually matters in this case.

**Comment by artem0** [comment]
This issue is also reproducible for me, probably, upgrade to Catalina broke something.

**Comment by hanung665** [comment]
> Installation went fine on my Mac with Catalina 10.15, to run "unauthorized applications" you will need to manually approve it from Security settings.
> 
> ![Screenshot 2019-10-16 at 12 03 46](https://user-images.githubusercontent.com/29174850/66909496-2820f380-f00d-11e9-88a1-3d7e5896d302.png)
> 
> ![Screenshot 2019-10-16 at 12 03 58](https://user-images.githubusercontent.com/29174850/66909512-2ce5a780-f00d-11e9-852a-b6a76dabb2c5.png)
> 
> ![Screenshot 2019-10-16 at 12 04 05](https://user-images.githubusercontent.com/29174850/66909520-2fe09800-f00d-11e9-9d36-0b2e0cefbaf9.png)

This work for me and most app which weren't signed by Apple developer. It's happened not on Catalina only but did since Mojave.

**Comment by bristi** [comment]
Works for me as well, sorry I missed this.

Just a quick question before I close this issue; what would it take for Amethyst to overcome this issue / how come "it is not from an identified developer"?

**Comment by hanung665** [comment]
Amethyst developer should register as Apple developer (paid, yearly).

**Comment by bristi** [comment]
Ok. Thanks so much for providing this awesome productivity tool for mac os!
