### ISSUE TITLE
TwoPane layout

### ISSUE THREAD

**Issue by mwz** [ianyh/Amethyst#894]
Hi, would it be possible to implement a [TwoPane](https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Layout-TwoPane.html) layout from XMonad? This layout is very similar to the Tall layout, except that there is only one window showed on the secondary pane and any additional windows in this layout can be cycled through (on the secondary pane).

**Comment by ianyh** [comment]
Possible, but I’m inclined to wait for #51 before adding new layouts.

**Comment by mwz** [comment]
It seems that this would be much easier to implement than a generic functionality for handling user-defined layouts, especially that this layout is probably a simpler version of Tall or the column layouts.

Are you open for external contributions or do you strictly want to wait for #51?

**Comment by cgtz** [comment]
I implemented something like this, but reversed (windows stacked on the main pane instead of secondary) in #897 by slightly adapting `TallLayout`. @ianyh, are you open to merging new layouts like this or do you still want to wait for #51? Is #51 currently being worked on?

**Comment by ianyh** [comment]
Yeah, I think contributions would be fine. I just don’t have the bandwidth myself.

**Comment by x-ji** [comment]
Any update on this? A TwoPane layout like the one from XMonad would be really nice. I could also give it a try if you're open to PRs.

Alternatively, @cgtz are you interested in finishing the PR you opened a while ago? I think that would achieve something very similar.

**Comment by mwz** [comment]
hey all, I've got this layout working locally - I will tidy up the code, write some tests and try to open a PR soon.

**Comment by mwz** [comment]
Ok, here's the PR #1124.
