### ISSUE TITLE
Windows rearranged when opening new tab

### ISSUE THREAD

**Issue by yvgny** [ianyh/Amethyst#895]
## System

 - **Amethyst version**: 0.15.0 (84)
 - **macOS version**: 10.14.6

## What's the problem?
When a window is at the main pane and a new tab is opened (inside the window), the layout is rearranged and the window gets moved away the main pane. This happens only (as far as I noticed) with windows that use native tabs (Finder, Terminal, and so on).
 
## How can it be reproduced?
In the Tall layout, open two windows : a Finder on the main pane and a Terminal as a secondary window. Then open a new tab in the Finder. The layout is rearranged and the Terminal is now placed on the main pane.

## What applications are involved?
Every applications that uses the native tabs (Finder, Mail, Terminal, and so on)

## Has anything fixed it, even temporarily?
No

**Comment by amad** [comment]
This is a known issue #633

**Comment by ianyh** [comment]
That issue should have been largely fixed, so I will leave this as a separate issue.

**Comment by illettante** [comment]
I can confirm similar behaviour in Monterey, 12.1 (21C52), Amethyst 0.15.6 (93); on Tall, Wide and Column (haven't played with applying row/floating/widescreen-tall/bsp yet). Opening a new tab automatically swaps the focused Finder window to the leftmost/bottom-leftmost available pane. If you restore Finder to the main panel, when cycling through tabs, each tab opened will move the finder app into whichever pane it was last in with that tab open. Tabs seem to be treated like new finder windows.

**Comment by ianyh** [comment]
I think this should be fixed by #1360
