### ISSUE TITLE
floating doesn't work in 0.14.3b

### ISSUE THREAD

**Issue by tuananh** [ianyh/Amethyst#900]
## System

 - **Amethyst version**: 0.14.3b
 - **macOS version**: Catalina

## What's the problem?

Floating windows stop working

## dotfile (if you have one)

```
{

}
```

**Comment by pascalw** [comment]
Confirmed, same happening for me. I have a bunch of applications listed in the Floating settings panel, but with 0.14.3b this seems to be ignored unless I toggle floating specifically for a single application using the floating hotkey.

**Comment by DCitalo** [comment]
Same happen for me. 

** System**

macOS version: High Sierra 10.13.6
