### ISSUE TITLE
Feature request: limit the number of windows in layout, overlap the rest

### ISSUE THREAD

**Issue by itaysk** [ianyh/Amethyst#904]
First of all I wanted to thank you for this amazing tool. Thanks!

Let's say I'm in a tall layout, and I start opening windows. The first windows will get the major column and the rest will be added to the minor column, so far so good. At some point, it's becoming useless to just add more windows to the minor column because they are so small they are unusable. At this point I would want more windows to fit the existing slots, cycling from the start (meaning, they will be placed on top of the other windows, hiding them). 
The number of windows that fit in a given layout and stay usable is probably known to the user based on screen resolution and personal preference. For example, I know that I can't fit more than 3 windows on the minor, and I never found myself wanting to break this rule. If for example I needed another window in the same space even if just for a moment, it will be unusable, and I now need to rearrange the windows just to perform a momentary task. It would be nice to be able to set this preference  as a limit (per layout), and the n+1 window will just be place in the place of the tall, and the n+2 the the first minor, and so on. If I opened 3 or 30 windows the layout will stay the same.

possibly related to https://github.com/ianyh/Amethyst/issues/710

**Comment by ianyh** [comment]
Would this be accomplished with #1083 ?

**Comment by itaysk** [comment]
Sorry I'm not using Amethyst anymore so can't comment on that

**Comment by ianyh** [comment]
Okay, no worries.
