### ISSUE TITLE
Parallels windows are not getting resized

### ISSUE THREAD

**Issue by iamkarlson** [ianyh/Amethyst#905]
## System

 - **Amethyst**: 0.14.2
 - **MacOS**: 10.14.6

## What's the problem?
When you use Parallels Desktop with Coherence mode all the windows from Windows are not getting resized. It looks like Amethyst knows nothing about them.

## How can it be reproduced?

1. Get a Parallels Desktop (you can use trial version). 
2. Install it with Windows (also free). 
3. Open a few Mac apps 
4. Open at least 1 Windows app in a coherence mode. 
1. Try to change layout

## What applications are involved?
Parallels Desktop 15.1.1

## Has anything fixed it, even temporarily?
Nope

## Screenshots

![image](https://user-images.githubusercontent.com/4534374/68944617-8a0c7e80-07ae-11ea-83c8-01507e7b1d2f.png)

**Comment by martin-braun** [comment]
I can confirm this issue. Parallels has a mode called "coherence mode" which will wrap all Windows windows into MacOS windows, so they can coexist to host windows. They also appear as icons when minimized to the dock. It really gives a complete nice experience working with Windows apps on MacOS, but Amethyst will not pick up such windows, which is very tragic.

**Comment by azinsharaf** [comment]
@iamkarlson @martin-braun 
That is the only reason i didn't continue to use amethyst. Instead i am using yabai which recognizes the windows of Windows in the coherence mode. 
That would be great if this capability can be added to amethyst.

**Comment by iamkarlson** [comment]
macos is terrible for windows tiling, switched to arch+sway and have had zero problems since then.

**Comment by azinsharaf** [comment]
hi @ianyh Does amethyst support coherence mode of Parallels now?

**Comment by ianyh** [comment]
I think 0.18.0 should, but I don't have Parallels set up to test it.

**Comment by azinsharaf** [comment]
i tested it with 0.18.0 (default settings) and didn't work.

**Comment by ianyh** [comment]
Okay!
