### ISSUE TITLE
Binary Space Partitioning broken on macOS Catalina, through various issues with window/event detection

### ISSUE THREAD

**Issue by MutatingFunc** [ianyh/Amethyst#906]
## System

 - **Amethyst version**: 0.14.2 or 0.14.3b (Latest release & dev, older versions untested)
 - **macOS version**: 10.15.1 (Catalina)

## What's the problem?

When in Binary Space Partitioning:

- Windows are laid out as if no windows have been closed.
(Renders the layout unusable)
- Existing windows when Amethyst is launched are not detected.
(Renders the layout inconvenient unless used continuously from user login)
- New windows do not respect the setting to automatically make them the main window.
(Minor annoyance)

## How can it be reproduced?

Appears to happen every time.

## What applications are involved?

Appears to include all applications.

## Has anything fixed it, even temporarily?

Relaunching Amethyst clears the set of ‘ghost’ windows, but the issue returns when a window is closed.
No Amethyst settings tested resolve the problem.

## dotfile (if you have one)

Just using the Amethyst app & menu bar UI.

## Screenshots

Problems are as described, would rather not provide screenshots unless necessary.

**Comment by ianyh** [comment]
Opened #923 to track the main pane setting.

**Comment by Bulletninja** [comment]
bsp sometimes "spirals" to the left, sometimes to the right in big sur. Is it possible to make it consistent?
I've even had it (bsp, that is), partition in 4 columns and only allocate 2 windows, in the first and third one (only had 2 windows open in total).
