### ISSUE TITLE
Amethyst builds are not notarized

### ISSUE THREAD

**Issue by MutatingFunc** [ianyh/Amethyst#909]
## System

 - **Amethyst version**: 0.14.2, and previously released versions
 - **macOS version**: 10.15.1 (Catalina)

## What's the problem?

Amethyst builds are not notarized, resulting in macOS Catalina producing a warning that the application may contain malware. The user doesn't get the option to launch the application without right-clicking and selecting open.

For more information: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

## How can it be reproduced?

Launch Amethyst for the first time on macOS Catalina.

## What applications are involved?

Amethyst

## Has anything fixed it, even temporarily?

The user must right-click the application, select Open, then continue through the malware warning to run the program.

## dotfile (if you have one)

N/A

## Screenshots

<img width="532" alt="Untitled" src="https://user-images.githubusercontent.com/20416941/69011222-3346a680-0960-11ea-99f4-d381429ba2a2.png">
The default prompt. Clicking OK will dismiss the dialog, and the app will not launch.

**Comment by ianyh** [comment]
Closed in #899

**Comment by MutatingFunc** [comment]
Hi, just to say the Amethyst 0.14.5 release doesn't seem to be notarized yet. This is a particularly acute issue for users where their security policy makes this a requirement for downloaded apps.

Thanks for keeping this up so far with 0.14.4!

**Comment by ianyh** [comment]
Thanks for the callout. Fixed.
