### ISSUE TITLE
Binary Space partitioning not doing anything

### ISSUE THREAD

**Issue by vegerot** [ianyh/Amethyst#926]
## System

 - **Amethyst version**: 0.14.3
 - **macOS version**: 10.15.2

## What's the problem?
Trying to switch layout to Binary Space Partitioning does nothing.  Switching to Binary Space Partitioning keeps the same layout as whatever I had previous to BSP.  Additionally, sometimes below the popup window when I switch layouts it may see things like `(Optional (numbers))`, or `nil`, or sometimes nothing below the popup.  I have tried using the shortcut to force-reevaluate the layout, and defined specific shortcuts to switch to BSP to no avail.

## How can it be reproduced?
Switch to BSP

## What applications are involved?
All

## Has anything fixed it, even temporarily?
No

## dotfile (if you have one)
Amethyst has a dot file?  How do I use it?
```
{

}
```

## Screenshots

<img width="347" alt="Screen Shot 2020-01-01 at 8 44 43 PM" src="https://user-images.githubusercontent.com/5297725/71648863-c866ea00-2cd7-11ea-8bb4-13493b4534e6.png">
<img width="307" alt="Screen Shot 2020-01-01 at 8 45 38 PM" src="https://user-images.githubusercontent.com/5297725/71648864-c866ea00-2cd7-11ea-9f4b-b43c5fd4e6ee.png">

**Comment by ianyh** [comment]
Fixed in 0.14.4.
