### ISSUE TITLE
Firefox window doesn't resize correctly or at least not on first try

### ISSUE THREAD

**Issue by GabLeRoux** [ianyh/Amethyst#929]
## System

 - **Amethyst version**: 0.14.3 (79)
 - **macOS version**: 10.15.2 (19C57)

## What's the problem?

Firefox window doesn't have same behavior as other windows when resizing. It's being animated. I'm quite sure it's a problem with firefox and not Amethyst as I also experience similar behavior with Spectacle or Rectangle.

When applying a layout such as Tall, Fullscreen or anything else, if Firefox didn't have the full size before applying the layout, it's not being resized properly.

Also, the animation is kinda slow, I wish I could disable it, but I didn't find the right settings in Firefox (searched through `about:config` with no luck).

## How can it be reproduced?

Download firefox, resize the window to a smaller window, apply a layout, lie down, try not to cry, cry a lot

## What applications are involved?

Firefox

## Has anything fixed it, even temporarily?

Applying the layout multiple times until window gets the right size, resize manually or use Spectacle or Rectangle multiple times

## dotfile (if you have one)

I don't have a dotfile, should-I?

## Screenshots (gif :tada:)

![2020-01-13 14 04 30](https://user-images.githubusercontent.com/1264761/72284285-9f672300-360e-11ea-82ee-e0b9e734f2b5.gif)

**Comment by ianyh** [comment]
This is the AXEnhancedUserInterface issue. #1257
