### ISSUE TITLE
Display focus is not recognized by certain Mac internals

### ISSUE THREAD

**Issue by Tbhesswebber** [ianyh/Amethyst#931]
## System

 - **Amethyst version**: 0.14.3
 - **macOS version**: 10.14.6

## What's the problem?
With an application open on each of two displays, changing display focus followed by changing workspaces using Mac shortcut changes workspaces on the original display rather than the newly focused display.

### Main
1. Use your keyboard shortcut to change focused display ✅ 
1. Use your keyboard shortcut (not from Amethyst) to move to workspace left or right ❌ 

### Attempted Alternative
1. Use your keyboard shortcut to change focused display ✅ 
1. Use your keyboard shortcut to change focused window ✅ 
1. Use your keyboard shortcut (not from Amethyst) to move to workspace left or right ❌ 

## What applications are involved?
Mac settings (specifically keyboard shortcuts)
Amethyst

## Has anything fixed it, even temporarily?
Nope - this seems to be an issue with what Amethyst considers focused versus what some parts of Mac consider focused.

**Comment by ianyh** [comment]
It's not a focus issue, it's a mouse position issue. macOS chooses which screen to shift space on by which contains the mouse. There is an option in preferences for moving your mouse to focused windows that is intended as a fix for this. There's not a whole lot we can do to get around how the OS works, though.
