### ISSUE TITLE
Tall Right layout piles applications on the left side

### ISSUE THREAD

**Issue by chrislawlor** [ianyh/Amethyst#933]
## System

 - **Amethyst version**: 0.14.4
 - **macOS version**: 10.14.6

## What's the problem?

Applications are incorrectly stacked on the left side of the "Tall Right" layout. Rather than being stacked vertically, they are piled (on the z-axis) in the bottom left corner.

If there are only two applications on the monitor, they display correctly.

This is a dual monitor setup, using Full Screen layout on my Macbook and Tall Right on an external monitor.

## How can it be reproduced?

Upgrade to 0.14.4

## What applications are involved?

Various combinations of Finder, Slack, iTerm, PyCharm, VSCode

## Has anything fixed it, even temporarily?

No, this started immediately after the 0.14.4 upgrade.

## dotfile (if you have one)

I don't think I have one, I set up Amethyst a couple years ago and haven't had to mess with it at all (Bravo for that!)

## Screenshots

Three or more open windows, there are multiple windows piled up on the z-axis in the bottom left corner:

![Screen Shot 2020-02-06 at 10 16 52 AM](https://user-images.githubusercontent.com/238952/73950476-fdafba80-48c9-11ea-895a-4c2085b6fae2.png)

Two windows still tile correctly:

![Screen Shot 2020-02-06 at 10 15 49 AM](https://user-images.githubusercontent.com/238952/73950526-1029f400-48ca-11ea-976d-5011d33739c5.png)

**Comment by ianyh** [comment]
That seems to be working as intended. I just tested it on my machine as well. The intention for that layout is that the main pane is on the right.

**Comment by chrislawlor** [comment]
The main pane on the right is fine. Perhaps I didn't describe the issue well, the problem is that there are multiple windows that should be stacked vertically on the left side, but only one is visible. The other windows are underneath, and there is empty space in the upper left of the screen.

**Comment by ianyh** [comment]
Ah, gotcha.

**Comment by chrislawlor** [comment]
Confirmed this issue is resolved for me on 0.15.0, thank you!!!

**Comment by ianyh** [comment]
Good to hear. 🙂
