### ISSUE TITLE
Amethyst Commands Not working For macOS Mojave

### ISSUE THREAD

**Issue by tjaved573** [ianyh/Amethyst#939]
## System

 - **Amethyst version**:
 - **macOS version**: Mojave 10.14.6

## What's the problem?
Commands not working/doing anything, even though Amethyst is given permission in
Security & Privacy.

## Has anything fixed it, even temporarily?
Nothing.

## dotfile (if you have one)

```
{

}
```

**Comment by ianyh** [comment]
< 10.15 is no longer supported.
