### ISSUE TITLE
Cannot add to floating window list

### ISSUE THREAD

**Issue by rayj-pgi** [ianyh/Amethyst#944]
**Describe the bug**
Whenever I try to add an application to the floating window list nothing is added.

**Applications:**
Amethyst 0.14.4

**To Reproduce**
Preferences
Floating tab
Plus Sign
Click App
Nothing in the list

**Additional context**
I rolled back to 0.14.2 and I was able to successfully add my app to the floating window list

**Comment by ianyh** [comment]
Duplicate of #935.
