### ISSUE TITLE
Hide Layout HUD when switching spaces

### ISSUE THREAD

**Issue by brandonkal** [ianyh/Amethyst#949]
**Is your feature request related to a problem? Please describe.**

It is annoying that when switching spaces, the layout HUD is always shown. This should really only be shown when I am Shift-Cmd-Spacing between layout options.

**Describe the solution you'd like**
When sliding between spaces, no layout HUD popup should be displayed.

**Comment by ianyh** [comment]
Already a feature. You can configure it in preferences.
