### ISSUE TITLE
Amethyst doesn't seem to acknowledge when an app is hidden

### ISSUE THREAD

**Issue by dsedivec** [ianyh/Amethyst#971]
**Describe the bug**
When I hide an application, Amethyst leaves its tiles empty.  Cycling windows will then happily cycle to the hidden app, immediately un-hiding it.  Forcing reevaluation does nothing.  Restarting Amethyst re-tiles correctly, filling in the empty tiles left by hiding an application.

Note that minimizing windows, rather than hiding them, does work correctly: Amethyst immediately re-tiles and doesn't cycle the minimized windows.  However, I have a lot of windows, and having them clutter up the dock, causing it to shrink and shrink as it tries to expand its width, becomes untenable.

**Applications:**
Behavior witnessed with Firefox, Preview, iTerm... any app as far as I know.

**To Reproduce**
1. Open 2+ apps
2. Open Amethyst
3. Put Amethyst in, say, tall layout
4. Hide one of the apps

You will now see that its space in the tiling is empty.

**Expected behavior**
I expected that hiding an app would work the same as minimizing all of its windows, causing Amethyst to re-tile, and remove the windows from cycling order.

**Screenshots**
Before:
<img width="1440" alt="before" src="https://user-images.githubusercontent.com/95333/75695783-3431e880-5c70-11ea-8863-8e26a8cd474f.png">

After hiding Firefox with ⌘H:
<img width="1440" alt="after1" src="https://user-images.githubusercontent.com/95333/75695860-4ca20300-5c70-11ea-87d2-eaa2abb7c8fd.png">

After cycling back to where Firefox would have been with ⇧⌥K:
<img width="1440" alt="after2" src="https://user-images.githubusercontent.com/95333/75695952-6fccb280-5c70-11ea-904f-5f0d88023c76.png">

**Versions:**
 - macOS: 10.13.6
 - Amethyst: 0.15.0 (84)

**Additional context**
Thank you for Amethyst!

I'm just trying to get into tiling window management on macOS, and Amethyst was *way* more approachable than chunkwm.  (And I'm not yet sure if my case of "many many windows" is some kind of indication that tiling WM is not for me.)

**Comment by rdewolff** [comment]
Thanks for fixing this in the new release 💪

**Comment by anuragrao04** [comment]
this issue still seems to be existent in my system
macOS Ventura and latest install through brew - 0.16.0. M1 Macbook Air
Edit: This is only observed on Spotify. Editing Spotify settings to 'Close button should minimize the Spotify window' fixes the issue. Seems to be an issue with Spotify.
