### ISSUE TITLE
Can I have a dotfile configuration?

### ISSUE THREAD

**Issue by Vxider** [ianyh/Amethyst#979]
Can I have a dotfile configuration to sync settings over my computers? I found `~/.amethyst` was mentioned in some issues, but I cannot find a example or I cannot found how to export from GUI.

**Comment by ianyh** [comment]
It's somewhat vestigial from a time without in-app preferences so it is not explicitly supported. If you want an example this is the one internally for the default configuration. https://github.com/ianyh/Amethyst/blob/development/Amethyst/default.amethyst

**Comment by alfonmga** [comment]
Hey @Amethyst, do you think If I save file `~/Library/Preferences/com.amethyst.Amethyst.plist` and Amethyst used version then I can recover my settings 100% later or things will break? thanks!
