### ISSUE TITLE
Feature Request: Show current main pane count in HUD

### ISSUE THREAD

**Issue by stephenkirk** [ianyh/Amethyst#980]
**Is your feature request related to a problem? Please describe.**
Almost all actions in Amethyst provide the user with feedback, but the main pane count can sometimes be ambiguous. Because of this, an unsuspecting user can inadvertently set a very high main pane count, ending up in a weird state where the space seems "broken".

In this state, the layout seems to contradict the currently set layout, resizing does not seem to work, and if the main pane count is much greater than the amount of windows, "decrease main pane count" does not seem to provide any feedback until the main pane count is lower than the amount of windows. In reality, this is because there is only a main pane. This is a state that is both reasonably easy to trigger, and hard to debug.

Currently, the way to solve this is to spam "decrease main pane count", without feedback, until the main pane count is something sensible.

Example of how this state can appear, in the "Tall" layout:
![Screenshot 2020-03-12 at 11 20 42](https://user-images.githubusercontent.com/5837934/76511487-85ea2800-6453-11ea-88e3-7a1a94d7e8ad.png)

**Describe the solution you'd like**
Provide the user with feedback on the main pane count in the layout HUD. I probably would've figured this out much earlier, if I saw that I had a main pane count that was higher than the amount of windows in the space. 

**Describe alternatives you've considered**
* When there are `n` windows on a space, and the main pane count is set to a value larger than `n`, "decrease main pane count" could reduce the main pane count to `n-1` (so it always provides feedback)
* Show main pane count when changing main pane count (with an option to remove this)

**Comment by ianyh** [comment]
This can get wrapped up in #970.
