### ISSUE TITLE
Regular expression support for window title filters

### ISSUE THREAD

**Issue by Vxider** [ianyh/Amethyst#981]
Can I only floating the "Get Info" popup of Finder? I have set it in perference and add `*简介*`(means 'Info' in chinese) in window title restriction, but it will not take effect.
<img width="660" alt="截屏2020-03-1219 45 13" src="https://user-images.githubusercontent.com/6134315/76518453-13e90180-649a-11ea-872e-d6976e7c9919.png">

**Comment by ianyh** [comment]
Window title restrictions only support exact matches. It would be pretty reasonable to extend this with some regex matching.

**Comment by yougotwill** [comment]
Regex matching for window titles would be amazing! I use Zeplin (http://zeplin.io/) a lot and it offers a pop out window feature to compare designs which I want to float but the window title changes to "Pop Out: [name of design here]". Should I add this as a separate issue? @ianyh

**Comment by ianyh** [comment]
> Regex matching for window titles would be amazing! I use Zeplin (http://zeplin.io/) a lot and it offers a pop out window feature to compare designs which I want to float but the window title changes to "Pop Out: [name of design here]". Should I add this as a separate issue? @ianyh 

I think this existing issue is fine for covering that.

**Comment by mike-lloyd03** [comment]
Voicing my support for this request. If I knew Swift, I'd take a crack at it.

**Comment by howcrazy** [comment]
Regular + 1

**Comment by wenkokke** [comment]
Wildcard patterns would already be sufficient for most use cases, and might require less documentation?
