### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by rdewolff** [ianyh/Amethyst#984]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I'd love to be able to have a layout with margin on the sides on the main window. 

**Describe alternatives you've considered**
Maybe I can use an existing layout with custom settings ? Margin or other ?

**Additional context**
n/a

**Comment by ianyh** [comment]
Margins on the sides of _only_ the main window? You can add padding around windows and margins between them.

**Comment by ianyh** [comment]
This should be possible now with custom layouts.
