### ISSUE TITLE
Calendar.app suggestion popup alters layout.

### ISSUE THREAD

**Issue by tjweir** [ianyh/Amethyst#993]
**Describe the bug**
Calendar.app auto-completion windows are treated as normal windows and shift the layout. 

**Applications:**
Calendar.app

**To Reproduce**
Using a layout that is *not* full-screen, I was using *Tall*, create a new event in Calendar and edit the title.  You must have similarly named events to get the suggestions popup to appear.

**Expected behavior**
I expected the popup to not modify the layout.

**Screenshots**
YT link of issue - https://youtu.be/rTixuJWAOkk

**Versions:**
 - macOS: Mojave - 10.14.6
 - Amethyst: 0.15.2 - build 87
 
**Debug Info**
```
$ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
```

**Additional context**
You're awesome.

**Comment by tjweir** [comment]
This may be a dupe of #883

**Comment by tjweir** [comment]
It is in fact a dupe of #883 and the workaround listed [1] solves this as well.
Would you like me to leave it open or close it?

[1] - https://github.com/ianyh/Amethyst/issues/883#issuecomment-548714142

**Comment by ianyh** [comment]
I’ll close as a dupe, but the datapoint is helpful.
