### ISSUE TITLE
Move to a new workspace with current working app

### ISSUE THREAD

**Issue by sbmaruf** [ianyh/Amethyst#994]
**Is your feature request related to a problem? Please describe.**
I am a new user of Amethyst. I came from a Linux background. I used to work with only a keyboard in Linux. But after moving to mac, it's been a pain. While Amethyst helps to resolve most of the tiling related issue I found one problem really annoying. I am not sure if this is already implemented or not. 

When we are working on an app, you can press `Ctrl+right-arrow` to go to a new or next workspace. I want to move to the new workspace with my current working app. In Unity Desktop this can be done with `Shift + Ctrl + Alt + Arrow` which is a great and handy feature.

**Describe the solution you'd like**
I am not sure about how it should be done. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kiryph** [comment]
Did you see the shortcuts to throw windows to new spaces?

Default Shortcut | Description
-- | --
mod2 + left | Throw focused window to space left
mod2 + right | Throw focused window to space right
mod2 + 1 | Throw focused window to space 1
mod2 + 2 | Throw focused window to space 2

And there is also the option "Follow thrown windows between spaces".
BTW: I assume that you mean a macOS "space" with workspace.

**Comment by ianyh** [comment]
Yeah, see the above comment. The feature exists. Let me know if there's still any confusion.

**Comment by sbmaruf** [comment]
Thank you for the reply. Yes, the feature exists.
