### ISSUE TITLE
Layouts settings screen after making changes 

### ISSUE THREAD

**Issue by AshuHK** [ianyh/Amethyst#999]
I cannot change or even see the list of layouts in the settings after removing one and now I have 3Columnleft but I cannot remove it from my list. 

1. Add a layout to the current list. 
2. Relaunch Amethyst. Then the list of layouts will be a single line that can't be clicked and the intervals and "restore layouts on launch" settings are bugged out as seen in the screenshot. 

Screenshot: 
![Screen Shot 2020-03-29 at 1 25 46 PM](https://user-images.githubusercontent.com/50347238/77855858-4183b980-71c1-11ea-8b3b-7d4a7cca5cfa.png)

**Versions:**
 - macOS: 10.15.4
 - Amethyst: 0.15.2 (87)

**Comment by ianyh** [comment]
Ugh. Auto layout is such a pain sometimes.

**Comment by ianyh** [comment]
Should be fixed by #996

**Comment by hrvstr** [comment]
Can we expect this fix in a dev build or do we have to wait for the stable release? I have "Get development builds" checked but 0.15.2 (87) is still the latest version when I check for updates?

**Comment by ianyh** [comment]
Released the fix.
